// Code generated by go-swagger; DO NOT EDIT.

package matchmakingclientmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ModelsMatchOption models match option
//
// swagger:model models.MatchOption
type ModelsMatchOption struct {

	// multi value
	// Required: true
	MultiValue *bool `json:"multi_value"`

	// name
	// Required: true
	Name string `json:"name"`
}

// Validate validates this models match option
func (m *ModelsMatchOption) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMultiValue(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsMatchOption) validateMultiValue(formats strfmt.Registry) error {

	if err := validate.Required("multi_value", "body", m.MultiValue); err != nil {
		return err
	}

	return nil
}

func (m *ModelsMatchOption) validateName(formats strfmt.Registry) error {

	if err := validate.RequiredString("name", "body", string(m.Name)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ModelsMatchOption) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsMatchOption) UnmarshalBinary(b []byte) error {
	var res ModelsMatchOption
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
