// Copyright (c) 2021 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by go-swagger; DO NOT EDIT.

package entitlement

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUserAppEntitlementOwnershipByAppIDParams creates a new GetUserAppEntitlementOwnershipByAppIDParams object
// with the default values initialized.
func NewGetUserAppEntitlementOwnershipByAppIDParams() *GetUserAppEntitlementOwnershipByAppIDParams {
	var ()
	return &GetUserAppEntitlementOwnershipByAppIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetUserAppEntitlementOwnershipByAppIDParamsWithTimeout creates a new GetUserAppEntitlementOwnershipByAppIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetUserAppEntitlementOwnershipByAppIDParamsWithTimeout(timeout time.Duration) *GetUserAppEntitlementOwnershipByAppIDParams {
	var ()
	return &GetUserAppEntitlementOwnershipByAppIDParams{

		timeout: timeout,
	}
}

// NewGetUserAppEntitlementOwnershipByAppIDParamsWithContext creates a new GetUserAppEntitlementOwnershipByAppIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetUserAppEntitlementOwnershipByAppIDParamsWithContext(ctx context.Context) *GetUserAppEntitlementOwnershipByAppIDParams {
	var ()
	return &GetUserAppEntitlementOwnershipByAppIDParams{

		Context: ctx,
	}
}

// NewGetUserAppEntitlementOwnershipByAppIDParamsWithHTTPClient creates a new GetUserAppEntitlementOwnershipByAppIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetUserAppEntitlementOwnershipByAppIDParamsWithHTTPClient(client *http.Client) *GetUserAppEntitlementOwnershipByAppIDParams {
	var ()
	return &GetUserAppEntitlementOwnershipByAppIDParams{
		HTTPClient: client,
	}
}

/*GetUserAppEntitlementOwnershipByAppIDParams contains all the parameters to send to the API endpoint
for the get user app entitlement ownership by app Id operation typically these are written to a http.Request
*/
type GetUserAppEntitlementOwnershipByAppIDParams struct {

	/*AppID*/
	AppID string
	/*Namespace*/
	Namespace string
	/*UserID*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get user app entitlement ownership by app Id params
func (o *GetUserAppEntitlementOwnershipByAppIDParams) WithTimeout(timeout time.Duration) *GetUserAppEntitlementOwnershipByAppIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get user app entitlement ownership by app Id params
func (o *GetUserAppEntitlementOwnershipByAppIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get user app entitlement ownership by app Id params
func (o *GetUserAppEntitlementOwnershipByAppIDParams) WithContext(ctx context.Context) *GetUserAppEntitlementOwnershipByAppIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get user app entitlement ownership by app Id params
func (o *GetUserAppEntitlementOwnershipByAppIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get user app entitlement ownership by app Id params
func (o *GetUserAppEntitlementOwnershipByAppIDParams) WithHTTPClient(client *http.Client) *GetUserAppEntitlementOwnershipByAppIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get user app entitlement ownership by app Id params
func (o *GetUserAppEntitlementOwnershipByAppIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the get user app entitlement ownership by app Id params
func (o *GetUserAppEntitlementOwnershipByAppIDParams) WithAppID(appID string) *GetUserAppEntitlementOwnershipByAppIDParams {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the get user app entitlement ownership by app Id params
func (o *GetUserAppEntitlementOwnershipByAppIDParams) SetAppID(appID string) {
	o.AppID = appID
}

// WithNamespace adds the namespace to the get user app entitlement ownership by app Id params
func (o *GetUserAppEntitlementOwnershipByAppIDParams) WithNamespace(namespace string) *GetUserAppEntitlementOwnershipByAppIDParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the get user app entitlement ownership by app Id params
func (o *GetUserAppEntitlementOwnershipByAppIDParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithUserID adds the userID to the get user app entitlement ownership by app Id params
func (o *GetUserAppEntitlementOwnershipByAppIDParams) WithUserID(userID string) *GetUserAppEntitlementOwnershipByAppIDParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get user app entitlement ownership by app Id params
func (o *GetUserAppEntitlementOwnershipByAppIDParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserAppEntitlementOwnershipByAppIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param appId
	qrAppID := o.AppID
	qAppID := qrAppID
	if qAppID != "" {
		if err := r.SetQueryParam("appId", qAppID); err != nil {
			return err
		}
	}

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
