// Copyright (c) 2021 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/AccelByte/accelbyte-go-sdk/services-api/pkg/utils"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/AccelByte/accelbyte-go-sdk/iam-sdk/pkg/iamclientmodels"
)

// NewAdminAddRoleManagersV3Params creates a new AdminAddRoleManagersV3Params object
// with the default values initialized.
func NewAdminAddRoleManagersV3Params() *AdminAddRoleManagersV3Params {
	var ()
	return &AdminAddRoleManagersV3Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewAdminAddRoleManagersV3ParamsWithTimeout creates a new AdminAddRoleManagersV3Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewAdminAddRoleManagersV3ParamsWithTimeout(timeout time.Duration) *AdminAddRoleManagersV3Params {
	var ()
	return &AdminAddRoleManagersV3Params{

		timeout: timeout,
	}
}

// NewAdminAddRoleManagersV3ParamsWithContext creates a new AdminAddRoleManagersV3Params object
// with the default values initialized, and the ability to set a context for a request
func NewAdminAddRoleManagersV3ParamsWithContext(ctx context.Context) *AdminAddRoleManagersV3Params {
	var ()
	return &AdminAddRoleManagersV3Params{

		Context: ctx,
	}
}

// NewAdminAddRoleManagersV3ParamsWithHTTPClient creates a new AdminAddRoleManagersV3Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAdminAddRoleManagersV3ParamsWithHTTPClient(client *http.Client) *AdminAddRoleManagersV3Params {
	var ()
	return &AdminAddRoleManagersV3Params{
		HTTPClient: client,
	}
}

/*AdminAddRoleManagersV3Params contains all the parameters to send to the API endpoint
for the admin add role managers v3 operation typically these are written to a http.Request
*/
type AdminAddRoleManagersV3Params struct {

	/*RetryPolicy*/
	RetryPolicy *utils.Retry
	/*Body*/
	Body *iamclientmodels.ModelRoleManagersRequestV3
	/*RoleID
	  Role ID, should follow UUID version 4 without hyphen

	*/
	RoleID string

	timeout        time.Duration
	AuthInfoWriter runtime.ClientAuthInfoWriter
	Context        context.Context
	HTTPClient     *http.Client
}

// WithTimeout adds the timeout to the admin add role managers v3 params
func (o *AdminAddRoleManagersV3Params) WithTimeout(timeout time.Duration) *AdminAddRoleManagersV3Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the admin add role managers v3 params
func (o *AdminAddRoleManagersV3Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the admin add role managers v3 params
func (o *AdminAddRoleManagersV3Params) WithContext(ctx context.Context) *AdminAddRoleManagersV3Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the admin add role managers v3 params
func (o *AdminAddRoleManagersV3Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// SetAuthInfoWriter adds the authInfoWriter to the admin add role managers v3 params
func (o *AdminAddRoleManagersV3Params) SetAuthInfoWriter(authInfoWriter runtime.ClientAuthInfoWriter) {
	o.AuthInfoWriter = authInfoWriter
}

// WithHTTPClient adds the HTTPClient to the admin add role managers v3 params
func (o *AdminAddRoleManagersV3Params) WithHTTPClient(client *http.Client) *AdminAddRoleManagersV3Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the admin add role managers v3 params
func (o *AdminAddRoleManagersV3Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// SetHTTPClient adds the HTTPClient Transport to the admin add role managers v3 params
func (o *AdminAddRoleManagersV3Params) SetHTTPClientTransport(roundTripper http.RoundTripper) {
	if o.HTTPClient != nil {
		o.HTTPClient.Transport = roundTripper
	} else {
		o.HTTPClient = &http.Client{Transport: roundTripper}
	}
}

// WithBody adds the body to the admin add role managers v3 params
func (o *AdminAddRoleManagersV3Params) WithBody(body *iamclientmodels.ModelRoleManagersRequestV3) *AdminAddRoleManagersV3Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the admin add role managers v3 params
func (o *AdminAddRoleManagersV3Params) SetBody(body *iamclientmodels.ModelRoleManagersRequestV3) {
	o.Body = body
}

// WithRoleID adds the roleID to the admin add role managers v3 params
func (o *AdminAddRoleManagersV3Params) WithRoleID(roleID string) *AdminAddRoleManagersV3Params {
	o.SetRoleID(roleID)
	return o
}

// SetRoleID adds the roleId to the admin add role managers v3 params
func (o *AdminAddRoleManagersV3Params) SetRoleID(roleID string) {
	o.RoleID = roleID
}

// WriteToRequest writes these params to a swagger request
func (o *AdminAddRoleManagersV3Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param roleId
	if err := r.SetPathParam("roleId", o.RoleID); err != nil {
		return err
	}

	// setting the default header value
	if err := r.SetHeaderParam("User-Agent", utils.UserAgentGen()); err != nil {
		return err
	}

	if err := r.SetHeaderParam("X-Amzn-Trace-Id", utils.AmazonTraceIDGen()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}

	return nil
}
