// Code generated by go-swagger; DO NOT EDIT.

package agreement

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"io/ioutil"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/AccelByte/accelbyte-go-sdk/legal-sdk/pkg/legalclientmodels"
)

// ChangePreferenceConsentReader is a Reader for the ChangePreferenceConsent structure.
type ChangePreferenceConsentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ChangePreferenceConsentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewChangePreferenceConsentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewChangePreferenceConsentBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		data, err := ioutil.ReadAll(response.Body())
		if err != nil {
			return nil, err
		}

		return nil, fmt.Errorf("Requested PATCH /agreement/public/agreements/localized-policy-versions/preferences returns an error %d: %s", response.Code(), string(data))
	}
}

// NewChangePreferenceConsentOK creates a ChangePreferenceConsentOK with default headers values
func NewChangePreferenceConsentOK() *ChangePreferenceConsentOK {
	return &ChangePreferenceConsentOK{}
}

/*ChangePreferenceConsentOK handles this case with default header values.

  successful operation
*/
type ChangePreferenceConsentOK struct {
}

func (o *ChangePreferenceConsentOK) Error() string {
	return fmt.Sprintf("[PATCH /agreement/public/agreements/localized-policy-versions/preferences][%d] changePreferenceConsentOK ", 200)
}

func (o *ChangePreferenceConsentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewChangePreferenceConsentBadRequest creates a ChangePreferenceConsentBadRequest with default headers values
func NewChangePreferenceConsentBadRequest() *ChangePreferenceConsentBadRequest {
	return &ChangePreferenceConsentBadRequest{}
}

/*ChangePreferenceConsentBadRequest handles this case with default header values.

  <table><tr><td>ErrorCode</td><td>ErrorMessage</td></tr><tr><td>40017</td><td>Policy with id : [{policyId}] is not marketing preference</td></tr></table>
*/
type ChangePreferenceConsentBadRequest struct {
	Payload *legalclientmodels.ErrorEntity
}

func (o *ChangePreferenceConsentBadRequest) Error() string {
	return fmt.Sprintf("[PATCH /agreement/public/agreements/localized-policy-versions/preferences][%d] changePreferenceConsentBadRequest  %+v", 400, o.Payload)
}

func (o *ChangePreferenceConsentBadRequest) GetPayload() *legalclientmodels.ErrorEntity {
	return o.Payload
}

func (o *ChangePreferenceConsentBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(legalclientmodels.ErrorEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
