// Code generated by go-swagger; DO NOT EDIT.

package d_l_c

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io/ioutil"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteDLCItemConfigReader is a Reader for the DeleteDLCItemConfig structure.
type DeleteDLCItemConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDLCItemConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteDLCItemConfigNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		data, err := ioutil.ReadAll(response.Body())
		if err != nil {
			return nil, err
		}

		return nil, fmt.Errorf("Requested DELETE /admin/namespaces/{namespace}/dlc/config/item returns an error %d: %s", response.Code(), string(data))
	}
}

// NewDeleteDLCItemConfigNoContent creates a DeleteDLCItemConfigNoContent with default headers values
func NewDeleteDLCItemConfigNoContent() *DeleteDLCItemConfigNoContent {
	return &DeleteDLCItemConfigNoContent{}
}

/*DeleteDLCItemConfigNoContent handles this case with default header values.

  Delete successfully
*/
type DeleteDLCItemConfigNoContent struct {
}

func (o *DeleteDLCItemConfigNoContent) Error() string {
	return fmt.Sprintf("[DELETE /admin/namespaces/{namespace}/dlc/config/item][%d] deleteDLCItemConfigNoContent ", 204)
}

func (o *DeleteDLCItemConfigNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
