AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description:
  Tic-Tac-Toe App (Golang)

  SAM Template for the Tic-Tac-Toe App (Golang)
Resources:
  TicTacToeFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 15
      # The Amazon Resource Name (ARN) of the function's execution role.
      # Required: Yes
      # Type: String
      Role: ''
      # Specifies the events that trigger this function. Events consist of a type and a set of properties that depend on the type.
      # Type: EventSource
      # Required: Yes
      # AWS CloudFormation compatibility: This property is unique to AWS SAM and doesn't have an AWS CloudFormation equivalent.
      Events:
        TicTacToe:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: ANY
      # For network connectivity to AWS resources in a VPC, specify a list of security groups and subnets in the VPC.
      # Required: Yes
      # More info about VpcConfig https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-vpcconfig.html
      VpcConfig:
        SecurityGroupIds:
          - ''
        SubnetIds:
          - ''
      # The configuration for the runtime environment.
      # Type: Environment
      # Required: Yes
      Environment:
        Variables:
          ACCELBYTE_BASE_URL: ''
          IAM_BASE_URL: ''
          IAM_CLIENT_ID: ''
          REDIS_URL: ''