// Code generated by go-swagger; DO NOT EDIT.

package admin_player_record

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/AccelByte/accelbyte-go-sdk/cloudsave-sdk/pkg/cloudsaveclientmodels"
)

// AdminGetPlayerRecordHandlerV1Reader is a Reader for the AdminGetPlayerRecordHandlerV1 structure.
type AdminGetPlayerRecordHandlerV1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AdminGetPlayerRecordHandlerV1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAdminGetPlayerRecordHandlerV1OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewAdminGetPlayerRecordHandlerV1InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAdminGetPlayerRecordHandlerV1Default(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return result, nil
	}
}

// NewAdminGetPlayerRecordHandlerV1OK creates a AdminGetPlayerRecordHandlerV1OK with default headers values
func NewAdminGetPlayerRecordHandlerV1OK() *AdminGetPlayerRecordHandlerV1OK {
	return &AdminGetPlayerRecordHandlerV1OK{}
}

/*AdminGetPlayerRecordHandlerV1OK handles this case with default header values.

  Record in user-level retrieved
*/
type AdminGetPlayerRecordHandlerV1OK struct {
	Payload *cloudsaveclientmodels.ModelsPlayerRecord
}

func (o *AdminGetPlayerRecordHandlerV1OK) Error() string {
	return fmt.Sprintf("[GET /cloudsave/v1/admin/namespaces/{namespace}/users/{userID}/records/{key}][%d] adminGetPlayerRecordHandlerV1OK  %+v", 200, o.Payload)
}

func (o *AdminGetPlayerRecordHandlerV1OK) GetPayload() *cloudsaveclientmodels.ModelsPlayerRecord {
	return o.Payload
}

func (o *AdminGetPlayerRecordHandlerV1OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(cloudsaveclientmodels.ModelsPlayerRecord)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAdminGetPlayerRecordHandlerV1InternalServerError creates a AdminGetPlayerRecordHandlerV1InternalServerError with default headers values
func NewAdminGetPlayerRecordHandlerV1InternalServerError() *AdminGetPlayerRecordHandlerV1InternalServerError {
	return &AdminGetPlayerRecordHandlerV1InternalServerError{}
}

/*AdminGetPlayerRecordHandlerV1InternalServerError handles this case with default header values.

  Internal Server Error
*/
type AdminGetPlayerRecordHandlerV1InternalServerError struct {
	Payload *cloudsaveclientmodels.ResponseError
}

func (o *AdminGetPlayerRecordHandlerV1InternalServerError) Error() string {
	return fmt.Sprintf("[GET /cloudsave/v1/admin/namespaces/{namespace}/users/{userID}/records/{key}][%d] adminGetPlayerRecordHandlerV1InternalServerError  %+v", 500, o.Payload)
}

func (o *AdminGetPlayerRecordHandlerV1InternalServerError) GetPayload() *cloudsaveclientmodels.ResponseError {
	return o.Payload
}

func (o *AdminGetPlayerRecordHandlerV1InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(cloudsaveclientmodels.ResponseError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAdminGetPlayerRecordHandlerV1Default creates a AdminGetPlayerRecordHandlerV1Default with default headers values
func NewAdminGetPlayerRecordHandlerV1Default(code int) *AdminGetPlayerRecordHandlerV1Default {
	return &AdminGetPlayerRecordHandlerV1Default{
		_statusCode: code,
	}
}

/*AdminGetPlayerRecordHandlerV1Default handles this case with default header values.

  Record in user-level retrieved
*/
type AdminGetPlayerRecordHandlerV1Default struct {
	_statusCode int

	Payload *cloudsaveclientmodels.ModelsPlayerRecord
}

// Code gets the status code for the admin get player record handler v1 default response
func (o *AdminGetPlayerRecordHandlerV1Default) Code() int {
	return o._statusCode
}

func (o *AdminGetPlayerRecordHandlerV1Default) Error() string {
	return fmt.Sprintf("[GET /cloudsave/v1/admin/namespaces/{namespace}/users/{userID}/records/{key}][%d] adminGetPlayerRecordHandlerV1 default  %+v", o._statusCode, o.Payload)
}

func (o *AdminGetPlayerRecordHandlerV1Default) GetPayload() *cloudsaveclientmodels.ModelsPlayerRecord {
	return o.Payload
}

func (o *AdminGetPlayerRecordHandlerV1Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(cloudsaveclientmodels.ModelsPlayerRecord)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
