// Code generated by go-swagger; DO NOT EDIT.

package payment_config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"io/ioutil"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/AccelByte/accelbyte-go-sdk/platform-sdk/pkg/platformclientmodels"
)

// QueryPaymentProviderConfigReader is a Reader for the QueryPaymentProviderConfig structure.
type QueryPaymentProviderConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *QueryPaymentProviderConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewQueryPaymentProviderConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		data, err := ioutil.ReadAll(response.Body())
		if err != nil {
			return nil, err
		}

		return nil, fmt.Errorf("Requested GET /platform/admin/payment/config/provider returns an error %d: %s", response.Code(), string(data))
	}
}

// NewQueryPaymentProviderConfigOK creates a QueryPaymentProviderConfigOK with default headers values
func NewQueryPaymentProviderConfigOK() *QueryPaymentProviderConfigOK {
	return &QueryPaymentProviderConfigOK{}
}

/*QueryPaymentProviderConfigOK handles this case with default header values.

  successful operation
*/
type QueryPaymentProviderConfigOK struct {
	Payload *platformclientmodels.PaymentProviderConfigPagingSlicedResult
}

func (o *QueryPaymentProviderConfigOK) Error() string {
	return fmt.Sprintf("[GET /platform/admin/payment/config/provider][%d] queryPaymentProviderConfigOK  %+v", 200, o.Payload)
}

func (o *QueryPaymentProviderConfigOK) GetPayload() *platformclientmodels.PaymentProviderConfigPagingSlicedResult {
	return o.Payload
}

func (o *QueryPaymentProviderConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(platformclientmodels.PaymentProviderConfigPagingSlicedResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
