// Copyright (c) 2021 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/AccelByte/accelbyte-go-sdk/services-api/pkg/utils"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListCategoriesBasicParams creates a new ListCategoriesBasicParams object
// with the default values initialized.
func NewListCategoriesBasicParams() *ListCategoriesBasicParams {
	var ()
	return &ListCategoriesBasicParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListCategoriesBasicParamsWithTimeout creates a new ListCategoriesBasicParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListCategoriesBasicParamsWithTimeout(timeout time.Duration) *ListCategoriesBasicParams {
	var ()
	return &ListCategoriesBasicParams{

		timeout: timeout,
	}
}

// NewListCategoriesBasicParamsWithContext creates a new ListCategoriesBasicParams object
// with the default values initialized, and the ability to set a context for a request
func NewListCategoriesBasicParamsWithContext(ctx context.Context) *ListCategoriesBasicParams {
	var ()
	return &ListCategoriesBasicParams{

		Context: ctx,
	}
}

// NewListCategoriesBasicParamsWithHTTPClient creates a new ListCategoriesBasicParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListCategoriesBasicParamsWithHTTPClient(client *http.Client) *ListCategoriesBasicParams {
	var ()
	return &ListCategoriesBasicParams{
		HTTPClient: client,
	}
}

/*ListCategoriesBasicParams contains all the parameters to send to the API endpoint
for the list categories basic operation typically these are written to a http.Request
*/
type ListCategoriesBasicParams struct {

	/*RetryPolicy*/
	RetryPolicy *utils.Retry
	/*Namespace
	  Namespace

	*/
	Namespace string
	/*StoreID
	  default is published store id

	*/
	StoreID *string

	timeout        time.Duration
	AuthInfoWriter runtime.ClientAuthInfoWriter
	Context        context.Context
	HTTPClient     *http.Client
}

// WithTimeout adds the timeout to the list categories basic params
func (o *ListCategoriesBasicParams) WithTimeout(timeout time.Duration) *ListCategoriesBasicParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list categories basic params
func (o *ListCategoriesBasicParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list categories basic params
func (o *ListCategoriesBasicParams) WithContext(ctx context.Context) *ListCategoriesBasicParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list categories basic params
func (o *ListCategoriesBasicParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// SetAuthInfoWriter adds the authInfoWriter to the list categories basic params
func (o *ListCategoriesBasicParams) SetAuthInfoWriter(authInfoWriter runtime.ClientAuthInfoWriter) {
	o.AuthInfoWriter = authInfoWriter
}

// WithHTTPClient adds the HTTPClient to the list categories basic params
func (o *ListCategoriesBasicParams) WithHTTPClient(client *http.Client) *ListCategoriesBasicParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list categories basic params
func (o *ListCategoriesBasicParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNamespace adds the namespace to the list categories basic params
func (o *ListCategoriesBasicParams) WithNamespace(namespace string) *ListCategoriesBasicParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the list categories basic params
func (o *ListCategoriesBasicParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithStoreID adds the storeID to the list categories basic params
func (o *ListCategoriesBasicParams) WithStoreID(storeID *string) *ListCategoriesBasicParams {
	o.SetStoreID(storeID)
	return o
}

// SetStoreID adds the storeId to the list categories basic params
func (o *ListCategoriesBasicParams) SetStoreID(storeID *string) {
	o.StoreID = storeID
}

// WriteToRequest writes these params to a swagger request
func (o *ListCategoriesBasicParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	if o.StoreID != nil {

		// query param storeId
		var qrStoreID string
		if o.StoreID != nil {
			qrStoreID = *o.StoreID
		}
		qStoreID := qrStoreID
		if qStoreID != "" {
			if err := r.SetQueryParam("storeId", qStoreID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}

	return nil
}
