// Code generated by go-swagger; DO NOT EDIT.

package sessionclientmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ApimodelsCreateGameSessionRequest apimodels create game session request
//
// swagger:model apimodels.CreateGameSessionRequest
type ApimodelsCreateGameSessionRequest struct {

	// attributes
	// Required: true
	Attributes interface{} `json:"attributes"`

	// backfill ticket ID
	// Required: true
	BackfillTicketID *string `json:"backfillTicketID"`

	// client version
	// Required: true
	ClientVersion *string `json:"clientVersion"`

	// configuration name
	// Required: true
	ConfigurationName *string `json:"configurationName"`

	// deployment
	// Required: true
	Deployment *string `json:"deployment"`

	// inactive timeout
	// Required: true
	InactiveTimeout *int32 `json:"inactiveTimeout"`

	// invite timeout
	// Required: true
	InviteTimeout *int32 `json:"inviteTimeout"`

	// joinability
	// Required: true
	Joinability *string `json:"joinability"`

	// match pool
	// Required: true
	MatchPool *string `json:"matchPool"`

	// max players
	// Required: true
	MaxPlayers *int32 `json:"maxPlayers"`

	// min players
	// Required: true
	MinPlayers *int32 `json:"minPlayers"`

	// persistent
	Persistent bool `json:"persistent"`

	// persistent TTL
	PersistentTTL int32 `json:"persistentTTL,omitempty"`

	// requested regions
	// Required: true
	RequestedRegions []string `json:"requestedRegions"`

	// server name
	// Required: true
	ServerName *string `json:"serverName"`

	// teams
	// Required: true
	Teams []*ModelsTeam `json:"teams"`

	// text chat
	// Required: true
	TextChat *bool `json:"textChat"`

	// ticket i ds
	// Required: true
	TicketIDs []string `json:"ticketIDs"`

	// type
	// Required: true
	Type *string `json:"type"`
}

// Validate validates this apimodels create game session request
func (m *ApimodelsCreateGameSessionRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAttributes(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBackfillTicketID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateClientVersion(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateConfigurationName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDeployment(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInactiveTimeout(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInviteTimeout(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateJoinability(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMatchPool(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMaxPlayers(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMinPlayers(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRequestedRegions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateServerName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTeams(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTextChat(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTicketIDs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ApimodelsCreateGameSessionRequest) validateAttributes(formats strfmt.Registry) error {

	if err := validate.Required("attributes", "body", m.Attributes); err != nil {
		return err
	}

	return nil
}

func (m *ApimodelsCreateGameSessionRequest) validateBackfillTicketID(formats strfmt.Registry) error {

	if err := validate.Required("backfillTicketID", "body", m.BackfillTicketID); err != nil {
		return err
	}

	return nil
}

func (m *ApimodelsCreateGameSessionRequest) validateClientVersion(formats strfmt.Registry) error {

	if err := validate.Required("clientVersion", "body", m.ClientVersion); err != nil {
		return err
	}

	return nil
}

func (m *ApimodelsCreateGameSessionRequest) validateConfigurationName(formats strfmt.Registry) error {

	if err := validate.Required("configurationName", "body", m.ConfigurationName); err != nil {
		return err
	}

	return nil
}

func (m *ApimodelsCreateGameSessionRequest) validateDeployment(formats strfmt.Registry) error {

	if err := validate.Required("deployment", "body", m.Deployment); err != nil {
		return err
	}

	return nil
}

func (m *ApimodelsCreateGameSessionRequest) validateInactiveTimeout(formats strfmt.Registry) error {

	if err := validate.Required("inactiveTimeout", "body", m.InactiveTimeout); err != nil {
		return err
	}

	return nil
}

func (m *ApimodelsCreateGameSessionRequest) validateInviteTimeout(formats strfmt.Registry) error {

	if err := validate.Required("inviteTimeout", "body", m.InviteTimeout); err != nil {
		return err
	}

	return nil
}

func (m *ApimodelsCreateGameSessionRequest) validateJoinability(formats strfmt.Registry) error {

	if err := validate.Required("joinability", "body", m.Joinability); err != nil {
		return err
	}

	return nil
}

func (m *ApimodelsCreateGameSessionRequest) validateMatchPool(formats strfmt.Registry) error {

	if err := validate.Required("matchPool", "body", m.MatchPool); err != nil {
		return err
	}

	return nil
}

func (m *ApimodelsCreateGameSessionRequest) validateMaxPlayers(formats strfmt.Registry) error {

	if err := validate.Required("maxPlayers", "body", m.MaxPlayers); err != nil {
		return err
	}

	return nil
}

func (m *ApimodelsCreateGameSessionRequest) validateMinPlayers(formats strfmt.Registry) error {

	if err := validate.Required("minPlayers", "body", m.MinPlayers); err != nil {
		return err
	}

	return nil
}

func (m *ApimodelsCreateGameSessionRequest) validateRequestedRegions(formats strfmt.Registry) error {

	if err := validate.Required("requestedRegions", "body", m.RequestedRegions); err != nil {
		return err
	}

	return nil
}

func (m *ApimodelsCreateGameSessionRequest) validateServerName(formats strfmt.Registry) error {

	if err := validate.Required("serverName", "body", m.ServerName); err != nil {
		return err
	}

	return nil
}

func (m *ApimodelsCreateGameSessionRequest) validateTeams(formats strfmt.Registry) error {

	if err := validate.Required("teams", "body", m.Teams); err != nil {
		return err
	}

	for i := 0; i < len(m.Teams); i++ {
		if swag.IsZero(m.Teams[i]) { // not required
			continue
		}

		if m.Teams[i] != nil {
			if err := m.Teams[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("teams" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ApimodelsCreateGameSessionRequest) validateTextChat(formats strfmt.Registry) error {

	if err := validate.Required("textChat", "body", m.TextChat); err != nil {
		return err
	}

	return nil
}

func (m *ApimodelsCreateGameSessionRequest) validateTicketIDs(formats strfmt.Registry) error {

	if err := validate.Required("ticketIDs", "body", m.TicketIDs); err != nil {
		return err
	}

	return nil
}

func (m *ApimodelsCreateGameSessionRequest) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ApimodelsCreateGameSessionRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApimodelsCreateGameSessionRequest) UnmarshalBinary(b []byte) error {
	var res ApimodelsCreateGameSessionRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
