{
  "host": "demo.accelbyte.io",
  "info": {
    "description": "Justice Achievement Service",
    "title": "justice-achievement-service",
    "version": ""
  },
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "HasPermission": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {
        "ADMIN:NAMESPACE:{namespace}:ACHIEVEMENT [CREATE]": "ADMIN:NAMESPACE:{namespace}:ACHIEVEMENT [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:ACHIEVEMENT [DELETE]": "ADMIN:NAMESPACE:{namespace}:ACHIEVEMENT [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:ACHIEVEMENT [READ]": "ADMIN:NAMESPACE:{namespace}:ACHIEVEMENT [READ]",
        "ADMIN:NAMESPACE:{namespace}:ACHIEVEMENT [UPDATE]": "ADMIN:NAMESPACE:{namespace}:ACHIEVEMENT [UPDATE]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:ACHIEVEMENT [READ]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:ACHIEVEMENT [READ]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:ACHIEVEMENT [UPDATE]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:ACHIEVEMENT [UPDATE]",
        "NAMESPACE:{namespace}:ACHIEVEMENT [READ]": "NAMESPACE:{namespace}:ACHIEVEMENT [READ]",
        "NAMESPACE:{namespace}:USER:{userId}:ACHIEVEMENT [READ]": "NAMESPACE:{namespace}:USER:{userId}:ACHIEVEMENT [READ]",
        "NAMESPACE:{namespace}:USER:{userId}:ACHIEVEMENT [UPDATE]": "NAMESPACE:{namespace}:USER:{userId}:ACHIEVEMENT [UPDATE]"
      },
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "HasScope": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {
        "social": "social"
      },
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "authorization": {
      "in": "header",
      "name": "Authorization",
      "type": "apiKey"
    }
  },
  "swagger": "2.0",
  "paths": {
    "/achievement/v1/admin/namespaces/{namespace}/achievements": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Required permission \n\u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:ACHIEVEMENT [READ]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\u0026lt;/p\u0026gt;",
        "operationId": "AdminListAchievements",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:ACHIEVEMENT [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Query achievements",
        "tags": [
          "achievements"
        ]
      },
      "post": {
        "description": "\u0026lt;p\u0026gt;Required permission \n\t\t\t\u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:ACHIEVEMENT [CREATE]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\u0026lt;/p\u0026gt;\n        \tOther detail info:\n          - achievementCode: Human readable unique code to indentify the achievement. Must be lowercase \n\t\t\tand maximum length is 32\n          - incremental:  If the achievement is not incremental, it does not need to[...]",
        "operationId": "AdminCreateNewAchievement",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:ACHIEVEMENT [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Create new achievement",
        "tags": [
          "achievements"
        ]
      }
    },
    "/achievement/v1/admin/namespaces/{namespace}/achievements/export": {
      "get": {
        "description": "\n\t\t\t\tRequired permission ADMIN:NAMESPACE:{namespace}:ACHIEVEMENT [READ]\n\n\t\t\t\tRequired Scope: social\n\t\t\t",
        "operationId": "ExportAchievements",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:ACHIEVEMENT [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Export achievements configuration into a json file",
        "tags": [
          "achievements"
        ]
      }
    },
    "/achievement/v1/admin/namespaces/{namespace}/achievements/import": {
      "post": {
        "description": "\n\t\t\t\tRequired permission ADMIN:NAMESPACE:{namespace}:ACHIEVEMENT [UPDATE]\n\n\t\t\t\tRequired Scope: social\n\n\t\t\t\tImport channels configuration from file. It will merge with existing channels.\n\t\t\t\tAvailable import strategy:\n\t\t\t\t- leaveOut: if channel with same key exist, the existing will be used and imported one will be ignored (default)\n\t\t\t\t- replace: if channel with same key exist, the imported channel will be used and existing one will be remo[...]",
        "operationId": "ImportAchievements",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:ACHIEVEMENT [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Import achievements from file",
        "tags": [
          "achievements"
        ]
      }
    },
    "/achievement/v1/admin/namespaces/{namespace}/achievements/{achievementCode}": {
      "delete": {
        "description": "\u0026lt;p\u0026gt;Required permission \n\u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:ACHIEVEMENT [DELETE]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\u0026lt;/p\u0026gt;",
        "operationId": "AdminDeleteAchievement",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:ACHIEVEMENT [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete an achievement",
        "tags": [
          "achievements"
        ]
      },
      "get": {
        "description": "\u0026lt;p\u0026gt;Required permission \n\u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:ACHIEVEMENT [READ]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\u0026lt;/p\u0026gt;",
        "operationId": "AdminGetAchievement",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:ACHIEVEMENT [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get an achievement",
        "tags": [
          "achievements"
        ]
      },
      "patch": {
        "description": "\u0026lt;p\u0026gt;Required permission \n\u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:ACHIEVEMENT [UPDATE]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\u0026lt;/p\u0026gt;",
        "operationId": "AdminUpdateAchievementListOrder",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:ACHIEVEMENT [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Update achievements listOrder",
        "tags": [
          "achievements"
        ]
      },
      "put": {
        "description": "\u0026lt;p\u0026gt;Required permission \n\u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:ACHIEVEMENT [UPDATE]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\u0026lt;/p\u0026gt;",
        "operationId": "AdminUpdateAchievement",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:ACHIEVEMENT [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Update an achievement",
        "tags": [
          "achievements"
        ]
      }
    },
    "/achievement/v1/admin/namespaces/{namespace}/users/{userId}/achievements": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Required permission\n\u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:ACHIEVEMENT [READ]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\u0026lt;/p\u0026gt;",
        "operationId": "AdminListUserAchievements",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:ACHIEVEMENT [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Query user achievements [include achieved and in-progress]",
        "tags": [
          "achievements"
        ]
      }
    },
    "/achievement/v1/admin/namespaces/{namespace}/users/{userId}/achievements/{achievementCode}/unlock": {
      "put": {
        "description": "\u0026lt;p\u0026gt;Required permission \n\u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:ACHIEVEMENT [UPDATE]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\u0026lt;/p\u0026gt;",
        "operationId": "AdminUnlockAchievement",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:ACHIEVEMENT [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Unlock an achievement",
        "tags": [
          "achievements"
        ]
      }
    },
    "/achievement/v1/public/namespaces/{namespace}/achievements": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Required permission \n\u0026lt;code\u0026gt;NAMESPACE:{namespace}:ACHIEVEMENT [READ]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\u0026lt;/p\u0026gt;",
        "operationId": "PublicListAchievements",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:ACHIEVEMENT [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Query achievements",
        "tags": [
          "achievements"
        ]
      }
    },
    "/achievement/v1/public/namespaces/{namespace}/achievements/{achievementCode}": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Required permission \n\u0026lt;code\u0026gt;NAMESPACE:{namespace}:ACHIEVEMENT [READ]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\u0026lt;/p\u0026gt;",
        "operationId": "PublicGetAchievement",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:ACHIEVEMENT [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get an achievement",
        "tags": [
          "achievements"
        ]
      }
    },
    "/achievement/v1/public/namespaces/{namespace}/users/{userId}/achievements": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Required permission \n\u0026lt;code\u0026gt;NAMESPACE:{namespace}:USER:{userId}:ACHIEVEMENT [READ]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\u0026lt;/p\u0026gt;",
        "operationId": "PublicListUserAchievements",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:ACHIEVEMENT [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Query user achievements [include achieved and in-progress]",
        "tags": [
          "achievements"
        ]
      }
    },
    "/achievement/v1/public/namespaces/{namespace}/users/{userId}/achievements/{achievementCode}/unlock": {
      "put": {
        "description": "\u0026lt;p\u0026gt;Required permission \n\u0026lt;code\u0026gt;NAMESPACE:{namespace}:USER:{userId}:ACHIEVEMENT [UPDATE]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\u0026lt;/p\u0026gt;",
        "operationId": "PublicUnlockAchievement",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:ACHIEVEMENT [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Unlock an achievement",
        "tags": [
          "achievements"
        ]
      }
    }
  }
}