{
  "host": "demo.accelbyte.io",
  "info": {
    "description": "Manage AMS Fleets",
    "title": "fleet-commander",
    "version": "1.7.1"
  },
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "HasPermission": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {
        "ADMIN:NAMESPACE:{namespace}:AMS:ARTIFACT [DELETE]": "ADMIN:NAMESPACE:{namespace}:AMS:ARTIFACT [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:AMS:ARTIFACT [READ]": "ADMIN:NAMESPACE:{namespace}:AMS:ARTIFACT [READ]",
        "ADMIN:NAMESPACE:{namespace}:AMS:ARTIFACT [UPDATE]": "ADMIN:NAMESPACE:{namespace}:AMS:ARTIFACT [UPDATE]",
        "ADMIN:NAMESPACE:{namespace}:ARMADA [READ]": "ADMIN:NAMESPACE:{namespace}:ARMADA [READ]",
        "ADMIN:NAMESPACE:{namespace}:ARMADA:ACCOUNT [CREATE]": "ADMIN:NAMESPACE:{namespace}:ARMADA:ACCOUNT [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:ARMADA:ACCOUNT [READ]": "ADMIN:NAMESPACE:{namespace}:ARMADA:ACCOUNT [READ]",
        "ADMIN:NAMESPACE:{namespace}:ARMADA:ACCOUNT [UPDATE]": "ADMIN:NAMESPACE:{namespace}:ARMADA:ACCOUNT [UPDATE]",
        "ADMIN:NAMESPACE:{namespace}:ARMADA:FLEET [CREATE]": "ADMIN:NAMESPACE:{namespace}:ARMADA:FLEET [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:ARMADA:FLEET [DELETE]": "ADMIN:NAMESPACE:{namespace}:ARMADA:FLEET [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:ARMADA:FLEET [READ]": "ADMIN:NAMESPACE:{namespace}:ARMADA:FLEET [READ]",
        "ADMIN:NAMESPACE:{namespace}:ARMADA:FLEET [UPDATE]": "ADMIN:NAMESPACE:{namespace}:ARMADA:FLEET [UPDATE]",
        "ADMIN:NAMESPACE:{namespace}:QOS:SERVER [READ]": "ADMIN:NAMESPACE:{namespace}:QOS:SERVER [READ]",
        "ADMIN:NAMESPACE:{namespace}:QOS:SERVER [UPDATE]": "ADMIN:NAMESPACE:{namespace}:QOS:SERVER [UPDATE]",
        "NAMESPACE:{namespace}:AMS:LOCALDS [CREATE]": "NAMESPACE:{namespace}:AMS:LOCALDS [CREATE]",
        "NAMESPACE:{namespace}:AMS:SERVER:CLAIM [UPDATE]": "NAMESPACE:{namespace}:AMS:SERVER:CLAIM [UPDATE]",
        "NAMESPACE:{namespace}:ARMADA:WATCHDOG [CREATE]": "NAMESPACE:{namespace}:ARMADA:WATCHDOG [CREATE]"
      },
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "HasScope": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {},
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "authorization": {
      "in": "header",
      "name": "Authorization",
      "type": "apiKey"
    }
  },
  "swagger": "2.0",
  "paths": {
    "/ams/auth": {
      "get": {
        "operationId": "AuthCheck",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Check if fleet commander is authorized to talk to AMS with this IAM",
        "tags": [
          "Auth"
        ]
      }
    },
    "/ams/healthz": {
      "get": {
        "operationId": "PortalHealthCheck",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Health check",
        "tags": [
          "Fleet Commander"
        ]
      }
    },
    "/ams/v1/admin/namespaces/{namespace}/account": {
      "get": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:ARMADA:ACCOUNT [READ]",
        "operationId": "AccountGet",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:ARMADA:ACCOUNT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get the account associated with the namespace.",
        "tags": [
          "Account"
        ]
      },
      "post": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:ARMADA:ACCOUNT [CREATE]",
        "operationId": "AccountCreate",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:ARMADA:ACCOUNT [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Create a new AMS account",
        "tags": [
          "Account"
        ]
      }
    },
    "/ams/v1/admin/namespaces/{namespace}/account/link": {
      "get": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:ARMADA:ACCOUNT [READ]",
        "operationId": "AccountLinkTokenGet",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:ARMADA:ACCOUNT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get a linking token for another namespace to use to link to the account to which this namespace is linked.  Fails if no account linked.",
        "tags": [
          "Account"
        ]
      },
      "post": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:ARMADA:ACCOUNT [CREATE]",
        "operationId": "AccountLink",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:ARMADA:ACCOUNT [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Link an account to the namespace.  Will attempt to register the linkage in AMS shipyard.  Requires a valid link token for the account. Fails if an account is already linked",
        "tags": [
          "Account"
        ]
      }
    },
    "/ams/v1/admin/namespaces/{namespace}/artifacts": {
      "get": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:AMS:ARTIFACT [READ]",
        "operationId": "ArtifactGet",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:AMS:ARTIFACT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get all artifacts matching the provided criteria",
        "tags": [
          "Artifacts"
        ]
      }
    },
    "/ams/v1/admin/namespaces/{namespace}/artifacts/usage": {
      "get": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:AMS:ARTIFACT [READ]",
        "operationId": "ArtifactUsageGet",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:AMS:ARTIFACT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Retrieves artifact storage usage for the namespace",
        "tags": [
          "Artifacts"
        ]
      }
    },
    "/ams/v1/admin/namespaces/{namespace}/artifacts/{artifactID}": {
      "delete": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:AMS:ARTIFACT [DELETE]",
        "operationId": "ArtifactDelete",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:AMS:ARTIFACT [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Deletes the specified artifact",
        "tags": [
          "Artifacts"
        ]
      }
    },
    "/ams/v1/admin/namespaces/{namespace}/artifacts/{artifactID}/url": {
      "get": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:AMS:ARTIFACT [READ]",
        "operationId": "ArtifactGetURL",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:AMS:ARTIFACT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get a signed URL for a specific artifact",
        "tags": [
          "Artifacts"
        ]
      }
    },
    "/ams/v1/admin/namespaces/{namespace}/fleets": {
      "get": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:ARMADA:FLEET [READ]",
        "operationId": "FleetList",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:ARMADA:FLEET [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "get a list of all fleets in the namespace",
        "tags": [
          "Fleets"
        ]
      },
      "post": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:ARMADA:FLEET [CREATE]",
        "operationId": "FleetCreate",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:ARMADA:FLEET [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Create a fleet. Optionally, sampling rules for the fleet can also be specified",
        "tags": [
          "Fleets"
        ]
      }
    },
    "/ams/v1/admin/namespaces/{namespace}/fleets/{fleetID}": {
      "delete": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:ARMADA:FLEET [DELETE]",
        "operationId": "FleetDelete",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:ARMADA:FLEET [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "delete a fleet",
        "tags": [
          "Fleets"
        ]
      },
      "get": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:ARMADA:FLEET [READ]",
        "operationId": "FleetGet",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:ARMADA:FLEET [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "get a fleet",
        "tags": [
          "Fleets"
        ]
      },
      "put": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:ARMADA:FLEET [UPDATE]",
        "operationId": "FleetUpdate",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:ARMADA:FLEET [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update a fleet – overrides current data. Optionally, sampling rules for the fleet can also be updated",
        "tags": [
          "Fleets"
        ]
      }
    },
    "/ams/v1/admin/namespaces/{namespace}/fleets/{fleetID}/artifacts-sampling-rules": {
      "get": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:AMS:ARTIFACT [READ]",
        "operationId": "FleetArtifactSamplingRulesGet",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:AMS:ARTIFACT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get the sampling rules for a fleet",
        "tags": [
          "Artifacts"
        ]
      },
      "put": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:AMS:ARTIFACT [UPDATE]",
        "operationId": "FleetArtifactSamplingRulesSet",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:AMS:ARTIFACT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Set sampling rules for a fleet",
        "tags": [
          "Artifacts"
        ]
      }
    },
    "/ams/v1/admin/namespaces/{namespace}/fleets/{fleetID}/servers": {
      "get": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:ARMADA:FLEET [READ]",
        "operationId": "FleetServers",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:ARMADA:FLEET [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "get server details and counts for a fleet",
        "tags": [
          "Fleets"
        ]
      }
    },
    "/ams/v1/admin/namespaces/{namespace}/fleets/{fleetID}/servers/history": {
      "get": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:ARMADA:FLEET [READ]",
        "operationId": "FleetServerHistory",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:ARMADA:FLEET [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "get history records of a specific dedicated server for a fleet",
        "tags": [
          "Servers"
        ]
      }
    },
    "/ams/v1/admin/namespaces/{namespace}/images": {
      "get": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:ARMADA:ACCOUNT [READ]",
        "operationId": "ImageList",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:ARMADA:ACCOUNT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get a list of images which exist (uploaded, uploading, or building) in the linked account.  Fails if no account is linked",
        "tags": [
          "Images"
        ]
      }
    },
    "/ams/v1/admin/namespaces/{namespace}/images/{imageID}": {
      "get": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:ARMADA:ACCOUNT [READ]",
        "operationId": "ImageGet",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:ARMADA:ACCOUNT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get details about an image.",
        "tags": [
          "Images"
        ]
      },
      "patch": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:ARMADA:ACCOUNT [UPDATE]",
        "operationId": "ImagePatch",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:ARMADA:ACCOUNT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Edit the image name, toggle IsProtected, or add/remove tags",
        "tags": [
          "Images"
        ]
      }
    },
    "/ams/v1/admin/namespaces/{namespace}/qos": {
      "get": {
        "description": "```\n\t\t\tRequired Permission: ADMIN:NAMESPACE:{namespace}:QOS:SERVER [READ]\n\n\t\t\tThis endpoint lists all QoS services available in all regions.\n\n\t\t\tThis endpoint is intended to be called by game client to find out all available regions.\n\t\t\tAfter getting a list of QoS on each region, game client is expected to ping each one with UDP\n\t\t\tconnection as described below:\n\n\t\t\t1. Make UDP connection to each QoS\u0026#39;s IP:Port\n\t\t\t2. Send string \u00[...]",
        "operationId": "QoSRegionsGet",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:QOS:SERVER [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get the list of available AMS QoS regions.",
        "tags": [
          "AMS QoS"
        ]
      }
    },
    "/ams/v1/admin/namespaces/{namespace}/qos/{region}": {
      "patch": {
        "description": "```\n\t\t\tRequired Permission: ADMIN:NAMESPACE:{namespace}:QOS:SERVER [UPDATE]\n\n\t\t\tThis endpoint updates the registered QoS service\u0026#39;s configurable configuration.\n\t\t\t",
        "operationId": "QoSRegionsUpdate",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:QOS:SERVER [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update the status of a QoS region",
        "tags": [
          "AMS QoS"
        ]
      }
    },
    "/ams/v1/admin/namespaces/{namespace}/regions": {
      "get": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:ARMADA [READ]",
        "operationId": "InfoRegions",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:ARMADA [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get the list of available AMS regions.",
        "tags": [
          "AMS Info"
        ]
      }
    },
    "/ams/v1/admin/namespaces/{namespace}/servers/{serverID}": {
      "get": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:ARMADA:FLEET [READ]",
        "operationId": "FleetServerInfo",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:ARMADA:FLEET [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "get information about a specific dedicated server",
        "tags": [
          "Servers"
        ]
      }
    },
    "/ams/v1/admin/namespaces/{namespace}/servers/{serverID}/history": {
      "get": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:ARMADA:FLEET [READ]",
        "operationId": "ServerHistory",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:ARMADA:FLEET [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "get history records of a specific dedicated server",
        "tags": [
          "Servers"
        ]
      }
    },
    "/ams/v1/admin/namespaces/{namespace}/supported-instances": {
      "get": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:ARMADA [READ]",
        "operationId": "InfoSupportedInstances",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:ARMADA [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get a list of available VM configurations",
        "tags": [
          "AMS Info"
        ]
      }
    },
    "/ams/v1/namespaces/{namespace}/fleets/{fleetID}/claim": {
      "put": {
        "description": "Required Permission: NAMESPACE:{namespace}:AMS:SERVER:CLAIM [UPDATE]",
        "operationId": "FleetClaimByID",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:AMS:SERVER:CLAIM [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "claim a Dedicated Server from a specific fleet",
        "tags": [
          "Fleets"
        ]
      }
    },
    "/ams/v1/namespaces/{namespace}/local/{watchdogID}/connect": {
      "get": {
        "description": "Required Permission: NAMESPACE:{namespace}:AMS:LOCALDS [CREATE]",
        "operationId": "LocalWatchdogConnect",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:AMS:LOCALDS [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "connect a (local) watchdog to support local ds development scenarios",
        "tags": [
          "Watchdogs"
        ]
      }
    },
    "/ams/v1/namespaces/{namespace}/servers/claim": {
      "put": {
        "description": "Required Permission: NAMESPACE:{namespace}:AMS:SERVER:CLAIM [UPDATE]",
        "operationId": "FleetClaimByKeys",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:AMS:SERVER:CLAIM [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "claim a Dedicated Server from fleets with matching claim keys",
        "tags": [
          "Fleets"
        ]
      }
    },
    "/ams/v1/namespaces/{namespace}/watchdogs/{watchdogID}/connect": {
      "get": {
        "description": "Required Permission: NAMESPACE:{namespace}:ARMADA:WATCHDOG [CREATE]",
        "operationId": "WatchdogConnect",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:ARMADA:WATCHDOG [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "connect a watchdog",
        "tags": [
          "Watchdogs"
        ]
      }
    },
    "/ams/version": {
      "get": {
        "operationId": "func1",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Version info",
        "tags": [
          "Fleet Commander"
        ]
      }
    },
    "/healthz": {
      "get": {
        "operationId": "BasicHealthCheck",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Health check",
        "tags": [
          "Fleet Commander"
        ]
      }
    }
  },
  "x-docs": {
    "alias": "ams",
    "host": "https://demo.accelbyte.io",
    "path": "/ams/apidocs/api.json"
  },
  "x-version": {
    "buildDate": "2023-12-12T23:27:16+00:00",
    "gitHash": "4b9eccaa605be6d9677fe13f13e48547754c5fc5",
    "name": "fleet-commander",
    "version": "1.7.1",
    "version-roles-seeding": "1.0.5"
  }
}