{
  "host": "demo.accelbyte.io",
  "info": {
    "description": "Justice Challenge Service",
    "title": "justice-challenge-service",
    "version": "1.0.0"
  },
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "HasPermission": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {
        "ADMIN:NAMESPACE:{namespace}:CHALLENGE [CREATE]": "ADMIN:NAMESPACE:{namespace}:CHALLENGE [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:CHALLENGE [DELETE]": "ADMIN:NAMESPACE:{namespace}:CHALLENGE [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:CHALLENGE [READ]": "ADMIN:NAMESPACE:{namespace}:CHALLENGE [READ]",
        "ADMIN:NAMESPACE:{namespace}:CHALLENGE [UPDATE]": "ADMIN:NAMESPACE:{namespace}:CHALLENGE [UPDATE]",
        "ADMIN:NAMESPACE:{namespace}:CHALLENGE:PROGRESSION [UPDATE]": "ADMIN:NAMESPACE:{namespace}:CHALLENGE:PROGRESSION [UPDATE]",
        "ADMIN:NAMESPACE:{namespace}:CHALLENGE:REWARD [READ]": "ADMIN:NAMESPACE:{namespace}:CHALLENGE:REWARD [READ]",
        "NAMESPACE:{namespace}:CHALLENGE [READ]": "NAMESPACE:{namespace}:CHALLENGE [READ]",
        "NAMESPACE:{namespace}:CHALLENGE:PROGRESSION [READ]": "NAMESPACE:{namespace}:CHALLENGE:PROGRESSION [READ]",
        "NAMESPACE:{namespace}:CHALLENGE:PROGRESSION [UPDATE]": "NAMESPACE:{namespace}:CHALLENGE:PROGRESSION [UPDATE]",
        "NAMESPACE:{namespace}:CHALLENGE:REWARD:CLAIM [UPDATE]": "NAMESPACE:{namespace}:CHALLENGE:REWARD:CLAIM [UPDATE]"
      },
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "HasScope": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {},
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "authorization": {
      "in": "header",
      "name": "Authorization",
      "type": "apiKey"
    }
  },
  "swagger": "2.0",
  "paths": {
    "/challenge/v1/admin/namespaces/{namespace}/challenges": {
      "get": {
        "description": "\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;Required permission: ADMIN:NAMESPACE:{namespace}:CHALLENGE [READ]\u0026lt;/li\u0026gt;\u0026lt;/ul\u0026gt;",
        "operationId": "adminGetChallenges",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:CHALLENGE [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "List Challenges",
        "tags": [
          "Challenge Configuration"
        ]
      },
      "post": {
        "description": "\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;Required permission: ADMIN:NAMESPACE:{namespace}:CHALLENGE [CREATE]\u0026lt;/li\u0026gt;\u0026lt;/ul\u0026gt;Challenge is a collection of goals that can be completed by players. Challenge can have rules that specify what and when goals will be available for players to be taken.\u0026lt;p\u0026gt;Request body:\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;code: only lowercase letters, numbers, and the separator - are allowed; must start and[...]",
        "operationId": "adminCreateChallenge",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:CHALLENGE [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Create New Challenge",
        "tags": [
          "Challenge Configuration"
        ]
      }
    },
    "/challenge/v1/admin/namespaces/{namespace}/challenges/{challengeCode}": {
      "delete": {
        "description": "\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;Required permission: ADMIN:NAMESPACE:{namespace}:CHALLENGE [DELETE]\u0026lt;/li\u0026gt;\u0026lt;/ul\u0026gt;",
        "operationId": "adminDeleteChallenge",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:CHALLENGE [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete a Challenge",
        "tags": [
          "Challenge Configuration"
        ]
      },
      "get": {
        "description": "\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;Required permission: ADMIN:NAMESPACE:{namespace}:CHALLENGE [READ]\u0026lt;/li\u0026gt;\u0026lt;/ul\u0026gt;",
        "operationId": "adminGetChallenge",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:CHALLENGE [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get a Challenge",
        "tags": [
          "Challenge Configuration"
        ]
      },
      "put": {
        "description": "\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;Required permission: ADMIN:NAMESPACE:{namespace}:CHALLENGE [UPDATE]\u0026lt;/li\u0026gt;\u0026lt;/ul\u0026gt;\u0026lt;p\u0026gt;Request body:\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;name: name of the challenge\u0026lt;/li\u0026gt;\u0026lt;li\u0026gt;description: text describing about the challenge (optional)\u0026lt;/li\u0026gt;\u0026lt;li\u0026gt;startDate: timestamp of when the challenge is started\u0026lt;/li\u0026gt;\u0026lt;li\u[...]",
        "operationId": "adminUpdateChallenge",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:CHALLENGE [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update a Challenge",
        "tags": [
          "Challenge Configuration"
        ]
      }
    },
    "/challenge/v1/admin/namespaces/{namespace}/challenges/{challengeCode}/goals": {
      "get": {
        "description": "\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;Required permission: ADMIN:NAMESPACE:{namespace}:CHALLENGE [READ]\u0026lt;/li\u0026gt;\u0026lt;/ul\u0026gt;",
        "operationId": "adminGetGoals",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:CHALLENGE [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "List Goals of a Challenge",
        "tags": [
          "Goal Configuration"
        ]
      },
      "post": {
        "description": "\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;Required permission: ADMIN:NAMESPACE:{namespace}:CHALLENGE [CREATE]\u0026lt;/li\u0026gt;\u0026lt;p\u0026gt;Request body:\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;code: unique within a challenge\u0026lt;/li\u0026gt;\u0026lt;li\u0026gt;name: name of the goal \u0026lt;/li\u0026gt;\u0026lt;li\u0026gt;description:  text describing the goal (optional)\u0026lt;/li\u0026gt;\u0026lt;li\u0026gt;schedule:  a time range that indicated the availab[...]",
        "operationId": "adminCreateGoal",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:CHALLENGE [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Create New Goal",
        "tags": [
          "Goal Configuration"
        ]
      }
    },
    "/challenge/v1/admin/namespaces/{namespace}/challenges/{challengeCode}/goals/{code}": {
      "delete": {
        "description": "\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;Required permission: ADMIN:NAMESPACE:{namespace}:CHALLENGE [DELETE]\u0026lt;/li\u0026gt;\u0026lt;/ul\u0026gt;",
        "operationId": "adminDeleteGoal",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:CHALLENGE [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete Goal",
        "tags": [
          "Goal Configuration"
        ]
      },
      "get": {
        "description": "\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;Required permission: ADMIN:NAMESPACE:{namespace}:CHALLENGE [READ]\u0026lt;/li\u0026gt;\u0026lt;/ul\u0026gt;",
        "operationId": "adminGetGoal",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:CHALLENGE [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get Goal",
        "tags": [
          "Goal Configuration"
        ]
      },
      "put": {
        "description": "\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;Required permission: ADMIN:NAMESPACE:{namespace}:CHALLENGE [UPDATE]\u0026lt;/li\u0026gt;\u0026lt;/ul\u0026gt;",
        "operationId": "adminUpdateGoals",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:CHALLENGE [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update Goal",
        "tags": [
          "Goal Configuration"
        ]
      }
    },
    "/challenge/v1/admin/namespaces/{namespace}/challenges/{challengeCode}/periods": {
      "get": {
        "description": "\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;Required permission: ADMIN:NAMESPACE:{namespace}:CHALLENGE [READ]\u0026lt;/li\u0026gt;\u0026lt;/ul\u0026gt;",
        "operationId": "adminGetPeriods",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:CHALLENGE [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get Challenge's Periods",
        "tags": [
          "Challenge Configuration"
        ]
      }
    },
    "/challenge/v1/admin/namespaces/{namespace}/challenges/{challengeCode}/randomize": {
      "post": {
        "description": "\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;Required permission: ADMIN:NAMESPACE:{namespace}:CHALLENGE [UPDATE]\u0026lt;/li\u0026gt;\u0026lt;/ul\u0026gt;This is a utility endpoint to execute randomize goals schedule on challenge that the assignmentRule is RANDOMIZED.",
        "operationId": "adminRandomizeChallenge",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:CHALLENGE [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Randomize Goals of a Challenge",
        "tags": [
          "Challenge Configuration"
        ]
      }
    },
    "/challenge/v1/admin/namespaces/{namespace}/challenges/{challengeCode}/tied": {
      "delete": {
        "description": "\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;Required permission: ADMIN:NAMESPACE:{namespace}:CHALLENGE [DELETE]\u0026lt;/li\u0026gt;\u0026lt;li\u0026gt;This endpoint will delete the combination of related data: CHALLENGES, GOALS, SCHEDULES, PLAYER PROGRESSIONS\u0026lt;/li\u0026gt;\u0026lt;/ul\u0026gt;",
        "operationId": "adminDeleteTiedChallenge",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:CHALLENGE [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete Tied Challenge",
        "tags": [
          "Challenge Configuration"
        ]
      }
    },
    "/challenge/v1/admin/namespaces/{namespace}/progress/evaluate": {
      "post": {
        "description": "\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;Required permission: ADMIN:NAMESPACE:{namespace}:CHALLENGE:PROGRESSION [UPDATE]\u0026lt;/li\u0026gt;\u0026lt;/ul\u0026gt;",
        "operationId": "adminEvaluateProgress",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:CHALLENGE:PROGRESSION [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Evaluate User's Progressions",
        "tags": [
          "Challenge Progression"
        ]
      }
    },
    "/challenge/v1/admin/namespaces/{namespace}/users/{userId}/rewards": {
      "get": {
        "description": "\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;Required permission: ADMIN:NAMESPACE:{namespace}:CHALLENGE:REWARD [READ]\u0026lt;/li\u0026gt;\u0026lt;/ul\u0026gt;",
        "operationId": "adminGetUserRewards",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:CHALLENGE:REWARD [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "List User's Rewards",
        "tags": [
          "Player Reward"
        ]
      }
    },
    "/challenge/v1/public/namespaces/{namespace}/challenges": {
      "get": {
        "description": "\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;Required permission: NAMESPACE:{namespace}:CHALLENGE [READ]\u0026lt;/li\u0026gt;\u0026lt;/ul\u0026gt;",
        "operationId": "GetChallenges",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:CHALLENGE [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "List Challenges",
        "tags": [
          "Challenge List"
        ]
      }
    },
    "/challenge/v1/public/namespaces/{namespace}/challenges/{challengeCode}/goals": {
      "get": {
        "description": "\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;Required permission: NAMESPACE:{namespace}:CHALLENGE [READ]\u0026lt;/li\u0026gt;\u0026lt;/ul\u0026gt;",
        "operationId": "publicGetScheduledGoals",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:CHALLENGE [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "List Goals of a Challenge",
        "tags": [
          "Challenge List"
        ]
      }
    },
    "/challenge/v1/public/namespaces/{namespace}/users/me/progress/evaluate": {
      "post": {
        "description": "\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;Required permission: NAMESPACE:{namespace}:CHALLENGE:PROGRESSION [UPDATE]\u0026lt;/li\u0026gt;\u0026lt;/ul\u0026gt;",
        "operationId": "EvaluateMyProgress",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:CHALLENGE:PROGRESSION [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Evaluate User's Challenge Progressions",
        "tags": [
          "Challenge Progression"
        ]
      }
    },
    "/challenge/v1/public/namespaces/{namespace}/users/me/progress/{challengeCode}": {
      "get": {
        "description": "\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;Required permission: NAMESPACE:{namespace}:CHALLENGE:PROGRESSION [READ]\u0026lt;/li\u0026gt;\u0026lt;/ul\u0026gt;",
        "operationId": "publicGetUserProgression",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:CHALLENGE:PROGRESSION [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "List User's Progressions",
        "tags": [
          "Challenge Progression"
        ]
      }
    },
    "/challenge/v1/public/namespaces/{namespace}/users/me/rewards": {
      "get": {
        "description": "\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;Required permission: ADMIN:NAMESPACE:{namespace}:CHALLENGE:REWARD [READ]\u0026lt;/li\u0026gt;\u0026lt;/ul\u0026gt;",
        "operationId": "publicGetUserRewards",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:CHALLENGE:REWARD [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "List User's Rewards",
        "tags": [
          "Player Reward"
        ]
      }
    },
    "/challenge/v1/public/namespaces/{namespace}/users/me/rewards/claim": {
      "post": {
        "description": "\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;Required permission: NAMESPACE:{namespace}:CHALLENGE:REWARD:CLAIM [UPDATE]\u0026lt;/li\u0026gt;\u0026lt;/ul\u0026gt;",
        "operationId": "publicClaimUserRewards",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:CHALLENGE:REWARD:CLAIM [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Claim User's Rewards",
        "tags": [
          "Player Reward"
        ]
      }
    }
  },
  "x-docs": {
    "alias": "challenge",
    "host": "https://stage.accelbyte.io",
    "path": "/challenge/apidocs/api.json"
  },
  "x-version": {
    "buildDate": "2024-03-22T03:20:36+00:00",
    "gitHash": "93c858b58e86e228a0083690f27501f2ec0224d8",
    "name": "justice-challenge-service",
    "realm": "staging",
    "version": "1.2.3",
    "version-roles-seeding": "1.2.16"
  }
}