{
  "host": "demo.accelbyte.io",
  "info": {
    "contact": {
      "email": "engineering@accelbyte.io",
      "name": "Engineering Team at AccelByte",
      "url": "https://accelbyte.io"
    },
    "description": "Justice DS Artifact Service",
    "title": "justice-ds-artifact-manager",
    "version": "1.11.1"
  },
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "HasPermission": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {
        "ADMIN:DSAM:ARTIFACT:NODES [DELETE]": "ADMIN:DSAM:ARTIFACT:NODES [DELETE]",
        "ADMIN:DSAM:ARTIFACT:NODES [READ]": "ADMIN:DSAM:ARTIFACT:NODES [READ]",
        "ADMIN:DSAM:ARTIFACT:QUEUE [DELETE]": "ADMIN:DSAM:ARTIFACT:QUEUE [DELETE]",
        "ADMIN:DSAM:ARTIFACT:QUEUE [READ]": "ADMIN:DSAM:ARTIFACT:QUEUE [READ]",
        "ADMIN:DSAM:ARTIFACT:QUEUE [UPDATE]": "ADMIN:DSAM:ARTIFACT:QUEUE [UPDATE]",
        "ADMIN:NAMESPACE:{namespace}:DSAM:ARTIFACT [READ]": "ADMIN:NAMESPACE:{namespace}:DSAM:ARTIFACT [READ]",
        "ADMIN:NAMESPACE:{namespace}:DSAM:ARTIFACT:QUEUE [DELETE]": "ADMIN:NAMESPACE:{namespace}:DSAM:ARTIFACT:QUEUE [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:DSAM:ARTIFACT:QUEUE [READ]": "ADMIN:NAMESPACE:{namespace}:DSAM:ARTIFACT:QUEUE [READ]",
        "ADMIN:NAMESPACE:{namespace}:DSAM:SERVER [READ]": "ADMIN:NAMESPACE:{namespace}:DSAM:SERVER [READ]"
      },
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "HasScope": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {
        "social": "social"
      },
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "authorization": {
      "in": "header",
      "name": "Authorization",
      "type": "apiKey"
    }
  },
  "swagger": "2.0",
  "paths": {
    "/dsartifact/artifacts/nodes/ipaddresses": {
      "delete": {
        "description": "Required permission: ADMIN:DSAM:ARTIFACT:NODES [DELETE]\n\nRequired scope: social\n\nThis endpoint will delete a node by IP",
        "operationId": "deleteNodeByID",
        "security": [
          {
            "HasPermission": [
              "ADMIN:DSAM:ARTIFACT:NODES [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete a node that previously held artifact queue by IP address",
        "tags": [
          "Artifact Upload Process Queue"
        ]
      },
      "get": {
        "description": "Required permission: ADMIN:DSAM:ARTIFACT:NODES [READ]\n\nRequired scope: social\n\nThis endpoint will list IP Address of all artifact queue",
        "operationId": "listNodesIPAddress",
        "security": [
          {
            "HasPermission": [
              "ADMIN:DSAM:ARTIFACT:NODES [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get IP Address of all nodes that all artifact in queue resides. This IP Address is the IP Address of nomad client",
        "tags": [
          "Artifact Upload Process Queue"
        ]
      }
    },
    "/dsartifact/artifacts/queues": {
      "get": {
        "description": "```\nRequired permission: ADMIN:DSAM:ARTIFACT:QUEUE [READ]\n\nThis endpoint is used to get the list of queues on a node\n```",
        "operationId": "listQueue",
        "security": [
          {
            "HasPermission": [
              "ADMIN:DSAM:ARTIFACT:QUEUE [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get list of queues on a node",
        "tags": [
          "Artifact Upload Process Queue"
        ]
      }
    },
    "/dsartifact/artifacts/queues/active": {
      "delete": {
        "description": "```\nRequired permission: ADMIN:DSAM:ARTIFACT:QUEUE [DELETE]\n\nThis endpoint is used to delete active queue process on a node\n```",
        "operationId": "deleteActiveQueue",
        "security": [
          {
            "HasPermission": [
              "ADMIN:DSAM:ARTIFACT:QUEUE [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete active queue process on a node",
        "tags": [
          "Artifact Upload Process Queue"
        ]
      },
      "get": {
        "description": "```\nRequired permission: ADMIN:DSAM:ARTIFACT:QUEUE [READ]\n\nThis endpoint is used to get an active queue process on a node\n```",
        "operationId": "getActiveQueue",
        "security": [
          {
            "HasPermission": [
              "ADMIN:DSAM:ARTIFACT:QUEUE [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get active queue process on a node",
        "tags": [
          "Artifact Upload Process Queue"
        ]
      },
      "put": {
        "description": "```\nRequired permission: ADMIN:DSAM:ARTIFACT:QUEUE [UPDATE]\n\nThis endpoint is used to set a queue entry as the current active queue\nfor artifact uploading process on a node\n```",
        "operationId": "setActiveQueue",
        "security": [
          {
            "HasPermission": [
              "ADMIN:DSAM:ARTIFACT:QUEUE [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Set a queue as active queue",
        "tags": [
          "Artifact Upload Process Queue"
        ]
      }
    },
    "/dsartifact/artifacts/queues/failed": {
      "put": {
        "description": "```\nRequired permission: ADMIN:DSAM:ARTIFACT:QUEUE [UPDATE]\n\nThis endpoint is used to report a failed artifact upload\n```",
        "operationId": "reportFailedUpload",
        "security": [
          {
            "HasPermission": [
              "ADMIN:DSAM:ARTIFACT:QUEUE [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Report failed artifact upload",
        "tags": [
          "Artifact Upload Process Queue"
        ]
      }
    },
    "/dsartifact/namespaces/{namespace}/artifacts/queues": {
      "delete": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSAM:ARTIFACT:QUEUE [DELETE]\n\nRequired scope: social\n\nThis endpoint will delete a queue entry",
        "operationId": "deleteQueue",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSAM:ARTIFACT:QUEUE [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete a queue entry",
        "tags": [
          "Artifact Upload Process Queue"
        ]
      }
    },
    "/dsartifact/namespaces/{namespace}/artifacts/queues/active/all": {
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSAM:ARTIFACT:QUEUE [READ]\n\nRequired scope: social\n\nThis endpoint will list all DSes which artifact is currently in uploading process. ",
        "operationId": "listAllActiveQueue",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSAM:ARTIFACT:QUEUE [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get all currently uploading artifact queue",
        "tags": [
          "Artifact Upload Process Queue"
        ]
      }
    },
    "/dsartifact/namespaces/{namespace}/artifacts/queues/all": {
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSAM:ARTIFACT:QUEUE [READ]\n\nRequired scope: social\n\nThis endpoint will list all DSes which has artifact in upload queue.",
        "operationId": "listAllQueue",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSAM:ARTIFACT:QUEUE [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get all artifact upload process queues",
        "tags": [
          "Artifact Upload Process Queue"
        ]
      }
    },
    "/dsartifact/namespaces/{namespace}/servers/search": {
      "get": {
        "description": "```\nRequired permission: ADMIN:NAMESPACE:{namespace}:DSAM:SERVER [READ]\n\nThis endpoint used to retrieve terminated servers in a namespace\n```",
        "operationId": "listTerminatedServersWithNamespace",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSAM:SERVER [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Retrieve All Terminated Servers in a Namespace",
        "tags": [
          "Terminated Servers"
        ]
      }
    },
    "/dsartifact/namespaces/{namespace}/servers/{podName}/artifacts/download": {
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSAM:ARTIFACT [READ]\n\nRequired scope: social\n\nThis endpoint will download dedicated server\u0026#39;s Artifact file (.zip).",
        "operationId": "downloadServerArtifacts",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSAM:ARTIFACT [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Download dedicated server artifact files",
        "tags": [
          "Download Server Artifact"
        ]
      }
    },
    "/dsartifact/namespaces/{namespace}/servers/{podName}/artifacts/exists": {
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSAM:ARTIFACT [READ]\n\nRequired scope: social\n\nThis endpoint will check artifact file existence before download file.\n\nThis endpoint will return the artifact status.\n\nThe possible status is : \u0026#39;Empty\u0026#39;, \u0026#39;In Queue\u0026#39;, \u0026#39;Uploading\u0026#39;, \u0026#39;Ready\u0026#39;, \u0026#39;Failed\u0026#39;",
        "operationId": "checkServerArtifact",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSAM:ARTIFACT [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Check dedicated server artifacts files existence",
        "tags": [
          "Download Server Artifact"
        ]
      }
    },
    "/dsartifact/servers/search": {
      "get": {
        "description": "```\nRequired permission: ADMIN:NAMESPACE:{namespace}:DSAM:SERVER [READ]\n\nThis endpoint used to retrieve terminated servers in all namespace\n```",
        "operationId": "listTerminatedServers",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSAM:SERVER [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Retrieve All Terminated Servers",
        "tags": [
          "All Terminated Servers"
        ]
      }
    },
    "/dsartifact/v1/messages": {
      "get": {
        "description": "get the list of messages.",
        "operationId": "publicGetMessages",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "get service messages"
      }
    }
  },
  "x-docs": {
    "alias": "dsartifact",
    "host": "https://stage.accelbyte.io",
    "path": "/dsartifact/apidocs/api.json"
  },
  "x-version": {
    "buildDate": "2024-03-20T02:15:27+00:00",
    "gitHash": "55ef7ee079c70e428e425cf01ef20cc6ecb277fb",
    "name": "justice-ds-artifact-manager",
    "revisionID": "1.11.1",
    "version": "1.11.1",
    "version-roles-seeding": "0.0.3"
  }
}