{
  "host": "demo.accelbyte.io",
  "info": {
    "description": "Justice DSM Controller Service",
    "title": "justice-dsm-controller-service",
    "version": "6.3.3"
  },
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "HasPermission": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {
        "ADMIN:NAMESPACE:*:DSM:CONFIG [READ]": "ADMIN:NAMESPACE:*:DSM:CONFIG [READ]",
        "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [CREATE]": "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [DELETE]": "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]": "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]",
        "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [UPDATE]": "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [UPDATE]",
        "ADMIN:NAMESPACE:{namespace}:DSM:SERVER [DELETE]": "ADMIN:NAMESPACE:{namespace}:DSM:SERVER [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:DSM:SERVER [READ]": "ADMIN:NAMESPACE:{namespace}:DSM:SERVER [READ]",
        "ADMIN:NAMESPACE:{namespace}:DSM:SESSION [DELETE]": "ADMIN:NAMESPACE:{namespace}:DSM:SESSION [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:DSM:SESSION [READ]": "ADMIN:NAMESPACE:{namespace}:DSM:SESSION [READ]",
        "NAMESPACE:{namespace}:DSM:CONFIG [CREATE]": "NAMESPACE:{namespace}:DSM:CONFIG [CREATE]",
        "NAMESPACE:{namespace}:DSM:CONFIG [DELETE]": "NAMESPACE:{namespace}:DSM:CONFIG [DELETE]",
        "NAMESPACE:{namespace}:DSM:CONFIG [READ]": "NAMESPACE:{namespace}:DSM:CONFIG [READ]",
        "NAMESPACE:{namespace}:DSM:SERVER [READ]": "NAMESPACE:{namespace}:DSM:SERVER [READ]",
        "NAMESPACE:{namespace}:DSM:SERVER [UPDATE]": "NAMESPACE:{namespace}:DSM:SERVER [UPDATE]",
        "NAMESPACE:{namespace}:DSM:SESSION [CREATE]": "NAMESPACE:{namespace}:DSM:SESSION [CREATE]",
        "NAMESPACE:{namespace}:DSM:SESSION [DELETE]": "NAMESPACE:{namespace}:DSM:SESSION [DELETE]",
        "NAMESPACE:{namespace}:DSM:SESSION [READ]": "NAMESPACE:{namespace}:DSM:SESSION [READ]",
        "NAMESPACE:{namespace}:DSM:SESSION [UPDATE]": "NAMESPACE:{namespace}:DSM:SESSION [UPDATE]"
      },
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "HasScope": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {
        "social": "social"
      },
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "authorization": {
      "in": "header",
      "name": "Authorization",
      "type": "apiKey"
    }
  },
  "swagger": "2.0",
  "paths": {
    "/dsmcontroller/admin/configs": {
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]\n\nRequired scope: social\n\nThis endpoint lists all of dedicated servers configs.",
        "operationId": "ListConfig",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "List all configs",
        "tags": [
          "Config"
        ]
      },
      "post": {
        "deprecated": true,
        "description": "```\nRequired permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [CREATE]\nRequired scope: social\n\nThis endpoint adds/modifies config. When there are ready servers and\nthe server version is updated, those servers will be replaced with newer version.\n\nPort is where your game listens for incoming UDP connection, if empty it\u0026#39;ll be set to 15000\n\nCPU and Memory limit / request are formatted with Kubernetes format,\ne.g. CPU of 1000m is 1 core, and Memory of 512[...]",
        "operationId": "SaveConfig",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Save config",
        "tags": [
          "Config"
        ]
      }
    },
    "/dsmcontroller/admin/images": {
      "post": {
        "description": "```\nRequired permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [CREATE]\nRequired scope: social\n\nThis endpoint will create image.\n\nSample image:\n{\n\t\u0026#34;namespace\u0026#34;:\u0026#34;dewa\u0026#34;,\n\t\u0026#34;version\u0026#34;:\u0026#34;1.0.0\u0026#34;,\n\t\u0026#34;image\u0026#34;:\u0026#34;144436415367.dkr.ecr.us-west-2.amazonaws.com/dewa:1.0.0\u0026#34;,\n\t\u0026#34;persistent\u0026#34;:false\n}\n```",
        "operationId": "CreateImage",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Create image",
        "tags": [
          "Image Config"
        ]
      },
      "put": {
        "description": "```\nRequired permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [UPDATE]\nRequired scope: social\n\nThis endpoint will update an image name and/or image persistent flag.\n\nSample image:\n{\n\t\u0026#34;namespace\u0026#34;:\u0026#34;dewa\u0026#34;,\n\t\u0026#34;version\u0026#34;:\u0026#34;1.0.0\u0026#34;,\n\t\u0026#34;image\u0026#34;:\u0026#34;144436415367.dkr.ecr.us-west-2.amazonaws.com/dewa:1.0.0\u0026#34;,\n\t\u0026#34;persistent\u0026#34;:false\n}\n```",
        "operationId": "UpdateImage",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Update image",
        "tags": [
          "Image Config"
        ]
      }
    },
    "/dsmcontroller/admin/images/import": {
      "post": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [CREATE]\n\nRequired scope: social\n\nThis endpoint import a dedicated servers images in a namespace.\n\nThe image will be upsert. Existing version will be replaced with imported image, will create new one if not found.\n\nExample data inside imported file\n[\n  {\n\t\u0026#34;namespace\u0026#34;: \u0026#34;dewa\u0026#34;,\n\t\u0026#34;image\u0026#34;: \u0026#34;123456789.dkr.ecr.us-west-2.amazonaws.com/ds-dewa:0[...]",
        "operationId": "ImportImages",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "import images for a namespace",
        "tags": [
          "Image Config"
        ]
      }
    },
    "/dsmcontroller/admin/images/patches": {
      "post": {
        "description": "```\nRequired permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [CREATE]\nRequired scope: social\n\nThis endpoint will create image patch.\n\nSample image:\n{\n\t\u0026#34;namespace\u0026#34;:\u0026#34;dewa\u0026#34;,\n\t\u0026#34;version\u0026#34;:\u0026#34;1.0.0\u0026#34;,\n\t\u0026#34;patchVersion\u0026#34;:\u0026#34;1.0.0-patch\u0026#34;,\n\t\u0026#34;image\u0026#34;:\u0026#34;144436415367.dkr.ecr.us-west-2.amazonaws.com/dewa:1.0.0-patch\u0026#34;,\n\t\u0026#34;persi[...]",
        "operationId": "CreateImagePatch",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Create image patch",
        "tags": [
          "Image Config"
        ]
      }
    },
    "/dsmcontroller/admin/instances/spec/lowest": {
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:*:DSM:CONFIG [READ]\n\nRequired scope: social\n\nThis endpoint returns the lowest instance spec, both cpu (in Mhz) and memory (in Mb).",
        "operationId": "GetLowestInstanceSpec",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:*:DSM:CONFIG [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get lowest instance spec.",
        "tags": [
          "Pod Config"
        ]
      }
    },
    "/dsmcontroller/admin/namespaces/{namespace}/configs": {
      "delete": {
        "description": "```\nRequired permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [DELETE]\nRequired scope: social\n\nThis endpoint removes config. When there are ready servers,\nthose servers will be removed.\n```",
        "operationId": "DeleteConfig",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete config",
        "tags": [
          "Config"
        ]
      },
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]\n\nRequired scope: social\n\nThis endpoint get a dedicated servers config in a namespace.",
        "operationId": "GetConfig",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get config for a namespace",
        "tags": [
          "Config"
        ]
      },
      "patch": {
        "description": "```\nRequired permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [UPDATE]\nRequired scope: social\n\nThis endpoint modifies config. When there are ready servers and\nthe server version is updated, those servers will be replaced with newer version.\n\nPort is where your game listens for incoming UDP connection, if empty it\u0026#39;ll be set to 15000\n\nCPU and Memory limit / request are formatted with Kubernetes format,\ne.g. CPU of 1000m is 1 core, and Memory of 512Mi is[...]",
        "operationId": "UpdateConfig",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Update config",
        "tags": [
          "Config"
        ]
      },
      "post": {
        "description": "```\nRequired permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [CREATE]\nRequired scope: social\n\nThis endpoint creates config.\n\nPort is where your game listens for incoming UDP connection, if empty it\u0026#39;ll be set to 15000\n\nCPU and Memory limit / request are formatted with Kubernetes format,\ne.g. CPU of 1000m is 1 core, and Memory of 512Mi is 512 MB.\n\nThe creation/claim/session/unreachable/heartbeat timeouts are all in seconds.\nCreation timeout is time l[...]",
        "operationId": "CreateConfig",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Create config",
        "tags": [
          "Config"
        ]
      }
    },
    "/dsmcontroller/admin/namespaces/{namespace}/configs/cache": {
      "delete": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [DELETE]\n\nRequired scope: social\n\nThis endpoint clears config cache in a namespace",
        "operationId": "ClearCache",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Clear config cache",
        "tags": [
          "Config"
        ]
      }
    },
    "/dsmcontroller/admin/namespaces/{namespace}/configs/deployments": {
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]\n\nRequired scope: social\n\nThis endpoint get a all deployments in a namespace\n\nParameter Offset and Count is Required",
        "operationId": "GetAllDeployment",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get All Deployments",
        "tags": [
          "Deployment Config"
        ]
      }
    },
    "/dsmcontroller/admin/namespaces/{namespace}/configs/deployments/{deployment}": {
      "delete": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [DELETE]\n\nRequired scope: social\n\nThis endpoint delete a dedicated server deployment in a namespace",
        "operationId": "DeleteDeployment",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete Deployment",
        "tags": [
          "Deployment Config"
        ]
      },
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]\n\nRequired scope: social\n\nThis endpoint get a dedicated server deployment in a namespace",
        "operationId": "GetDeployment",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get Deployment",
        "tags": [
          "Deployment Config"
        ]
      },
      "patch": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [UPDATE]\n\nRequired scope: social\n\nThis endpoint update a dedicated servers deployment in a namespace.",
        "operationId": "UpdateDeployment",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Update deployment",
        "tags": [
          "Deployment Config"
        ]
      },
      "post": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [CREATE]\n\nRequired scope: social\n\nThis endpoint create a dedicated servers deployment in a namespace.",
        "operationId": "CreateDeployment",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Create deployment",
        "tags": [
          "Deployment Config"
        ]
      }
    },
    "/dsmcontroller/admin/namespaces/{namespace}/configs/deployments/{deployment}/overrides/regions/{region}": {
      "delete": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [DELETE]\n\nRequired scope: social\n\nThis endpoint delete a dedicated server deployment override in a namespace in a region for root deployment",
        "operationId": "DeleteRootRegionOverride",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete Region Override",
        "tags": [
          "Deployment Config"
        ]
      },
      "patch": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [UPDATE]\n\nRequired scope: social\n\nThis endpoint update a dedicated servers deployment override in a namespace in a region for root deployment.",
        "operationId": "UpdateRootRegionOverride",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Update region override",
        "tags": [
          "Deployment Config"
        ]
      },
      "post": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [CREATE]\n\nRequired scope: social\n\nThis endpoint creates a dedicated servers deployment override in a namespace in a region for root deployment.",
        "operationId": "CreateRootRegionOverride",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Create region override",
        "tags": [
          "Deployment Config"
        ]
      }
    },
    "/dsmcontroller/admin/namespaces/{namespace}/configs/deployments/{deployment}/overrides/version/{version}": {
      "post": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [CREATE]\n\nRequired scope: social\n\nThis endpoint create a dedicated servers deployment override in a namespace.",
        "operationId": "CreateDeploymentOverride",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Create deployment override",
        "tags": [
          "Deployment Config"
        ]
      }
    },
    "/dsmcontroller/admin/namespaces/{namespace}/configs/deployments/{deployment}/overrides/versions/{version}": {
      "delete": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [DELETE]\n\nRequired scope: social\n\nThis endpoint delete a dedicated server deployment override in a namespace",
        "operationId": "DeleteDeploymentOverride",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete Deployment Override",
        "tags": [
          "Deployment Config"
        ]
      },
      "patch": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [UPDATE]\n\nRequired scope: social\n\nThis endpoint update a dedicated servers deployment override in a namespace.",
        "operationId": "UpdateDeploymentOverride",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Update deployment override",
        "tags": [
          "Deployment Config"
        ]
      }
    },
    "/dsmcontroller/admin/namespaces/{namespace}/configs/deployments/{deployment}/overrides/versions/{version}/regions/{region}": {
      "delete": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [DELETE]\n\nRequired scope: social\n\nThis endpoint delete a dedicated server deployment override in a namespace in a region for deployment overrides",
        "operationId": "DeleteOverrideRegionOverride",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete region override for deployment override",
        "tags": [
          "Deployment Config"
        ]
      },
      "patch": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [UPDATE]\n\nRequired scope: social\n\nThis endpoint update a dedicated servers deployment override in a namespace in a region for deployment overrides.",
        "operationId": "UpdateOverrideRegionOverride",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Update region override for deployment override",
        "tags": [
          "Deployment Config"
        ]
      },
      "post": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [CREATE]\n\nRequired scope: social\n\nThis endpoint creates a dedicated servers deployment override in a namespace in a region for deployment overrides.",
        "operationId": "CreateOverrideRegionOverride",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Create region override for deployment override",
        "tags": [
          "Deployment Config"
        ]
      }
    },
    "/dsmcontroller/admin/namespaces/{namespace}/configs/pods": {
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]\n\nRequired scope: social\n\nThis endpoint get a all pod configs in a namespace\n\nParameter Offset and Count is Required",
        "operationId": "GetAllPodConfig",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get all pod configs",
        "tags": [
          "Pod Config"
        ]
      }
    },
    "/dsmcontroller/admin/namespaces/{namespace}/configs/pods/{name}": {
      "delete": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [DELETE]\n\nRequired scope: social\n\nThis endpoint delete a dedicated server pod config in a namespace",
        "operationId": "DeletePodConfig",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete pod config",
        "tags": [
          "Pod Config"
        ]
      },
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]\n\nRequired scope: social\n\nThis endpoint get a dedicated server pod config in a namespace",
        "operationId": "GetPodConfig",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get Pod Config",
        "tags": [
          "Pod Config"
        ]
      },
      "patch": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [UPDATE]\n\nRequired scope: social\n\nThis endpoint update a dedicated servers pod config in a namespace.",
        "operationId": "UpdatePodConfig",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Update pod config",
        "tags": [
          "Pod Config"
        ]
      },
      "post": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [CREATE]\n\nRequired scope: social\n\nThis endpoint create a dedicated servers pod config in a namespace.",
        "operationId": "CreatePodConfig",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Create pod config",
        "tags": [
          "Pod Config"
        ]
      }
    },
    "/dsmcontroller/admin/namespaces/{namespace}/configs/ports/{name}": {
      "delete": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [DELETE]\n\nRequired scope: social\n\nThis endpoint delete a dedicated server port config in a namespace",
        "operationId": "DeletePort",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete port config",
        "tags": [
          "Config"
        ]
      },
      "patch": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [UPDATE]\n\nRequired scope: social\n\nThis endpoint update a dedicated servers port config in a namespace.",
        "operationId": "UpdatePort",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Update port config",
        "tags": [
          "Config"
        ]
      },
      "post": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [CREATE]\n\nRequired scope: social\n\nThis endpoint create a dedicated servers port config in a namespace.",
        "operationId": "AddPort",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Create port config",
        "tags": [
          "Config"
        ]
      }
    },
    "/dsmcontroller/admin/namespaces/{namespace}/images": {
      "delete": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [UPDATE]\n\nRequired scope: social.\n\nThis endpoint will delete an image that specified in the request parameter.\n\nDefault image is cannot be deleted and will throw error 422 (Unprocessable entity).",
        "operationId": "DeleteImage",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete an image",
        "tags": [
          "Image Config"
        ]
      },
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]\n\nRequired scope: social\n\nThis endpoint lists all of dedicated servers images.\n\nParameter Offset and Count is Required",
        "operationId": "ListImages",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "List all DS images",
        "tags": [
          "Image Config"
        ]
      }
    },
    "/dsmcontroller/admin/namespaces/{namespace}/images/export": {
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]\n\nRequired scope: social\n\nThis endpoint export a dedicated servers images in a namespace.\n",
        "operationId": "ExportImages",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "export DSM Controller images for a namespace",
        "tags": [
          "Image Config"
        ]
      }
    },
    "/dsmcontroller/admin/namespaces/{namespace}/images/limit": {
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]\n\nRequired scope: social\n\nThis endpoint get ds image limit for specific namespace",
        "operationId": "GetImageLimit",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "DS Image Limit",
        "tags": [
          "Image Config"
        ]
      }
    },
    "/dsmcontroller/admin/namespaces/{namespace}/images/patches": {
      "delete": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [UPDATE]\n\nRequired scope: social\n\nThis endpoint will delete an image patch that specified in the request parameter",
        "operationId": "DeleteImagePatch",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete an image patch",
        "tags": [
          "Image Config"
        ]
      }
    },
    "/dsmcontroller/admin/namespaces/{namespace}/images/versions/{version}": {
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]\n\nRequired scope: social\n\nThis endpoint get specific version of dedicated servers images.",
        "operationId": "GetImageDetail",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "DS Image Detail",
        "tags": [
          "Image Config"
        ]
      }
    },
    "/dsmcontroller/admin/namespaces/{namespace}/images/versions/{version}/patches": {
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]\n\nRequired scope: social\n\nThis endpoint get image patches by version.\n\nImage Size unit is byte.",
        "operationId": "GetImagePatches",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get All Image Patches by Version",
        "tags": [
          "Image Config"
        ]
      }
    },
    "/dsmcontroller/admin/namespaces/{namespace}/images/versions/{version}/patches/{versionPatch}": {
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]\n\nRequired scope: social\n\nThis endpoint get specific image patch version of dedicated servers version.",
        "operationId": "GetImagePatchDetail",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "DS Image patch Detail",
        "tags": [
          "Image Config"
        ]
      }
    },
    "/dsmcontroller/admin/namespaces/{namespace}/repository": {
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]\n\nRequired scope: social\n\nThis endpoint get a dedicated servers repository name in a namespace.",
        "operationId": "GetRepository",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get repository for a namespace",
        "tags": [
          "Image Config"
        ]
      }
    },
    "/dsmcontroller/admin/namespaces/{namespace}/servers": {
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:SERVER [READ]\n\nRequired scope: social\n\nThis endpoint lists all of dedicated servers in a namespace managed by this service.\n\nParameter Offset and Count is Required",
        "operationId": "ListServer",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:SERVER [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "List all managed servers in a region",
        "tags": [
          "Admin"
        ]
      }
    },
    "/dsmcontroller/admin/namespaces/{namespace}/servers/count": {
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:SERVER [READ]\n\nRequired scope: social\n\nThis endpoint counts all of dedicated servers in a namespace managed by this service.",
        "operationId": "CountServer",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:SERVER [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Count all managed servers",
        "tags": [
          "Admin"
        ]
      }
    },
    "/dsmcontroller/admin/namespaces/{namespace}/servers/count/detailed": {
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:SERVER [READ]\n\nRequired scope: social\n\nThis endpoint counts all of dedicated servers in a region managed by this service.",
        "operationId": "CountServerDetailed",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:SERVER [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get detailed count of managed servers in a region",
        "tags": [
          "Admin"
        ]
      }
    },
    "/dsmcontroller/admin/namespaces/{namespace}/servers/local": {
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:SERVER [READ]\n\nRequired scope: social\n\nThis endpoint lists all of local dedicated servers in a namespace managed by this service.",
        "operationId": "ListLocalServer",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:SERVER [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "List all managed local servers",
        "tags": [
          "Admin"
        ]
      }
    },
    "/dsmcontroller/admin/namespaces/{namespace}/servers/local/{name}": {
      "delete": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:SERVER [DELETE]\n\nRequired scope: social\n\nThis endpoint deletes a specified local dedicated server from DB.\nNote that DSM has no ability to shutdown local DS.",
        "operationId": "DeleteLocalServer",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:SERVER [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete a local server",
        "tags": [
          "Admin"
        ]
      }
    },
    "/dsmcontroller/admin/namespaces/{namespace}/servers/{podName}": {
      "delete": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:SERVER [DELETE]\n\nRequired scope: social\n\nThis endpoint deletes a specified dedicated server from DB and terminates the DS pod.",
        "operationId": "DeleteServer",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:SERVER [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete a server in a region",
        "tags": [
          "Admin"
        ]
      },
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:SERVER [READ]\n\nRequired scope: social\n\nThis endpoint queries a specified dedicated server from DB.",
        "operationId": "GetServer",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:SERVER [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Query a server in a region",
        "tags": [
          "Admin"
        ]
      }
    },
    "/dsmcontroller/admin/namespaces/{namespace}/sessions": {
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:SESSION [READ]\n\nRequired scope: social\n\nThis endpoint lists all of sessions in a namespace managed by this service.\n\nParameter Offset and Count is Required",
        "operationId": "ListSession",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:SESSION [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "List all managed sessions in a region",
        "tags": [
          "Admin"
        ]
      }
    },
    "/dsmcontroller/admin/namespaces/{namespace}/sessions/count": {
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:SESSION [READ]\n\nRequired scope: social\n\nThis endpoint count all of sessions in a namespace managed by this service.",
        "operationId": "CountSession",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:SESSION [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Count all sessions",
        "tags": [
          "Admin"
        ]
      }
    },
    "/dsmcontroller/admin/namespaces/{namespace}/sessions/{sessionID}": {
      "delete": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:SESSION [DELETE]\n\nRequired scope: social\n\nThis endpoint deletes a specified session and its corresponding match result from DB.",
        "operationId": "DeleteSession",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:SESSION [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete a session in a region",
        "tags": [
          "Admin"
        ]
      }
    },
    "/dsmcontroller/admin/repository": {
      "post": {
        "description": "```\nRequired permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [CREATE]\nRequired scope: social\n\nThis endpoint will create image repository.\n\nSample repository:\n{\n\t\u0026#34;namespace\u0026#34;:\u0026#34;testing\u0026#34;,\n\t\u0026#34;repository\u0026#34;:\u0026#34;ds-testing-924623\u0026#34;,\n}\n```",
        "operationId": "CreateRepository",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Create repository",
        "tags": [
          "Image Config"
        ]
      }
    },
    "/dsmcontroller/admin/v1/namespaces/{namespace}/configs/export": {
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]\n\nRequired scope: social\n\nThis endpoint export a dedicated servers config in a namespace.\n",
        "operationId": "exportConfigV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "export DSM Controller configuration for a namespace",
        "tags": [
          "Config"
        ]
      }
    },
    "/dsmcontroller/admin/v1/namespaces/{namespace}/configs/import": {
      "post": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [CREATE]\n\nRequired scope: social\n\nThis endpoint import a dedicated servers config in a namespace.\n\nIf there is an existing configuration, the configuration would be replaced.\n",
        "operationId": "importConfigV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:DSM:CONFIG [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "import config for a namespace",
        "tags": [
          "Config"
        ]
      }
    },
    "/dsmcontroller/namespaces/{namespace}/configs/deployments": {
      "get": {
        "description": "Required permission: NAMESPACE:{namespace}:DSM:CONFIG [READ]\n\nRequired scope: social\n\nThis endpoint get a all deployments in a namespace\n\nParameter Offset and Count is Required",
        "operationId": "GetAllDeploymentClient",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:DSM:CONFIG [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get All Deployments for client",
        "tags": [
          "Deployment Config"
        ]
      }
    },
    "/dsmcontroller/namespaces/{namespace}/configs/deployments/{deployment}": {
      "delete": {
        "description": "Required permission: NAMESPACE:{namespace}:DSM:CONFIG [DELETE]\n\nRequired scope: social\n\nThis endpoint delete a dedicated server deployment in a namespace",
        "operationId": "DeleteDeploymentClient",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:DSM:CONFIG [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete Deployment for client",
        "tags": [
          "Deployment Config"
        ]
      },
      "post": {
        "description": "Required permission: NAMESPACE:{namespace}:DSM:CONFIG [CREATE]\n\nRequired scope: social\n\nThis endpoint create a dedicated servers deployment in a namespace.",
        "operationId": "CreateDeploymentClient",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:DSM:CONFIG [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Create deployment for client",
        "tags": [
          "Deployment Config"
        ]
      }
    },
    "/dsmcontroller/namespaces/{namespace}/configs/pods": {
      "get": {
        "description": "Required permission: NAMESPACE:{namespace}:DSM:CONFIG [READ]\n\nRequired scope: social\n\nThis endpoint get a all pod configs in a namespace\n\nParameter Offset and Count is Required",
        "operationId": "GetAllPodConfigClient",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:DSM:CONFIG [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get all pod configs for client",
        "tags": [
          "Pod Config"
        ]
      }
    },
    "/dsmcontroller/namespaces/{namespace}/configs/pods/{name}": {
      "delete": {
        "description": "Required permission: NAMESPACE:{namespace}:DSM:CONFIG [DELETE]\n\nRequired scope: social\n\nThis endpoint delete a dedicated server pod config in a namespace",
        "operationId": "DeletePodConfigClient",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:DSM:CONFIG [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete pod config for client",
        "tags": [
          "Pod Config"
        ]
      },
      "post": {
        "description": "Required permission: NAMESPACE:{namespace}:DSM:CONFIG [CREATE]\n\nRequired scope: social\n\nThis endpoint create a dedicated servers pod config in a namespace.",
        "operationId": "CreatePodConfigClient",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:DSM:CONFIG [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Create pod config for client",
        "tags": [
          "Pod Config"
        ]
      }
    },
    "/dsmcontroller/namespaces/{namespace}/images/limit": {
      "get": {
        "description": "Required permission: NAMESPACE:{namespace}:DSM:CONFIG [READ]\n\nRequired scope: social\n\nThis endpoint get DS image limit for specific namespace.This endpoint also give the non-persistent image which is used by any deployments",
        "operationId": "ImageLimitClient",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:DSM:CONFIG [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "DS Image Limit for Client",
        "tags": [
          "Image Config"
        ]
      }
    },
    "/dsmcontroller/namespaces/{namespace}/images/versions/{version}": {
      "get": {
        "description": "Required permission: NAMESPACE:{namespace}:DSM:CONFIG [READ]\n\nRequired scope: social\n\nThis endpoint get specific version of dedicated servers images.",
        "operationId": "ImageDetailClient",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:DSM:CONFIG [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "DS Image Detail Client",
        "tags": [
          "Image Config"
        ]
      }
    },
    "/dsmcontroller/namespaces/{namespace}/servers": {
      "get": {
        "description": "Required permission: NAMESPACE:{namespace}:DSM:SERVER [READ]\n\nRequired scope: social\n\nThis endpoint lists all of dedicated servers in a namespace managed by this service.\n\nParameter Offset and Count is Required",
        "operationId": "ListServerClient",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:DSM:SERVER [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "List all managed servers in a region for client",
        "tags": [
          "Server"
        ]
      }
    },
    "/dsmcontroller/namespaces/{namespace}/servers/heartbeat": {
      "put": {
        "description": "```\nRequired permission: NAMESPACE:{namespace}:DSM:SERVER [UPDATE]\nRequired scope: social\n\nThis endpoint is intended to be called by dedicated server\nwhich already has claimed to extend its lifetime.\nDS should call this periodically after it claimed.\nThe timeframe between 2 heartbeat call should be smaller than\nthe session timout in the deployment configuration.\nIf the last heartbeat is longer than the session timout, the server.\nwill be considered as expired an[...]",
        "operationId": "ServerHeartbeat",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:DSM:SERVER [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Server Heartbeat",
        "tags": [
          "Server"
        ]
      }
    },
    "/dsmcontroller/namespaces/{namespace}/servers/local/deregister": {
      "post": {
        "description": "```\nRequired permission: NAMESPACE:{namespace}:DSM:SERVER [UPDATE]\nRequired scope: social\n\nThis endpoint is intended to be called by local dedicated server\nto let DSM know that it is shutting down.\n\nCalling this will remove the server records from DB.```",
        "operationId": "DeregisterLocalServer",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:DSM:SERVER [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Deregister local DS",
        "tags": [
          "Server"
        ]
      }
    },
    "/dsmcontroller/namespaces/{namespace}/servers/local/register": {
      "post": {
        "description": "```\nRequired permission: NAMESPACE:{namespace}:DSM:SERVER [UPDATE]\nRequired scope: social\n\nUse the alternative GET of the same endpoint to upgrade DS connection to DSM via websocket.\n\nThis endpoint is intended to be called by local dedicated server to let DSM know that it is ready for use.\nUse local DS only for development purposes since DSM wouldn\u0026#39;t be able to properly manage local DS in production.\nThis MUST be called by DS after it is ready to accept m[...]",
        "operationId": "RegisterLocalServer",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:DSM:SERVER [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Register a local DS",
        "tags": [
          "Server"
        ]
      }
    },
    "/dsmcontroller/namespaces/{namespace}/servers/register": {
      "post": {
        "description": "```\nRequired permission: NAMESPACE:{namespace}:DSM:SERVER [UPDATE]\nRequired scope: social\n\nThis endpoint is intended to be called by dedicated server to let DSM know that it is ready for use.\nThis MUST be called by DS after it is ready to accept match data and incoming client connections.\n\nUpon successfully calling this endpoint, the dedicated\nserver is listed under READY servers.```",
        "operationId": "RegisterServer",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:DSM:SERVER [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Register a DS",
        "tags": [
          "Server"
        ]
      }
    },
    "/dsmcontroller/namespaces/{namespace}/servers/shutdown": {
      "post": {
        "description": "Required permission: NAMESPACE:{namespace}:DSM:SERVER [UPDATE]\n\nRequired scope: social\n\nThis endpoint is intended to be called by dedicated server to let DSM know that it is shutting down. Calling this will remove the server and session records from DB.Set \u0026#39;kill_me\u0026#39; in request to \u0026#39;true\u0026#39; if the DS cannot shut itself down.",
        "operationId": "ShutdownServer",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:DSM:SERVER [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Mark a DS is shutting down",
        "tags": [
          "Server"
        ]
      }
    },
    "/dsmcontroller/namespaces/{namespace}/servers/{podName}/config/sessiontimeout": {
      "get": {
        "description": "```\nRequired permission: NAMESPACE:{namespace}:DSM:CONFIG [READ]\nRequired scope: social\n\nThis endpoint is intended to be called by dedicated server\nto get the session timeout that will be used for the DS.\nDS will use this session timeout to make sure it regularly make heartbeat\ncall to the DSMC, before the session timeout.```",
        "operationId": "GetServerSessionTimeout",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:DSM:CONFIG [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get the session timeout that will be used for the server",
        "tags": [
          "Server"
        ]
      }
    },
    "/dsmcontroller/namespaces/{namespace}/servers/{podName}/session": {
      "get": {
        "description": "```\nRequired permission: NAMESPACE:{namespace}:DSM:SERVER [UPDATE]\nRequired scope: social\n\nThis endpoint is intended to be called by dedicated server\nto query its session ID.\nDS should call this when it first receive player connection,\nto see if it is actually claimed```",
        "operationId": "GetServerSession",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:DSM:SERVER [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get Session ID",
        "tags": [
          "Server"
        ]
      }
    },
    "/dsmcontroller/namespaces/{namespace}/sessions": {
      "post": {
        "description": "Required permission: NAMESPACE:{namespace}:DSM:SESSION [CREATE]\n\nRequired scope: social\n\nThis endpoint is intended to be called by game session manager (matchmaker, lobby, etc.) to get a dedicated server for a game session.\n\nIf a dedicated server is available, it will respond with a dedicated server details ready to be used.\n\nOtherwise it will trigger new dedicated server creation and respond with a server status CREATING. The game session manager then expected to[...]",
        "operationId": "CreateSession",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:DSM:SESSION [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Register a new game session",
        "tags": [
          "Session"
        ]
      }
    },
    "/dsmcontroller/namespaces/{namespace}/sessions/claim": {
      "post": {
        "description": "Required permission: NAMESPACE:{namespace}:DSM:SESSION [UPDATE]\n\nRequired scope: social\n\nThis endpoint is intended to be called by game session manager (matchmaker, lobby, etc.) to claim a dedicated server. The dedicated server cannot be claimed unless the status is READY",
        "operationId": "ClaimServer",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:DSM:SESSION [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Claim a DS for a game session",
        "tags": [
          "Session"
        ]
      }
    },
    "/dsmcontroller/namespaces/{namespace}/sessions/{sessionID}": {
      "get": {
        "description": "Required permission: NAMESPACE:{namespace}:DSM:SESSION [READ]\n\nRequired scope: social\n\nThis endpoint is intended to be called by game session manager (matchmaker, lobby, etc.) to query the status of dedicated server that is created for the session.\n\nThe server is ready to use when the status is READY. At which point, the game session manager can claim the server using the GET /namespaces/{namespace}/sessions/{sessionID}/claim endpoint",
        "operationId": "GetSession",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:DSM:SESSION [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Query specified session",
        "tags": [
          "Session"
        ]
      }
    },
    "/dsmcontroller/namespaces/{namespace}/sessions/{sessionID}/cancel": {
      "delete": {
        "description": "Required permission: NAMESPACE:{namespace}:DSM:SESSION [DELETE]\n\nRequired scope: social\n\nThis endpoint is intended to be called by game session manager (matchmaker, lobby, etc.) to cancel a temporary dedicated server. The dedicated server cannot be canceled unless the status is CREATING",
        "operationId": "CancelSession",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:DSM:SESSION [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Cancel session of a Temporary DS",
        "tags": [
          "Session"
        ]
      }
    },
    "/dsmcontroller/public/provider/default": {
      "get": {
        "description": "This endpoints returns the default provider.",
        "operationId": "GetDefaultProvider",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get default provider",
        "tags": [
          "Public"
        ]
      }
    },
    "/dsmcontroller/public/providers": {
      "get": {
        "description": "This endpoints returns list of supported providers. Armada is the default provider.",
        "operationId": "ListProviders",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "List all supported providers",
        "tags": [
          "Public"
        ]
      }
    },
    "/dsmcontroller/public/providers/regions/{region}": {
      "get": {
        "description": "This endpoint returns the providers by region.",
        "operationId": "ListProvidersByRegion",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "List providers by region",
        "tags": [
          "Public"
        ]
      }
    },
    "/dsmcontroller/v1/messages": {
      "get": {
        "description": "get the list of messages.",
        "operationId": "publicGetMessages",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "get service messages",
        "tags": [
          "Dsmc Operations"
        ]
      }
    }
  },
  "x-docs": {
    "alias": "dsmcontroller",
    "host": "https://stage.accelbyte.io",
    "path": "/dsmcontroller/apidocs/api.json"
  },
  "x-version": {
    "buildDate": "unknown",
    "gitHash": "b711d461472e6a064db4aef9014234176d88a58b",
    "name": "justice-dedicated-server-manager-controller-service",
    "revisionID": "6.3.3",
    "version": "6.3.3",
    "version-roles-seeding": "0.0.3"
  }
}