{
  "host": "demo.accelbyte.io",
  "info": {
    "description": "Justice Event Log Service",
    "title": "justice-event-log-service",
    "version": ""
  },
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "HasPermission": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {
        "ADMIN:NAMESPACE:{namespace}:EVENT [CREATE]": "ADMIN:NAMESPACE:{namespace}:EVENT [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:EVENT [DELETE]": "ADMIN:NAMESPACE:{namespace}:EVENT [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:EVENT [READ]": "ADMIN:NAMESPACE:{namespace}:EVENT [READ]",
        "ADMIN:NAMESPACE:{namespace}:EVENT [UPDATE]": "ADMIN:NAMESPACE:{namespace}:EVENT [UPDATE]",
        "NAMESPACE:{namespace}:EVENT [CREATE]": "NAMESPACE:{namespace}:EVENT [CREATE]",
        "NAMESPACE:{namespace}:EVENT [UPDATE]": "NAMESPACE:{namespace}:EVENT [UPDATE]"
      },
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "HasScope": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {
        "analytics": "analytics"
      },
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "authorization": {
      "in": "header",
      "name": "Authorization",
      "type": "apiKey"
    }
  },
  "swagger": "2.0",
  "paths": {
    "/event/descriptions/agentType": {
      "get": {
        "deprecated": true,
        "operationId": "AgentTypeDescriptionHandler",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get list of agent type and the descriptions",
        "tags": [
          "Event Descriptions"
        ]
      }
    },
    "/event/descriptions/agentType/listByAgentTypes": {
      "get": {
        "deprecated": true,
        "operationId": "SpecificAgentTypeDescriptionHandler",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get specific list of agent type and the descriptions by comma separated value of agent types",
        "tags": [
          "Event Descriptions"
        ]
      }
    },
    "/event/descriptions/eventId": {
      "get": {
        "deprecated": true,
        "operationId": "EventIDDescriptionHandler",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get list of eventID and the descriptions",
        "tags": [
          "Event Descriptions"
        ]
      }
    },
    "/event/descriptions/eventId/listByEventIds": {
      "get": {
        "deprecated": true,
        "operationId": "SpecificEventIDDescriptionHandler",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get specific list of eventID and the descriptions by comma separated value of eventIDs",
        "tags": [
          "Event Descriptions"
        ]
      }
    },
    "/event/descriptions/eventLevel": {
      "get": {
        "deprecated": true,
        "operationId": "EventLevelDescriptionHandler",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get list of event level and the descriptions",
        "tags": [
          "Event Descriptions"
        ]
      }
    },
    "/event/descriptions/eventLevel/listByEventLevels": {
      "get": {
        "deprecated": true,
        "operationId": "SpecificEventLevelDescriptionHandler",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get specific list of event level and the descriptions by comma separated value of event levels",
        "tags": [
          "Event Descriptions"
        ]
      }
    },
    "/event/descriptions/eventType": {
      "get": {
        "deprecated": true,
        "operationId": "EventTypeDescriptionHandler",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get list of event type and the descriptions",
        "tags": [
          "Event Descriptions"
        ]
      }
    },
    "/event/descriptions/eventType/listByEventTypes": {
      "get": {
        "deprecated": true,
        "operationId": "SpecificEventTypeDescriptionHandler",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get specific list of event type and the descriptions by comma separated value of event types",
        "tags": [
          "Event Descriptions"
        ]
      }
    },
    "/event/descriptions/ux": {
      "get": {
        "deprecated": true,
        "operationId": "UXNameDescriptionHandler",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get list of ux name and the descriptions",
        "tags": [
          "Event Descriptions"
        ]
      }
    },
    "/event/descriptions/ux/listByUx": {
      "get": {
        "deprecated": true,
        "operationId": "SpecificUXDescriptionHandler",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get specific list of UX and the descriptions by comma separated value of UX",
        "tags": [
          "Event Descriptions"
        ]
      }
    },
    "/event/namespaces/{namespace}": {
      "get": {
        "deprecated": true,
        "description": "Required permission \u0026lt;code\u0026gt;NAMESPACE:{namespace}:EVENT [UPDATE]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;analytics\u0026lt;/code\u0026gt;",
        "operationId": "GetEventByNamespaceHandler",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:EVENT [UPDATE]"
            ],
            "HasScope": [
              "analytics"
            ],
            "authorization": []
          }
        ],
        "summary": "Get events from all users in a namespace",
        "tags": [
          "Event"
        ]
      },
      "post": {
        "deprecated": true,
        "description": "Required permission \u0026lt;code\u0026gt;NAMESPACE:{namespace}:EVENT [CREATE]\u0026lt;/code\u0026gt;and scope \u0026lt;code\u0026gt;analytics\u0026lt;/code\u0026gt;",
        "operationId": "PostEventHandler",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:EVENT [CREATE]"
            ],
            "HasScope": [
              "analytics"
            ],
            "authorization": []
          }
        ],
        "summary": "Post an activity log",
        "tags": [
          "Event"
        ]
      }
    },
    "/event/namespaces/{namespace}/eventId/{eventId}": {
      "get": {
        "deprecated": true,
        "description": "Required permission \u0026lt;code\u0026gt;NAMESPACE:{namespace}:EVENT [UPDATE]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;analytics\u0026lt;/code\u0026gt;",
        "operationId": "GetEventByEventIDHandler",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:EVENT [UPDATE]"
            ],
            "HasScope": [
              "analytics"
            ],
            "authorization": []
          }
        ],
        "summary": "Get events from all users in a namespace with specific eventID",
        "tags": [
          "Event"
        ]
      }
    },
    "/event/namespaces/{namespace}/eventType/{eventType}": {
      "get": {
        "deprecated": true,
        "description": "Required permission \u0026lt;code\u0026gt;NAMESPACE:{namespace}:EVENT [UPDATE]\u0026lt;/code\u0026gt;and scope \u0026lt;code\u0026gt;analytics\u0026lt;/code\u0026gt;",
        "operationId": "GetEventByEventTypeHandler",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:EVENT [UPDATE]"
            ],
            "HasScope": [
              "analytics"
            ],
            "authorization": []
          }
        ],
        "summary": "Get events from all users in a namespace with specific eventType",
        "tags": [
          "Event"
        ]
      }
    },
    "/event/namespaces/{namespace}/eventType/{eventType}/eventId/{eventId}": {
      "get": {
        "deprecated": true,
        "description": "Required permission \u0026lt;code\u0026gt;NAMESPACE:{namespace}:EVENT [UPDATE]\u0026lt;/code\u0026gt;and scope \u0026lt;code\u0026gt;analytics\u0026lt;/code\u0026gt;",
        "operationId": "GetEventByEventTypeAndEventIDHandler",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:EVENT [UPDATE]"
            ],
            "HasScope": [
              "analytics"
            ],
            "authorization": []
          }
        ],
        "summary": "Get events from all users in a namespace with specific eventID and eventType",
        "tags": [
          "Event"
        ]
      }
    },
    "/event/namespaces/{namespace}/users/{userId}": {
      "get": {
        "deprecated": true,
        "description": "Required permission \u0026lt;code\u0026gt;NAMESPACE:{namespace}:EVENT [UPDATE]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;analytics\u0026lt;/code\u0026gt;",
        "operationId": "GetEventByUserIDHandler",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:EVENT [UPDATE]"
            ],
            "HasScope": [
              "analytics"
            ],
            "authorization": []
          }
        ],
        "summary": "Get events from specific user",
        "tags": [
          "Event"
        ]
      }
    },
    "/event/namespaces/{namespace}/users/{userId}/activities": {
      "delete": {
        "deprecated": true,
        "description": "Required permission \u0026lt;code\u0026gt;NAMESPACE:{namespace}:EVENT [UPDATE]\u0026lt;/code\u0026gt;and scope \u0026lt;code\u0026gt;analytics\u0026lt;/code\u0026gt;",
        "operationId": "DeleteUserActivitiesHandler",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:EVENT [UPDATE]"
            ],
            "HasScope": [
              "analytics"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete all user's activities",
        "tags": [
          "User Information"
        ]
      },
      "get": {
        "deprecated": true,
        "description": "Required permission \u0026lt;code\u0026gt;NAMESPACE:{namespace}:EVENT [UPDATE]\u0026lt;/code\u0026gt;and scope \u0026lt;code\u0026gt;analytics\u0026lt;/code\u0026gt;",
        "operationId": "GetUserActivitiesHandler",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:EVENT [UPDATE]"
            ],
            "HasScope": [
              "analytics"
            ],
            "authorization": []
          }
        ],
        "summary": "Get all user's activities",
        "tags": [
          "User Information"
        ]
      }
    },
    "/event/namespaces/{namespace}/users/{userId}/eventId/{eventId}": {
      "get": {
        "deprecated": true,
        "description": "Required permission \u0026lt;code\u0026gt;NAMESPACE:{namespace}:EVENT [UPDATE]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;analytics\u0026lt;/code\u0026gt;",
        "operationId": "GetEventByUserIDAndEventIDHandler",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:EVENT [UPDATE]"
            ],
            "HasScope": [
              "analytics"
            ],
            "authorization": []
          }
        ],
        "summary": "Get events from specific user with specific eventID",
        "tags": [
          "Event"
        ]
      }
    },
    "/event/namespaces/{namespace}/users/{userId}/eventType/{eventType}": {
      "get": {
        "deprecated": true,
        "description": "Required permission \u0026lt;code\u0026gt;NAMESPACE:{namespace}:EVENT [UPDATE]and scope \u0026lt;code\u0026gt;analytics\u0026lt;/code\u0026gt;",
        "operationId": "GetEventByUserIDAndEventTypeHandler",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:EVENT [UPDATE]"
            ],
            "HasScope": [
              "analytics"
            ],
            "authorization": []
          }
        ],
        "summary": "Get events from specific user with specific eventType",
        "tags": [
          "Event"
        ]
      }
    },
    "/event/namespaces/{namespace}/users/{userId}/eventType/{eventType}/eventId/{eventId}": {
      "get": {
        "deprecated": true,
        "description": "Required permission \u0026lt;code\u0026gt;NAMESPACE:{namespace}:EVENT [UPDATE]\u0026lt;/code\u0026gt;and scope \u0026lt;code\u0026gt;analytics\u0026lt;/code\u0026gt;",
        "operationId": "GetEventByUserEventIDAndEventTypeHandler",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:EVENT [UPDATE]"
            ],
            "HasScope": [
              "analytics"
            ],
            "authorization": []
          }
        ],
        "summary": "Get events from specific user with specific eventID and eventType",
        "tags": [
          "Event"
        ]
      }
    },
    "/event/namespaces/{namespace}/users/{userId}/lastActivityTime": {
      "get": {
        "deprecated": true,
        "description": "Required permission \u0026lt;code\u0026gt;NAMESPACE:{namespace}:EVENT [UPDATE]\u0026lt;/code\u0026gt;and scope \u0026lt;code\u0026gt;analytics\u0026lt;/code\u0026gt;",
        "operationId": "LastUserActivityTimeHandler",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:EVENT [UPDATE]"
            ],
            "HasScope": [
              "analytics"
            ],
            "authorization": []
          }
        ],
        "summary": "Get last activity time of a user in a namespace",
        "tags": [
          "User Information"
        ]
      }
    },
    "/event/registry/eventIds": {
      "get": {
        "deprecated": true,
        "description": "Required permission \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:EVENT [READ]\u0026lt;/code\u0026gt;and scope \u0026lt;code\u0026gt;analytics\u0026lt;/code\u0026gt;",
        "operationId": "GetRegisteredEventsHandler",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:EVENT [READ]"
            ],
            "HasScope": [
              "analytics"
            ],
            "authorization": []
          }
        ],
        "summary": "Get registered events in the Event Registry",
        "tags": [
          "Event Registry"
        ]
      },
      "post": {
        "deprecated": true,
        "description": "Required permission \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:EVENT [CREATE]\u0026lt;/code\u0026gt;and scope \u0026lt;code\u0026gt;analytics\u0026lt;/code\u0026gt;",
        "operationId": "RegisterEventHandler",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:EVENT [CREATE]"
            ],
            "HasScope": [
              "analytics"
            ],
            "authorization": []
          }
        ],
        "summary": "Register an eventID to the Event Registry",
        "tags": [
          "Event Registry"
        ]
      }
    },
    "/event/registry/eventIds/{eventId}": {
      "delete": {
        "deprecated": true,
        "description": "Required permission \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:EVENT [DELETE]\u0026lt;/code\u0026gt;and scope \u0026lt;code\u0026gt;analytics\u0026lt;/code\u0026gt;",
        "operationId": "UnregisterEventIDHandler",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:EVENT [DELETE]"
            ],
            "HasScope": [
              "analytics"
            ],
            "authorization": []
          }
        ],
        "summary": "Unregister eventID from the Event Registry",
        "tags": [
          "Event Registry"
        ]
      },
      "get": {
        "deprecated": true,
        "description": "Required permission \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:EVENT [READ]\u0026lt;/code\u0026gt;and scope \u0026lt;code\u0026gt;analytics\u0026lt;/code\u0026gt;",
        "operationId": "GetRegisteredEventIDHandler",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:EVENT [READ]"
            ],
            "HasScope": [
              "analytics"
            ],
            "authorization": []
          }
        ],
        "summary": "Get registered eventID data from the Event Registry",
        "tags": [
          "Event Registry"
        ]
      },
      "post": {
        "deprecated": true,
        "description": "Required permission \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:EVENT [UPDATE]\u0026lt;/code\u0026gt;and scope \u0026lt;code\u0026gt;analytics\u0026lt;/code\u0026gt;",
        "operationId": "UpdateEventRegistryHandler",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:EVENT [UPDATE]"
            ],
            "HasScope": [
              "analytics"
            ],
            "authorization": []
          }
        ],
        "summary": "Update an eventID data in the Event Registry",
        "tags": [
          "Event Registry"
        ]
      }
    },
    "/event/registry/eventTypes/{eventType}": {
      "get": {
        "deprecated": true,
        "description": "Required permission \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:EVENT [READ]\u0026lt;/code\u0026gt;and scope \u0026lt;code\u0026gt;analytics\u0026lt;/code\u0026gt;",
        "operationId": "GetRegisteredEventsByEventTypeHandler",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:EVENT [READ]"
            ],
            "HasScope": [
              "analytics"
            ],
            "authorization": []
          }
        ],
        "summary": "Get registered eventID data from the Event Registry based on the event type",
        "tags": [
          "Event Registry"
        ]
      }
    },
    "/event/v2/admin/namespaces/{namespace}/query": {
      "post": {
        "description": "\u0026lt;p\u0026gt;This endpoint is using POST which is somewhat unfamiliar, \n\t\t\tbut it\u0026#39;s logical that we have to send/post a filter (search term) in order to get the data.\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;This endpoint will not return anything if you give it an empty filters in the request body. \u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;Required permission \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:EVENT [READ]\u0026lt;/code\u0026gt;[...]",
        "operationId": "QueryEventStreamHandler",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:EVENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "A generic query to get a set of events based on the provided filters",
        "tags": [
          "Event V2"
        ]
      }
    },
    "/event/v2/admin/namespaces/{namespace}/users/{userId}/event": {
      "get": {
        "description": "Required permission \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:EVENT [READ]\u0026lt;/code\u0026gt;and scope \u0026lt;code\u0026gt;analytics\u0026lt;/code\u0026gt;",
        "operationId": "GetEventSpecificUserV2Handler",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:EVENT [READ]"
            ],
            "HasScope": [
              "analytics"
            ],
            "authorization": []
          }
        ],
        "summary": "Get events from a specific user",
        "tags": [
          "Event V2"
        ]
      }
    },
    "/event/v2/public/namespaces/{namespace}/users/{userId}/edithistory": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Available Type: \u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;ul\u0026gt;\n\t\t\t\t\u0026lt;li\u0026gt;email\u0026lt;/li\u0026gt;\n\t\t\t\t\u0026lt;li\u0026gt;password\u0026lt;/li\u0026gt;\n\t\t\t\t\u0026lt;li\u0026gt;displayname\u0026lt;/li\u0026gt;\n\t\t\t\t\u0026lt;li\u0026gt;dateofbirth\u0026lt;/li\u0026gt;\n\t\t\t\t\u0026lt;li\u0026gt;country\u0026lt;/li\u0026gt;\n\t\t\t\t\u0026lt;li\u0026gt;language\u0026lt;/li\u0026gt;\n\t\t\t\u0026lt;/ul\u0026gt;\n\t\t\t[...]",
        "operationId": "GetPublicEditHistory",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get a user edit history based on the provided type",
        "tags": [
          "Event V2"
        ]
      }
    },
    "/event/v2/public/namespaces/{namespace}/users/{userId}/event": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Requires valid user access token\u0026lt;/p\u0026gt;",
        "operationId": "GetUserEventsV2Public",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get events from a specific user",
        "tags": [
          "Event V2"
        ]
      }
    }
  },
  "x-docs": {
    "alias": "event",
    "host": "https://stage.accelbyte.io",
    "path": "/event/apidocs/api.json"
  },
  "x-version": {
    "buildDate": "2023-04-27T01:37:53+00:00",
    "gitHash": "89fe404cf31775652711a54b75bce82c16b5a232",
    "name": "justice-event-log-service",
    "realm": "staging",
    "version": "2.0.2",
    "version-roles-seeding": "0.0.3"
  }
}