{
  "host": "demo.accelbyte.io",
  "info": {
    "contact": {
      "email": "engineering@accelbyte.io",
      "name": "Engineering Team at AccelByte",
      "url": "https://accelbyte.io"
    },
    "description": "Justice GDPR Service",
    "title": "justice-gdpr-service",
    "version": "2.3.0"
  },
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "HasPermission": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {
        "ADMIN:NAMESPACE:{namespace}:EMAIL:CONFIGURATION [CREATE]": "ADMIN:NAMESPACE:{namespace}:EMAIL:CONFIGURATION [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:EMAIL:CONFIGURATION [DELETE]": "ADMIN:NAMESPACE:{namespace}:EMAIL:CONFIGURATION [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:EMAIL:CONFIGURATION [READ]": "ADMIN:NAMESPACE:{namespace}:EMAIL:CONFIGURATION [READ]",
        "ADMIN:NAMESPACE:{namespace}:EMAIL:CONFIGURATION [UPDATE]": "ADMIN:NAMESPACE:{namespace}:EMAIL:CONFIGURATION [UPDATE]",
        "ADMIN:NAMESPACE:{namespace}:GDPR:CONFIGURATION [DELETE]": "ADMIN:NAMESPACE:{namespace}:GDPR:CONFIGURATION [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:GDPR:CONFIGURATION [READ]": "ADMIN:NAMESPACE:{namespace}:GDPR:CONFIGURATION [READ]",
        "ADMIN:NAMESPACE:{namespace}:GDPR:CONFIGURATION [UPDATE]": "ADMIN:NAMESPACE:{namespace}:GDPR:CONFIGURATION [UPDATE]",
        "ADMIN:NAMESPACE:{namespace}:INFORMATION:USER [READ]": "ADMIN:NAMESPACE:{namespace}:INFORMATION:USER [READ]",
        "ADMIN:NAMESPACE:{namespace}:INFORMATION:USER:{userId} [CREATE]": "ADMIN:NAMESPACE:{namespace}:INFORMATION:USER:{userId} [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:INFORMATION:USER:{userId} [DELETE]": "ADMIN:NAMESPACE:{namespace}:INFORMATION:USER:{userId} [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:INFORMATION:USER:{userId} [READ]": "ADMIN:NAMESPACE:{namespace}:INFORMATION:USER:{userId} [READ]"
      },
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "HasScope": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {
        "account": "account"
      },
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "authorization": {
      "in": "header",
      "name": "Authorization",
      "type": "apiKey"
    }
  },
  "swagger": "2.0",
  "paths": {
    "/gdpr/admin/namespaces/{namespace}/deletions": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:INFORMATION:USER[READ]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;account\u0026lt;/code\u0026gt;\u0026lt;/p\u0026gt;",
        "operationId": "AdminGetListDeletionDataRequest",
        "security": [
          {
            "HasPermission": [],
            "HasScope": [
              "account"
            ],
            "authorization": []
          }
        ],
        "summary": "Retrieve all user's account deletion requests in specified date",
        "tags": [
          "Data Deletion"
        ]
      }
    },
    "/gdpr/admin/namespaces/{namespace}/emails/configurations": {
      "delete": {
        "description": "Delete a list of admin email addresses to stop receiving personal data request notification. \n\t\t\t\u0026lt;p\u0026gt;Required permission \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:EMAIL:CONFIGURATION [DELETE]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;account\u0026lt;/code\u0026gt;\u0026lt;/p\u0026gt;",
        "operationId": "DeleteAdminEmailConfiguration",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:EMAIL:CONFIGURATION [DELETE]"
            ],
            "HasScope": [
              "account"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete admin emails configurations",
        "tags": [
          "Configuration"
        ]
      },
      "get": {
        "description": "Get list of admin email address configuration. \n\t\t\t\u0026lt;p\u0026gt;Required permission \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:EMAIL:CONFIGURATION [READ]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;account\u0026lt;/code\u0026gt;\u0026lt;/p\u0026gt;",
        "operationId": "GetAdminEmailConfiguration",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:EMAIL:CONFIGURATION [READ]"
            ],
            "HasScope": [
              "account"
            ],
            "authorization": []
          }
        ],
        "summary": "Get admin email addresses configuration",
        "tags": [
          "Configuration"
        ]
      },
      "post": {
        "description": "Add admin email address for receiving personal data request notification. \n\t\t\t\u0026lt;p\u0026gt;Required permission \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:EMAIL:CONFIGURATION [CREATE]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;account\u0026lt;/code\u0026gt;\u0026lt;/p\u0026gt;",
        "operationId": "SaveAdminEmailConfiguration",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:EMAIL:CONFIGURATION [CREATE]"
            ],
            "HasScope": [
              "account"
            ],
            "authorization": []
          }
        ],
        "summary": "Add admin email address configuration",
        "tags": [
          "Configuration"
        ]
      },
      "put": {
        "description": "Update admin email address for receiving personal data request notification. \u0026lt;p\u0026gt;Required permission \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:EMAIL:CONFIGURATION [UPDATE]\u0026lt;/code\u0026gt;\u0026lt;/p\u0026gt;",
        "operationId": "UpdateAdminEmailConfiguration",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:EMAIL:CONFIGURATION [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update admin email address configuration",
        "tags": [
          "Configuration"
        ]
      }
    },
    "/gdpr/admin/namespaces/{namespace}/requests": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:INFORMATION:USER [READ]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;account\u0026lt;/code\u0026gt;\u0026lt;/p\u0026gt;",
        "operationId": "AdminGetListPersonalDataRequest",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INFORMATION:USER [READ]"
            ],
            "HasScope": [
              "account"
            ],
            "authorization": []
          }
        ],
        "summary": "Get list personal data requests",
        "tags": [
          "Data Retrieval"
        ]
      }
    },
    "/gdpr/admin/namespaces/{namespace}/services/configurations": {
      "get": {
        "description": "Get Registered Services Configuration.\n\t\t\t\u0026lt;p\u0026gt;Required permission \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:GDPR:CONFIGURATION [READ]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;account\u0026lt;/code\u0026gt;\u0026lt;/p\u0026gt;",
        "operationId": "AdminGetServicesConfiguration",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:GDPR:CONFIGURATION [READ]"
            ],
            "HasScope": [
              "account"
            ],
            "authorization": []
          }
        ],
        "summary": "Get Registered Services Configuration",
        "tags": [
          "Configuration"
        ]
      },
      "put": {
        "description": "Update Registered Services Configuration.\n\t\t\t\u0026lt;p\u0026gt;Required permission \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:GDPR:CONFIGURATION [UPDATE]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;account\u0026lt;/code\u0026gt;\u0026lt;/p\u0026gt;",
        "operationId": "AdminUpdateServicesConfiguration",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:GDPR:CONFIGURATION [UPDATE]"
            ],
            "HasScope": [
              "account"
            ],
            "authorization": []
          }
        ],
        "summary": "Update Registered Services Configuration",
        "tags": [
          "Configuration"
        ]
      }
    },
    "/gdpr/admin/namespaces/{namespace}/services/configurations/reset": {
      "delete": {
        "description": "\u0026lt;b\u0026gt;[TEST FACILITY ONLY]\u0026lt;/b\u0026gt;\u0026lt;br/\u0026gt;Reset Registered Services Configuration to use the default configuration.\n\t\t\t\u0026lt;p\u0026gt;Required permission \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:GDPR:CONFIGURATION [DELETE]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;account\u0026lt;/code\u0026gt;\u0026lt;/p\u0026gt;",
        "operationId": "AdminResetServicesConfiguration",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:GDPR:CONFIGURATION [DELETE]"
            ],
            "HasScope": [
              "account"
            ],
            "authorization": []
          }
        ],
        "summary": "Reset Registered Services Configuration",
        "tags": [
          "Configuration"
        ]
      }
    },
    "/gdpr/admin/namespaces/{namespace}/users/{userId}/deletions": {
      "delete": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:INFORMATION:USER:{userId} [DELETE]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;account\u0026lt;/code\u0026gt;\u0026lt;/p\u0026gt;",
        "operationId": "AdminCancelUserAccountDeletionRequest",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INFORMATION:USER:{userId} [DELETE]"
            ],
            "HasScope": [
              "account"
            ],
            "authorization": []
          }
        ],
        "summary": "Cancel user's account deletion request",
        "tags": [
          "Data Deletion"
        ]
      },
      "get": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:INFORMATION:USER:{userId}[READ]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;account\u0026lt;/code\u0026gt;\u0026lt;/p\u0026gt;",
        "operationId": "AdminGetUserAccountDeletionRequest",
        "security": [
          {
            "HasPermission": [],
            "HasScope": [
              "account"
            ],
            "authorization": []
          }
        ],
        "summary": "Retrieve specific user's account deletion request",
        "tags": [
          "Data Deletion"
        ]
      },
      "post": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:INFORMATION:USER:{userId} [CREATE]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;account\u0026lt;/code\u0026gt;\u0026lt;/p\u0026gt;",
        "operationId": "AdminSubmitUserAccountDeletionRequest",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INFORMATION:USER:{userId} [CREATE]"
            ],
            "HasScope": [
              "account"
            ],
            "authorization": []
          }
        ],
        "summary": "Submit user's account deletion requests",
        "tags": [
          "Data Deletion"
        ]
      }
    },
    "/gdpr/admin/namespaces/{namespace}/users/{userId}/requests": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:INFORMATION:USER:{userId} [READ]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;account\u0026lt;/code\u0026gt;\u0026lt;/p\u0026gt;",
        "operationId": "AdminGetUserPersonalDataRequests",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INFORMATION:USER:{userId} [READ]"
            ],
            "HasScope": [
              "account"
            ],
            "authorization": []
          }
        ],
        "summary": "Get user's personal data requests",
        "tags": [
          "Data Retrieval"
        ]
      },
      "post": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:INFORMATION:USER:{userId} [CREATE]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;account\u0026lt;/code\u0026gt;\u0026lt;/p\u0026gt;\n\u0026lt;p\u0026gt;If admin request data for themselves, password is need to be set\u0026lt;/p\u0026gt;",
        "operationId": "AdminRequestDataRetrieval",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INFORMATION:USER:{userId} [CREATE]"
            ],
            "HasScope": [
              "account"
            ],
            "authorization": []
          }
        ],
        "summary": "Submit user personal data retrieval request",
        "tags": [
          "Data Retrieval"
        ]
      }
    },
    "/gdpr/admin/namespaces/{namespace}/users/{userId}/requests/{requestDate}": {
      "delete": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:INFORMATION:USER:{userId} [DELETE]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;account\u0026lt;/code\u0026gt;\u0026lt;/p\u0026gt;",
        "operationId": "AdminCancelUserPersonalDataRequest",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INFORMATION:USER:{userId} [DELETE]"
            ],
            "HasScope": [
              "account"
            ],
            "authorization": []
          }
        ],
        "summary": "Cancel user's personal data requests",
        "tags": [
          "Data Retrieval"
        ]
      }
    },
    "/gdpr/admin/namespaces/{namespace}/users/{userId}/requests/{requestDate}/generate": {
      "post": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:INFORMATION:USER:{userId} [READ]\u0026lt;/code\u0026gt; and scope \u0026lt;code\u0026gt;account\u0026lt;/code\u0026gt;\u0026lt;/p\u0026gt;",
        "operationId": "AdminGeneratePersonalDataURL",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INFORMATION:USER:{userId} [READ]"
            ],
            "HasScope": [
              "account"
            ],
            "authorization": []
          }
        ],
        "summary": "Generate personal data download url",
        "tags": [
          "Data Retrieval"
        ]
      }
    },
    "/gdpr/public/namespaces/{namespace}/users/{userId}/deletions": {
      "delete": {
        "description": "\u0026lt;p\u0026gt;Requires valid user access token\u0026lt;/p\u0026gt;",
        "operationId": "PublicCancelUserAccountDeletionRequest",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Cancel user's account deletion request",
        "tags": [
          "Data Deletion"
        ]
      },
      "post": {
        "description": "\u0026lt;p\u0026gt;Requires valid user access token and password",
        "operationId": "PublicSubmitUserAccountDeletionRequest",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Submit user's account deletion requests",
        "tags": [
          "Data Deletion"
        ]
      }
    },
    "/gdpr/public/namespaces/{namespace}/users/{userId}/deletions/status": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Requires valid user access token\u0026lt;/p\u0026gt;",
        "operationId": "PublicGetUserAccountDeletionStatus",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Retrieve specific user's account deletion status",
        "tags": [
          "Data Deletion"
        ]
      }
    },
    "/gdpr/public/namespaces/{namespace}/users/{userId}/requests": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Requires valid user access token\u0026lt;/p\u0026gt;",
        "operationId": "PublicGetUserPersonalDataRequests",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get user's personal data requests",
        "tags": [
          "Data Retrieval"
        ]
      },
      "post": {
        "description": "\u0026lt;p\u0026gt;Requires valid user access token\u0026lt;/p\u0026gt;",
        "operationId": "PublicRequestDataRetrieval",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Submit personal data retrieval request",
        "tags": [
          "Data Retrieval"
        ]
      }
    },
    "/gdpr/public/namespaces/{namespace}/users/{userId}/requests/{requestDate}": {
      "delete": {
        "description": "\u0026lt;p\u0026gt;Requires valid user access token\u0026lt;/p\u0026gt;",
        "operationId": "PublicCancelUserPersonalDataRequest",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Cancel user's personal data requests",
        "tags": [
          "Data Retrieval"
        ]
      }
    },
    "/gdpr/public/namespaces/{namespace}/users/{userId}/requests/{requestDate}/generate": {
      "post": {
        "description": "\u0026lt;p\u0026gt;Requires valid user access token\u0026lt;/p\u0026gt;",
        "operationId": "PublicGeneratePersonalDataURL",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Generate personal data download url",
        "tags": [
          "Data Retrieval"
        ]
      }
    },
    "/gdpr/public/users/me/deletions": {
      "delete": {
        "description": "\u0026lt;p\u0026gt;Requires valid user access token\u0026lt;/p\u0026gt;",
        "operationId": "PublicCancelMyAccountDeletionRequest",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Cancel my account deletion request",
        "tags": [
          "Data Deletion"
        ]
      },
      "post": {
        "description": "\u0026lt;p\u0026gt;Requires valid user access token\u0026lt;br\u0026gt;\n\t\tThis is for in-game only and require a valid platformId and platform token. If a full account is not logged by 3rd platform, then please use \u0026lt;a href=\u0026#39;#operations-Data_Deletion-PublicSubmitUserAccountDeletionRequest\u0026#39;\u0026gt;/gdpr/public/namespaces/{namespace}/users/{userId}/deletions\u0026lt;/a\u0026gt;\t\n\t\t",
        "operationId": "PublicSubmitMyAccountDeletionRequest",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Submit my account deletion requests.",
        "tags": [
          "Data Deletion"
        ]
      }
    },
    "/gdpr/public/users/me/deletions/status": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Requires valid user access token\u0026lt;/p\u0026gt;",
        "operationId": "PublicGetMyAccountDeletionStatus",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Retrieve my account deletion status",
        "tags": [
          "Data Deletion"
        ]
      }
    }
  },
  "x-docs": {
    "alias": "gdpr",
    "host": "https://demo.accelbyte.io",
    "path": "/gdpr/apidocs/api.json"
  },
  "x-version": {
    "buildDate": "2023-10-06T04:57:47+00:00",
    "gitHash": "425eb9f769b49a66a1018be5e0cc5bad49da8f78",
    "name": "justice-gdpr-service",
    "realm": "demo",
    "version": "2.3.0",
    "version-roles-seeding": "0.0.48"
  }
}