{
  "host": "demo.accelbyte.io",
  "info": {
    "description": "justice-inventory-service",
    "title": "justice-inventory-service",
    "version": "0.1.0"
  },
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "HasPermission": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {
        "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [CREATE]": "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [DELETE]": "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [READ]": "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [READ]",
        "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [UPDATE]": "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [UPDATE]",
        "ADMIN:NAMESPACE:{namespace}:INVENTORY:ITEMTYPE [CREATE]": "ADMIN:NAMESPACE:{namespace}:INVENTORY:ITEMTYPE [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:INVENTORY:ITEMTYPE [DELETE]": "ADMIN:NAMESPACE:{namespace}:INVENTORY:ITEMTYPE [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:INVENTORY:ITEMTYPE [READ]": "ADMIN:NAMESPACE:{namespace}:INVENTORY:ITEMTYPE [READ]",
        "ADMIN:NAMESPACE:{namespace}:INVENTORY:TAG [CREATE]": "ADMIN:NAMESPACE:{namespace}:INVENTORY:TAG [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:INVENTORY:TAG [DELETE]": "ADMIN:NAMESPACE:{namespace}:INVENTORY:TAG [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:INVENTORY:TAG [READ]": "ADMIN:NAMESPACE:{namespace}:INVENTORY:TAG [READ]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [CREATE]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [DELETE]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [READ]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [READ]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [UPDATE]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [UPDATE]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [CREATE]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [DELETE]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [READ]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [READ]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [UPDATE]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [UPDATE]"
      },
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "HasScope": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {},
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "authorization": {
      "in": "header",
      "name": "Authorization",
      "type": "apiKey"
    }
  },
  "swagger": "2.0",
  "paths": {
    "/inventory/v1/admin/namespaces/{namespace}/inventories": {
      "get": {
        "description": "\n\t\t\tListing all inventories in a namespace.\n\t\t\tThe response body will be in the form of standard pagination.\n\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [READ]\n\t\t",
        "operationId": "AdminListInventories",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [READ]"
            ],
            "authorization": []
          },
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "To list all inventories",
        "tags": [
          "Admin Inventories"
        ]
      },
      "post": {
        "description": "\n\t\t\tCreating an inventory.\n\t\t\tThe inventory configuration must exists otherwise it will fail.\n\t\t\tThe max slots and max upgrade slots of an inventory will be initialized according to the inventory configuration it used,\n\t\t\tbut it can be changed later when using AdminUpdateInventory endpoint.\n\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [CREATE]\n\t\t",
        "operationId": "AdminCreateInventory",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [CREATE]"
            ],
            "authorization": []
          },
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To create inventory",
        "tags": [
          "Admin Inventories"
        ]
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/inventories/{inventoryId}": {
      "delete": {
        "description": "\n\t\t\tDeleting an inventory.\n\t\t\tIf an inventory still has items, it cannot be deleted.\n\t\t\t\n\t\t\tADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [DELETE]\n\t\t",
        "operationId": "deleteInventory",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [DELETE]"
            ],
            "authorization": []
          },
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To delete inventory",
        "tags": [
          "Admin Inventories"
        ]
      },
      "get": {
        "description": "\n\t\t\tGetting an inventory info.\n\t\t\t\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [READ]\n\t\t",
        "operationId": "AdminGetInventory",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [READ]"
            ],
            "authorization": []
          },
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "To get an inventory",
        "tags": [
          "Admin Inventories"
        ]
      },
      "put": {
        "description": "\n\t\t\tUpdating an inventory.\n\t\t\tMaxSlots will be increased from existing value\n\t\t\t\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [UPDATE]\n\t\t",
        "operationId": "AdminUpdateInventory",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [UPDATE]"
            ],
            "authorization": []
          },
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To update inventory",
        "tags": [
          "Admin Inventories"
        ]
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/inventories/{inventoryId}/items": {
      "get": {
        "description": "\n\t\t\tListing all items in an inventory.\n\t\t\tThe response body will be in the form of standard pagination.\n\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [READ]\n\t\t",
        "operationId": "AdminListItems",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [READ]"
            ],
            "authorization": []
          },
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "To list all items",
        "tags": [
          "Admin Items"
        ]
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/inventories/{inventoryId}/items/{itemId}": {
      "get": {
        "description": "\n\t\t\tGetting an item info.\n\t\t\t\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [READ]\n\t\t",
        "operationId": "AdminGetInventoryItem",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [READ]"
            ],
            "authorization": []
          },
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "To get an item",
        "tags": [
          "Admin Items"
        ]
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/inventoryConfigurations": {
      "get": {
        "description": "\n\t\t\tListing all inventory configurations in a namespace.\n\t\t\tThe response body will be in the form of standard pagination.\n\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [READ]\n\t\t",
        "operationId": "AdminListInventoryConfigurations",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [READ]"
            ],
            "authorization": []
          },
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "To list inventory configurations",
        "tags": [
          "Admin Inventory Configurations"
        ]
      },
      "post": {
        "description": "\n\t\t\tCreating inventory configuration.\n\t\t\tThere cannot be one inventory configuration duplicate code per namespace.\n\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [CREATE]\n\t\t",
        "operationId": "AdminCreateInventoryConfiguration",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [CREATE]"
            ],
            "authorization": []
          },
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To create inventory configuration",
        "tags": [
          "Admin Inventory Configurations"
        ]
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/inventoryConfigurations/{inventoryConfigurationId}": {
      "delete": {
        "description": "\n\t\t\tDeleting an inventory configuration.\n\t\t\tIf an inventory already reference this type (i.e. STATUS is \u0026amp;#34;TIED\u0026amp;#34;), then the type cannot be deleted anymore.\n\t\t\t\n\t\t\tADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [DELETE]\n\t\t",
        "operationId": "AdminDeleteInventoryConfiguration",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [DELETE]"
            ],
            "authorization": []
          },
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To delete inventory configuration",
        "tags": [
          "Admin Inventory Configurations"
        ]
      },
      "get": {
        "description": "\n\t\t\tGetting an inventory configuration info.\n\t\t\t\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [READ]\n\t\t",
        "operationId": "AdminGetInventoryConfiguration",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [READ]"
            ],
            "authorization": []
          },
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "To get inventory configuration",
        "tags": [
          "Admin Inventory Configurations"
        ]
      },
      "put": {
        "description": "\n\t\t\tUpdating inventory configuration.\n\t\t\tThere cannot be duplicate code per namespace.\n\t\t\t\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [UPDATE]\n\t\t",
        "operationId": "AdminUpdateInventoryConfiguration",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [UPDATE]"
            ],
            "authorization": []
          },
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To update inventory configuration",
        "tags": [
          "Admin Inventory Configurations"
        ]
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/itemtypes": {
      "get": {
        "description": "\n\t\t\tThis endpoint will list all item types in a namespace.\n\t\t\tThe response body will be in the form of standard pagination.\n\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:INVENTORY:ITEMTYPE [READ]\n\t\t",
        "operationId": "AdminListItemTypes",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:ITEMTYPE [READ]"
            ],
            "authorization": []
          },
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:ITEMTYPE [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "To list itemtypes",
        "tags": [
          "Admin Item Types"
        ]
      },
      "post": {
        "description": "\n\t\t\tThis endpoint will create a new itemtype.\n\t\t\tThe itemtype name must be unique per namespace.\n\t\t\tIt is safe to call this endpoint even if the itemtype already exists.\n\t\t\t\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:INVENTORY:ITEMTYPE [CREATE]\n\t\t",
        "operationId": "AdminCreateItemType",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:ITEMTYPE [CREATE]"
            ],
            "authorization": []
          },
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:ITEMTYPE [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To create an itemtype",
        "tags": [
          "Admin Item Types"
        ]
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/itemtypes/{itemTypeName}": {
      "delete": {
        "description": "\n\t\t\tThis endpoint will delete a item type by itemtypeName in a specified namespace.\n\t\t\tIf the itemtypeName doesn\u0026amp;#39;t exist in a namespace, it\u0026amp;#39;ll return not found.\n\t\t\t\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:INVENTORY:ITEMTYPE [DELETE]\n\t\t",
        "operationId": "AdminDeleteItemType",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:ITEMTYPE [DELETE]"
            ],
            "authorization": []
          },
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:ITEMTYPE [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To delete an item type",
        "tags": [
          "Admin Item Types"
        ]
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/tags": {
      "get": {
        "description": "\n\t\t\tThis endpoint will list all tags in a namespace.\n\t\t\tThe response body will be in the form of standard pagination.\n\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:INVENTORY:TAG [READ]\n\t\t",
        "operationId": "AdminListTags",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:TAG [READ]"
            ],
            "authorization": []
          },
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:TAG [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "To list tags",
        "tags": [
          "Admin Tags"
        ]
      },
      "post": {
        "description": "\n\t\t\tThis endpoint will create a new tag.\n\t\t\tThe tag name must be unique per namespace.\n\t\t\tIt is safe to call this endpoint even if the tag already exists.\n\t\t\t\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:INVENTORY:TAG [CREATE]\n\t\t",
        "operationId": "AdminCreateTag",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:TAG [CREATE]"
            ],
            "authorization": []
          },
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:TAG [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To create a tag",
        "tags": [
          "Admin Tags"
        ]
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/tags/{tagName}": {
      "delete": {
        "description": "\n\t\t\tThis endpoint will delete a tag by tagName in a specified namespace.\n\t\t\tIf the tagName doesn\u0026amp;#39;t exist in a namespace, it\u0026amp;#39;ll return not found.\n\t\t\t\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:INVENTORY:TAG [DELETE]\n\t\t",
        "operationId": "AdminDeleteTag",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:TAG [DELETE]"
            ],
            "authorization": []
          },
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:TAG [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To delete a tag",
        "tags": [
          "Admin Tags"
        ]
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/users/{userId}/inventories/{inventoryId}/items": {
      "delete": {
        "description": "\n\t\t\tBulk remove user\u0026amp;#39;s own items\u0026amp;#39;.\n\t\t\t\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [DELETE]\n\t\t",
        "operationId": "AdminBulkRemoveItems",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [DELETE]"
            ],
            "authorization": []
          },
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To bulk remove items",
        "tags": [
          "Admin Items"
        ]
      },
      "post": {
        "description": "\n\t\t\tSaving an item to specific inventory.\n\t\t\tThe item will be saved in specific user\u0026amp;#39;s inventory,\n\t\t\t\n\t\t\tIf the item already exists, its qty will be increased,\n\t\t\tso no new item with same sourceItemId will be created\n\n\t\t\tTags will be auto-created.\n\t\t\tItemType will be auto-created.\n\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [CREATE]\n\t\t",
        "operationId": "AdminSaveItemToInventory",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [CREATE]"
            ],
            "authorization": []
          },
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To save item to specific inventory",
        "tags": [
          "Admin Items"
        ]
      },
      "put": {
        "description": "\n\t\t\tBulk Updating user\u0026amp;#39;s own items.\n\t\t\tTags will be auto-created.\n\t\t\t\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [UPDATE]\n\t\t",
        "operationId": "AdminBulkUpdateMyItems",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [UPDATE]"
            ],
            "authorization": []
          },
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To bulk update items",
        "tags": [
          "Admin Items"
        ]
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/users/{userId}/inventories/{inventoryId}/items/{itemId}/consume": {
      "post": {
        "description": "\n\t\t\tConsume user\u0026amp;#39;s own item\n\t\t\t\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [UPDATE]\n\t\t",
        "operationId": "AdminConsumeUserItem",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [UPDATE]"
            ],
            "authorization": []
          },
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To consume item",
        "tags": [
          "Admin Items"
        ]
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/users/{userId}/items": {
      "post": {
        "description": "\n\t\t\tSaving an item.\n\t\t\tThe item will be saved in user\u0026amp;#39;s inventory,\n\t\t\tIf it doesn\u0026amp;#39;t exist it\u0026amp;#39;ll be created.\n\t\t\t\n\t\t\tIf the item already exists, its qty will be increased,\n\t\t\tso no new item with same sourceItemId will be created\n\n\t\t\tTags will be auto-created.\n\t\t\tItemType will be auto-created.\n\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [CREATE]\n\t\t",
        "operationId": "AdminSaveItem",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [CREATE]"
            ],
            "authorization": []
          },
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To save item",
        "tags": [
          "Admin Items"
        ]
      }
    },
    "/inventory/v1/public/namespaces/{namespace}/inventoryConfigurations": {
      "get": {
        "description": "\n\t\tListing all inventory configurations in a namespace.\n\t\tThe response body will be in the form of standard pagination.\n\t",
        "operationId": "PublicListInventoryConfigurations",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "To list inventory configurations",
        "tags": [
          "Public Inventory Configurations"
        ]
      }
    },
    "/inventory/v1/public/namespaces/{namespace}/itemtypes": {
      "get": {
        "description": "\n\t\t\tThis endpoint will list all item types in a namespace.\n\t\t\tThe response body will be in the form of standard pagination.\n\t\t",
        "operationId": "PublicListItemTypes",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "To list item types",
        "tags": [
          "Public Item Types"
        ]
      }
    },
    "/inventory/v1/public/namespaces/{namespace}/tags": {
      "get": {
        "description": "\n\t\t\tThis endpoint will list all tags in a namespace.\n\t\t\tThe response body will be in the form of standard pagination.\n\t\t",
        "operationId": "PublicListTags",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "To list tags",
        "tags": [
          "Public Tags"
        ]
      }
    },
    "/inventory/v1/public/namespaces/{namespace}/users/me/inventories": {
      "get": {
        "description": "\n\t\t\tListing all my inventories in a namespace.\n\t\t\tThe response body will be in the form of standard pagination.\n\t\t",
        "operationId": "PublicListInventories",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "To list all my inventories",
        "tags": [
          "Public Inventories"
        ]
      }
    },
    "/inventory/v1/public/namespaces/{namespace}/users/me/inventories/{inventoryId}/items": {
      "delete": {
        "description": "\n        \tBulk remove user\u0026amp;#39;s own items.\n    \t",
        "operationId": "PublicBulkRemoveMyItems",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "To bulk remove items",
        "tags": [
          "Public Items"
        ]
      },
      "get": {
        "description": "\n\t\t\tListing all user\u0026amp;#39;s owned items in an inventory.\n\t\t\tThe response body will be in the form of standard pagination.\n\t\t",
        "operationId": "PublicListItems",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "To list all items",
        "tags": [
          "Public Items"
        ]
      },
      "put": {
        "description": "\n        \tBulk Updating user\u0026amp;#39;s own items.\n    \t",
        "operationId": "PublicBulkUpdateMyItems",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "To bulk update items",
        "tags": [
          "Public Items"
        ]
      }
    },
    "/inventory/v1/public/namespaces/{namespace}/users/me/inventories/{inventoryId}/items/movement": {
      "post": {
        "description": "\n\t\t\tMove items between inventories that is owned by the same user.\n\t\t",
        "operationId": "PublicMoveMyItems",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "To move items between my inventories",
        "tags": [
          "Public Items"
        ]
      }
    },
    "/inventory/v1/public/namespaces/{namespace}/users/me/inventories/{inventoryId}/items/{itemId}": {
      "get": {
        "description": "\n\t\t\tGetting an user\u0026amp;#39;s owned item info.\n\t\t",
        "operationId": "PublicGetItem",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "To get an item",
        "tags": [
          "Public Items"
        ]
      }
    },
    "/inventory/v1/public/namespaces/{namespace}/users/me/inventories/{inventoryId}/items/{itemId}/consume": {
      "post": {
        "description": "\n\t\t\tConsume user\u0026amp;#39;s own item.\n\t\t",
        "operationId": "PublicConsumeMyItem",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "To consume item",
        "tags": [
          "Public Items"
        ]
      }
    }
  },
  "x-docs": {
    "alias": "inventory",
    "host": "https://development.accelbyte.io",
    "path": "/inventory/apidocs/api.json"
  },
  "x-version": {
    "buildDate": "2023-08-28T07:21:48+00:00",
    "gitHash": "7615d05cee13469c402b39bf9431d054fdd60c9c",
    "name": "justice-inventory-service",
    "realm": "DEV",
    "version": "0.1.0"
  }
}