{
  "host": "demo.accelbyte.io",
  "info": {
    "description": "justice-inventory-service",
    "title": "justice-inventory-service",
    "version": "0.2.1"
  },
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "HasPermission": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {
        "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [CREATE]": "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [DELETE]": "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [READ]": "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [READ]",
        "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [UPDATE]": "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [UPDATE]",
        "ADMIN:NAMESPACE:{namespace}:INVENTORY:INTEGRATIONCONFIGURATION [CREATE]": "ADMIN:NAMESPACE:{namespace}:INVENTORY:INTEGRATIONCONFIGURATION [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:INVENTORY:INTEGRATIONCONFIGURATION [READ]": "ADMIN:NAMESPACE:{namespace}:INVENTORY:INTEGRATIONCONFIGURATION [READ]",
        "ADMIN:NAMESPACE:{namespace}:INVENTORY:INTEGRATIONCONFIGURATION [UPDATE]": "ADMIN:NAMESPACE:{namespace}:INVENTORY:INTEGRATIONCONFIGURATION [UPDATE]",
        "ADMIN:NAMESPACE:{namespace}:INVENTORY:ITEMTYPE [CREATE]": "ADMIN:NAMESPACE:{namespace}:INVENTORY:ITEMTYPE [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:INVENTORY:ITEMTYPE [DELETE]": "ADMIN:NAMESPACE:{namespace}:INVENTORY:ITEMTYPE [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:INVENTORY:ITEMTYPE [READ]": "ADMIN:NAMESPACE:{namespace}:INVENTORY:ITEMTYPE [READ]",
        "ADMIN:NAMESPACE:{namespace}:INVENTORY:TAG [CREATE]": "ADMIN:NAMESPACE:{namespace}:INVENTORY:TAG [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:INVENTORY:TAG [DELETE]": "ADMIN:NAMESPACE:{namespace}:INVENTORY:TAG [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:INVENTORY:TAG [READ]": "ADMIN:NAMESPACE:{namespace}:INVENTORY:TAG [READ]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [CREATE]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [DELETE]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [READ]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [READ]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [UPDATE]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [UPDATE]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [CREATE]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [DELETE]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [READ]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [READ]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [UPDATE]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [UPDATE]"
      },
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "HasScope": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {},
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "authorization": {
      "in": "header",
      "name": "Authorization",
      "type": "apiKey"
    }
  },
  "swagger": "2.0",
  "paths": {
    "/inventory/v1/admin/namespaces/{namespace}/chainingOperations": {
      "post": {
        "description": "\n\t\t\tCreate chaining Operations.\n\t\t\tThis process will run sequentially \n\t\t\t1. remove item process\n\t\t\t2. consume item process\n\t\t\t3. update item process\n\t\t\t4. create item process\n               if toSpecificInventory set as true, then inventoryId field will be mandatory, vice versa\n\t\t\t\n\t\t\tThe behavior of each process is same with current admin level endpoint\n\n\t\t\trequestId: Request id(Optional), client should provide a unique request id t[...]",
        "operationId": "AdminCreateChainingOperations",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To Create Chaining Operation",
        "tags": [
          "Admin Chaining Operations"
        ],
        "x-errorCodes": {}
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/integrationConfigurations": {
      "get": {
        "description": "\n\t\t\tListing all integration configurations in a namespace.\n\t\t\tThe response body will be in the form of standard pagination.\n\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:INVENTORY:INTEGRATIONCONFIGURATION [READ]\n\t\t",
        "operationId": "AdminListIntegrationConfigurations",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:INTEGRATIONCONFIGURATION [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "To list integration configurations",
        "tags": [
          "Admin Integration Configurations"
        ],
        "x-errorCodes": {}
      },
      "post": {
        "description": "\n\t\t\tCreating integration configuration.\n\t\t\tThere cannot be one duplicate serviceName per namespace.\n\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:INVENTORY:INTEGRATIONCONFIGURATION [CREATE]\n\t\t",
        "operationId": "AdminCreateIntegrationConfiguration",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:INTEGRATIONCONFIGURATION [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To create integration configuration",
        "tags": [
          "Admin Integration Configurations"
        ],
        "x-errorCodes": {}
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/integrationConfigurations/{integrationConfigurationId}": {
      "put": {
        "description": "\n\t\t\tto update integration configuration\n\t\t\tThere cannot be duplicate serviceName per namespace.\n\t\t\t\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:INVENTORY:INTEGRATIONCONFIGURATION [UPDATE]\n\t\t",
        "operationId": "AdminUpdateIntegrationConfiguration",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:INTEGRATIONCONFIGURATION [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To update integration configuration",
        "tags": [
          "Admin Integration Configurations"
        ],
        "x-errorCodes": {}
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/integrationConfigurations/{integrationConfigurationId}/status": {
      "put": {
        "description": "\n\t\t\tto update status  integration configuration to be Active / Not Active.\n\t\t\tThere cannot be duplicate serviceName per namespace.\n\t\t\t\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:INVENTORY:INTEGRATIONCONFIGURATION [UPDATE]\n\t\t",
        "operationId": "AdminUpdateStatusIntegrationConfiguration",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:INTEGRATIONCONFIGURATION [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To update status integration configuration to be active / not active ",
        "tags": [
          "Admin Integration Configurations"
        ],
        "x-errorCodes": {}
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/inventories": {
      "get": {
        "description": "\n\t\t\tListing all inventories in a namespace.\n\t\t\tThe response body will be in the form of standard pagination.\n\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [READ]\n\t\t",
        "operationId": "AdminListInventories",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "To list all inventories",
        "tags": [
          "Admin Inventories"
        ],
        "x-errorCodes": {}
      },
      "post": {
        "description": "\n\t\t\tCreating an inventory.\n\t\t\tThe inventory configuration must exists otherwise it will fail.\n\t\t\tThe max slots and max upgrade slots of an inventory will be initialized according to the inventory configuration it used,\n\t\t\tbut it can be changed later when using AdminUpdateInventory endpoint.\n\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [CREATE]\n\t\t",
        "operationId": "AdminCreateInventory",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To create inventory",
        "tags": [
          "Admin Inventories"
        ],
        "x-errorCodes": {}
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/inventories/{inventoryId}": {
      "delete": {
        "description": "\n\t\t\tDeleting an inventory.\n\t\t\tIf an inventory still has items, it cannot be deleted.\n\t\t\t\n\t\t\tADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [DELETE]\n\t\t",
        "operationId": "deleteInventory",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To delete inventory",
        "tags": [
          "Admin Inventories"
        ],
        "x-errorCodes": {}
      },
      "get": {
        "description": "\n\t\t\tGetting an inventory info.\n\t\t\t\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [READ]\n\t\t",
        "operationId": "AdminGetInventory",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "To get an inventory",
        "tags": [
          "Admin Inventories"
        ],
        "x-errorCodes": {}
      },
      "put": {
        "description": "\n\t\t\tUpdating an inventory.\n\t\t\tPositive value will increase MaxSlots from existing value\n\t\t\tNegative value will decrease MaxSlots from existing value\n\t\t\tLimited slots can not be changed to unlimited, vice versa\n\t\t\t\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [UPDATE]\n\t\t",
        "operationId": "AdminUpdateInventory",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To update inventory",
        "tags": [
          "Admin Inventories"
        ],
        "x-errorCodes": {}
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/inventories/{inventoryId}/items": {
      "get": {
        "description": "\n\t\t\tListing all items in an inventory.\n\t\t\tThe response body will be in the form of standard pagination.\n\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [READ]\n\t\t",
        "operationId": "AdminListItems",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "To list all items",
        "tags": [
          "Admin Items"
        ],
        "x-errorCodes": {}
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/inventories/{inventoryId}/slots/{slotId}/sourceItems/{sourceItemId}": {
      "get": {
        "description": "\n\t\t\t\t\tGetting an item info.\n\n\t\t\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [READ]\n\t\t\t\t",
        "operationId": "AdminGetInventoryItem",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "To get an item",
        "tags": [
          "Admin Items"
        ],
        "x-errorCodes": {}
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/inventoryConfigurations": {
      "get": {
        "description": "\n\t\t\tListing all inventory configurations in a namespace.\n\t\t\tThe response body will be in the form of standard pagination.\n\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [READ]\n\t\t",
        "operationId": "AdminListInventoryConfigurations",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "To list inventory configurations",
        "tags": [
          "Admin Inventory Configurations"
        ],
        "x-errorCodes": {}
      },
      "post": {
        "description": "\n\t\t\tCreating inventory configuration.\n\t\t\tThere cannot be one inventory configuration duplicate code per namespace.\n\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [CREATE]\n\t\t",
        "operationId": "AdminCreateInventoryConfiguration",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To create inventory configuration",
        "tags": [
          "Admin Inventory Configurations"
        ],
        "x-errorCodes": {}
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/inventoryConfigurations/{inventoryConfigurationId}": {
      "delete": {
        "description": "\n\t\t\tDeleting an inventory configuration.\n\t\t\tIf an inventory already reference this type (i.e. STATUS is \u0026#34;TIED\u0026#34;), then the type cannot be deleted anymore.\n\t\t\t\n\t\t\tADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [DELETE]\n\t\t",
        "operationId": "AdminDeleteInventoryConfiguration",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To delete inventory configuration",
        "tags": [
          "Admin Inventory Configurations"
        ],
        "x-errorCodes": {}
      },
      "get": {
        "description": "\n\t\t\tGetting an inventory configuration info.\n\t\t\t\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [READ]\n\t\t",
        "operationId": "AdminGetInventoryConfiguration",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "To get inventory configuration",
        "tags": [
          "Admin Inventory Configurations"
        ],
        "x-errorCodes": {}
      },
      "put": {
        "description": "\n\t\t\tUpdating inventory configuration.\n\t\t\tThere cannot be duplicate code per namespace.\n\t\t\t\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [UPDATE]\n\t\t",
        "operationId": "AdminUpdateInventoryConfiguration",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:CONFIGURATION [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To update inventory configuration",
        "tags": [
          "Admin Inventory Configurations"
        ],
        "x-errorCodes": {}
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/itemtypes": {
      "get": {
        "description": "\n\t\t\tThis endpoint will list all item types in a namespace.\n\t\t\tThe response body will be in the form of standard pagination.\n\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:INVENTORY:ITEMTYPE [READ]\n\t\t",
        "operationId": "AdminListItemTypes",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:ITEMTYPE [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "To list itemtypes",
        "tags": [
          "Admin Item Types"
        ],
        "x-errorCodes": {}
      },
      "post": {
        "description": "\n\t\t\tThis endpoint will create a new itemtype.\n\t\t\tThe itemtype name must be unique per namespace.\n\t\t\tIt is safe to call this endpoint even if the itemtype already exists.\n\t\t\t\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:INVENTORY:ITEMTYPE [CREATE]\n\t\t",
        "operationId": "AdminCreateItemType",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:ITEMTYPE [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To create an itemtype",
        "tags": [
          "Admin Item Types"
        ],
        "x-errorCodes": {}
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/itemtypes/{itemTypeName}": {
      "delete": {
        "description": "\n\t\t\tThis endpoint will delete a item type by itemtypeName in a specified namespace.\n\t\t\tIf the itemtypeName doesn\u0026#39;t exist in a namespace, it\u0026#39;ll return not found.\n\t\t\t\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:INVENTORY:ITEMTYPE [DELETE]\n\t\t",
        "operationId": "AdminDeleteItemType",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:ITEMTYPE [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To delete an item type",
        "tags": [
          "Admin Item Types"
        ],
        "x-errorCodes": {}
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/tags": {
      "get": {
        "description": "\n\t\t\tThis endpoint will list all tags in a namespace.\n\t\t\tThe response body will be in the form of standard pagination.\n\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:INVENTORY:TAG [READ]\n\t\t",
        "operationId": "AdminListTags",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:TAG [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "To list tags",
        "tags": [
          "Admin Tags"
        ],
        "x-errorCodes": {}
      },
      "post": {
        "description": "\n\t\t\tThis endpoint will create a new tag.\n\t\t\tThe tag name must be unique per namespace.\n\t\t\tIt is safe to call this endpoint even if the tag already exists.\n\t\t\t\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:INVENTORY:TAG [CREATE]\n\t\t",
        "operationId": "AdminCreateTag",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:TAG [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To create a tag",
        "tags": [
          "Admin Tags"
        ],
        "x-errorCodes": {}
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/tags/{tagName}": {
      "delete": {
        "description": "\n\t\t\tThis endpoint will delete a tag by tagName in a specified namespace.\n\t\t\tIf the tagName doesn\u0026#39;t exist in a namespace, it\u0026#39;ll return not found.\n\t\t\t\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:INVENTORY:TAG [DELETE]\n\t\t",
        "operationId": "AdminDeleteTag",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:INVENTORY:TAG [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To delete a tag",
        "tags": [
          "Admin Tags"
        ],
        "x-errorCodes": {}
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/users/{userId}/inventories/{inventoryId}/consume": {
      "post": {
        "description": "\n\t\t\tConsume user\u0026#39;s own item\n\t\t\t\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [UPDATE]\n\t\t",
        "operationId": "AdminConsumeUserItem",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To consume item",
        "tags": [
          "Admin Items"
        ],
        "x-errorCodes": {}
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/users/{userId}/inventories/{inventoryId}/items": {
      "delete": {
        "description": "\n\t\t\tBulk remove user\u0026#39;s own items\u0026#39;.\n\t\t\t\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [DELETE]\n\t\t",
        "operationId": "AdminBulkRemoveItems",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To bulk remove items",
        "tags": [
          "Admin Items"
        ],
        "x-errorCodes": {}
      },
      "post": {
        "description": "\n\t\t\tSaving an item to specific inventory.\n\t\t\tThe item will be saved in specific user\u0026#39;s inventory,\n\t\t\t\n\t\t\tIf the item already exists, its qty will be increased,\n\t\t\tso no new item with same sourceItemId will be created\n\n\t\t\tTags will be auto-created.\n\t\t\tItemType will be auto-created.\n\n\t\t\tFor Ecommerce item, this fields will be override by ecommerce configuration \n\t\t\t(slotUsed, serverCustomAttributes, customAttributes, type)\n\n\[...]",
        "operationId": "AdminSaveItemToInventory",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To save item to specific inventory",
        "tags": [
          "Admin Items"
        ],
        "x-errorCodes": {}
      },
      "put": {
        "description": "\n\t\t\tBulk Updating user\u0026#39;s own items.\n\t\t\tTags will be auto-created.\n\t\t\t\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [UPDATE]\n\t\t",
        "operationId": "AdminBulkUpdateMyItems",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To bulk update items",
        "tags": [
          "Admin Items"
        ],
        "x-errorCodes": {}
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/users/{userId}/items": {
      "post": {
        "description": "\n\t\t\tSaving an item.\n\t\t\tThe item will be saved in user\u0026#39;s inventory,\n\t\t\tIf it doesn\u0026#39;t exist it\u0026#39;ll be created.\n\t\t\t\n\t\t\tIf the item already exists, its qty will be increased,\n\t\t\tso no new item with same sourceItemId will be created\n\n\t\t\tTags will be auto-created.\n\t\t\tItemType will be auto-created.\n\n\t\t\tFor Ecommerce item, this fields will be override by ecommerce configuration \n\t\t\t(slotUsed, serverCustomAttribut[...]",
        "operationId": "AdminSaveItem",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To save item",
        "tags": [
          "Admin Items"
        ],
        "x-errorCodes": {}
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/users/{userId}/items/entitlements/sync": {
      "put": {
        "description": "\n\t\t\tSync user\u0026#39;s entitlement from e-commerce service to inventory for non exist item at user inventory.\n\t\t\twill skip the item if already exist at user inventory.\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [UPDATE]\n\t\t",
        "operationId": "AdminSyncUserEntitlements",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY:ITEM [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To sync user's entitlements to e-commerce",
        "tags": [
          "Admin Items"
        ],
        "x-errorCodes": {}
      }
    },
    "/inventory/v1/admin/namespaces/{namespace}/users/{userId}/purchaseable": {
      "post": {
        "description": "\n\t\t\tValidate purchase ecommerce item.\n\t\t\t\n\t\t\tPermission: ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [UPDATE]\n\t\t",
        "operationId": "AdminPurchasable",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:INVENTORY [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "To validate user inventory capacity when purchase ecommerce item",
        "tags": [
          "Admin Inventories"
        ],
        "x-errorCodes": {}
      }
    },
    "/inventory/v1/public/namespaces/{namespace}/inventoryConfigurations": {
      "get": {
        "description": "\n\t\tListing all inventory configurations in a namespace.\n\t\tThe response body will be in the form of standard pagination.\n\t",
        "operationId": "PublicListInventoryConfigurations",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "To list inventory configurations",
        "tags": [
          "Public Inventory Configurations"
        ],
        "x-errorCodes": {}
      }
    },
    "/inventory/v1/public/namespaces/{namespace}/itemtypes": {
      "get": {
        "description": "\n\t\t\tThis endpoint will list all item types in a namespace.\n\t\t\tThe response body will be in the form of standard pagination.\n\t\t",
        "operationId": "PublicListItemTypes",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "To list item types",
        "tags": [
          "Public Item Types"
        ],
        "x-errorCodes": {}
      }
    },
    "/inventory/v1/public/namespaces/{namespace}/tags": {
      "get": {
        "description": "\n\t\t\tThis endpoint will list all tags in a namespace.\n\t\t\tThe response body will be in the form of standard pagination.\n\t\t",
        "operationId": "PublicListTags",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "To list tags",
        "tags": [
          "Public Tags"
        ],
        "x-errorCodes": {}
      }
    },
    "/inventory/v1/public/namespaces/{namespace}/users/me/inventories": {
      "get": {
        "description": "\n\t\t\tListing all my inventories in a namespace.\n\t\t\tThe response body will be in the form of standard pagination.\n\t\t",
        "operationId": "PublicListInventories",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "To list all my inventories",
        "tags": [
          "Public Inventories"
        ],
        "x-errorCodes": {}
      }
    },
    "/inventory/v1/public/namespaces/{namespace}/users/me/inventories/{inventoryId}/consume": {
      "post": {
        "description": "\n\t\t\tConsume user\u0026#39;s own item.\n\t\t",
        "operationId": "PublicConsumeMyItem",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "To consume item",
        "tags": [
          "Public Items"
        ],
        "x-errorCodes": {}
      }
    },
    "/inventory/v1/public/namespaces/{namespace}/users/me/inventories/{inventoryId}/items": {
      "delete": {
        "description": "\n        \tBulk remove user\u0026#39;s own items.\n    \t",
        "operationId": "PublicBulkRemoveMyItems",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "To bulk remove items",
        "tags": [
          "Public Items"
        ],
        "x-errorCodes": {}
      },
      "get": {
        "description": "\n\t\t\tListing all user\u0026#39;s owned items in an inventory.\n\t\t\tThe response body will be in the form of standard pagination.\n\t\t",
        "operationId": "PublicListItems",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "To list all items",
        "tags": [
          "Public Items"
        ],
        "x-errorCodes": {}
      },
      "put": {
        "description": "\n        \tBulk Updating user\u0026#39;s own items.\n    \t",
        "operationId": "PublicBulkUpdateMyItems",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "To bulk update items",
        "tags": [
          "Public Items"
        ],
        "x-errorCodes": {}
      }
    },
    "/inventory/v1/public/namespaces/{namespace}/users/me/inventories/{inventoryId}/items/movement": {
      "post": {
        "description": "\n\t\t\tMove items between inventories that is owned by the same user.\n\n\t\t\tCurrently, this endpoint supports transferring items exclusively from source OTHER.\n\t\t\tItems from source ECOMMERCE are not yet eligible for transfer.\n\t\t\tWe are working on expanding support to include source ECOMMERCE in future updates.\n\t\t",
        "operationId": "PublicMoveMyItems",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "To move items between my inventories",
        "tags": [
          "Public Items"
        ],
        "x-errorCodes": {}
      }
    },
    "/inventory/v1/public/namespaces/{namespace}/users/me/inventories/{inventoryId}/slots/{slotId}/sourceItems/{sourceItemId}": {
      "get": {
        "description": "\n\t\t\t\t\tGetting an user\u0026#39;s owned item info.\n\t\t\t\t",
        "operationId": "PublicGetItem",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "To get an item",
        "tags": [
          "Public Items"
        ],
        "x-errorCodes": {}
      }
    }
  },
  "x-docs": {
    "alias": "inventory",
    "host": "https://stage.accelbyte.io",
    "path": "/inventory/apidocs/api.json"
  },
  "x-version": {
    "buildDate": "2024-07-17T09:31:54+00:00",
    "gitHash": "4144599dbb7e81333a511653ca9df0679925736a",
    "name": "justice-inventory-service",
    "realm": "stage",
    "version": "0.2.1",
    "version-roles-seeding": "1.2.34"
  }
}