{
  "host": "demo.accelbyte.io",
  "info": {
    "contact": {
      "email": "engineering@accelbyte.io",
      "name": "Engineering Team at AccelByte",
      "url": "https://accelbyte.io"
    },
    "description": "Justice Leaderboard Service",
    "title": "justice-leaderboard-service",
    "version": "2.26.7"
  },
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "HasPermission": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {
        "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [CREATE]": "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [DELETE]": "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]": "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]",
        "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [UPDATE]": "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [UPDATE]",
        "ADMIN:NAMESPACE:{namespace}:LEADERBOARD:USER [DELETE]": "ADMIN:NAMESPACE:{namespace}:LEADERBOARD:USER [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:ANONYMIZATION [DELETE]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:ANONYMIZATION [DELETE]",
        "NAMESPACE:{namespace}:LEADERBOARD [CREATE]": "NAMESPACE:{namespace}:LEADERBOARD [CREATE]",
        "NAMESPACE:{namespace}:LEADERBOARD:USER:{userId} [DELETE]": "NAMESPACE:{namespace}:LEADERBOARD:USER:{userId} [DELETE]"
      },
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "HasScope": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {},
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "authorization": {
      "in": "header",
      "name": "Authorization",
      "type": "apiKey"
    }
  },
  "swagger": "2.0",
  "paths": {
    "/leaderboard/v1/admin/namespaces/{namespace}/leaderboards": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026#39;ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]\u0026#39;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;This endpoint return all leaderboard configurations\u0026lt;/p\u0026gt;\t\n\t\t",
        "operationId": "getLeaderboardConfigurationsAdminV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "list all leaderboards by given namespace",
        "tags": [
          "LeaderboardConfiguration"
        ]
      },
      "post": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026#39;ADMIN:NAMESPACE:{namespace}:LEADERBOARD [CREATE]\u0026#39;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;\u0026lt;b\u0026gt;Fields :\u0026lt;/b\u0026gt;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;LeaderboardConfig code must be lowercase and maximum length is 48 characters. \u0026lt;b\u0026gt;(required)\u0026lt;/b\u0026gt;.\u0026lt;/li\u0026gt;\n\t\t\t\t\u0026lt;li\u0026gt;Maximum length for leaderboa[...]",
        "operationId": "createLeaderboardConfigurationAdminV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "create new leaderboard",
        "tags": [
          "LeaderboardConfiguration"
        ]
      }
    },
    "/leaderboard/v1/admin/namespaces/{namespace}/leaderboards/archived": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Admin Get signed url in an all time leaderboard that archived. Notes: This will be a bulk endpoint to get sign url\u0026lt;/p\u0026gt;\n\t\t\t",
        "operationId": "AdminGetArchivedLeaderboardRankingDataV1Handler",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Admin Get signed url for archive all time leaderboard ranking data",
        "tags": [
          "LeaderboardData"
        ]
      },
      "post": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026#39;ADMIN:NAMESPACE:{namespace}:LEADERBOARD [CREATE]\u0026#39;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;Archive leaderboard ranking data for specified leaderboard codes. NOTE: This will remove all data of the leaderboard on every slug,\n\t\t\tremove the leaderboard code on stat mapping, and remove the leaderboard on the queue reset. This will be a bulk endpoint\u0026lt;/p\u0026gt;\n\t\t\t",
        "operationId": "CreateArchivedLeaderboardRankingDataV1Handler",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Archive a leadeboard data ranking",
        "tags": [
          "LeaderboardData"
        ]
      }
    },
    "/leaderboard/v1/admin/namespaces/{namespace}/leaderboards/delete": {
      "post": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026#39;ADMIN:NAMESPACE:{namespace}:LEADERBOARD [DELETE]\u0026#39;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;This endpoint delete multiple leaderboards configuration in one request\u0026lt;/p\u0026gt;\t\n\t\t",
        "operationId": "deleteBulkLeaderboardConfigurationAdminV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "delete bulk leaderboards. response body will contains failed leaderboard with the reason why it's failed to delete",
        "tags": [
          "LeaderboardConfiguration"
        ]
      }
    },
    "/leaderboard/v1/admin/namespaces/{namespace}/leaderboards/{leaderboardCode}": {
      "delete": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026#39;ADMIN:NAMESPACE:{namespace}:LEADERBOARD [DELETE]\u0026#39;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;This endpoint delete a leaderboard configuration\u0026lt;/p\u0026gt;\t\n\t\t",
        "operationId": "deleteLeaderboardConfigurationAdminV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "delete leaderboard by leaderboardCode",
        "tags": [
          "LeaderboardConfiguration"
        ]
      },
      "get": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026#39;ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]\u0026#39;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;This endpoint returns a leaderboard configuration\u0026lt;/p\u0026gt;\t\n\t\t",
        "operationId": "getLeaderboardConfigurationAdminV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "get leaderboard by leaderboardCode",
        "tags": [
          "LeaderboardConfiguration"
        ]
      },
      "put": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026#39;ADMIN:NAMESPACE:{namespace}:LEADERBOARD [UPDATE]\u0026#39;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;\u0026lt;b\u0026gt;Fields :\u0026lt;/b\u0026gt;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;ul\u0026gt;\n\t\t\t\t\u0026lt;li\u0026gt;Maximum length for leaderboard name is 128 characters.\u0026lt;/li\u0026gt;\n\t\t\t\t\u0026lt;li\u0026gt;Start time must be follow RFC3339 standard. e.g. 2020-10-02T15:00:00.05Z\u0026lt;/li\u0026gt[...]",
        "operationId": "updateLeaderboardConfigurationAdminV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "update leaderboard by leaderboardCode",
        "tags": [
          "LeaderboardConfiguration"
        ]
      }
    },
    "/leaderboard/v1/admin/namespaces/{namespace}/leaderboards/{leaderboardCode}/alltime": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026#39;ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]\u0026#39;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;Get rankings in an all time leaderboard.\u0026lt;/p\u0026gt;\n\t\t\t",
        "operationId": "GetAllTimeLeaderboardRankingAdminV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get all time leaderboard ranking data",
        "tags": [
          "LeaderboardData"
        ]
      }
    },
    "/leaderboard/v1/admin/namespaces/{namespace}/leaderboards/{leaderboardCode}/hard": {
      "delete": {
        "description": "\u0026lt;p\u0026gt;\u0026lt;b\u0026gt;[Test Facility Only]\u0026lt;/b\u0026gt;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;Required permission \u0026#39;ADMIN:NAMESPACE:{namespace}:LEADERBOARD [DELETE]\u0026#39;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;This endpoint will delete leaderboard configuration and its data\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;Note: this endpoint only works on development environment, you might want to use \u0026lt;b\u0026gt;archi[...]",
        "operationId": "hardDeleteLeaderboardAdminV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "hard delete leaderboard config and data by leaderboard code",
        "tags": [
          "LeaderboardConfiguration"
        ]
      }
    },
    "/leaderboard/v1/admin/namespaces/{namespace}/leaderboards/{leaderboardCode}/month": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026#39;ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]\u0026#39;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;Get rankings in current month leaderboard.\u0026lt;/p\u0026gt;\n\t\t\t",
        "operationId": "GetCurrentMonthLeaderboardRankingAdminV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get current month leaderboard ranking data",
        "tags": [
          "LeaderboardData"
        ]
      }
    },
    "/leaderboard/v1/admin/namespaces/{namespace}/leaderboards/{leaderboardCode}/reset": {
      "delete": {
        "description": "\u0026lt;p\u0026gt;\u0026lt;b\u0026gt;[Test Facility Only]\u0026lt;/b\u0026gt;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;Required permission \u0026#39;ADMIN:NAMESPACE:{namespace}:LEADERBOARD [DELETE]\u0026#39;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;This endpoint will delete user ranking by leaderboard code\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;Note: this endpoint only works on development environment.\u0026lt;/p\u0026gt;",
        "operationId": "deleteUserRankingByLeaderboardCodeAdminV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "delete all user ranking by leaderboard code",
        "tags": [
          "LeaderboardData"
        ]
      }
    },
    "/leaderboard/v1/admin/namespaces/{namespace}/leaderboards/{leaderboardCode}/season": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026#39;ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]\u0026#39;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;Get rankings in current season leaderboard.\u0026lt;/p\u0026gt;\n\t\t\t",
        "operationId": "GetCurrentSeasonLeaderboardRankingAdminV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get current season leaderboard ranking data",
        "tags": [
          "LeaderboardData"
        ]
      }
    },
    "/leaderboard/v1/admin/namespaces/{namespace}/leaderboards/{leaderboardCode}/today": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026#39;ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]\u0026#39;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;Get rankings in today leaderboard.\u0026lt;/p\u0026gt;\n\t\t\t",
        "operationId": "GetTodayLeaderboardRankingAdminV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get today leaderboard ranking data",
        "tags": [
          "LeaderboardData"
        ]
      }
    },
    "/leaderboard/v1/admin/namespaces/{namespace}/leaderboards/{leaderboardCode}/users/{userId}": {
      "delete": {
        "description": "Delete user ranking\nRequired permission: ADMIN:NAMESPACE:{namespace}:LEADERBOARD:USER [DELETE]\n\nRemove entry with provided userId from leaderboard. \nIf leaderboard with given leaderboard code not found, it will return http status not found (404).\nIf the leaderboard is found and no entry found in it, it will still return success (204) \n",
        "operationId": "deleteUserRankingAdminV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD:USER [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete user ranking",
        "tags": [
          "LeaderboardData"
        ]
      },
      "get": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026#39;ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]\u0026#39;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;Get user ranking in leaderboard\u0026lt;/p\u0026gt;\n\t\t\t",
        "operationId": "getUserRankingAdminV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get user ranking",
        "tags": [
          "LeaderboardData"
        ]
      },
      "put": {
        "description": "\u0026lt;p\u0026gt;Update user point in a leaderboard. This endpoint uses for test utility only.\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;Other detail info:\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;ul\u0026gt;\n\t\t\t\t\u0026lt;li\u0026gt;Required permission: resource=\u0026#34;ADMIN:NAMESPACE:{namespace}:USER:(userId):LEADERBOARD\u0026#34;, action=4 (UPDATE)\u0026lt;/li\u0026gt;\n\t\t\t\t\u0026lt;li\u0026gt;Returns: user ranking\u0026lt;/li\u0026gt;\n\t\t\t\u0026lt;/ul\u[...]",
        "operationId": "updateUserPointAdminV1",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Update user point",
        "tags": [
          "LeaderboardData"
        ]
      }
    },
    "/leaderboard/v1/admin/namespaces/{namespace}/leaderboards/{leaderboardCode}/week": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026#39;ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]\u0026#39;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;Get rankings in current week leaderboard.\u0026lt;/p\u0026gt;\n\t\t\t",
        "operationId": "GetCurrentWeekLeaderboardRankingAdminV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get current week leaderboard ranking data",
        "tags": [
          "LeaderboardData"
        ]
      }
    },
    "/leaderboard/v1/admin/namespaces/{namespace}/users/{userId}": {
      "delete": {
        "description": "Delete user ranking across leaderboard\nRequired permission: ADMIN:NAMESPACE:{namespace}:LEADERBOARD:USER [DELETE]\n\nRemove entry with provided userId from leaderboard.\n",
        "operationId": "deleteUserRankingsAdminV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD:USER [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete user ranking across leaderboard(s)",
        "tags": [
          "LeaderboardData"
        ]
      }
    },
    "/leaderboard/v1/admin/namespaces/{namespace}/users/{userId}/anonymization/leaderboards": {
      "delete": {
        "description": "\u0026lt;p\u0026gt;This API will delete specified user leaderboard\u0026lt;p\u0026gt;\n\u0026lt;p\u0026gt;Required permission\n\u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:ANONYMIZATION [DELETE]\u0026lt;/code\u0026gt;\n\u0026lt;/p\u0026gt; \n",
        "operationId": "adminAnonymizeUserLeaderboardAdminV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:ANONYMIZATION [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Anonymize user's leaderboard",
        "tags": [
          "Anonymization"
        ]
      }
    },
    "/leaderboard/v1/admin/namespaces/{namespace}/users/{userId}/leaderboards": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026#39;ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]\u0026#39;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;Get user leaderboard rankings\u0026lt;/p\u0026gt;\n\t\t\t",
        "operationId": "getUserLeaderboardRankingsAdminV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get user rankings",
        "tags": [
          "UserData"
        ]
      }
    },
    "/leaderboard/v1/public/namespaces/{namespace}/leaderboards": {
      "get": {
        "description": "\u0026lt;p\u0026gt;This endpoint return all leaderboard configurations\u0026lt;/p\u0026gt;\t\n\t\t",
        "operationId": "getLeaderboardConfigurationsPublicV1",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "list all leaderboards by given namespace",
        "tags": [
          "LeaderboardConfiguration"
        ]
      },
      "post": {
        "description": "Public endpoint to create a new leaderboard.\n\n\u0026lt;p\u0026gt;Required permission \u0026#39;NAMESPACE:{namespace}:LEADERBOARD [CREATE]\u0026#39;\u0026lt;/p\u0026gt;\n\u0026lt;p\u0026gt;\u0026lt;b\u0026gt;Fields :\u0026lt;/b\u0026gt;\u0026lt;/p\u0026gt;\n\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;LeaderboardConfig code must be lowercase and maximum length is 48 characters. \u0026lt;b\u0026gt;(required)\u0026lt;/b\u0026gt;.\u0026lt;/li\u0026gt;\n\t\u0026lt;li\u0026gt;Maxi[...]",
        "operationId": "createLeaderboardConfigurationPublicV1",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:LEADERBOARD [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "create new leaderboard",
        "tags": [
          "LeaderboardConfiguration"
        ]
      }
    },
    "/leaderboard/v1/public/namespaces/{namespace}/leaderboards/{leaderboardCode}/alltime": {
      "get": {
        "description": "\t\u0026lt;p\u0026gt;Get rankings in an all time leaderboard.\u0026lt;/p\u0026gt;\n\t\t\t",
        "operationId": "GetAllTimeLeaderboardRankingPublicV1",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get all time leaderboard ranking data",
        "tags": [
          "LeaderboardData"
        ]
      }
    },
    "/leaderboard/v1/public/namespaces/{namespace}/leaderboards/{leaderboardCode}/archived": {
      "get": {
        "description": "\t\u0026lt;p\u0026gt;Get signed url in an all time leaderboard that archived. NOTE: This will be a bulk endpoint to get sign url\u0026lt;/p\u0026gt;\n\t\t\t",
        "operationId": "GetArchivedLeaderboardRankingDataV1Handler",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get signed url for archive all time leaderboard ranking data",
        "tags": [
          "LeaderboardData"
        ]
      }
    },
    "/leaderboard/v1/public/namespaces/{namespace}/leaderboards/{leaderboardCode}/month": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Get rankings in current month leaderboard.\u0026lt;/p\u0026gt;",
        "operationId": "GetCurrentMonthLeaderboardRankingPublicV1",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get current month leaderboard ranking data",
        "tags": [
          "LeaderboardData"
        ]
      }
    },
    "/leaderboard/v1/public/namespaces/{namespace}/leaderboards/{leaderboardCode}/season": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Get rankings in current season leaderboard.\u0026lt;/p\u0026gt;",
        "operationId": "GetCurrentSeasonLeaderboardRankingPublicV1",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get current season leaderboard ranking data",
        "tags": [
          "LeaderboardData"
        ]
      }
    },
    "/leaderboard/v1/public/namespaces/{namespace}/leaderboards/{leaderboardCode}/today": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Get rankings in today leaderboard.\u0026lt;/p\u0026gt;",
        "operationId": "GetTodayLeaderboardRankingPublicV1",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get today leaderboard ranking data",
        "tags": [
          "LeaderboardData"
        ]
      }
    },
    "/leaderboard/v1/public/namespaces/{namespace}/leaderboards/{leaderboardCode}/users/{userId}": {
      "delete": {
        "description": "Delete user ranking\nRequired permission: NAMESPACE:{namespace}:LEADERBOARD:USER:{userId} [DELETE]\n\nRemove entry with provided userId from leaderboard. \nIf leaderboard with given leaderboard code not found, it will return http status not found (404).\nIf the leaderboard is found and no entry found in it, it will still return success (204) \n",
        "operationId": "deleteUserRankingPublicV1",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:LEADERBOARD:USER:{userId} [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete user ranking",
        "tags": [
          "LeaderboardData"
        ]
      },
      "get": {
        "description": "\u0026lt;p\u0026gt;Get user ranking in leaderboard\u0026lt;/p\u0026gt;",
        "operationId": "getUserRankingPublicV1",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get user ranking",
        "tags": [
          "LeaderboardData"
        ]
      }
    },
    "/leaderboard/v1/public/namespaces/{namespace}/leaderboards/{leaderboardCode}/week": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Get rankings in current week leaderboard.\u0026lt;/p\u0026gt;",
        "operationId": "GetCurrentWeekLeaderboardRankingPublicV1",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get current week leaderboard ranking data",
        "tags": [
          "LeaderboardData"
        ]
      }
    },
    "/leaderboard/v2/admin/namespaces/{namespace}/leaderboards/{leaderboardCode}/users/hidden": {
      "get": {
        "description": "Return hidden users on a leaderboard",
        "operationId": "GetHiddenUsersV2",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get hidden users on a leaderboard",
        "tags": [
          "UserVisibility"
        ]
      }
    },
    "/leaderboard/v2/admin/namespaces/{namespace}/leaderboards/{leaderboardCode}/users/{userId}/visibility": {
      "get": {
        "description": "User with false visibility status will have \u0026lt;b\u0026gt;hidden\u0026lt;/b\u0026gt; attribute set to true on it\u0026#39;s leaderboard entry",
        "operationId": "GetUserVisibilityStatusV2",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get user visibility status",
        "tags": [
          "UserVisibility"
        ]
      },
      "put": {
        "description": "User with false visibility status will have \u0026lt;b\u0026gt;hidden\u0026lt;/b\u0026gt; attribute  set to true on it\u0026#39;s leaderboard entry",
        "operationId": "SetUserLeaderboardVisibilityStatusV2",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Set user visibility status on a specific leaderboard code",
        "tags": [
          "UserVisibility"
        ]
      }
    },
    "/leaderboard/v2/admin/namespaces/{namespace}/users/{userId}/visibility": {
      "put": {
        "description": "User with false visibility status will have \u0026lt;b\u0026gt;hidden\u0026lt;/b\u0026gt; attribute  set to true on it\u0026#39;s leaderboard entry",
        "operationId": "SetUserVisibilityStatusV2",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Set user visibility status on a all current leaderboard",
        "tags": [
          "UserVisibility"
        ]
      }
    },
    "/leaderboard/v2/public/namespaces/{namespace}/leaderboards": {
      "get": {
        "description": "This endpoint return all leaderboard configurations",
        "operationId": "GetLeaderboardConfigurationsPublicV2",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "list all leaderboards by given namespace",
        "tags": [
          "LeaderboardConfiguration"
        ]
      }
    },
    "/leaderboard/v2/public/namespaces/{namespace}/leaderboards/{leaderboardCode}/alltime": {
      "get": {
        "description": "Get rankings in an all time leaderboard.",
        "operationId": "GetAllTimeLeaderboardRankingPublicV2",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get all time leaderboard ranking data",
        "tags": [
          "LeaderboardData"
        ]
      }
    },
    "/leaderboard/v3/admin/namespaces/{namespace}/leaderboards": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026#39;ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]\u0026#39;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;This endpoint return all leaderboard configurations\u0026lt;/p\u0026gt;\t\n\t\t",
        "operationId": "getLeaderboardConfigurationsAdminV3",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "list all leaderboards by given namespace",
        "tags": [
          "LeaderboardConfigurationV3"
        ]
      },
      "post": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026#39;ADMIN:NAMESPACE:{namespace}:LEADERBOARD [CREATE]\u0026#39;\u0026lt;/p\u0026gt;\u0026lt;p\u0026gt;\u0026lt;b\u0026gt;Fields :\u0026lt;/b\u0026gt;\u0026lt;/p\u0026gt;\n\t\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;leaderboardCode: unique leaderboard config code must be lowercase and maximum length is 48 characters. \u0026lt;b\u0026gt;(required)\u0026lt;/b\u0026gt;.\u0026lt;/li\u0026gt;\n\t\t\u0026lt;li\u0026gt;name: leaderboard n[...]",
        "operationId": "createLeaderboardConfigurationAdminV3",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "create new leaderboard",
        "tags": [
          "LeaderboardConfigurationV3"
        ]
      }
    },
    "/leaderboard/v3/admin/namespaces/{namespace}/leaderboards/delete": {
      "post": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026#39;ADMIN:NAMESPACE:{namespace}:LEADERBOARD [DELETE]\u0026#39;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;This endpoint delete multiple leaderboards configuration in one request\u0026lt;/p\u0026gt;\t\n\t\t",
        "operationId": "deleteBulkLeaderboardConfigurationAdminV3",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "delete bulk leaderboards. response body will contains failed leaderboard with the reason why it's failed to delete",
        "tags": [
          "LeaderboardConfigurationV3"
        ]
      }
    },
    "/leaderboard/v3/admin/namespaces/{namespace}/leaderboards/{leaderboardCode}": {
      "delete": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026#39;ADMIN:NAMESPACE:{namespace}:LEADERBOARD [DELETE]\u0026#39;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;This endpoint delete a leaderboard configuration\u0026lt;/p\u0026gt;\t\n\t\t",
        "operationId": "deleteLeaderboardConfigurationAdminV3",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "delete leaderboard by leaderboardCode",
        "tags": [
          "LeaderboardConfigurationV3"
        ]
      },
      "get": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026#39;ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]\u0026#39;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;This endpoint returns a leaderboard configuration\u0026lt;/p\u0026gt;\t\n\t\t",
        "operationId": "getLeaderboardConfigurationAdminV3",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "get leaderboard by leaderboardCode",
        "tags": [
          "LeaderboardConfigurationV3"
        ]
      },
      "put": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026#39;ADMIN:NAMESPACE:{namespace}:LEADERBOARD [UPDATE]\u0026#39;\u0026lt;/p\u0026gt;\u0026lt;p\u0026gt;\u0026lt;b\u0026gt;Fields :\u0026lt;/b\u0026gt;\u0026lt;/p\u0026gt;\n\t\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;leaderboardCode: unique leaderboard config code must be lowercase and maximum length is 48 characters. \u0026lt;b\u0026gt;(required)\u0026lt;/b\u0026gt;.\u0026lt;/li\u0026gt;\n\t\t\u0026lt;li\u0026gt;name: leaderboard n[...]",
        "operationId": "updateLeaderboardConfigurationAdminV3",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "update leaderboard by leaderboardCode",
        "tags": [
          "LeaderboardConfigurationV3"
        ]
      }
    },
    "/leaderboard/v3/admin/namespaces/{namespace}/leaderboards/{leaderboardCode}/alltime": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026#39;ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]\u0026#39;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;Get rankings in an all time leaderboard.\u0026lt;/p\u0026gt;\n\t\t\t",
        "operationId": "GetAllTimeLeaderboardRankingAdminV3",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get all time leaderboard ranking data",
        "tags": [
          "LeaderboardDataV3"
        ]
      }
    },
    "/leaderboard/v3/admin/namespaces/{namespace}/leaderboards/{leaderboardCode}/cycles/{cycleId}": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026#39;ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]\u0026#39;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;Get rankings in cycle leaderboard.\u0026lt;/p\u0026gt;\n\t\t\t",
        "operationId": "GetCurrentCycleLeaderboardRankingAdminV3",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get cycle leaderboard ranking data",
        "tags": [
          "LeaderboardDataV3"
        ]
      }
    },
    "/leaderboard/v3/admin/namespaces/{namespace}/leaderboards/{leaderboardCode}/hard": {
      "delete": {
        "description": "\u0026lt;p\u0026gt;\u0026lt;b\u0026gt;[Test Facility Only]\u0026lt;/b\u0026gt;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;Required permission \u0026#39;ADMIN:NAMESPACE:{namespace}:LEADERBOARD [DELETE]\u0026#39;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;This endpoint will delete leaderboard configuration and its data\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;Note: this endpoint only works on development environment, you might want to use \u0026lt;b\u0026gt;archi[...]",
        "operationId": "hardDeleteLeaderboardAdminV3",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "hard delete leaderboard config and data by leaderboard code",
        "tags": [
          "LeaderboardConfigurationV3"
        ]
      }
    },
    "/leaderboard/v3/admin/namespaces/{namespace}/leaderboards/{leaderboardCode}/reset": {
      "delete": {
        "description": "\u0026lt;p\u0026gt;\u0026lt;b\u0026gt;[Test Facility Only]\u0026lt;/b\u0026gt;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;Required permission \u0026#39;ADMIN:NAMESPACE:{namespace}:LEADERBOARD [DELETE]\u0026#39;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;This endpoint will delete user ranking by leaderboard code\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;Note: this endpoint only works on development environment.\u0026lt;/p\u0026gt;",
        "operationId": "deleteUserRankingByLeaderboardCodeAdminV3",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "delete all user ranking by leaderboard code",
        "tags": [
          "LeaderboardDataV3"
        ]
      }
    },
    "/leaderboard/v3/admin/namespaces/{namespace}/leaderboards/{leaderboardCode}/users/hidden": {
      "get": {
        "description": "Return hidden users on a leaderboard",
        "operationId": "GetHiddenUsersV3",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get hidden users on a leaderboard",
        "tags": [
          "UserVisibilityV3"
        ]
      }
    },
    "/leaderboard/v3/admin/namespaces/{namespace}/leaderboards/{leaderboardCode}/users/{userId}": {
      "delete": {
        "description": "Delete user ranking\nRequired permission: ADMIN:NAMESPACE:{namespace}:LEADERBOARD:USER [DELETE]\n\nRemove entry with provided userId from leaderboard. \nIf leaderboard with given leaderboard code not found, it will return http status not found (404).\nIf the leaderboard is found and no entry found in it, it will still return success (204) \n",
        "operationId": "deleteUserRankingAdminV3",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD:USER [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete user ranking",
        "tags": [
          "LeaderboardDataV3"
        ]
      },
      "get": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026#39;ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]\u0026#39;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;Get user ranking in leaderboard\u0026lt;/p\u0026gt;\n\t\t\t",
        "operationId": "getUserRankingAdminV3",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get user ranking",
        "tags": [
          "LeaderboardDataV3"
        ]
      }
    },
    "/leaderboard/v3/admin/namespaces/{namespace}/leaderboards/{leaderboardCode}/users/{userId}/visibility": {
      "get": {
        "description": "User with false visibility status will have \u0026lt;b\u0026gt;hidden\u0026lt;/b\u0026gt; attribute set to true on it\u0026#39;s leaderboard entry",
        "operationId": "GetUserVisibilityStatusV3",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get user visibility status",
        "tags": [
          "UserVisibilityV3"
        ]
      },
      "put": {
        "description": "User with false visibility status will have \u0026lt;b\u0026gt;hidden\u0026lt;/b\u0026gt; attribute  set to true on it\u0026#39;s leaderboard entry",
        "operationId": "SetUserLeaderboardVisibilityV3",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Set user visibility status on a specific leaderboard code",
        "tags": [
          "UserVisibilityV3"
        ]
      }
    },
    "/leaderboard/v3/admin/namespaces/{namespace}/users/{userId}": {
      "delete": {
        "description": "Delete user ranking across leaderboard\nRequired permission: ADMIN:NAMESPACE:{namespace}:LEADERBOARD:USER [DELETE]\n\nRemove entry with provided userId from leaderboard.\n",
        "operationId": "deleteUserRankingsAdminV3",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD:USER [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete user ranking across leaderboard(s)",
        "tags": [
          "LeaderboardDataV3"
        ]
      }
    },
    "/leaderboard/v3/admin/namespaces/{namespace}/users/{userId}/leaderboards": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Required permission \u0026#39;ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]\u0026#39;\u0026lt;/p\u0026gt;\n\t\t\t\u0026lt;p\u0026gt;Get user leaderboard rankings\u0026lt;/p\u0026gt;\n\t\t\t",
        "operationId": "getUserLeaderboardRankingsAdminV3",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LEADERBOARD [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get user rankings",
        "tags": [
          "UserDataV3"
        ]
      }
    },
    "/leaderboard/v3/admin/namespaces/{namespace}/users/{userId}/visibility": {
      "put": {
        "description": "User with false visibility status will have \u0026lt;b\u0026gt;hidden\u0026lt;/b\u0026gt; attribute  set to true on it\u0026#39;s leaderboard entry",
        "operationId": "SetUserVisibilityV3",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Set user visibility status on a all current leaderboard",
        "tags": [
          "UserVisibilityV3"
        ]
      }
    },
    "/leaderboard/v3/public/namespaces/{namespace}/leaderboards": {
      "get": {
        "description": "\u0026lt;p\u0026gt;This endpoint return all leaderboard configurations\u0026lt;/p\u0026gt;\t\n\t\t",
        "operationId": "getLeaderboardConfigurationsPublicV3",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "list all leaderboards by given namespace",
        "tags": [
          "LeaderboardConfigurationV3"
        ]
      }
    },
    "/leaderboard/v3/public/namespaces/{namespace}/leaderboards/{leaderboardCode}": {
      "get": {
        "description": "\u0026lt;p\u0026gt;This endpoint returns a leaderboard configuration\u0026lt;/p\u0026gt;\t\n\t\t",
        "operationId": "getLeaderboardConfigurationPublicV3",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "get leaderboard by leaderboardCode",
        "tags": [
          "LeaderboardConfigurationV3"
        ]
      }
    },
    "/leaderboard/v3/public/namespaces/{namespace}/leaderboards/{leaderboardCode}/alltime": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Get rankings in an all time leaderboard.\u0026lt;/p\u0026gt;",
        "operationId": "GetAllTimeLeaderboardRankingPublicV3",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get all time leaderboard ranking data",
        "tags": [
          "LeaderboardDataV3"
        ]
      }
    },
    "/leaderboard/v3/public/namespaces/{namespace}/leaderboards/{leaderboardCode}/cycles/{cycleId}": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Get rankings in cycle leaderboard.\u0026lt;/p\u0026gt;",
        "operationId": "GetCurrentCycleLeaderboardRankingPublicV3",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get cycle leaderboard ranking data",
        "tags": [
          "LeaderboardDataV3"
        ]
      }
    },
    "/leaderboard/v3/public/namespaces/{namespace}/leaderboards/{leaderboardCode}/users/bulk": {
      "post": {
        "description": "\u0026lt;p\u0026gt;Bulk get users ranking in leaderboard, max allowed 20 userIDs at a time.\u0026lt;/p\u0026gt;",
        "operationId": "bulkGetUsersRankingPublicV3",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Bulk get users ranking",
        "tags": [
          "LeaderboardDataV3"
        ]
      }
    },
    "/leaderboard/v3/public/namespaces/{namespace}/leaderboards/{leaderboardCode}/users/{userId}": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Get user ranking in leaderboard\u0026lt;/p\u0026gt;",
        "operationId": "getUserRankingPublicV3",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get user ranking",
        "tags": [
          "LeaderboardDataV3"
        ]
      }
    }
  },
  "x-docs": {
    "alias": "leaderboard",
    "host": "https://demo.accelbyte.io",
    "path": "/leaderboard/apidocs/api.json"
  },
  "x-version": {
    "buildDate": "2024-01-12T04:00:11+00:00",
    "gitHash": "d0ad56a2815be4beffce1b90de4796f196c07135",
    "name": "justice-leaderboard-service",
    "realm": "demo",
    "version": "2.26.7",
    "version-roles-seeding": "1.0.4"
  }
}