{
  "host": "demo.accelbyte.io",
  "info": {
    "description": "Justice Lobby Server",
    "title": "justice-lobby-server",
    "version": "staging"
  },
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "HasPermission": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {
        "ADMIN:NAMESPACE:*:LOBBY:CONFIG [READ]": "ADMIN:NAMESPACE:*:LOBBY:CONFIG [READ]",
        "ADMIN:NAMESPACE:{namespace}:LOBBY:CCU [READ]": "ADMIN:NAMESPACE:{namespace}:LOBBY:CCU [READ]",
        "ADMIN:NAMESPACE:{namespace}:LOBBY:CONFIG [READ]": "ADMIN:NAMESPACE:{namespace}:LOBBY:CONFIG [READ]",
        "ADMIN:NAMESPACE:{namespace}:LOBBY:CONFIG [UPDATE]": "ADMIN:NAMESPACE:{namespace}:LOBBY:CONFIG [UPDATE]",
        "ADMIN:NAMESPACE:{namespace}:NOTIFICATION [CREATE]": "ADMIN:NAMESPACE:{namespace}:NOTIFICATION [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:NOTIFICATION [DELETE]": "ADMIN:NAMESPACE:{namespace}:NOTIFICATION [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:NOTIFICATION [READ]": "ADMIN:NAMESPACE:{namespace}:NOTIFICATION [READ]",
        "ADMIN:NAMESPACE:{namespace}:NOTIFICATION [UPDATE]": "ADMIN:NAMESPACE:{namespace}:NOTIFICATION [UPDATE]",
        "ADMIN:NAMESPACE:{namespace}:PARTY:STORAGE [READ]": "ADMIN:NAMESPACE:{namespace}:PARTY:STORAGE [READ]",
        "ADMIN:NAMESPACE:{namespace}:PARTY:STORAGE [UPDATE]": "ADMIN:NAMESPACE:{namespace}:PARTY:STORAGE [UPDATE]",
        "ADMIN:NAMESPACE:{namespace}:PROFANITY [CREATE]": "ADMIN:NAMESPACE:{namespace}:PROFANITY [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:PROFANITY [DELETE]": "ADMIN:NAMESPACE:{namespace}:PROFANITY [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:PROFANITY [READ]": "ADMIN:NAMESPACE:{namespace}:PROFANITY [READ]",
        "ADMIN:NAMESPACE:{namespace}:PROFANITY [UPDATE]": "ADMIN:NAMESPACE:{namespace}:PROFANITY [UPDATE]",
        "ADMIN:NAMESPACE:{namespace}:THIRDPARTY:CONFIG [CREATE]": "ADMIN:NAMESPACE:{namespace}:THIRDPARTY:CONFIG [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:THIRDPARTY:CONFIG [DELETE]": "ADMIN:NAMESPACE:{namespace}:THIRDPARTY:CONFIG [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:THIRDPARTY:CONFIG [READ]": "ADMIN:NAMESPACE:{namespace}:THIRDPARTY:CONFIG [READ]",
        "ADMIN:NAMESPACE:{namespace}:THIRDPARTY:CONFIG [UPDATE]": "ADMIN:NAMESPACE:{namespace}:THIRDPARTY:CONFIG [UPDATE]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:PLAYER:ATTRIBUTES [READ]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:PLAYER:ATTRIBUTES [READ]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:PLAYER:ATTRIBUTES [UPDATE]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:PLAYER:ATTRIBUTES [UPDATE]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:PLAYER:BLOCK [CREATE]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:PLAYER:BLOCK [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:PLAYER:BLOCK [READ]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:PLAYER:BLOCK [READ]",
        "NAMESPACE:{namespace}:NOTIFICATION [CREATE]": "NAMESPACE:{namespace}:NOTIFICATION [CREATE]",
        "NAMESPACE:{namespace}:TEMPLATE [CREATE]": "NAMESPACE:{namespace}:TEMPLATE [CREATE]",
        "NAMESPACE:{namespace}:TEMPLATE [DELETE]": "NAMESPACE:{namespace}:TEMPLATE [DELETE]",
        "NAMESPACE:{namespace}:TEMPLATE [READ]": "NAMESPACE:{namespace}:TEMPLATE [READ]",
        "NAMESPACE:{namespace}:TEMPLATE [UPDATE]": "NAMESPACE:{namespace}:TEMPLATE [UPDATE]",
        "NAMESPACE:{namespace}:TOPIC [CREATE]": "NAMESPACE:{namespace}:TOPIC [CREATE]",
        "NAMESPACE:{namespace}:TOPIC [DELETE]": "NAMESPACE:{namespace}:TOPIC [DELETE]",
        "NAMESPACE:{namespace}:TOPIC [READ]": "NAMESPACE:{namespace}:TOPIC [READ]",
        "NAMESPACE:{namespace}:TOPIC [UPDATE]": "NAMESPACE:{namespace}:TOPIC [UPDATE]",
        "NAMESPACE:{namespace}:USER:{userId}:FRIENDS [CREATE]": "NAMESPACE:{namespace}:USER:{userId}:FRIENDS [CREATE]",
        "NAMESPACE:{namespace}:USER:{userId}:FRIENDS [READ]": "NAMESPACE:{namespace}:USER:{userId}:FRIENDS [READ]",
        "NAMESPACE:{namespace}:USER:{userId}:NOTIFICATION [CREATE]": "NAMESPACE:{namespace}:USER:{userId}:NOTIFICATION [CREATE]"
      },
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "HasScope": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {
        "social": "social"
      },
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "authorization": {
      "in": "header",
      "name": "Authorization",
      "type": "apiKey"
    }
  },
  "swagger": "2.0",
  "paths": {
    "/friends/namespaces/{namespace}/me": {
      "get": {
        "operationId": "getUserFriendsUpdated",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "get list of friends",
        "tags": [
          "friends",
          "public"
        ]
      }
    },
    "/friends/namespaces/{namespace}/me/incoming": {
      "get": {
        "operationId": "getUserIncomingFriends",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "get list of incoming friends",
        "tags": [
          "friends",
          "public"
        ]
      }
    },
    "/friends/namespaces/{namespace}/me/incoming-time": {
      "get": {
        "operationId": "getUserIncomingFriendsWithTime",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "get list of incoming friends with requested time info",
        "tags": [
          "friends",
          "public"
        ]
      }
    },
    "/friends/namespaces/{namespace}/me/outgoing": {
      "get": {
        "operationId": "getUserOutgoingFriends",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "get list of outgoing friends",
        "tags": [
          "friends",
          "public"
        ]
      }
    },
    "/friends/namespaces/{namespace}/me/outgoing-time": {
      "get": {
        "operationId": "getUserOutgoingFriendsWithTime",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "get list of outgoing friends with requested time info",
        "tags": [
          "friends",
          "public"
        ]
      }
    },
    "/friends/namespaces/{namespace}/me/request": {
      "post": {
        "description": "Client should provide either friendID or friendPublicID. If both are provided, friendID will be chosen to be used.",
        "operationId": "userRequestFriend",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "user add friend",
        "tags": [
          "friends",
          "public"
        ]
      }
    },
    "/friends/namespaces/{namespace}/me/request/accept": {
      "post": {
        "operationId": "userAcceptFriendRequest",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "user accept friend",
        "tags": [
          "friends",
          "public"
        ]
      }
    },
    "/friends/namespaces/{namespace}/me/request/cancel": {
      "post": {
        "operationId": "userCancelFriendRequest",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "user cancel a friend request",
        "tags": [
          "friends",
          "public"
        ]
      }
    },
    "/friends/namespaces/{namespace}/me/request/reject": {
      "post": {
        "operationId": "userRejectFriendRequest",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "user reject a friend request",
        "tags": [
          "friends",
          "public"
        ]
      }
    },
    "/friends/namespaces/{namespace}/me/status/{friendId}": {
      "get": {
        "operationId": "userGetFriendshipStatus",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "user get friendship status",
        "tags": [
          "friends",
          "public"
        ]
      }
    },
    "/friends/namespaces/{namespace}/me/unfriend": {
      "post": {
        "operationId": "userUnfriendRequest",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "user unfriend a friend",
        "tags": [
          "friends",
          "public"
        ]
      }
    },
    "/friends/namespaces/{namespace}/users/{userId}/add/bulk": {
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;NAMESPACE:{namespace}:USER:{userId}:FRIENDS [CREATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;friends request in a namespace.",
        "operationId": "addFriendsWithoutConfirmation",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:FRIENDS [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Add friends without confirmation",
        "tags": [
          "friends",
          "public"
        ]
      }
    },
    "/lobby/v1/admin/config": {
      "get": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:*:LOBBY:CONFIG [READ]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;get lobby config of all namespaces.\u0026lt;br\u0026gt;default MaxDSWaitTime is 120 (second)",
        "operationId": "adminGetAllConfigV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:*:LOBBY:CONFIG [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "admin get all namespaces config",
        "tags": [
          "config"
        ]
      }
    },
    "/lobby/v1/admin/config/namespaces/{namespace}": {
      "get": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:LOBBY:CONFIG [READ]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;get lobby config of a namespace.\u0026lt;br\u0026gt;default MaxDSWaitTime is 120 (second)",
        "operationId": "adminGetConfigV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LOBBY:CONFIG [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "admin get namespace config",
        "tags": [
          "config"
        ]
      },
      "put": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:LOBBY:CONFIG [UPDATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;update lobby config of a namespace.\u0026lt;br\u0026gt;MaxDSWaitTime value is cannot less than 1, if null it will use default value in 120 (second)",
        "operationId": "adminUpdateConfigV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LOBBY:CONFIG [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "admin update namespace config",
        "tags": [
          "config"
        ]
      }
    },
    "/lobby/v1/admin/config/namespaces/{namespace}/export": {
      "get": {
        "description": "\n\t\t\t\tRequired permission ADMIN:NAMESPACE:{namespace}:LOBBY:CONFIG [READ]\n\n\t\t\t\tRequired Scope: social\n\n\t\t\t\tExport lobby configuration to a json file. The file can then be imported from the /import endpoint. \n\t\t\t\nJSON Schema of the exported file:\n{\u0026#34;required\u0026#34;:[\u0026#34;namespace\u0026#34;,\u0026#34;entitlementItemID\u0026#34;,\u0026#34;chatRateLimitDuration\u0026#34;,\u0026#34;unregisterDelay\u0026#34;,\u0026#34;generalRateLimitDurat[...]",
        "operationId": "adminExportConfigV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LOBBY:CONFIG [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Export lobby config to a json file.",
        "tags": [
          "config"
        ]
      }
    },
    "/lobby/v1/admin/config/namespaces/{namespace}/import": {
      "post": {
        "description": "\n\t\t\t\tRequired permission ADMIN:NAMESPACE:{namespace}:LOBBY:CONFIG [UPDATE]\n\n\t\t\t\tRequired Scope: social\n\n\t\t\t\tImport config configuration from file. The existing configuration will be replaced.\n\t\t\t\tThe json file to import can be obtained from the /export endpoint. \n\t\t\t\t\n\t\t\t\tMaxDSWaitTime value is cannot less than 1, if null it will use default value in 120 (second)\n\t\t\t",
        "operationId": "adminImportConfigV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LOBBY:CONFIG [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Import lobby config from a json file.",
        "tags": [
          "config"
        ]
      }
    },
    "/lobby/v1/admin/friend/namespaces/{namespace}/users/{userId}": {
      "get": {
        "description": "Required permission : \u0026lt;code\u0026gt;NAMESPACE:{namespace}:USER:{userId}:FRIENDS [READ]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\u0026lt;br\u0026gt;get list of friends in a namespace.",
        "operationId": "get list of friends",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:FRIENDS [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "get list of friends",
        "tags": [
          "friends"
        ]
      }
    },
    "/lobby/v1/admin/notification/namespaces/{namespace}/bulkUsers/freeform/notify": {
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:NOTIFICATION [CREATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Sends notification to multiple user.\n\t\t\tAction Code: 50211",
        "operationId": "sendMultipleUsersFreeformNotificationV1Admin",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:NOTIFICATION [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "send freeform notification to multiple users",
        "tags": [
          "notification"
        ]
      }
    },
    "/lobby/v1/admin/notification/namespaces/{namespace}/freeform/notify": {
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:NOTIFICATION [CREATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Sends notification to all connected users in a namespace.\u0026lt;br\u0026gt;\n\t\t\tAction Code: 50201",
        "operationId": "sendUsersFreeformNotificationV1Admin",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:NOTIFICATION [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "send freeform notification to connected users",
        "tags": [
          "notification"
        ]
      }
    },
    "/lobby/v1/admin/notification/namespaces/{namespace}/parties/{partyId}/freeform/notify": {
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:NOTIFICATION [CREATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\t\t\u0026lt;br\u0026gt;Sends notification to a party.",
        "operationId": "sendPartyFreeformNotificationV1Admin",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:NOTIFICATION [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "send freeform notification to a party",
        "tags": [
          "notification"
        ]
      }
    },
    "/lobby/v1/admin/notification/namespaces/{namespace}/parties/{partyId}/templates/notify": {
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:NOTIFICATION [CREATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\t\t\u0026lt;br\u0026gt;Sends templated notification to a party.\n\t\t\t\t\t\u0026lt;br\u0026gt;In the request body, specify which template slug (template identifier) to use and the template language.\n\t\t\t\t\t\u0026lt;br\u0026gt;NotificationTemplate context is the key-value pair defini[...]",
        "operationId": "sendPartyTemplatedNotificationV1Admin",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:NOTIFICATION [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "send templated notification to a party",
        "tags": [
          "notification"
        ]
      }
    },
    "/lobby/v1/admin/notification/namespaces/{namespace}/templates": {
      "get": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:NOTIFICATION [READ]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Get all templates in a namespace\u0026lt;br\u0026gt;\n\t\t\tAction Code: 50203",
        "operationId": "getAllNotificationTemplatesV1Admin",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:NOTIFICATION [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "get all notification template in a namespace",
        "tags": [
          "notification"
        ]
      },
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:NOTIFICATION [CREATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Create new notification template. Include handlebars {{key}} for replaceable contexts. The key inside\n\t\t\thandlebars will be the key to be replaced when sending notification. Already existing template with the same\n\t\t\tslug and language can not be created.\n\t\t\[...]",
        "operationId": "createNotificationTemplateV1Admin",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:NOTIFICATION [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "create new notification template",
        "tags": [
          "notification"
        ]
      }
    },
    "/lobby/v1/admin/notification/namespaces/{namespace}/templates/notify": {
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:NOTIFICATION [CREATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Sends notification to all connected users in a namespace with predefined template.\n\t\t\t\u0026lt;br\u0026gt;In the request body, specify which template slug (template identifier) to use and the template language.\n\t\t\t\u0026lt;br\u0026gt;NotificationTemplate contex[...]",
        "operationId": "sendUsersTemplatedNotificationV1Admin",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:NOTIFICATION [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "send notification to connected users with template",
        "tags": [
          "notification"
        ]
      }
    },
    "/lobby/v1/admin/notification/namespaces/{namespace}/templates/{templateSlug}": {
      "delete": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:NOTIFICATION [DELETE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Delete template slug in notification template\u0026lt;br\u0026gt;\n\t\t\tAction Code: 50206",
        "operationId": "deleteNotificationTemplateSlugV1Admin",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:NOTIFICATION [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "delete template slug in notification template",
        "tags": [
          "notification"
        ]
      },
      "get": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:NOTIFICATION [READ]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Get all templates in a namespace\u0026lt;br\u0026gt;\n\t\t\tAction Code: 50205",
        "operationId": "getTemplateSlugLocalizationsTemplateV1Admin",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:NOTIFICATION [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "get all notification template localization in a slug",
        "tags": [
          "notification"
        ]
      }
    },
    "/lobby/v1/admin/notification/namespaces/{namespace}/templates/{templateSlug}/languages/{templateLanguage}": {
      "delete": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:NOTIFICATION [DELETE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;delete template localization\u0026lt;br/\u0026gt;\n\t\t\tAction Code: 50209",
        "operationId": "deleteTemplateLocalizationV1Admin",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:NOTIFICATION [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "delete template localization",
        "tags": [
          "notification"
        ]
      },
      "get": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:NOTIFICATION [READ]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Get a template localization\u0026lt;br/\u0026gt;\n\t\t\tAction Code: 50207",
        "operationId": "getSingleTemplateLocalizationV1Admin",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:NOTIFICATION [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "get a template localization",
        "tags": [
          "notification"
        ]
      },
      "put": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:NOTIFICATION [UPDATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br/\u0026gt;update template localization\u0026lt;br/\u0026gt;\n\t\t\tAction Code: 50208",
        "operationId": "updateTemplateLocalizationV1Admin",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:NOTIFICATION [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "update template localization",
        "tags": [
          "notification"
        ]
      }
    },
    "/lobby/v1/admin/notification/namespaces/{namespace}/templates/{templateSlug}/languages/{templateLanguage}/publish": {
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:NOTIFICATION [CREATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Publish notification template draft. Empty draft can not be published.\u0026lt;br/\u0026gt;\n\t\t\tAction Code: 50210",
        "operationId": "publishTemplateLocalizationV1Admin",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:NOTIFICATION [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "publish template localization draft",
        "tags": [
          "notification"
        ]
      }
    },
    "/lobby/v1/admin/notification/namespaces/{namespace}/topics": {
      "get": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:NOTIFICATION [READ]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;get topic by namespace.\u0026lt;br/\u0026gt;\n\t\t\tAction Code: 50213",
        "operationId": "getAllNotificationTopicsV1Admin",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:NOTIFICATION [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "get topic by namespace",
        "tags": [
          "notification"
        ]
      },
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:NOTIFICATION [CREATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Create new notification topic.\n\t\t\t\u0026lt;br\u0026gt;topic should be alphabets, no special char except underscore, uppercase and no spacing. for example: TOPIC_TEST.\n\t\t\tAlready existing topic can not be created\u0026lt;br/\u0026gt;\n\t\t\tAction Code: 50214",
        "operationId": "createNotificationTopicV1Admin",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:NOTIFICATION [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "create new notification topic",
        "tags": [
          "notification"
        ]
      }
    },
    "/lobby/v1/admin/notification/namespaces/{namespace}/topics/{topicName}": {
      "delete": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:NOTIFICATION [DELETE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;delete topic information by topic name.\n\t\t\t\u0026lt;br\u0026gt;topic should be alphabets, no special char except underscore, uppercase and no spacing. for example: TOPIC_TEST.\n\t\t\tAlready existing topic can not be created \u0026lt;br/\u0026gt;\n\t\t\tAction Code[...]",
        "operationId": "deleteNotificationTopicV1Admin",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:NOTIFICATION [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "delete topic information by topic name",
        "tags": [
          "notification"
        ]
      },
      "get": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:NOTIFICATION [READ]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;get topic information by topic name.\u0026lt;br/\u0026gt;\n\t\t\tAction Code: 50215",
        "operationId": "getNotificationTopicV1Admin",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:NOTIFICATION [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "get topic information by topic name",
        "tags": [
          "notification"
        ]
      },
      "put": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:NOTIFICATION [UPDATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;update topic information by topic name.\n\t\t\t\u0026lt;br\u0026gt;topic should be alphabets, no special char except underscore, uppercase and no spacing. for example: TOPIC_TEST.\n\t\t\tAlready existing topic can not be created \u0026lt;br/\u0026gt;\n\t\t\tAction Code[...]",
        "operationId": "updateNotificationTopicV1Admin",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:NOTIFICATION [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "update topic information by topic name",
        "tags": [
          "notification"
        ]
      }
    },
    "/lobby/v1/admin/notification/namespaces/{namespace}/users/{userId}/freeform/notify": {
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:NOTIFICATION [CREATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Sends notification to a user.\n\t\t\tAction Code: 50211",
        "operationId": "sendSpecificUserFreeformNotificationV1Admin",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:NOTIFICATION [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "send freeform notification to a user",
        "tags": [
          "notification"
        ]
      }
    },
    "/lobby/v1/admin/notification/namespaces/{namespace}/users/{userId}/templates/notify": {
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:NOTIFICATION [CREATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Sends templated notification to a user.\n\t\t\t\u0026lt;br\u0026gt;In the request body, specify which template slug (template identifier) to use and the template language.\n\t\t\t\u0026lt;br\u0026gt;NotificationTemplate context is the key-value pair defining the value [...]",
        "operationId": "sendSpecificUserTemplatedNotificationV1Admin",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:NOTIFICATION [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "send templated notification to specific user",
        "tags": [
          "notification"
        ]
      }
    },
    "/lobby/v1/admin/party/namespaces/{namespace}/parties/{partyId}": {
      "get": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:PARTY:STORAGE [READ]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;get party data in a namespace.",
        "operationId": "adminGetPartyDataV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:PARTY:STORAGE [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "admin get party data",
        "tags": [
          "party"
        ]
      }
    },
    "/lobby/v1/admin/party/namespaces/{namespace}/parties/{partyId}/attributes": {
      "put": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:PARTY:STORAGE [UPDATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;update party attributes in a namespace.",
        "operationId": "adminUpdatePartyAttributesV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:PARTY:STORAGE [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "admin update party attributes",
        "tags": [
          "Lobby Operations"
        ]
      }
    },
    "/lobby/v1/admin/party/namespaces/{namespace}/parties/{partyId}/join/{userId}": {
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:PARTY:STORAGE [UPDATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;admin join a player into a party.",
        "operationId": "adminJoinPartyV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:PARTY:STORAGE [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "admin join a player into a party",
        "tags": [
          "Lobby Operations"
        ]
      }
    },
    "/lobby/v1/admin/party/namespaces/{namespace}/users/{userId}/party": {
      "get": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:PARTY:STORAGE [READ]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;get party data in a namespace.",
        "operationId": "adminGetUserPartyV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:PARTY:STORAGE [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "admin get user party data",
        "tags": [
          "party"
        ]
      }
    },
    "/lobby/v1/admin/player/namespaces/{namespace}/ccu": {
      "get": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:LOBBY:CCU [READ]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Get the number of players connected to the Lobby in the given namespace.",
        "operationId": "adminGetLobbyCCU",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:LOBBY:CCU [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "admin get number of players currently connected to the lobby.",
        "tags": [
          "player"
        ]
      }
    },
    "/lobby/v1/admin/player/namespaces/{namespace}/users/{userId}/attributes": {
      "get": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:PLAYER:ATTRIBUTES [READ]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;get all player\u0026#39;s session attribute by user id in a namespace.",
        "operationId": "adminGetAllPlayerSessionAttribute",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:PLAYER:ATTRIBUTES [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "admin get all player's session attribute",
        "tags": [
          "player"
        ]
      },
      "put": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:PLAYER:ATTRIBUTES [UPDATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;set player\u0026#39;s session attribute by user id in a namespace.",
        "operationId": "adminSetPlayerSessionAttribute",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:PLAYER:ATTRIBUTES [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "admin set player's session attribute",
        "tags": [
          "player"
        ]
      }
    },
    "/lobby/v1/admin/player/namespaces/{namespace}/users/{userId}/attributes/{attribute}": {
      "get": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:PLAYER:ATTRIBUTES [READ]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;get player\u0026#39;s specific session attribute by user id in a namespace.",
        "operationId": "adminGetPlayerSessionAttribute",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:PLAYER:ATTRIBUTES [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "admin get player's session attribute",
        "tags": [
          "player"
        ]
      }
    },
    "/lobby/v1/admin/player/namespaces/{namespace}/users/{userId}/blocked": {
      "get": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:PLAYER:BLOCK [READ]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;get blocked players data by user id in a namespace.",
        "operationId": "adminGetPlayerBlockedPlayersV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:PLAYER:BLOCK [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "admin get blocked players by user id",
        "tags": [
          "player"
        ]
      }
    },
    "/lobby/v1/admin/player/namespaces/{namespace}/users/{userId}/blocked-by": {
      "get": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:PLAYER:BLOCK [READ]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;load get players who blocked this player in a namespace based on user id",
        "operationId": "adminGetPlayerBlockedByPlayersV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:PLAYER:BLOCK [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "get players who blocked this player by user id",
        "tags": [
          "player"
        ]
      }
    },
    "/lobby/v1/admin/player/namespaces/{namespace}/users/{userId}/bulk/block": {
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:PLAYER:BLOCK [CREATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Bulk block player in a namespace by list of user id",
        "operationId": "adminBulkBlockPlayersV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:PLAYER:BLOCK [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Admin bulk blocks player by list user id",
        "tags": [
          "player"
        ]
      }
    },
    "/lobby/v1/admin/profanity/namespaces/{namespace}/filters/debug": {
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:PROFANITY [READ]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;get the list of filters that would modify the phrase",
        "operationId": "adminDebugProfanityFilters",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:PROFANITY [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "get the list of filters that would modify the phrase",
        "tags": [
          "profanity"
        ]
      }
    },
    "/lobby/v1/admin/profanity/namespaces/{namespace}/list/{list}/filters": {
      "get": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:PROFANITY [READ]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;get the list of filters inside the list.",
        "operationId": "adminGetProfanityListFiltersV1",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:PROFANITY [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "get the list of filters inside the list",
        "tags": [
          "profanity"
        ]
      },
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:PROFANITY [CREATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;add a single filter into the list",
        "operationId": "adminAddProfanityFilterIntoList",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:PROFANITY [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "add a single filter into the list",
        "tags": [
          "profanity"
        ]
      }
    },
    "/lobby/v1/admin/profanity/namespaces/{namespace}/list/{list}/filters/bulk": {
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:PROFANITY [CREATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;add multiple filters into the list",
        "operationId": "adminAddProfanityFilters",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:PROFANITY [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "add multiple filters into the list",
        "tags": [
          "profanity"
        ]
      }
    },
    "/lobby/v1/admin/profanity/namespaces/{namespace}/list/{list}/filters/bulk-file": {
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:PROFANITY [CREATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;import a file with filters",
        "operationId": "adminImportProfanityFiltersFromFile",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:PROFANITY [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "import a file with filters",
        "tags": [
          "profanity"
        ]
      }
    },
    "/lobby/v1/admin/profanity/namespaces/{namespace}/list/{list}/filters/delete": {
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:PROFANITY [DELETE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;delete the filter from the list",
        "operationId": "adminDeleteProfanityFilter",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:PROFANITY [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "delete the filter from the list",
        "tags": [
          "profanity"
        ]
      }
    },
    "/lobby/v1/admin/profanity/namespaces/{namespace}/lists": {
      "get": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:PROFANITY [READ]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;get lists",
        "operationId": "adminGetProfanityLists",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:PROFANITY [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "get lists",
        "tags": [
          "profanity"
        ]
      },
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:PROFANITY [CREATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;create a new list",
        "operationId": "adminCreateProfanityList",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:PROFANITY [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "create a new list",
        "tags": [
          "profanity"
        ]
      }
    },
    "/lobby/v1/admin/profanity/namespaces/{namespace}/lists/{list}": {
      "delete": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:PROFANITY [DELETE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;delete a list include all filters inside of it",
        "operationId": "adminDeleteProfanityList",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:PROFANITY [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "delete a list include all filters inside of it",
        "tags": [
          "profanity"
        ]
      },
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:PROFANITY [UPDATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;update the list",
        "operationId": "adminUpdateProfanityList",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:PROFANITY [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "update the list",
        "tags": [
          "profanity"
        ]
      }
    },
    "/lobby/v1/admin/profanity/namespaces/{namespace}/rule": {
      "get": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:PROFANITY [READ]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;get current profanity rule",
        "operationId": "adminGetProfanityRule",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:PROFANITY [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "get current profanity rule",
        "tags": [
          "profanity"
        ]
      },
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:PROFANITY [UPDATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;set current profanity rule",
        "operationId": "adminSetProfanityRuleForNamespace",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:PROFANITY [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "set current profanity rule",
        "tags": [
          "profanity"
        ]
      }
    },
    "/lobby/v1/admin/profanity/namespaces/{namespace}/verify": {
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:PROFANITY [READ]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;verify a message directly from the UI or other services",
        "operationId": "adminVerifyMessageProfanityResponse",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:PROFANITY [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "verify a message directly from the UI or other services",
        "tags": [
          "profanity"
        ]
      }
    },
    "/lobby/v1/admin/thirdparty/namespaces/{namespace}/config/steam": {
      "delete": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:THIRDPARTY:CONFIG [DELETE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;delete third party config in a namespace.",
        "operationId": "adminDeleteThirdPartyConfig",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:THIRDPARTY:CONFIG [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete Third Party Steam Config",
        "tags": [
          "thirdParty"
        ]
      },
      "get": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:THIRDPARTY:CONFIG [READ]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;get third party config for specified namespace.",
        "operationId": "adminGetThirdPartyConfig",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:THIRDPARTY:CONFIG [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get Third Party Steam Config",
        "tags": [
          "thirdParty"
        ]
      },
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:THIRDPARTY:CONFIG [CREATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;create third party config in a namespace.",
        "operationId": "adminCreateThirdPartyConfig",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:THIRDPARTY:CONFIG [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Create Third Party Steam Config",
        "tags": [
          "thirdParty"
        ]
      },
      "put": {
        "description": "Required permission : \u0026lt;code\u0026gt;ADMIN:NAMESPACE:{namespace}:THIRDPARTY:CONFIG [UPDATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Update third party config in a namespace.",
        "operationId": "adminUpdateThirdPartyConfig",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:THIRDPARTY:CONFIG [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Update Third Party Steam Config",
        "tags": [
          "thirdParty"
        ]
      }
    },
    "/lobby/v1/messages": {
      "get": {
        "description": "get the list of messages.",
        "operationId": "publicGetMessages",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "get service messages",
        "tags": [
          "Lobby Operations"
        ]
      }
    },
    "/lobby/v1/public/party/namespaces/{namespace}/parties/{partyId}": {
      "get": {
        "description": "Required valid user authorization \u0026lt;br/\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;load personal party data in a namespace based on Party ID \u0026lt;br/\u0026gt;\n\t\t\tAction Code: 50101",
        "operationId": "publicGetPartyDataV1",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "get party data by party id",
        "tags": [
          "party"
        ]
      }
    },
    "/lobby/v1/public/party/namespaces/{namespace}/parties/{partyId}/attributes": {
      "put": {
        "description": "Required valid user authorization \u0026lt;br/\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;update party attributes in a namespace.",
        "operationId": "publicUpdatePartyAttributesV1",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "update party attributes",
        "tags": [
          "party"
        ]
      }
    },
    "/lobby/v1/public/party/namespaces/{namespace}/parties/{partyId}/limit": {
      "put": {
        "description": "Required valid user authorization \u0026lt;br/\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Set party limit, only party leader can call this endpoint.",
        "operationId": "publicSetPartyLimitV1",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "set party limit",
        "tags": [
          "party"
        ]
      }
    },
    "/lobby/v1/public/player/namespaces/{namespace}/users/me/blocked": {
      "get": {
        "description": "Required valid user authorization \u0026lt;br/\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;load blocked players in a namespace based on user id \u0026lt;br/\u0026gt;\n\t\t\tAction Code: 50101",
        "operationId": "publicGetPlayerBlockedPlayersV1",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "get blocked players by user id",
        "tags": [
          "player"
        ]
      }
    },
    "/lobby/v1/public/player/namespaces/{namespace}/users/me/blocked-by": {
      "get": {
        "description": "Required valid user authorization \u0026lt;br/\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;load get players who blocked this player in a namespace based on user id \u0026lt;br/\u0026gt;\n\t\t\tAction Code: 50101",
        "operationId": "publicGetPlayerBlockedByPlayersV1",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "get players who blocked this player by user id",
        "tags": [
          "player"
        ]
      }
    },
    "/lobby/v1/public/presence/namespaces/{namespace}/users/presence": {
      "get": {
        "description": "Query users presence with given namespace and userIds.",
        "operationId": "UsersPresenceHandlerV1",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Query users presence",
        "tags": [
          "presence"
        ]
      }
    },
    "/notification/namespaces/{namespace}/freeform": {
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;NAMESPACE:{namespace}:NOTIFICATION [CREATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Sends notification to all connected users in a namespace.",
        "operationId": "freeFormNotification",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:NOTIFICATION [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "send freeform notification to a user",
        "tags": [
          "admin",
          "notification"
        ]
      }
    },
    "/notification/namespaces/{namespace}/templated": {
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;NAMESPACE:{namespace}:NOTIFICATION [CREATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Sends notification to all connected users in a namespace with predefined template.\n\t\t\t\u0026lt;br\u0026gt;In the request body, specify which template slug (template identifier) to use and the template language.\n\t\t\t\u0026lt;br\u0026gt;NotificationTemplate context is t[...]",
        "operationId": "notificationWithTemplate",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:NOTIFICATION [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "send notification to a user with template",
        "tags": [
          "admin",
          "notification"
        ]
      }
    },
    "/notification/namespaces/{namespace}/templates": {
      "get": {
        "description": "Required permission : \u0026lt;code\u0026gt;NAMESPACE:{namespace}:TEMPLATE [READ]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Get all templates in a namespace",
        "operationId": "getGameTemplate",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:TEMPLATE [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "get all notification template in a namespace",
        "tags": [
          "admin",
          "notification"
        ]
      },
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;NAMESPACE:{namespace}:TEMPLATE [CREATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Create new notification template. Include handlebars {{key}} for replaceable contexts. The the key inside\n\t\t\thandlebars will be the key to be replaced when sending notification. Already existing template with the same\n\t\t\tslug and language can not be created.\n\t\t\t\u002[...]",
        "operationId": "createTemplate",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:TEMPLATE [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "create new notification template",
        "tags": [
          "admin",
          "notification"
        ]
      }
    },
    "/notification/namespaces/{namespace}/templates/{templateSlug}": {
      "delete": {
        "description": "Required permission : \u0026lt;code\u0026gt;NAMESPACE:{namespace}:TEMPLATE [DELETE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Delete localization template",
        "operationId": "deleteTemplateSlug",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:TEMPLATE [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "delete template localization",
        "tags": [
          "admin",
          "notification"
        ]
      },
      "get": {
        "description": "Required permission : \u0026lt;code\u0026gt;NAMESPACE:{namespace}:TEMPLATE [READ]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Get all templates in a namespace",
        "operationId": "getSlugTemplate",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:TEMPLATE [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "get all notification template in a slug",
        "tags": [
          "admin",
          "notification"
        ]
      }
    },
    "/notification/namespaces/{namespace}/templates/{templateSlug}/languages/{templateLanguage}": {
      "delete": {
        "description": "Required permission : \u0026lt;code\u0026gt;NAMESPACE:{namespace}:TEMPLATE [DELETE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Delete all template in a slug",
        "operationId": "deleteTemplateLocalization",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:TEMPLATE [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "delete template localization",
        "tags": [
          "admin",
          "notification"
        ]
      },
      "get": {
        "description": "Required permission : \u0026lt;code\u0026gt;NAMESPACE:{namespace}:TEMPLATE [READ]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Get a template localization",
        "operationId": "getLocalizationTemplate",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:TEMPLATE [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "get a template localization",
        "tags": [
          "admin",
          "notification"
        ]
      },
      "put": {
        "description": "Required permission : \u0026lt;code\u0026gt;NAMESPACE:{namespace}:TEMPLATE [UPDATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Modify draft template",
        "operationId": "updateLocalizationTemplate",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:TEMPLATE [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "update template draft",
        "tags": [
          "admin",
          "notification"
        ]
      }
    },
    "/notification/namespaces/{namespace}/templates/{templateSlug}/languages/{templateLanguage}/publish": {
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;NAMESPACE:{namespace}:TEMPLATE [CREATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Publish notification template draft. Empty draft can not be published.",
        "operationId": "publishTemplate",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:TEMPLATE [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "publish draft template",
        "tags": [
          "admin",
          "notification"
        ]
      }
    },
    "/notification/namespaces/{namespace}/topics": {
      "get": {
        "description": "Required permission : \u0026lt;code\u0026gt;NAMESPACE:{namespace}:TOPIC [READ]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;get topic by namespace.",
        "operationId": "getTopicByNamespace",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:TOPIC [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "get topic by namespace",
        "tags": [
          "notification",
          "public"
        ]
      },
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;NAMESPACE:{namespace}:TOPIC [CREATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Create new notification topic.\n\t\t\t\u0026lt;br\u0026gt;topic should be alphabets, no special char except underscore, uppercase and no spacing. for example: TOPIC_TEST.\n\t\t\tAlready existing topic can not be created",
        "operationId": "createTopic",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:TOPIC [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "create new notification topic",
        "tags": [
          "notification",
          "public"
        ]
      }
    },
    "/notification/namespaces/{namespace}/topics/{topic}": {
      "delete": {
        "description": "Required permission : \u0026lt;code\u0026gt;NAMESPACE:{namespace}:TOPIC [DELETE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;delete topic information by topic name.\n\t\t\t\u0026lt;br\u0026gt;topic should be alphabets, no special char except underscore, uppercase and no spacing. for example: TOPIC_TEST.\n\t\t\tAlready existing topic can not be created",
        "operationId": "deleteTopicByTopicName",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:TOPIC [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "delete topic information by topic name",
        "tags": [
          "notification",
          "public"
        ]
      },
      "get": {
        "description": "Required permission : \u0026lt;code\u0026gt;NAMESPACE:{namespace}:TOPIC [READ]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;get topic information by topic name.",
        "operationId": "getTopicByTopicName",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:TOPIC [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "get topic information by topic name",
        "tags": [
          "notification",
          "public"
        ]
      },
      "put": {
        "description": "Required permission : \u0026lt;code\u0026gt;NAMESPACE:{namespace}:TOPIC [UPDATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;update topic information by topic name.\n\t\t\t\u0026lt;br\u0026gt;topic should be alphabets, no special char except underscore, uppercase and no spacing. for example: TOPIC_TEST.\n\t\t\tAlready existing topic can not be created",
        "operationId": "updateTopicByTopicName",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:TOPIC [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "update topic information by topic name",
        "tags": [
          "notification",
          "public"
        ]
      }
    },
    "/notification/namespaces/{namespace}/users/{userId}/freeform": {
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;NAMESPACE:{namespace}:USER:{userId}:NOTIFICATION [CREATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Sends notification to a user.",
        "operationId": "freeFormNotificationByUserID",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:NOTIFICATION [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "send freeform notification to a user",
        "tags": [
          "notification",
          "public"
        ]
      }
    },
    "/notification/namespaces/{namespace}/users/{userId}/templated": {
      "post": {
        "description": "Required permission : \u0026lt;code\u0026gt;NAMESPACE:{namespace}:USER:{userId}:NOTIFICATION [CREATE]\u0026lt;/code\u0026gt; with scope \u0026lt;code\u0026gt;social\u0026lt;/code\u0026gt;\n\t\t\t\u0026lt;br\u0026gt;Sends notification to a user with predefined template.\n\t\t\t\u0026lt;br\u0026gt;In the request body, specify which template slug (template identifier) to use and the template language.\n\t\t\t\u0026lt;br\u0026gt;NotificationTemplate context is the key-value p[...]",
        "operationId": "notificationWithTemplateByUserID",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:NOTIFICATION [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "send notification to a user with template",
        "tags": [
          "notification",
          "public"
        ]
      }
    }
  },
  "x-docs": {
    "alias": "lobby",
    "host": "https://stage.accelbyte.io",
    "path": "/lobby/apidocs/api.json"
  },
  "x-version": {
    "buildDate": "2023-05-09T13:54:57+00:00",
    "gitHash": "136677829d15f573de47582252214116d245cd00",
    "name": "justice-lobby-server",
    "revisionID": "3.19.0",
    "version": "3.19.0",
    "version-justice": "3.45.0",
    "version-roles-seeding": "0.0.3"
  }
}