{
  "host": "demo.accelbyte.io",
  "info": {
    "description": "Justice Matchmaking Service",
    "title": "Justice Match Service v2",
    "version": "1.4.1"
  },
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "HasPermission": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {
        "NAMESPACE:{namespace}:MATCHMAKING:BACKFILL [CREATE]": "NAMESPACE:{namespace}:MATCHMAKING:BACKFILL [CREATE]",
        "NAMESPACE:{namespace}:MATCHMAKING:BACKFILL [UPDATE]": "NAMESPACE:{namespace}:MATCHMAKING:BACKFILL [UPDATE]",
        "NAMESPACE:{namespace}:MATCHMAKING:FUNCTIONS [CREATE]": "NAMESPACE:{namespace}:MATCHMAKING:FUNCTIONS [CREATE]",
        "NAMESPACE:{namespace}:MATCHMAKING:FUNCTIONS [DELETE]": "NAMESPACE:{namespace}:MATCHMAKING:FUNCTIONS [DELETE]",
        "NAMESPACE:{namespace}:MATCHMAKING:FUNCTIONS [READ]": "NAMESPACE:{namespace}:MATCHMAKING:FUNCTIONS [READ]",
        "NAMESPACE:{namespace}:MATCHMAKING:POOL [CREATE]": "NAMESPACE:{namespace}:MATCHMAKING:POOL [CREATE]",
        "NAMESPACE:{namespace}:MATCHMAKING:POOL [DELETE]": "NAMESPACE:{namespace}:MATCHMAKING:POOL [DELETE]",
        "NAMESPACE:{namespace}:MATCHMAKING:POOL [READ]": "NAMESPACE:{namespace}:MATCHMAKING:POOL [READ]",
        "NAMESPACE:{namespace}:MATCHMAKING:POOL [UPDATE]": "NAMESPACE:{namespace}:MATCHMAKING:POOL [UPDATE]",
        "NAMESPACE:{namespace}:MATCHMAKING:RULES [CREATE]": "NAMESPACE:{namespace}:MATCHMAKING:RULES [CREATE]",
        "NAMESPACE:{namespace}:MATCHMAKING:RULES [DELETE]": "NAMESPACE:{namespace}:MATCHMAKING:RULES [DELETE]",
        "NAMESPACE:{namespace}:MATCHMAKING:RULES [READ]": "NAMESPACE:{namespace}:MATCHMAKING:RULES [READ]",
        "NAMESPACE:{namespace}:MATCHMAKING:RULES [UPDATE]": "NAMESPACE:{namespace}:MATCHMAKING:RULES [UPDATE]",
        "NAMESPACE:{namespace}:MATCHMAKING:TICKET [CREATE]": "NAMESPACE:{namespace}:MATCHMAKING:TICKET [CREATE]",
        "NAMESPACE:{namespace}:MATCHMAKING:TICKET [DELETE]": "NAMESPACE:{namespace}:MATCHMAKING:TICKET [DELETE]",
        "NAMESPACE:{namespace}:MATCHMAKING:TICKET [READ]": "NAMESPACE:{namespace}:MATCHMAKING:TICKET [READ]"
      },
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "HasScope": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {
        "social": "social"
      },
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "authorization": {
      "in": "header",
      "name": "Authorization",
      "type": "apiKey"
    }
  },
  "swagger": "2.0",
  "paths": {
    "/healthz": {
      "get": {
        "operationId": "GetHealthcheckInfo",
        "security": [
          {
            "authorization": []
          }
        ]
      }
    },
    "/match2/healthz": {
      "get": {
        "operationId": "GetHealthcheckInfoV1",
        "security": [
          {
            "authorization": []
          }
        ]
      }
    },
    "/match2/v1/namespaces/{namespace}/backfill": {
      "post": {
        "description": " Required Permission: NAMESPACE:{namespace}:MATCHMAKING:BACKFILL [CREATE]\n\nRequired Scope: social\n\nCreate backfill ticket\n",
        "operationId": "CreateBackfill",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:BACKFILL [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Create a backfill ticket",
        "tags": [
          "Backfill"
        ]
      }
    },
    "/match2/v1/namespaces/{namespace}/backfill/{backfillID}/proposal/accept": {
      "put": {
        "description": " Required Permission: NAMESPACE:{namespace}:MATCHMAKING:BACKFILL [UPDATE]\n\nRequired Scope: social\n\nAccept backfill proposal\n",
        "operationId": "AcceptBackfill",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:BACKFILL [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Accept a backfill proposal",
        "tags": [
          "Backfill"
        ]
      }
    },
    "/match2/v1/namespaces/{namespace}/backfill/{backfillID}/proposal/reject": {
      "put": {
        "description": " Required Permission: NAMESPACE:{namespace}:MATCHMAKING:BACKFILL [UPDATE]\n\nRequired Scope: social\n\nReject backfill proposal\n",
        "operationId": "RejectBackfill",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:BACKFILL [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Reject a backfill proposal",
        "tags": [
          "Backfill"
        ]
      }
    },
    "/match2/v1/namespaces/{namespace}/match-functions": {
      "get": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:FUNCTIONS [READ]\n\nRequired Scope: social\n\nList existing match functions.\n",
        "operationId": "MatchFunctionList",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:FUNCTIONS [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "List existing match functions",
        "tags": [
          "Match-Functions"
        ]
      },
      "post": {
        "description": " Required Permission: NAMESPACE:{namespace}:MATCHMAKING:FUNCTIONS [CREATE]\n\nRequired Scope: social\n\nCreates a new matchmaking function.\n",
        "operationId": "CreateMatchFunction",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:FUNCTIONS [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Create a match function",
        "tags": [
          "Match-Functions"
        ]
      }
    },
    "/match2/v1/namespaces/{namespace}/match-functions/{name}": {
      "delete": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:FUNCTIONS [DELETE]\n\nRequired Scope: social\n\nDeletes an existing match function.\n",
        "operationId": "DeleteMatchFunction",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:FUNCTIONS [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete a match function",
        "tags": [
          "Match-Functions"
        ]
      }
    },
    "/match2/v1/namespaces/{namespace}/match-pools": {
      "get": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:POOL [READ]\n\nRequired Scope: social\n\nList matchmaking pools.\n",
        "operationId": "MatchPoolList",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:POOL [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "List match pools",
        "tags": [
          "Match-Pools"
        ]
      },
      "post": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:POOL [CREATE]\n\nRequired Scope: social\n\nCreates a new matchmaking pool.\n\nA pool is isolated from other pools (i.e. tickets may be matched with other tickets in the same pool, but not with tickets in other pools).\nEach pool has its own matchmaking rules and/or logic.\n\nticket_expiration_seconds and backfill_ticket_expiration_seconds will be set to 300 seconds (5 minutes) by default if not filled.\n",
        "operationId": "CreateMatchPool",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:POOL [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Create a match pool",
        "tags": [
          "Match-Pools"
        ]
      }
    },
    "/match2/v1/namespaces/{namespace}/match-pools/{pool}": {
      "delete": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:POOL [DELETE]\n\nRequired Scope: social\n\nDeletes an existing matchmaking pool.\n",
        "operationId": "DeleteMatchPool",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:POOL [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete a match pool",
        "tags": [
          "Match-Pools"
        ]
      },
      "get": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:POOL [READ]\n\nRequired Scope: social\n\nGet details for a specific match pool\n",
        "operationId": "MatchPoolDetails",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:POOL [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get details for a specific match pool",
        "tags": [
          "Match-Pools"
        ]
      },
      "put": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:POOL [UPDATE]\n\nRequired Scope: social\n\nUpdates an existing matchmaking pool.\n\nticket_expiration_seconds and backfill_ticket_expiration_seconds will be set to 300 seconds (5 minutes) by default if not filled.\n",
        "operationId": "UpdateMatchPool",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:POOL [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Update a match pool",
        "tags": [
          "Match-Pools"
        ]
      }
    },
    "/match2/v1/namespaces/{namespace}/match-tickets": {
      "post": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:TICKET [CREATE]\n\nRequired Scope: social\n\nCreates a new request for matchmaking\n",
        "operationId": "CreateMatchTicket",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:TICKET [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Create a matchmaking ticket",
        "tags": [
          "Match-Tickets"
        ]
      }
    },
    "/match2/v1/namespaces/{namespace}/match-tickets/{ticketid}": {
      "delete": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:TICKET [DELETE]\n\nRequired Scope: social\n\nDeletes an existing matchmaking ticket.\n",
        "operationId": "DeleteMatchTicket",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:TICKET [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete a match ticket",
        "tags": [
          "Match-Tickets"
        ]
      },
      "get": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:TICKET [READ]\n\nRequired Scope: social\n\nGet details for a specific match ticket\n",
        "operationId": "MatchTicketDetails",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:TICKET [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get details for a specific match ticket",
        "tags": [
          "Match-Tickets"
        ]
      }
    },
    "/match2/v1/namespaces/{namespace}/rulesets": {
      "get": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:RULES [READ]\n\nRequired Scope: social\n\nList rule sets.\n",
        "operationId": "RuleSetList",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:RULES [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "List existing rule sets",
        "tags": [
          "Rule-Sets"
        ]
      },
      "post": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:RULES [CREATE]\n\nRequired Scope: social\n\nCreates a new rules set.\n\nA rule set has a name and contains arbitrary data which is meaningful to some particular match function(s)\nThe name is used for a match pool to select the ruleset data that should be sent to the match function when matchmaking in that pool.\n",
        "operationId": "CreateRuleSet",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:RULES [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Create a match rule set",
        "tags": [
          "Rule-Sets"
        ]
      }
    },
    "/match2/v1/namespaces/{namespace}/rulesets/{ruleset}": {
      "delete": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:RULES [DELETE]\n\nRequired Scope: social\n\nDeletes an existing rule set.\n",
        "operationId": "DeleteRuleSet",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:RULES [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete a rule set",
        "tags": [
          "Rule-Sets"
        ]
      },
      "get": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:RULES [READ]\n\nRequired Scope: social\n\nGet details for a specific rule set\n",
        "operationId": "RuleSetDetails",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:RULES [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get details for a specific rule set",
        "tags": [
          "Rule-Sets"
        ]
      },
      "put": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:RULES [UPDATE]\n\nRequired Scope: social\n\nUpdates an existing matchmaking rule set.\n",
        "operationId": "UpdateRuleSet",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:RULES [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Update a match rule set",
        "tags": [
          "Rule-Sets"
        ]
      }
    },
    "/match2/version": {
      "get": {
        "operationId": "versionCheckHandler",
        "security": [
          {
            "authorization": []
          }
        ]
      }
    }
  }
}