{
  "host": "demo.accelbyte.io",
  "info": {
    "description": "Justice Matchmaking Service",
    "title": "Justice Matchmaking Service",
    "version": "2.25.3"
  },
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "HasPermission": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {
        "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Create]": "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Create]",
        "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Delete]": "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Delete]",
        "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [READ]": "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [READ]",
        "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Read]": "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Read]",
        "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Update]": "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Update]",
        "NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [CREATE]": "NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [CREATE]",
        "NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Delete]": "NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Delete]",
        "NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [READ]": "NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [READ]",
        "NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [UPDATE]": "NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [UPDATE]",
        "NAMESPACE:{namespace}:MATCHMAKING:CHANNEL:METRICS [READ]": "NAMESPACE:{namespace}:MATCHMAKING:CHANNEL:METRICS [READ]",
        "NAMESPACE:{namespace}:MATCHMAKING:REBALANCE [Update]": "NAMESPACE:{namespace}:MATCHMAKING:REBALANCE [Update]",
        "NAMESPACE:{namespace}:MATCHRESULT [CREATE]": "NAMESPACE:{namespace}:MATCHRESULT [CREATE]",
        "NAMESPACE:{namespace}:SESSION [CREATE]": "NAMESPACE:{namespace}:SESSION [CREATE]",
        "NAMESPACE:{namespace}:SESSION [READ]": "NAMESPACE:{namespace}:SESSION [READ]",
        "NAMESPACE:{namespace}:SESSION [UPDATE]": "NAMESPACE:{namespace}:SESSION [UPDATE]"
      },
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "HasScope": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {
        "social": "social"
      },
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "authorization": {
      "in": "header",
      "name": "Authorization",
      "type": "apiKey"
    }
  },
  "swagger": "2.0",
  "paths": {
    "/healthz": {
      "get": {
        "operationId": "GetHealthcheckInfo",
        "security": [
          {
            "authorization": []
          }
        ],
        "tags": [
          "Matchmaking Operations"
        ]
      }
    },
    "/matchmaking/healthz": {
      "get": {
        "operationId": "handlerV3Healthz",
        "security": [
          {
            "authorization": []
          }
        ],
        "tags": [
          "Matchmaking Operations"
        ]
      }
    },
    "/matchmaking/namespaces/{namespace}/channels": {
      "get": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [READ]\n\nRequired Scope: social\n\nReads all available channels in a namespace\n",
        "operationId": "GetAllChannelsHandler",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get all channels",
        "tags": [
          "Matchmaking",
          "admin"
        ]
      },
      "post": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [CREATE]\n\nRequired Scope: social\n\nCreates a new matchmaking channel.\n\nMatchmaking channels is a list of pool name that is eligible for matchmaking processes. \nGameMode isolates each matchmaking pools.\n\nIf match timeout is set to 0, by default, incoming matchmaking requests will be timed out after 1 hour.\n\nIf max worker delay is set to 0, by default, it will wait for at max ~8 seconds during low volu[...]",
        "operationId": "CreateChannelHandler",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Create a channel",
        "tags": [
          "Matchmaking",
          "admin"
        ]
      }
    },
    "/matchmaking/namespaces/{namespace}/channels/{channelName}/metrics": {
      "get": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:CHANNEL:METRICS [READ]\n\t\nRequired Scope: social\n\nGet metric for a specific match pool\n\t\nResult: queue_time in seconds\n",
        "operationId": "GetMatchPoolMetric",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:CHANNEL:METRICS [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get metrics for a specific channel",
        "tags": [
          "Matchmaking",
          "public"
        ]
      }
    },
    "/matchmaking/namespaces/{namespace}/channels/{channel}": {
      "delete": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Delete]\n\nRequired Scope: social\n\nDeletes a matchmaking channel. Matchmaking channels is a list of \npool name that is eligible for matchmaking processes. GameMode isolates each matchmaking pools.\n\nTrying to delete non-existent channel will result deletion success\n",
        "operationId": "DeleteChannelHandler",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Delete]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete a channel",
        "tags": [
          "Matchmaking",
          "admin"
        ]
      }
    },
    "/matchmaking/namespaces/{namespace}/matchresult": {
      "post": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHRESULT [CREATE]\n\nRequired Scope: social\n\nProcess match result into final attribute value and stores it to player attribute\n\nWill return final attribute value\n",
        "operationId": "StoreMatchResults",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHRESULT [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Store match result",
        "tags": [
          "Matchmaking",
          "public"
        ]
      }
    },
    "/matchmaking/namespaces/{namespace}/rebalance": {
      "post": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:REBALANCE [Update]\n\t\t\nRequired Scope: social\n\t\t\nDo rebalance the teams based on MMR from given matchID, \nconsider attribute name \u0026#34;mmr\u0026#34; (case-insensitive), \nor any first attribute with criteria \u0026#34;distance\u0026#34;\n\t\t\nWill return rebalanced mm result",
        "operationId": "Rebalance",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:REBALANCE [Update]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Rebalance Matchmaking based on MMR",
        "tags": [
          "Matchmaking",
          "public"
        ]
      }
    },
    "/matchmaking/namespaces/{namespace}/sessions": {
      "post": {
        "description": "Required Permission: NAMESPACE:{namespace}:SESSION [CREATE]\n\nRequired Scope: social\n\nQueues joinable session so that it will be matched with player\u0026#39;s match request tickets. \nThe session queued must be in a channel/game mode that is set to have joinable flag. \nThe session will be in queue until it is full or expired. \nBoth the number of players and session queue timeout can be set in the channel\u0026#39;s config.\n\nThis endpoint is intended to be called b[...]",
        "operationId": "QueueSessionHandler",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:SESSION [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Queue joinable session",
        "tags": [
          "Matchmaking",
          "public"
        ]
      }
    },
    "/matchmaking/namespaces/{namespace}/sessions/dequeue": {
      "post": {
        "description": "Required Permission: NAMESPACE:{namespace}:SESSION [UPDATE]\n\nRequired Scope: social\n\nDequeues joinable session so that it will not be matched with player\u0026#39;s match request tickets. \n\nThis endpoint is intended to be called by game server to let matchmaker know that \nthe game server does not want more players to its session, even though it is not full. \n",
        "operationId": "DequeueSessionHandler",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:SESSION [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Dequeue joinable session",
        "tags": [
          "Matchmaking",
          "public"
        ]
      }
    },
    "/matchmaking/namespaces/{namespace}/sessions/{matchID}/status": {
      "get": {
        "description": "Required Permission: NAMESPACE:{namespace}:SESSION [READ]\n\nRequired Scope: social\n\nQueries the specified session\u0026#39;s status. Game servers are expected to \ncall this periodically as long as it has a session in queue to see \nif there are new players being matched to the session.\n\nPossible session statuses are \u0026#34;sessionInQueue\u0026#34;, \u0026#34;sessionFull\u0026#34;, and \u0026#34;sessionTimeout\u0026#34;.\n\nif party_id value empty/null, field will[...]",
        "operationId": "QuerySessionHandler",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:SESSION [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Query joinable session status",
        "tags": [
          "Matchmaking",
          "public"
        ]
      }
    },
    "/matchmaking/social/playtime/namespaces/{namespace}/weight": {
      "patch": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [UPDATE]\n\nRequired Scope: social\n\nUpdate a connection weight between player and playtime.\n\nThis endpoint is intended to be called by admin for debugging purpose on social matchmaking rule.\n",
        "operationId": "UpdatePlayTimeWeight",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Update player -- playtime connection weight",
        "tags": [
          "Social Matchmaking"
        ]
      }
    },
    "/matchmaking/v1/admin/namespaces/{namespace}/channels/all/parties": {
      "get": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Read]\n\nRequired Scope: social\n\nGet all parties queueing in all channels.",
        "operationId": "GetAllPartyInAllChannel",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Read]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get all party in all channels",
        "tags": [
          "Matchmaking"
        ]
      }
    },
    "/matchmaking/v1/admin/namespaces/{namespace}/channels/all/sessions/bulk": {
      "get": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Read]\n\nRequired Scope: social\n\nBulk get sessions.",
        "operationId": "BulkGetSessions",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Read]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Bulk get sessions",
        "tags": [
          "Matchmaking"
        ]
      }
    },
    "/matchmaking/v1/admin/namespaces/{namespace}/channels/export": {
      "get": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Read]\n\nRequired Scope: social\n\nExport channels configuration to file. \n\nAction Code: 510114",
        "operationId": "ExportChannels",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Read]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Export channels",
        "tags": [
          "Matchmaking"
        ]
      }
    },
    "/matchmaking/v1/admin/namespaces/{namespace}/channels/import": {
      "post": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Update]\n\nRequired Scope: social\n\nImport channels configuration from file. It will merge with existing channels.\nAvailable import strategy:\n- leaveOut: if channel with same key exist, the existing will be used and imported one will be ignored (default)\n- replace: if channel with same key exist, the imported channel will be used and existing one will be removed\n\nAction Code: 510113",
        "operationId": "ImportChannels",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Update]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Import channels",
        "tags": [
          "Matchmaking"
        ]
      }
    },
    "/matchmaking/v1/admin/namespaces/{namespace}/channels/{channelName}": {
      "get": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [READ]\n\nRequired Scope: social\n\nReads single channel based on namespace and channel name\n\nAction Code: 510112",
        "operationId": "GetSingleMatchmakingChannel",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get single channel",
        "tags": [
          "Matchmaking"
        ]
      },
      "patch": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Update]\n\nRequired Scope: social\n\nUpdate channel based on namespace and channel name\n\nAction Code: 510111",
        "operationId": "UpdateMatchmakingChannel",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Update]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Update a channel",
        "tags": [
          "Matchmaking"
        ]
      }
    },
    "/matchmaking/v1/admin/namespaces/{namespace}/channels/{channelName}/mocks": {
      "delete": {
        "description": "\tRequired Permission: ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Update]\n\t\n\tRequired Scope: social\n\t\n\tDelete all mock tickets and matches in a channel.\n\u0026#39;",
        "operationId": "CleanAllMocks",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Update]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete all mock tickets and matches",
        "tags": [
          "Mock Matchmaking"
        ]
      }
    },
    "/matchmaking/v1/admin/namespaces/{namespace}/channels/{channelName}/mocks/matches": {
      "get": {
        "description": "\tRequired Permission: ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Read]\n\t\n\tRequired Scope: social\n\t\n\tRead all mock matches in a channel resulted from matching mock tickets.\n\u0026#39;",
        "operationId": "GetAllMockMatches",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Read]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get all mock matches",
        "tags": [
          "Mock Matchmaking"
        ]
      },
      "post": {
        "description": "\tRequired Permission: ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Read]\n\t\n\tRequired Scope: social\n\t\n\tRead mock matches that has timestamp older than specified timestamp in a channel resulted from matching mock tickets.\n\u0026#39;",
        "operationId": "GetMockMatchesByTimestamp",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Read]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get mock matches after timestamp",
        "tags": [
          "Mock Matchmaking"
        ]
      }
    },
    "/matchmaking/v1/admin/namespaces/{namespace}/channels/{channelName}/mocks/tickets": {
      "get": {
        "description": "\tRequired Permission: ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Read]\n\t\n\tRequired Scope: social\n\t\n\tRead all mock tickets in a channel.\n\u0026#39;",
        "operationId": "GetAllMockTickets",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Read]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get all mock tickets",
        "tags": [
          "Mock Matchmaking"
        ]
      },
      "post": {
        "description": "\tRequired Permission: ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Create]\n\t\n\tRequired Scope: social\n\t\n\tCreate and queue mock tickets into specified game mode\u0026#39;s pool. \n\tTicket\u0026#39;s MMRs will be randomized using Normal distribution according to the input mean and standard deviation.\n\tAll mock tickets and matches will be cleaned up automatically after 1 day.\n\u0026#39;",
        "operationId": "CreateMockTickets",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Create]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Create mock tickets",
        "tags": [
          "Mock Matchmaking"
        ]
      }
    },
    "/matchmaking/v1/admin/namespaces/{namespace}/channels/{channelName}/mocks/tickets/bulk": {
      "post": {
        "description": "\tRequired Permission: ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Create]\n\t\n\tRequired Scope: social\n\t\n\tCreate and queue mock tickets into specified game mode\u0026#39;s pool. \n\tThe tickets input will be used as is.\n\u0026#39;",
        "operationId": "BulkCreateMockTickets",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Create]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Bulk create mock tickets",
        "tags": [
          "Mock Matchmaking"
        ]
      }
    },
    "/matchmaking/v1/admin/namespaces/{namespace}/channels/{channelName}/mocks/tickets/query": {
      "post": {
        "description": "\tRequired Permission: ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Read]\n\t\n\tRequired Scope: social\n\t\n\tRead mock tickets after the specified timestamp in a channel.\n\u0026#39;",
        "operationId": "GetMockTicketsByTimestamp",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Read]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get mock tickets after timestamp",
        "tags": [
          "Mock Matchmaking"
        ]
      }
    },
    "/matchmaking/v1/admin/namespaces/{namespace}/channels/{channelName}/parties": {
      "get": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Read]\n\nRequired Scope: social\n\nGet all parties queueing in a channel.",
        "operationId": "GetAllPartyInChannel",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Read]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get all party in a channel",
        "tags": [
          "Matchmaking"
        ]
      }
    },
    "/matchmaking/v1/admin/namespaces/{namespace}/channels/{channelName}/sessions": {
      "get": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Read]\n\nRequired Scope: social\n\nGet all sessions in a channel.\n\nif party_id value empty/null, field will not show in response body.",
        "operationId": "GetAllSessionsInChannel",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Read]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get all channel sessions",
        "tags": [
          "Matchmaking"
        ]
      }
    },
    "/matchmaking/v1/admin/namespaces/{namespace}/channels/{channelName}/sessions/{matchID}": {
      "delete": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Delete]\n\nRequired Scope: social\n\nDelete a session in a channel.",
        "operationId": "DeleteSessionInChannel",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Delete]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete session in a channel",
        "tags": [
          "Matchmaking"
        ]
      },
      "post": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Create]\n\t\nRequired Scope: social\n\t\nAdd user into the session in a channel.",
        "operationId": "AddUserIntoSessionInChannel",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Create]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Add user into the session in a channel",
        "tags": [
          "Matchmaking"
        ]
      }
    },
    "/matchmaking/v1/admin/namespaces/{namespace}/channels/{channelName}/sessions/{matchID}/users/{userID}": {
      "delete": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Delete]\n\t\nRequired Scope: social\n\t\nDelete a user from a session in the channel.",
        "operationId": "DeleteUserFromSessionInChannel",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Delete]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete user from the session in a channel",
        "tags": [
          "Matchmaking"
        ]
      }
    },
    "/matchmaking/v1/admin/namespaces/{namespace}/channels/{channelName}/stats": {
      "get": {
        "description": "\tRequired Permission: ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Read]\n\t\n\tRequired Scope: social\n\t\n\tGet a channel\u0026#39;s stat data (mean, stddev, min, max) according to the stats collected from statistics service.\n\u0026#39;",
        "operationId": "GetStatData",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Read]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get stats",
        "tags": [
          "Matchmaking"
        ]
      }
    },
    "/matchmaking/v1/admin/namespaces/{namespace}/sessions/history/search": {
      "get": {
        "deprecated": true,
        "description": "\n\u0026lt;p\u0026gt;\n\t\u0026lt;h2\u0026gt;The endpoint is going to be deprecated\u0026lt;/h2\u0026gt; \u0026lt;/br\u0026gt;\n\t\u0026lt;strong\u0026gt;Endpoint migration guide\u0026lt;/strong\u0026gt;\n\t\u0026lt;ul\u0026gt;\n\t\t\u0026lt;li\u0026gt;\u0026lt;b\u0026gt;Substitute endpoint: \u0026lt;i\u0026gt;/sessionbrowser/admin/namespaces/{namespace}/sessions/history/search [GET]\u0026lt;/i\u0026gt;\u0026lt;/b\u0026gt;\u0026lt;/li\u0026gt;\n\t\u0026lt;/ul\u0026gt;\n\u[...]",
        "operationId": "SearchSessions",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Read]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Search sessions",
        "tags": [
          "Matchmaking"
        ]
      }
    },
    "/matchmaking/v1/admin/namespaces/{namespace}/sessions/{matchID}/history/detailed": {
      "get": {
        "deprecated": true,
        "description": "\n\u0026lt;p\u0026gt;\n\t\u0026lt;h2\u0026gt;The endpoint is going to be deprecated\u0026lt;/h2\u0026gt; \u0026lt;/br\u0026gt;\n\t\u0026lt;strong\u0026gt;Endpoint migration guide\u0026lt;/strong\u0026gt;\n\t\u0026lt;ul\u0026gt;\n\t\t\u0026lt;li\u0026gt;\u0026lt;b\u0026gt;Substitute endpoint: \u0026lt;i\u0026gt;/sessionbrowser/admin/namespaces/{namespace}/sessions/{sessionId}/history/detailed [GET]\u0026lt;/i\u0026gt;\u0026lt;/b\u0026gt;\u0026lt;/li\u0026gt;\n\t\u0026lt;/u[...]",
        "operationId": "GetSessionHistoryDetailed",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Read]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get session history detailed",
        "tags": [
          "Matchmaking"
        ]
      }
    },
    "/matchmaking/v1/messages": {
      "get": {
        "description": "get the list of messages.",
        "operationId": "publicGetMessages",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "get service messages",
        "tags": [
          "Matchmaking Operations"
        ]
      }
    },
    "/matchmaking/v1/public/namespaces/{namespace}/channels": {
      "get": {
        "description": "Reads all available channels in a namespace\n",
        "operationId": "PublicGetAllMatchmakingChannel",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get all channels",
        "tags": [
          "Matchmaking"
        ]
      }
    },
    "/matchmaking/v1/public/namespaces/{namespace}/channels/{channelName}": {
      "get": {
        "description": "Reads single channel based on namespace and channel name\n",
        "operationId": "PublicGetSingleMatchmakingChannel",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get single channel",
        "tags": [
          "Matchmaking"
        ]
      }
    },
    "/matchmaking/v2/admin/namespaces/{namespace}/sessions/history/search": {
      "get": {
        "deprecated": true,
        "description": "\u0026lt;p\u0026gt;\n\t\u0026lt;h2\u0026gt;The endpoint is going to be deprecated\u0026lt;/h2\u0026gt; \u0026lt;/br\u0026gt;\n\t\u0026lt;strong\u0026gt;Endpoint migration guide\u0026lt;/strong\u0026gt;\n\t\u0026lt;ul\u0026gt;\n\t\t\u0026lt;li\u0026gt;\u0026lt;b\u0026gt;Substitute endpoint: \u0026lt;i\u0026gt;/sessionbrowser/admin/namespaces/{namespace}/sessions/history/search [GET]\u0026lt;/i\u0026gt;\u0026lt;/b\u0026gt;\u0026lt;/li\u0026gt;\n\t\u0026lt;/ul\u0026gt;\n\u00[...]",
        "operationId": "SearchSessionsV2",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:CHANNEL [Read]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Search sessions",
        "tags": [
          "Matchmaking"
        ]
      }
    },
    "/matchmaking/version": {
      "get": {
        "operationId": "versionCheckHandler",
        "security": [
          {
            "authorization": []
          }
        ],
        "tags": [
          "Matchmaking Operations"
        ]
      }
    }
  },
  "x-docs": {
    "alias": "matchmaking",
    "host": "https://stage.accelbyte.io",
    "path": "/matchmaking/apidocs/api.json"
  },
  "x-version": {
    "buildDate": "2023-07-11T10:32:55+00:00",
    "gitHash": "fe302e4e67193b7a6a1305b00da3dadbae880817",
    "version": "2.25.3",
    "version-roles-seeding": "0.0.23"
  }
}