{
  "host": "demo.accelbyte.io",
  "info": {
    "description": "Justice Matchmaking Service",
    "title": "Justice Match Service v2",
    "version": "2.9.0"
  },
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "HasPermission": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {
        "ADMIN:MATCHMAKING:CONFIGURATION:ENVIRONMENTVARIABLE [READ]": "ADMIN:MATCHMAKING:CONFIGURATION:ENVIRONMENTVARIABLE [READ]",
        "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:POOL:METRICS [READ]": "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:POOL:METRICS [READ]",
        "NAMESPACE:{namespace}:MATCHMAKING:BACKFILL [CREATE]": "NAMESPACE:{namespace}:MATCHMAKING:BACKFILL [CREATE]",
        "NAMESPACE:{namespace}:MATCHMAKING:BACKFILL [DELETE]": "NAMESPACE:{namespace}:MATCHMAKING:BACKFILL [DELETE]",
        "NAMESPACE:{namespace}:MATCHMAKING:BACKFILL [UPDATE]": "NAMESPACE:{namespace}:MATCHMAKING:BACKFILL [UPDATE]",
        "NAMESPACE:{namespace}:MATCHMAKING:BACKFILL []": "NAMESPACE:{namespace}:MATCHMAKING:BACKFILL []",
        "NAMESPACE:{namespace}:MATCHMAKING:FUNCTIONS [CREATE]": "NAMESPACE:{namespace}:MATCHMAKING:FUNCTIONS [CREATE]",
        "NAMESPACE:{namespace}:MATCHMAKING:FUNCTIONS [DELETE]": "NAMESPACE:{namespace}:MATCHMAKING:FUNCTIONS [DELETE]",
        "NAMESPACE:{namespace}:MATCHMAKING:FUNCTIONS [READ]": "NAMESPACE:{namespace}:MATCHMAKING:FUNCTIONS [READ]",
        "NAMESPACE:{namespace}:MATCHMAKING:FUNCTIONS [UPDATE]": "NAMESPACE:{namespace}:MATCHMAKING:FUNCTIONS [UPDATE]",
        "NAMESPACE:{namespace}:MATCHMAKING:POOL [CREATE]": "NAMESPACE:{namespace}:MATCHMAKING:POOL [CREATE]",
        "NAMESPACE:{namespace}:MATCHMAKING:POOL [DELETE]": "NAMESPACE:{namespace}:MATCHMAKING:POOL [DELETE]",
        "NAMESPACE:{namespace}:MATCHMAKING:POOL [READ]": "NAMESPACE:{namespace}:MATCHMAKING:POOL [READ]",
        "NAMESPACE:{namespace}:MATCHMAKING:POOL [UPDATE]": "NAMESPACE:{namespace}:MATCHMAKING:POOL [UPDATE]",
        "NAMESPACE:{namespace}:MATCHMAKING:POOL:METRICS [READ]": "NAMESPACE:{namespace}:MATCHMAKING:POOL:METRICS [READ]",
        "NAMESPACE:{namespace}:MATCHMAKING:RULES [CREATE]": "NAMESPACE:{namespace}:MATCHMAKING:RULES [CREATE]",
        "NAMESPACE:{namespace}:MATCHMAKING:RULES [DELETE]": "NAMESPACE:{namespace}:MATCHMAKING:RULES [DELETE]",
        "NAMESPACE:{namespace}:MATCHMAKING:RULES [READ]": "NAMESPACE:{namespace}:MATCHMAKING:RULES [READ]",
        "NAMESPACE:{namespace}:MATCHMAKING:RULES [UPDATE]": "NAMESPACE:{namespace}:MATCHMAKING:RULES [UPDATE]",
        "NAMESPACE:{namespace}:MATCHMAKING:TICKET [CREATE]": "NAMESPACE:{namespace}:MATCHMAKING:TICKET [CREATE]",
        "NAMESPACE:{namespace}:MATCHMAKING:TICKET [DELETE]": "NAMESPACE:{namespace}:MATCHMAKING:TICKET [DELETE]",
        "NAMESPACE:{namespace}:MATCHMAKING:TICKET [READ]": "NAMESPACE:{namespace}:MATCHMAKING:TICKET [READ]"
      },
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "HasScope": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {
        "social": "social"
      },
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "authorization": {
      "in": "header",
      "name": "Authorization",
      "type": "apiKey"
    }
  },
  "swagger": "2.0",
  "paths": {
    "/healthz": {
      "get": {
        "operationId": "GetHealthcheckInfo",
        "security": [
          {
            "authorization": []
          }
        ]
      }
    },
    "/match2/healthz": {
      "get": {
        "operationId": "GetHealthcheckInfoV1",
        "security": [
          {
            "authorization": []
          }
        ]
      }
    },
    "/match2/v1/environment-variables": {
      "get": {
        "description": "Required Permission: ADMIN:MATCHMAKING:CONFIGURATION:ENVIRONMENTVARIABLE [READ]\n\nRequired Scope: social\n\nList environment variables.\n",
        "operationId": "EnvironmentVariableList",
        "security": [
          {
            "HasPermission": [
              "ADMIN:MATCHMAKING:CONFIGURATION:ENVIRONMENTVARIABLE [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "List environment variables",
        "tags": [
          "Environment-Variables",
          "admin"
        ]
      }
    },
    "/match2/v1/namespaces/{namespace}/backfill": {
      "post": {
        "description": " Required Permission: NAMESPACE:{namespace}:MATCHMAKING:BACKFILL [CREATE]\n\nRequired Scope: social\n\nCreate backfill ticket\n",
        "operationId": "CreateBackfill",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:BACKFILL [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Create a backfill ticket",
        "tags": [
          "Backfill",
          "public"
        ]
      }
    },
    "/match2/v1/namespaces/{namespace}/backfill/proposal": {
      "get": {
        "description": " Required Permission: NAMESPACE:{namespace}:MATCHMAKING:BACKFILL [GET]\n\nRequired Scope: social\n\nGet backfill proposal\n",
        "operationId": "GetBackfillProposal",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:BACKFILL []"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get backfill proposal",
        "tags": [
          "Backfill",
          "public"
        ]
      }
    },
    "/match2/v1/namespaces/{namespace}/backfill/{backfillID}": {
      "delete": {
        "description": " Required Permission: NAMESPACE:{namespace}:MATCHMAKING:BACKFILL [DELETE]\n\nRequired Scope: social\n\nDelete backfill ticket\n",
        "operationId": "DeleteBackfill",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:BACKFILL [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete a backfill ticket",
        "tags": [
          "Backfill",
          "public"
        ]
      },
      "get": {
        "description": " Required Permission: NAMESPACE:{namespace}:MATCHMAKING:BACKFILL [GET]\n\nRequired Scope: social\n\nGet backfill ticket by ID\n",
        "operationId": "GetBackfill",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:BACKFILL []"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get a backfill ticket",
        "tags": [
          "Backfill",
          "public"
        ]
      }
    },
    "/match2/v1/namespaces/{namespace}/backfill/{backfillID}/proposal/accept": {
      "put": {
        "description": " Required Permission: NAMESPACE:{namespace}:MATCHMAKING:BACKFILL [UPDATE]\n\nRequired Scope: social\n\nAccept backfill proposal\n",
        "operationId": "AcceptBackfill",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:BACKFILL [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Accept a backfill proposal",
        "tags": [
          "Backfill",
          "public"
        ]
      }
    },
    "/match2/v1/namespaces/{namespace}/backfill/{backfillID}/proposal/reject": {
      "put": {
        "description": " Required Permission: NAMESPACE:{namespace}:MATCHMAKING:BACKFILL [UPDATE]\n\nRequired Scope: social\n\nReject backfill proposal\n",
        "operationId": "RejectBackfill",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:BACKFILL [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Reject a backfill proposal",
        "tags": [
          "Backfill",
          "public"
        ]
      }
    },
    "/match2/v1/namespaces/{namespace}/match-functions": {
      "get": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:FUNCTIONS [READ]\n\nRequired Scope: social\n\nList existing match functions.\n",
        "operationId": "MatchFunctionList",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:FUNCTIONS [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "List existing match functions",
        "tags": [
          "Match-Functions",
          "admin"
        ]
      },
      "post": {
        "description": " Required Permission: NAMESPACE:{namespace}:MATCHMAKING:FUNCTIONS [CREATE]\n\nRequired Scope: social\n\nCreates a new matchmaking function.\n",
        "operationId": "CreateMatchFunction",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:FUNCTIONS [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Create a match function",
        "tags": [
          "Match-Functions",
          "admin"
        ]
      }
    },
    "/match2/v1/namespaces/{namespace}/match-functions/{name}": {
      "delete": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:FUNCTIONS [DELETE]\n\nRequired Scope: social\n\nDeletes an existing match function.\n",
        "operationId": "DeleteMatchFunction",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:FUNCTIONS [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete a match function",
        "tags": [
          "Match-Functions",
          "admin"
        ]
      },
      "put": {
        "description": " Required Permission: NAMESPACE:{namespace}:MATCHMAKING:FUNCTIONS [UPDATE]\n\nRequired Scope: social\n\nUpdate existing matchmaking function.\n",
        "operationId": "UpdateMatchFunction",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:FUNCTIONS [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Update a match function",
        "tags": [
          "Match-Functions",
          "admin"
        ]
      }
    },
    "/match2/v1/namespaces/{namespace}/match-pools": {
      "get": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:POOL [READ]\n\nRequired Scope: social\n\nList matchmaking pools.\n",
        "operationId": "MatchPoolList",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:POOL [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "List match pools",
        "tags": [
          "Match-Pools",
          "admin"
        ]
      },
      "post": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:POOL [CREATE]\n\nRequired Scope: social\n\nCreates a new matchmaking pool.\n\nA pool is isolated from other pools (i.e. tickets may be matched with other tickets in the same pool, but not with tickets in other pools).\nEach pool has its own matchmaking rules and/or logic.\n\nticket_expiration_seconds and backfill_ticket_expiration_seconds will be set to 300 seconds (5 minutes) by default if not filled.\n\nMatch Functi[...]",
        "operationId": "CreateMatchPool",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:POOL [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Create a match pool",
        "tags": [
          "Match-Pools",
          "admin"
        ]
      }
    },
    "/match2/v1/namespaces/{namespace}/match-pools/{pool}": {
      "delete": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:POOL [DELETE]\n\nRequired Scope: social\n\nDeletes an existing matchmaking pool.\n",
        "operationId": "DeleteMatchPool",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:POOL [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete a match pool",
        "tags": [
          "Match-Pools",
          "admin"
        ]
      },
      "get": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:POOL [READ]\n\nRequired Scope: social\n\nGet details for a specific match pool\n",
        "operationId": "MatchPoolDetails",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:POOL [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get details for a specific match pool",
        "tags": [
          "Match-Pools",
          "admin"
        ]
      },
      "put": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:POOL [UPDATE]\n\nRequired Scope: social\n\nUpdates an existing matchmaking pool.\n\nticket_expiration_seconds and backfill_ticket_expiration_seconds will be set to 300 seconds (5 minutes) by default if not filled.\n\nMatch Function holds information about the name of the match logic server that matchmaking can refers to. By default we provide (\u0026#34;default\u0026#34; and \u0026#34;basic\u0026#34;). \nMatch Functio[...]",
        "operationId": "UpdateMatchPool",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:POOL [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Update a match pool",
        "tags": [
          "Match-Pools",
          "admin"
        ]
      }
    },
    "/match2/v1/namespaces/{namespace}/match-pools/{pool}/metrics": {
      "get": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:POOL:METRICS [READ]\n\nRequired Scope: social\n\nGet metric for a specific match pool\n\nResult: queueTime in seconds\n",
        "operationId": "MatchPoolMetric",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:POOL:METRICS [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get metrics for a specific match pool",
        "tags": [
          "Match-Pools",
          "public"
        ]
      }
    },
    "/match2/v1/namespaces/{namespace}/match-pools/{pool}/metrics/player": {
      "get": {
        "description": "Required Permission: ADMIN:NAMESPACE:{namespace}:MATCHMAKING:POOL:METRICS [READ]\n\nRequired Scope: social\n\nGet player metric for a specific match pool\n",
        "operationId": "GetPlayerMetric",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:MATCHMAKING:POOL:METRICS [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get metrics player for a specific match pool",
        "tags": [
          "Match-Pools",
          "admin"
        ]
      }
    },
    "/match2/v1/namespaces/{namespace}/match-tickets": {
      "post": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:TICKET [CREATE]\n\nRequired Scope: social\n\nCreates a new request for matchmaking.\n\nCross Platform: Allow player to play game with \u0026#34;any\u0026#34; registered plaftforms.\n1. Cross Platform can be enabled through session service or create match ticket. \n\ta. via ticket: specify several cross_platform on create match ticket attributes. \n\t   This value will override player attributes in session service. e.g[...]",
        "operationId": "CreateMatchTicket",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:TICKET [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Create a matchmaking ticket",
        "tags": [
          "Match-Tickets",
          "public"
        ]
      }
    },
    "/match2/v1/namespaces/{namespace}/match-tickets/me": {
      "get": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:TICKET [READ]\n\nRequired Scope: social\n\nGet my match tickets.\n",
        "operationId": "GetMyMatchTickets",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:TICKET [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get my match tickets",
        "tags": [
          "Match-Tickets",
          "public"
        ]
      }
    },
    "/match2/v1/namespaces/{namespace}/match-tickets/{ticketid}": {
      "delete": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:TICKET [DELETE]\n\nRequired Scope: social\n\nDeletes an existing matchmaking ticket.\n",
        "operationId": "DeleteMatchTicket",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:TICKET [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete a match ticket",
        "tags": [
          "Match-Tickets",
          "public"
        ]
      },
      "get": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:TICKET [READ]\n\nRequired Scope: social\n\nGet details for a specific match ticket\n",
        "operationId": "MatchTicketDetails",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:TICKET [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get details for a specific match ticket",
        "tags": [
          "Match-Tickets",
          "public"
        ]
      }
    },
    "/match2/v1/namespaces/{namespace}/rulesets": {
      "get": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:RULES [READ]\n\nRequired Scope: social\n\nList rule sets.\n",
        "operationId": "RuleSetList",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:RULES [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "List existing rule sets",
        "tags": [
          "Rule-Sets",
          "admin"
        ]
      },
      "post": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:RULES [CREATE]\n\nRequired Scope: social\n\nCreates a new rules set.\n\nA rule set has a name and contains arbitrary data which is meaningful to some particular match function(s)\nThe name is used for a match pool to select the ruleset data that should be sent to the match function when matchmaking in that pool.\n\nTo use custom rules set please set enable_custom_match_function=true. Default (false).\n",
        "operationId": "CreateRuleSet",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:RULES [CREATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Create a match rule set",
        "tags": [
          "Rule-Sets",
          "admin"
        ]
      }
    },
    "/match2/v1/namespaces/{namespace}/rulesets/{ruleset}": {
      "delete": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:RULES [DELETE]\n\nRequired Scope: social\n\nDeletes an existing rule set.\n",
        "operationId": "DeleteRuleSet",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:RULES [DELETE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete a rule set",
        "tags": [
          "Rule-Sets",
          "admin"
        ]
      },
      "get": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:RULES [READ]\n\nRequired Scope: social\n\nGet details for a specific rule set\n",
        "operationId": "RuleSetDetails",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:RULES [READ]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Get details for a specific rule set",
        "tags": [
          "Rule-Sets",
          "admin"
        ]
      },
      "put": {
        "description": "Required Permission: NAMESPACE:{namespace}:MATCHMAKING:RULES [UPDATE]\n\nRequired Scope: social\n\nUpdates an existing matchmaking rule set.\n\t\nTo use custom rules set please set enable_custom_match_function=true. Default (false).\n",
        "operationId": "UpdateRuleSet",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:MATCHMAKING:RULES [UPDATE]"
            ],
            "HasScope": [
              "social"
            ],
            "authorization": []
          }
        ],
        "summary": "Update a match rule set",
        "tags": [
          "Rule-Sets",
          "admin"
        ]
      }
    },
    "/match2/version": {
      "get": {
        "operationId": "versionCheckHandler",
        "security": [
          {
            "authorization": []
          }
        ]
      }
    }
  },
  "x-docs": {
    "alias": "match2",
    "host": "https://stage.accelbyte.io",
    "path": "/match2/apidocs/api.json"
  },
  "x-version": {
    "buildDate": "2023-08-28T05:45:36+00:00",
    "gitHash": "5b7625604fbf11ff485de569199c7debc79ab9b8",
    "version": "2.9.0",
    "version-roles-seeding": "0.0.38"
  }
}