{
  "host": "demo.accelbyte.io",
  "info": {
    "contact": {
      "email": "engineering@accelbyte.io",
      "name": "Engineering Team at AccelByte",
      "url": "https://accelbyte.io"
    },
    "description": "Justice Reporting Service",
    "title": "justice-reporting-service",
    "version": "0.1.27"
  },
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "HasPermission": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {
        "ADMIN:NAMESPACE:{namespace}:REASON [CREATE]": "ADMIN:NAMESPACE:{namespace}:REASON [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:REASON [DELETE]": "ADMIN:NAMESPACE:{namespace}:REASON [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:REASON [READ]": "ADMIN:NAMESPACE:{namespace}:REASON [READ]",
        "ADMIN:NAMESPACE:{namespace}:REASON [UPDATE]": "ADMIN:NAMESPACE:{namespace}:REASON [UPDATE]",
        "ADMIN:NAMESPACE:{namespace}:REPORTINGCONFIG [CREATE]": "ADMIN:NAMESPACE:{namespace}:REPORTINGCONFIG [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:REPORTINGCONFIG [READ]": "ADMIN:NAMESPACE:{namespace}:REPORTINGCONFIG [READ]",
        "ADMIN:NAMESPACE:{namespace}:RULE [CREATE]": "ADMIN:NAMESPACE:{namespace}:RULE [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:RULE [DELETE]": "ADMIN:NAMESPACE:{namespace}:RULE [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:RULE [READ]": "ADMIN:NAMESPACE:{namespace}:RULE [READ]",
        "ADMIN:NAMESPACE:{namespace}:RULE [UPDATE]": "ADMIN:NAMESPACE:{namespace}:RULE [UPDATE]",
        "ADMIN:NAMESPACE:{namespace}:TICKET [CREATE]": "ADMIN:NAMESPACE:{namespace}:TICKET [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:TICKET [DELETE]": "ADMIN:NAMESPACE:{namespace}:TICKET [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:TICKET [READ]": "ADMIN:NAMESPACE:{namespace}:TICKET [READ]",
        "ADMIN:NAMESPACE:{namespace}:TICKET [UPDATE]": "ADMIN:NAMESPACE:{namespace}:TICKET [UPDATE]",
        "ADMIN:REPORTINGCONFIG [CREATE]": "ADMIN:REPORTINGCONFIG [CREATE]",
        "ADMIN:REPORTINGCONFIG [READ]": "ADMIN:REPORTINGCONFIG [READ]"
      },
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "HasScope": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {},
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "authorization": {
      "in": "header",
      "name": "Authorization",
      "type": "apiKey"
    }
  },
  "swagger": "2.0",
  "paths": {
    "/reporting/v1/admin/extensionActions": {
      "get": {
        "description": "Required permission: ADMIN:REPORTINGCONFIG [READ]\nGet a list of auto moderation actions",
        "operationId": "adminFindActionList",
        "security": [
          {
            "HasPermission": [
              "ADMIN:REPORTINGCONFIG [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Find Auto Moderation Action List",
        "tags": [
          "Admin Extension Categories and Auto Moderation Actions"
        ]
      },
      "post": {
        "description": "Required permission: ADMIN:REPORTINGCONFIG [CREATE]\nCreate auto moderation action",
        "operationId": "adminCreateModAction",
        "security": [
          {
            "HasPermission": [
              "ADMIN:REPORTINGCONFIG [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Create Auto Moderation Action data",
        "tags": [
          "Admin Extension Categories and Auto Moderation Actions"
        ]
      }
    },
    "/reporting/v1/admin/extensionCategories": {
      "get": {
        "description": "Required permission: ADMIN:REPORTINGCONFIG [READ]\nGet a list of extension category data with the specified name",
        "operationId": "adminFindExtensionCategoryList",
        "security": [
          {
            "HasPermission": [
              "ADMIN:REPORTINGCONFIG [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Find Extension Category List",
        "tags": [
          "Admin Extension Categories and Auto Moderation Actions"
        ]
      },
      "post": {
        "description": "Required permission: ADMIN:REPORTINGCONFIG [CREATE]\nCreate extension category data",
        "operationId": "adminCreateExtensionCategory",
        "security": [
          {
            "HasPermission": [
              "ADMIN:REPORTINGCONFIG [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Create Extension Category",
        "tags": [
          "Admin Extension Categories and Auto Moderation Actions"
        ]
      }
    },
    "/reporting/v1/admin/namespaces/{namespace}/configurations": {
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:REPORTINGCONFIG [READ]\nTimeInterval is in nanoseconds.\nWhen there\u0026#39;s no configuration set, the response is the default value (configurable through envar).\n",
        "operationId": "Get",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:REPORTINGCONFIG [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get configuration",
        "tags": [
          "Admin Configurations"
        ]
      },
      "post": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:REPORTINGCONFIG [CREATE]\nThe behaviour of this endpoint is upsert based on the namespace.\nSo, you can use this for both creating \u0026amp; updating the configuration.\nTimeInterval is in nanoseconds.\n",
        "operationId": "Upsert",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:REPORTINGCONFIG [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Create/Update configuration",
        "tags": [
          "Admin Configurations"
        ]
      }
    },
    "/reporting/v1/admin/namespaces/{namespace}/reasonGroups": {
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:REASON [READ]\nReturn list of reason groups ID and title under given namespace. To fetch the reasons inside a group, use get reason group endpoint.",
        "operationId": "adminListReasonGroups",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:REASON [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "List reason groups under a namespace",
        "tags": [
          "Admin Reasons"
        ]
      },
      "post": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:REASON [CREATE]\nCreate a reason group for easier query. You can query reasons by specifying the group title in the list reasons query.\nReason group title is case insensitive, meaning you can\u0026#39;t have \u0026lt;b\u0026gt;reason\u0026lt;/b\u0026gt; if you already create a reason titled \u0026lt;b\u0026gt;Reason\u0026lt;/b\u0026gt;",
        "operationId": "createReasonGroup",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:REASON [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Create a reason group",
        "tags": [
          "Admin Reasons"
        ]
      }
    },
    "/reporting/v1/admin/namespaces/{namespace}/reasonGroups/{groupId}": {
      "delete": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:REASON [DELETE]",
        "operationId": "deleteReasonGroup",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:REASON [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete a reason group",
        "tags": [
          "Admin Reasons"
        ]
      },
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:REASON [READ]",
        "operationId": "getReasonGroup",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:REASON [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get reason group",
        "tags": [
          "Admin Reasons"
        ]
      },
      "patch": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:REASON [UPDATE]\nReason group title is case insensitive, meaning you can\u0026#39;t have \u0026lt;b\u0026gt;reason\u0026lt;/b\u0026gt; if you already create a reason titled \u0026lt;b\u0026gt;Reason\u0026lt;/b\u0026gt;\nIf no reasonIds passed when updating, the current reasons under the reason group will be kept (reasons will not be removed from the group).",
        "operationId": "updateReasonGroup",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:REASON [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update a reason group",
        "tags": [
          "Admin Reasons"
        ]
      }
    },
    "/reporting/v1/admin/namespaces/{namespace}/reasons": {
      "get": {
        "operationId": "adminGetReasons",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get list of reasons",
        "tags": [
          "Admin Reasons"
        ]
      },
      "post": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:REASON [CREATE]",
        "operationId": "createReason",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:REASON [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Create a report reason",
        "tags": [
          "Admin Reasons"
        ]
      }
    },
    "/reporting/v1/admin/namespaces/{namespace}/reasons/all": {
      "get": {
        "description": "\u0026lt;p\u0026gt;This endpoint get all reasons without pagination.\u0026lt;/p\u0026gt;\n\u0026lt;p\u0026gt; Required Permission: ADMIN:NAMESPACE:{namespace}:REASON [READ]\u0026lt;/p\u0026gt;",
        "operationId": "adminGetAllReasons",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:REASON [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get all reasons",
        "tags": [
          "Admin Reasons"
        ]
      }
    },
    "/reporting/v1/admin/namespaces/{namespace}/reasons/unused": {
      "get": {
        "description": "\u0026lt;p\u0026gt;This endpoint get reasons not used by moderation rules.\u0026lt;/p\u0026gt;\n\u0026lt;p\u0026gt; Required Permission: ADMIN:NAMESPACE:{namespace}:REASON [READ]\u0026lt;/p\u0026gt;",
        "operationId": "adminGetUnusedReasons",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:REASON [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get list of reasons that not used by moderation rules",
        "tags": [
          "Admin Reasons"
        ]
      }
    },
    "/reporting/v1/admin/namespaces/{namespace}/reasons/{reasonId}": {
      "delete": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:REASON [DELETE]",
        "operationId": "deleteReason",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:REASON [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete a report reason",
        "tags": [
          "Admin Reasons"
        ]
      },
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:REASON [READ]",
        "operationId": "adminGetReason",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:REASON [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get a single reason",
        "tags": [
          "Admin Reasons"
        ]
      },
      "patch": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:REASON [UPDATE]",
        "operationId": "updateReason",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:REASON [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update a report reason",
        "tags": [
          "Admin Reasons"
        ]
      }
    },
    "/reporting/v1/admin/namespaces/{namespace}/reports": {
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:TICKET [READ]\nReports list can be ordered by:\n- createdAt\n- updatedAt",
        "operationId": "listReports",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:TICKET [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "List reports",
        "tags": [
          "Admin Reports"
        ]
      },
      "post": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:TICKET [CREATE]\nSubmit a report and will return ticket for reported object.\nNew ticket will be created if no OPEN ticket present for reported object (based by objectId and objectType) in a namespace.\n\nAdmin can only submit report once for each different user / object reported in the same OPEN ticket. \nReporting the same user / object in the same OPEN ticket will return HTTP code 409 (conflict).\n\nFill the \u0026#39;re[...]",
        "operationId": "adminSubmitReport",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:TICKET [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Submit a report by admin",
        "tags": [
          "Admin Reports"
        ]
      }
    },
    "/reporting/v1/admin/namespaces/{namespace}/rule": {
      "post": {
        "description": "\u0026lt;p\u0026gt;This endpoint create moderation rule.\u0026lt;/p\u0026gt;\n\u0026lt;p\u0026gt; Required Permission: ADMIN:NAMESPACE:{namespace}:RULE [CREATE]\u0026lt;/p\u0026gt;\n\u0026lt;p\u0026gt; Supported Category: \u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;UGC\u0026lt;/li\u0026gt;\u0026lt;li\u0026gt;USER\u0026lt;/li\u0026gt;\u0026lt;li\u0026gt;CHAT\u0026lt;/li\u0026gt;\u0026lt;li\u0026gt;EXTENSION\u0026lt;/li\u0026gt;\u0026lt;/ul\u0026gt;\u0026lt;/p\u0026gt;\n\u0026l[...]",
        "operationId": "createModerationRule",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:RULE [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Create auto moderation rule",
        "tags": [
          "Admin Moderation Rule"
        ]
      }
    },
    "/reporting/v1/admin/namespaces/{namespace}/rule/{ruleId}": {
      "delete": {
        "description": "\u0026lt;p\u0026gt;This endpoint delete moderation rule.\u0026lt;/p\u0026gt;\n\u0026lt;p\u0026gt; Required Permission: ADMIN:NAMESPACE:{namespace}:RULE [DELETE]",
        "operationId": "deleteModerationRule",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:RULE [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete auto moderation rule",
        "tags": [
          "Admin Moderation Rule"
        ]
      },
      "put": {
        "description": "\u0026lt;p\u0026gt;This endpoint update moderation rule.\u0026lt;/p\u0026gt;\n\u0026lt;p\u0026gt; Required Permission: ADMIN:NAMESPACE:{namespace}:RULE [UPDATE]\n\u0026lt;p\u0026gt; Supported Category:\u0026lt;ul\u0026gt;\u0026lt;li\u0026gt;UGC\u0026lt;/li\u0026gt;\u0026lt;li\u0026gt;USER\u0026lt;/li\u0026gt;\u0026lt;li\u0026gt;CHAT\u0026lt;/li\u0026gt;\u0026lt;li\u0026gt;EXTENSION\u0026lt;/li\u0026gt;\u0026lt;/ul\u0026gt;\u0026lt;/p\u0026gt;\n\u0026lt;p\u0026gt; Supporte[...]",
        "operationId": "updateModerationRule",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:RULE [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update auto moderation rule",
        "tags": [
          "Admin Moderation Rule"
        ]
      }
    },
    "/reporting/v1/admin/namespaces/{namespace}/rule/{ruleId}/status": {
      "put": {
        "description": "\u0026lt;p\u0026gt;This endpoint enable/disable moderation rule status.\u0026lt;/p\u0026gt;\n\u0026lt;p\u0026gt; Required Permission: ADMIN:NAMESPACE:{namespace}:RULE [UPDATE]",
        "operationId": "updateModerationRuleStatus",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:RULE [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Enable/Disable auto moderation rule",
        "tags": [
          "Admin Moderation Rule"
        ]
      }
    },
    "/reporting/v1/admin/namespaces/{namespace}/rules": {
      "get": {
        "description": "\u0026lt;p\u0026gt;This endpoint get moderation rules.\u0026lt;/p\u0026gt;\n\u0026lt;p\u0026gt; Required Permission: ADMIN:NAMESPACE:{namespace}:RULE [READ]",
        "operationId": "getModerationRules",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:RULE [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get auto moderation rules",
        "tags": [
          "Admin Moderation Rule"
        ]
      }
    },
    "/reporting/v1/admin/namespaces/{namespace}/rules/{ruleId}": {
      "get": {
        "description": "\u0026lt;p\u0026gt;This endpoint get moderation rule.\u0026lt;/p\u0026gt;\n\u0026lt;p\u0026gt; Required Permission: ADMIN:NAMESPACE:{namespace}:RULE [READ]",
        "operationId": "getModerationRuleDetails",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:RULE [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get auto moderation rule",
        "tags": [
          "Admin Moderation Rule"
        ]
      }
    },
    "/reporting/v1/admin/namespaces/{namespace}/tickets": {
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:TICKET [READ]\nTickets list can be ordered by:\n- createdAt\n- reportsCount\n- status (currently there are OPEN, AUTO_MODERATED and CLOSED statuses, desc order will put ticket with CLOSED status at the top)",
        "operationId": "listTickets",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:TICKET [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "List report tickets",
        "tags": [
          "Admin Tickets"
        ]
      }
    },
    "/reporting/v1/admin/namespaces/{namespace}/tickets/statistic": {
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:TICKET [READ]",
        "operationId": "ticketStatistic",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:TICKET [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Ticket statistic",
        "tags": [
          "Admin Tickets"
        ]
      }
    },
    "/reporting/v1/admin/namespaces/{namespace}/tickets/{ticketId}": {
      "delete": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:TICKET [DELETE]\nThis endpoint will delete ticket and all its reports.\n",
        "operationId": "deleteTicket",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:TICKET [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete single ticket",
        "tags": [
          "Admin Tickets"
        ]
      },
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:TICKET [READ]",
        "operationId": "getTicketDetail",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:TICKET [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get single ticket",
        "tags": [
          "Admin Tickets"
        ]
      }
    },
    "/reporting/v1/admin/namespaces/{namespace}/tickets/{ticketId}/reports": {
      "get": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:TICKET [READ]\nList reports ordered by createdAt in descending order.",
        "operationId": "getReportsByTicket",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:TICKET [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get reports by ticket ID",
        "tags": [
          "Admin Tickets"
        ]
      }
    },
    "/reporting/v1/admin/namespaces/{namespace}/tickets/{ticketId}/resolutions": {
      "post": {
        "description": "Required permission: ADMIN:NAMESPACE:{namespace}:TICKET [UPDATE]\nUpdate ticket resolution status to either OPEN or CLOSED. It is mandatory to provide notes",
        "operationId": "updateTicketResolutions",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:TICKET [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update ticket resolution to a given status",
        "tags": [
          "Admin Tickets"
        ]
      }
    },
    "/reporting/v1/public/namespaces/{namespace}/reasonGroups": {
      "get": {
        "description": "Return list of reason groups ID and title under given namespace.",
        "operationId": "publicListReasonGroups",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "List reason groups under a namespace",
        "tags": [
          "Public Reasons"
        ]
      }
    },
    "/reporting/v1/public/namespaces/{namespace}/reasons": {
      "get": {
        "operationId": "publicGetReasons",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get list of reasons",
        "tags": [
          "Public Reasons"
        ]
      }
    },
    "/reporting/v1/public/namespaces/{namespace}/reports": {
      "post": {
        "description": "User need to be authenticated to access this endpoint.\nSubmit a report and will return ticket for reported object.\nNew ticket will be created if no OPEN ticket present for reported object (based by objectId and objectType) in a namespace.\n\nUser can only submit report once for each different user / object reported in the same OPEN ticket. \nReporting the same user / object in the same OPEN ticket will return HTTP code 409 (conflict).\n\nFill the \u0026#39;reason\u0026#[...]",
        "operationId": "submitReport",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Submit a report",
        "tags": [
          "Public Reports"
        ]
      }
    }
  },
  "x-docs": {
    "alias": "reporting",
    "host": "https://stage.accelbyte.io",
    "path": "/reporting/apidocs/api.json"
  },
  "x-version": {
    "buildDate": "2023-05-23T02:15:12+00:00",
    "gitHash": "455759492da75cd326aceeacf29aa6dfda785376",
    "name": "justice-reporting-service",
    "realm": "staging",
    "version": "0.1.27",
    "version-roles-seeding": "0.0.3"
  }
}