{
  "host": "demo.accelbyte.io",
  "info": {
    "contact": {
      "email": "engineering@accelbyte.io",
      "name": "Engineering Team at AccelByte",
      "url": "https://accelbyte.io"
    },
    "description": "Justice UGC Service",
    "title": "justice-ugc-service",
    "version": "2.19.1"
  },
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "HasPermission": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {
        "ADMIN:NAMESPACE:{namespace}:CONTENT:APPROVAL [CREATE]": "ADMIN:NAMESPACE:{namespace}:CONTENT:APPROVAL [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:UGCCONFIG [CREATE]": "ADMIN:NAMESPACE:{namespace}:UGCCONFIG [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:UGCCONFIG [DELETE]": "ADMIN:NAMESPACE:{namespace}:UGCCONFIG [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:UGCCONFIG [READ]": "ADMIN:NAMESPACE:{namespace}:UGCCONFIG [READ]",
        "ADMIN:NAMESPACE:{namespace}:UGCCONFIG [UPDATE]": "ADMIN:NAMESPACE:{namespace}:UGCCONFIG [UPDATE]",
        "ADMIN:NAMESPACE:{namespace}:USER:*:CONTENT [READ]": "ADMIN:NAMESPACE:{namespace}:USER:*:CONTENT [READ]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId} [DELETE]": "ADMIN:NAMESPACE:{namespace}:USER:{userId} [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CHANNEL [CREATE]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CHANNEL [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CHANNEL [DELETE]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CHANNEL [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CHANNEL [READ]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CHANNEL [READ]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CHANNEL [UPDATE]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CHANNEL [UPDATE]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [CREATE]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [CREATE]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [CREATE]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [DELETE]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [DELETE]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [READ]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [READ]",
        "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [UPDATE]": "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [UPDATE]",
        "NAMESPACE:{namespace}:USER:{userId} [DELETE]": "NAMESPACE:{namespace}:USER:{userId} [DELETE]",
        "NAMESPACE:{namespace}:USER:{userId}:CHANNEL [CREATE]": "NAMESPACE:{namespace}:USER:{userId}:CHANNEL [CREATE]",
        "NAMESPACE:{namespace}:USER:{userId}:CHANNEL [DELETE]": "NAMESPACE:{namespace}:USER:{userId}:CHANNEL [DELETE]",
        "NAMESPACE:{namespace}:USER:{userId}:CHANNEL [READ]": "NAMESPACE:{namespace}:USER:{userId}:CHANNEL [READ]",
        "NAMESPACE:{namespace}:USER:{userId}:CHANNEL [UPDATE]": "NAMESPACE:{namespace}:USER:{userId}:CHANNEL [UPDATE]",
        "NAMESPACE:{namespace}:USER:{userId}:CONTENT [CREATE]": "NAMESPACE:{namespace}:USER:{userId}:CONTENT [CREATE]",
        "NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]": "NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]",
        "NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]": "NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]",
        "NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]": "NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]",
        "NAMESPACE:{namespace}:USER:{userId}:CONTENT:SHARECODE [UPDATE]": "NAMESPACE:{namespace}:USER:{userId}:CONTENT:SHARECODE [UPDATE]",
        "NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [CREATE]": "NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [CREATE]",
        "NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [DELETE]": "NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [DELETE]",
        "NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [READ]": "NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [READ]",
        "NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [UPDATE]": "NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [UPDATE]"
      },
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "HasScope": {
      "authorizationUrl": "https://dummy.oauth.net/auth",
      "flow": "accessCode",
      "scopes": {},
      "tokenUrl": "https://dumy.oauth.net/token",
      "type": "oauth2"
    },
    "authorization": {
      "in": "header",
      "name": "Authorization",
      "type": "apiKey"
    }
  },
  "swagger": "2.0",
  "paths": {
    "/ugc/v1/admin/namespaces/{namespace}/channels": {
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CHANNEL [READ]\u0026lt;/b\u0026gt;",
        "operationId": "SingleAdminGetChannel",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CHANNEL [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get Channels",
        "tags": [
          "Admin Channel"
        ]
      },
      "post": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CHANNEL [CREATE]\u0026lt;/b\u0026gt;",
        "operationId": "AdminCreateChannel",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CHANNEL [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Create Channel",
        "tags": [
          "Admin Channel"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/channels/{channelId}": {
      "delete": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CHANNEL [DELETE]\u0026lt;/b\u0026gt;",
        "operationId": "SingleAdminDeleteChannel",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CHANNEL [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete Channel",
        "tags": [
          "Admin Channel"
        ]
      },
      "put": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CHANNEL [UPDATE]\u0026lt;/b\u0026gt;",
        "operationId": "SingleAdminUpdateChannel",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CHANNEL [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update Channel",
        "tags": [
          "Admin Channel"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/channels/{channelId}/contents": {
      "post": {
        "deprecated": true,
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [CREATE]\u0026lt;/b\u0026gt;.\\n \n\t\t\t\tAll request body are required except preview, tags and customAttributes.\n\t\t\t\t",
        "operationId": "AdminUploadContentDirect",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Upload content to a channel",
        "tags": [
          "Admin Content"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/channels/{channelId}/contents/s3": {
      "post": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [CREATE]\u0026lt;/b\u0026gt;.\n\nAll request body are required except \u0026lt;code\u0026gt;preview\u0026lt;/code\u0026gt;, \u0026lt;code\u0026gt;tags\u0026lt;/code\u0026gt;, \u0026lt;code\u0026gt;contentType\u0026lt;/code\u0026gt;, \u0026lt;code\u0026gt;customAttributes\u0026lt;/code\u0026gt; and \u0026lt;code\u0026gt;shareCode\u0026lt;/code\u0026gt;.\n\n\u0026lt;code\u0026gt;content[...]",
        "operationId": "AdminUploadContentS3",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Upload content to S3 bucket",
        "tags": [
          "Admin Content"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/channels/{channelId}/contents/s3/{contentId}": {
      "put": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]\u0026lt;/b\u0026gt;.\n\nAll request body are required except \u0026lt;code\u0026gt;payload\u0026lt;/code\u0026gt;, \u0026lt;code\u0026gt;preview\u0026lt;/code\u0026gt;, \u0026lt;code\u0026gt;tags\u0026lt;/code\u0026gt;,\u0026lt;code\u0026gt;contentType\u0026lt;/code\u0026gt;, \u0026lt;code\u0026gt;updateContentFile\u0026lt;/code\u0026gt;, \u0026lt;code\u0026gt;customAttribute[...]",
        "operationId": "SingleAdminUpdateContentS3",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update content to S3 bucket",
        "tags": [
          "Admin Content"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/channels/{channelId}/contents/search": {
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:*:CONTENT [READ]\u0026lt;/b\u0026gt;\n\nFor advance tag filtering supports \u0026amp; as AND operator and | as OR operator and parentheses () for priority. e.g: \n\n\u0026lt;code\u0026gt;tags=red\u0026lt;/code\u0026gt;\n\n\u0026lt;code\u0026gt;tags=red\u0026amp;animal\u0026lt;/code\u0026gt;\n\n\u0026lt;code\u0026gt;tags=red|animal\u0026lt;/code\u0026gt;\n\n\u0026lt;code\u0026gt;tags=red\u0026amp;anima[...]",
        "operationId": "AdminSearchChannelSpecificContent",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:*:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Search contents specific to a channel",
        "tags": [
          "Admin Content"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/channels/{channelId}/contents/{contentId}": {
      "delete": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]\u0026lt;/b\u0026gt;.",
        "operationId": "SingleAdminDeleteContent",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete content",
        "tags": [
          "Admin Content"
        ]
      },
      "put": {
        "deprecated": true,
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]\u0026lt;/b\u0026gt;.\\n \n\t\t\t\t\tAll request body are required except preview, tags and customAttributes.\n\t\t\t\t\t",
        "operationId": "SingleAdminUpdateContentDirect",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update content to a channel",
        "tags": [
          "Admin Content"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/contents": {
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]\u0026lt;/b\u0026gt;.",
        "operationId": "SingleAdminGetContent",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get user's generated contents",
        "tags": [
          "Admin Content"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/contents/bulk": {
      "post": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:*:CONTENT [READ]\u0026lt;/b\u0026gt;.\n\t\t\t\t\t\tMaximum contentId per request 100",
        "operationId": "AdminGetContentBulk",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:*:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Bulk get content by content IDs",
        "tags": [
          "Admin Content"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/contents/search": {
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:*:CONTENT [READ]\u0026lt;/b\u0026gt;\n\nFor advance tag filtering supports \u0026amp; as AND operator and | as OR operator and parentheses () for priority. e.g: \n\n\u0026lt;code\u0026gt;tags=red\u0026lt;/code\u0026gt;\n\n\u0026lt;code\u0026gt;tags=red\u0026amp;animal\u0026lt;/code\u0026gt;\n\n\u0026lt;code\u0026gt;tags=red|animal\u0026lt;/code\u0026gt;\n\n\u0026lt;code\u0026gt;tags=red\u0026amp;anima[...]",
        "operationId": "AdminSearchContent",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:*:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Search contents",
        "tags": [
          "Admin Content"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/contents/sharecodes/bulk": {
      "post": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:*:CONTENT [READ]\u0026lt;/b\u0026gt;.\n\t\t\t\t\t\tMaximum sharecodes per request 100",
        "operationId": "AdminGetContentBulkByShareCodes",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:*:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Bulk get content by content sharecodes",
        "tags": [
          "Admin Content"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/contents/sharecodes/{shareCode}": {
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:*:CONTENT [READ]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminGetUserContentByShareCode",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:*:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get content by sharecode",
        "tags": [
          "Admin Content"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/contents/{contentId}": {
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:*:CONTENT [READ]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminGetSpecificContent",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:*:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get user specific content",
        "tags": [
          "Admin Content"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/contents/{contentId}/preview": {
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:*:CONTENT [READ]\u0026lt;/b\u0026gt;\u0026lt;p\u0026gt;\u0026lt;b\u0026gt;NOTE: Preview is Legacy Code, please use Screenshot for better solution to display preview of a content\u0026lt;/b\u0026gt;\u0026lt;/p\u0026gt;",
        "operationId": "AdminDownloadContentPreview",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:*:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get content preview",
        "tags": [
          "Admin Content"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/contents/{contentId}/rollback/{versionId}": {
      "put": {
        "description": "Required permission: \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]\u0026lt;/b\u0026gt;\n\t\t\t\tRollback content\u0026#39;s payload to specified version.",
        "operationId": "RollbackContentVersion",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Rollback content's payload version",
        "tags": [
          "Admin Content"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/contents/{contentId}/screenshots": {
      "post": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [CREATE]\u0026lt;/b\u0026gt;. \n\t\t\t\tAll request body are required except for contentType field. \n\t\t\t\tcontentType values is used to enforce the Content-Type header needed by the client to upload the content using the presigned URL.\n\t\t\t\tIf not specified, it will use fileExtension value.\n\t\t\t\tSupported file extensions: pjp, jpg, jpeg, jfif, bmp, png.\n\t\t\t\tMaximum de[...]",
        "operationId": "AdminUploadContentScreenshot",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Upload screenshots for content",
        "tags": [
          "Admin Content"
        ]
      },
      "put": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]\u0026lt;/b\u0026gt;. \n\t\t\t\t\tMaximum description length: 1024.\n\t\t\t\t\t",
        "operationId": "AdminUpdateScreenshots",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update screenshot of content",
        "tags": [
          "Admin Content"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/contents/{contentId}/screenshots/{screenshotId}": {
      "delete": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]\u0026lt;/b\u0026gt;.\n\t\t\t\t",
        "operationId": "AdminDeleteContentScreenshot",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete screenshots content",
        "tags": [
          "Admin Content"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/contents/{contentId}/versions": {
      "get": {
        "description": "Required permission: \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]\u0026lt;/b\u0026gt;\n\t\t\t\tContent\u0026#39;s payload versions created when UGC is created or updated with \u0026lt;code\u0026gt;updateContentFile\u0026lt;/code\u0026gt; set to true. Only list up to 10 latest versions.",
        "operationId": "ListContentVersions",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "List content's payload versions",
        "tags": [
          "Admin Content"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/groups": {
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [READ]\u0026lt;/b\u0026gt;.",
        "operationId": "SingleAdminGetAllGroups",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get all user groups",
        "tags": [
          "Admin Group"
        ]
      },
      "post": {
        "description": "Required permission ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [CREATE]",
        "operationId": "AdminCreateGroup",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Create groups",
        "tags": [
          "Admin Group"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/groups/{groupId}": {
      "delete": {
        "description": "Required permission ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [DELETE]",
        "operationId": "SingleAdminDeleteGroup",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete group",
        "tags": [
          "Admin Group"
        ]
      },
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [READ]\u0026lt;/b\u0026gt;.",
        "operationId": "SingleAdminGetGroup",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get specific user group",
        "tags": [
          "Admin Group"
        ]
      },
      "put": {
        "description": "Required permission ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [UPDATE]\n\t\t\t\t\treplace group name and contents with new ones.",
        "operationId": "SingleAdminUpdateGroup",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update group",
        "tags": [
          "Admin Group"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/groups/{groupId}/contents": {
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]\u0026lt;/b\u0026gt;.",
        "operationId": "SingleAdminGetGroupContents",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "(Legacy) Get contents belong to a group",
        "tags": [
          "Admin Group"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/tags": {
      "get": {
        "description": "Required permission ADMIN:NAMESPACE:{namespace}:UGCCONFIG [READ]",
        "operationId": "AdminGetTag",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:UGCCONFIG [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get tags",
        "tags": [
          "Admin Tag"
        ]
      },
      "post": {
        "description": "Required permission ADMIN:NAMESPACE:{namespace}:UGCCONFIG [CREATE]\n\t\t\t\tcreates a new tag",
        "operationId": "AdminCreateTag",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:UGCCONFIG [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Create tags",
        "tags": [
          "Admin Tag"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/tags/{tagId}": {
      "delete": {
        "description": "Required permission ADMIN:NAMESPACE:{namespace}:UGCCONFIG [DELETE]",
        "operationId": "AdminDeleteTag",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:UGCCONFIG [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete tags",
        "tags": [
          "Admin Tag"
        ]
      },
      "put": {
        "description": "Required permission ADMIN:NAMESPACE:{namespace}:UGCCONFIG [UPDATE]\n\t\t\t\tupdates a tag",
        "operationId": "AdminUpdateTag",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:UGCCONFIG [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update tag",
        "tags": [
          "Admin Tag"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/types": {
      "get": {
        "description": "Required permission ADMIN:NAMESPACE:{namespace}:UGCCONFIG [READ]",
        "operationId": "AdminGetType",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:UGCCONFIG [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get types",
        "tags": [
          "Admin Type"
        ]
      },
      "post": {
        "description": "Required permission ADMIN:NAMESPACE:{namespace}:UGCCONFIG [CREATE]\n\t\t\tcreates a new type and subtype",
        "operationId": "AdminCreateType",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:UGCCONFIG [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Create types",
        "tags": [
          "Admin Type"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/types/{typeId}": {
      "delete": {
        "description": "Required permission ADMIN:NAMESPACE:{namespace}:UGCCONFIG [DELETE]",
        "operationId": "AdminDeleteType",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:UGCCONFIG [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete types",
        "tags": [
          "Admin Type"
        ]
      },
      "put": {
        "description": "Required permission ADMIN:NAMESPACE:{namespace}:UGCCONFIG [UPDATE]\n\t\t\tupdates a type and subtype",
        "operationId": "AdminUpdateType",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:UGCCONFIG [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update types",
        "tags": [
          "Admin Type"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/users/{userId}/channels": {
      "delete": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CHANNEL [DELETE]\u0026lt;/b\u0026gt;",
        "operationId": "AdminDeleteAllUserChannels",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CHANNEL [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete all user channel",
        "tags": [
          "Anonymization"
        ]
      },
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CHANNEL [READ]\u0026lt;/b\u0026gt;",
        "operationId": "AdminGetChannel",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CHANNEL [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get Channels",
        "tags": [
          "Admin Channel"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/users/{userId}/channels/{channelId}": {
      "delete": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CHANNEL [DELETE]\u0026lt;/b\u0026gt;",
        "operationId": "AdminDeleteChannel",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CHANNEL [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete Channel",
        "tags": [
          "Admin Channel"
        ]
      },
      "put": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CHANNEL [UPDATE]\u0026lt;/b\u0026gt;",
        "operationId": "AdminUpdateChannel",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CHANNEL [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update Channel",
        "tags": [
          "Admin Channel"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/s3/sharecodes/{shareCode}": {
      "put": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]\u0026lt;/b\u0026gt;.\n\nAll request body are required except \u0026lt;code\u0026gt;payload\u0026lt;/code\u0026gt;, \u0026lt;code\u0026gt;preview\u0026lt;/code\u0026gt;, \u0026lt;code\u0026gt;tags\u0026lt;/code\u0026gt;,\u0026lt;code\u0026gt;contentType\u0026lt;/code\u0026gt;, \u0026lt;code\u0026gt;updateContentFile\u0026lt;/code\u0026gt;, \u0026lt;code\u0026gt;customAttribute[...]",
        "operationId": "AdminUpdateContentS3ByShareCode",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update content to S3 bucket by share code",
        "tags": [
          "Admin Content"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/s3/{contentId}": {
      "put": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]\u0026lt;/b\u0026gt;.\n\nAll request body are required except \u0026lt;code\u0026gt;payload\u0026lt;/code\u0026gt;, \u0026lt;code\u0026gt;preview\u0026lt;/code\u0026gt;, \u0026lt;code\u0026gt;tags\u0026lt;/code\u0026gt;,\u0026lt;code\u0026gt;contentType\u0026lt;/code\u0026gt;, \u0026lt;code\u0026gt;updateContentFile\u0026lt;/code\u0026gt;, \u0026lt;code\u0026gt;customAttribute[...]",
        "operationId": "AdminUpdateContentS3",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update content to S3 bucket",
        "tags": [
          "Admin Content"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/sharecodes/{shareCode}": {
      "delete": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]\u0026lt;/b\u0026gt;.",
        "operationId": "DeleteContentByShareCode",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete content by share code",
        "tags": [
          "Admin Content"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/{contentId}": {
      "delete": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminDeleteContent",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete content",
        "tags": [
          "Admin Content"
        ]
      },
      "put": {
        "deprecated": true,
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]\u0026lt;/b\u0026gt;.\\n \n\t\t\t\t\tAll request body are required except preview, tags and customAttributes.\n\t\t\t\t\t",
        "operationId": "AdminUpdateContentDirect",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update content to a channel",
        "tags": [
          "Admin Content"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/users/{userId}/contents": {
      "delete": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminDeleteAllUserContents",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete all user content",
        "tags": [
          "Anonymization"
        ]
      },
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminGetContent",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get user's generated contents",
        "tags": [
          "Admin Content"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/users/{userId}/contents/{contentId}/hide": {
      "put": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminHideUserContent",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Hide/Unhide user's generated contents",
        "tags": [
          "Admin Content"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/users/{userId}/groups": {
      "delete": {
        "description": "Required permission ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [DELETE]",
        "operationId": "AdminDeleteAllUserGroup",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete all user group",
        "tags": [
          "Anonymization"
        ]
      },
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [READ]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminGetAllGroups",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get all user groups",
        "tags": [
          "Admin Group"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/users/{userId}/groups/{groupId}": {
      "delete": {
        "description": "Required permission ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [DELETE]",
        "operationId": "AdminDeleteGroup",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete group",
        "tags": [
          "Admin Group"
        ]
      },
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [READ]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminGetGroup",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get specific user group",
        "tags": [
          "Admin Group"
        ]
      },
      "put": {
        "description": "Required permission ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [UPDATE]\n\t\t\t\t\treplace group name and contents with new ones.",
        "operationId": "AdminUpdateGroup",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update group",
        "tags": [
          "Admin Group"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/users/{userId}/groups/{groupId}/contents": {
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminGetGroupContents",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "(Legacy) Get contents belong to a group",
        "tags": [
          "Admin Group"
        ]
      }
    },
    "/ugc/v1/admin/namespaces/{namespace}/users/{userId}/states": {
      "delete": {
        "description": "Required permission ADMIN:NAMESPACE:{namespace}:USER:{userId} [DELETE]",
        "operationId": "AdminDeleteAllUserStates",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId} [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Remove all user related state: likes, downloads, followers, following",
        "tags": [
          "Anonymization"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/channels/{channelId}/contents": {
      "get": {
        "description": "Requires valid user token.\n\nFor advance tag filtering supports \u0026amp; as AND operator and | as OR operator and parentheses () for priority. e.g: \n\n\u0026lt;code\u0026gt;tags=red\u0026lt;/code\u0026gt;\n\n\u0026lt;code\u0026gt;tags=red\u0026amp;animal\u0026lt;/code\u0026gt;\n\n\u0026lt;code\u0026gt;tags=red|animal\u0026lt;/code\u0026gt;\n\n\u0026lt;code\u0026gt;tags=red\u0026amp;animal|wild\u0026lt;/code\u0026gt;\n\n\u0026lt;code\u0026gt;tags=red\u0026amp;(animal|w[...]",
        "operationId": "SearchChannelSpecificContent",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Search contents specific to a channel",
        "tags": [
          "Public Content (Legacy)"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/contents": {
      "get": {
        "description": "Public user can access without token or if token specified, requires valid user token.\n\nFor advance tag filtering supports \u0026amp; as AND operator and | as OR operator and parentheses () for priority. e.g: \n\n\u0026lt;code\u0026gt;tags=red\u0026lt;/code\u0026gt;\n\n\u0026lt;code\u0026gt;tags=red\u0026amp;animal\u0026lt;/code\u0026gt;\n\n\u0026lt;code\u0026gt;tags=red|animal\u0026lt;/code\u0026gt;\n\n\u0026lt;code\u0026gt;tags=red\u0026amp;animal|wild\u0026lt;/code\u[...]",
        "operationId": "PublicSearchContent",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Search contents",
        "tags": [
          "Public Content (Legacy)"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/contents/bulk": {
      "post": {
        "description": "Maximum requested Ids: 100.\n\t\t\tPublic user can access without token or if token specified, requires valid user token",
        "operationId": "PublicGetContentBulk",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get contents by content Ids ",
        "tags": [
          "Public Content (Legacy)"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/contents/followed": {
      "get": {
        "description": "Requires valid user token",
        "operationId": "GetFollowedContent",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get contents from followed creators",
        "tags": [
          "Public Follow"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/contents/liked": {
      "get": {
        "description": "Requires valid user token.\n\nFor advance tag filtering supports \u0026amp; as AND operator and | as OR operator and parentheses () for priority. e.g: \n\n\u0026lt;code\u0026gt;tags=red\u0026lt;/code\u0026gt;\n\n\u0026lt;code\u0026gt;tags=red\u0026amp;animal\u0026lt;/code\u0026gt;\n\n\u0026lt;code\u0026gt;tags=red|animal\u0026lt;/code\u0026gt;\n\n\u0026lt;code\u0026gt;tags=red\u0026amp;animal|wild\u0026lt;/code\u0026gt;\n\n\u0026lt;code\u0026gt;tags=red\u0026amp;(animal|w[...]",
        "operationId": "GetLikedContent",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get liked contents",
        "tags": [
          "Public Like (Legacy)"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/contents/sharecodes/bulk": {
      "post": {
        "description": "Require valid user token.\n\t\t\t\t\tMaximum sharecodes per request 100",
        "operationId": "PublicGetContentBulkByShareCodes",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Bulk get content by content sharecodes",
        "tags": [
          "Public Content (Legacy)"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/contents/sharecodes/{shareCode}": {
      "get": {
        "description": "Public user can access without token or if token specified, requires valid user token",
        "operationId": "PublicDownloadContentByShareCode",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get content by sharecode",
        "tags": [
          "Public Content (Legacy)"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/contents/{contentId}": {
      "get": {
        "description": "Public user can access without token or if token specified, requires valid user token",
        "operationId": "PublicDownloadContentByContentID",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get user specific content",
        "tags": [
          "Public Content (Legacy)"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/contents/{contentId}/downloadcount": {
      "post": {
        "description": "Requires valid user token",
        "operationId": "AddDownloadCount",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Add unique download count to a content",
        "tags": [
          "Public Download Count (Legacy)"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/contents/{contentId}/like": {
      "put": {
        "description": "Requires valid user token",
        "operationId": "UpdateContentLikeStatus",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Update like/unlike status to a content",
        "tags": [
          "Public Like (Legacy)"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/contents/{contentId}/preview": {
      "get": {
        "description": "\u0026lt;p\u0026gt;Requires valid user token\u0026lt;/p\u0026gt;\u0026lt;p\u0026gt;\u0026lt;b\u0026gt;NOTE: Preview is Legacy Code, please use Screenshot for better solution to display preview of a content\u0026lt;/b\u0026gt;\u0026lt;/p\u0026gt;",
        "operationId": "PublicDownloadContentPreview",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get content preview",
        "tags": [
          "Public Content (Legacy)"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/tags": {
      "get": {
        "description": "Publicly accessible",
        "operationId": "GetTag",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get tags",
        "tags": [
          "Public Tag"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/types": {
      "get": {
        "description": "Requires valid user token",
        "operationId": "GetType",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get types",
        "tags": [
          "Public Type"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/users": {
      "get": {
        "description": "Public user can access without token or if token specified, requires valid user token",
        "operationId": "PublicSearchCreator",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Search creator",
        "tags": [
          "Public Creator"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/users/followed": {
      "get": {
        "description": "Requires valid user token",
        "operationId": "GetFollowedUsers",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get followed creators",
        "tags": [
          "Public Follow"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/users/{userId}": {
      "get": {
        "description": "Public user can access without token or if token specified, requires valid user token",
        "operationId": "PublicGetCreator",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get creator stats: number of total like by other user, number of total following and follower user",
        "tags": [
          "Public Creator"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/users/{userId}/channels": {
      "delete": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CHANNEL [DELETE]\u0026lt;/b\u0026gt;",
        "operationId": "DeleteAllUserChannel",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CHANNEL [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete all user channel",
        "tags": [
          "Anonymization"
        ]
      },
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CHANNEL [READ]\u0026lt;/b\u0026gt;",
        "operationId": "GetChannels",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CHANNEL [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get Channels",
        "tags": [
          "Public Channel"
        ]
      },
      "post": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CHANNEL [CREATE]\u0026lt;/b\u0026gt;",
        "operationId": "PublicCreateChannel",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CHANNEL [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Create Channel",
        "tags": [
          "Public Channel"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/users/{userId}/channels/{channelId}": {
      "delete": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CHANNEL [DELETE]\u0026lt;/b\u0026gt;",
        "operationId": "DeleteChannel",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CHANNEL [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete Channel",
        "tags": [
          "Public Channel"
        ]
      },
      "put": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CHANNEL [UPDATE]\u0026lt;/b\u0026gt;",
        "operationId": "UpdateChannel",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CHANNEL [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update Channel",
        "tags": [
          "Public Channel"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents": {
      "post": {
        "deprecated": true,
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [CREATE]\u0026lt;/b\u0026gt;.\\n \n\t\t\tAll request body are required except preview, tags and customAttributes.\n\t\t\t",
        "operationId": "CreateContentDirect",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Upload content to a channel",
        "tags": [
          "Public Content (Legacy)"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/s3": {
      "post": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [CREATE]\u0026lt;/b\u0026gt;.\\n \n\t\t\t\tAll request body are required except payload, preview, tags, contentType and customAttributes.\n\t\t\t\tcontentType values is used to enforce the Content-Type header needed by the client to upload the content using the S3 presigned URL.\n\t\t\t\tIf not specified, it will use fileExtension value.\n\t\t\t\t\u0026lt;br\u0026gt;\u0026lt;p\u0026gt;\u002[...]",
        "operationId": "CreateContentS3",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Upload content to S3 bucket",
        "tags": [
          "Public Content (Legacy)"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/s3/sharecodes/{shareCode}": {
      "put": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]\u0026lt;/b\u0026gt;.\n\nAll request body are required except \u0026lt;code\u0026gt;payload\u0026lt;/code\u0026gt;, \u0026lt;code\u0026gt;preview\u0026lt;/code\u0026gt;, \u0026lt;code\u0026gt;tags\u0026lt;/code\u0026gt;,\u0026lt;code\u0026gt;contentType\u0026lt;/code\u0026gt;, \u0026lt;code\u0026gt;updateContentFile\u0026lt;/code\u0026gt;, \u0026lt;code\u0026gt;customAttributes\u002[...]",
        "operationId": "PublicUpdateContentByShareCode",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update content to S3 bucket by share code",
        "tags": [
          "Public Content (Legacy)"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/s3/{contentId}": {
      "put": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]\u0026lt;/b\u0026gt;.\n\t\t\t\tAll request body are required except payload, preview, tags, contentType, updateContentFile and customAttributes.\n\t\t\t\tcontentType values is used to enforce the Content-Type header needed by the client to upload the content using the S3 presigned URL.\n\t\t\t\tIf not specified, it will use fileExtension value.\n\t\t\t\tTo update content\u0026#39;s [...]",
        "operationId": "UpdateContentS3",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update content to S3 bucket",
        "tags": [
          "Public Content (Legacy)"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/sharecodes/{shareCode}": {
      "delete": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]\u0026lt;/b\u0026gt;.",
        "operationId": "PublicDeleteContentByShareCode",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete content by share code",
        "tags": [
          "Public Content (Legacy)"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/{contentId}": {
      "delete": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]\u0026lt;/b\u0026gt;.",
        "operationId": "DeleteContent",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete content",
        "tags": [
          "Public Content (Legacy)"
        ]
      },
      "put": {
        "deprecated": true,
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]\u0026lt;/b\u0026gt;.\\n \n\t\t\t\tAll request body are required except preview, tags and customAttributes.\n\t\t\t\t",
        "operationId": "UpdateContentDirect",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update content to a channel",
        "tags": [
          "Public Content (Legacy)"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/{contentId}/sharecode": {
      "patch": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT:SHARECODE [UPDATE]\u0026lt;/b\u0026gt;.\u0026lt;br\u0026gt;\n\t\t\t\t\tThis endpoint is used to modify the shareCode of a content. However, this operation is restricted by default and requires the above permission to be granted to the User role.\u0026lt;br\u0026gt;\n\t\t\t\t\t\u0026lt;code\u0026gt;shareCode\u0026lt;/code\u0026gt; format should follows:\n\t\t\t\t\tMax length: 7\n\t\t\t\t\tAv[...]",
        "operationId": "UpdateContentShareCode",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT:SHARECODE [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update content sharecode",
        "tags": [
          "Public Content (Legacy)"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/users/{userId}/contents": {
      "delete": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]\u0026lt;/b\u0026gt;.",
        "operationId": "DeleteAllUserContents",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete all user content",
        "tags": [
          "Anonymization"
        ]
      },
      "get": {
        "description": "Public user can access without token or if token specified, required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]\u0026lt;/b\u0026gt;.",
        "operationId": "PublicGetUserContent",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get user's generated contents",
        "tags": [
          "Public Content (Legacy)"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/users/{userId}/contents/{contentId}/screenshots": {
      "post": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [CREATE]\u0026lt;/b\u0026gt;. \n\t\t\t\tAll request body are required except for contentType field. \n\t\t\t\tcontentType values is used to enforce the Content-Type header needed by the client to upload the content using the presigned URL.\n\t\t\t\tIf not specified, it will use fileExtension value.\n\t\t\t\tSupported file extensions: pjp, jpg, jpeg, jfif, bmp, png. \n\t\t\t\tMaximum descrip[...]",
        "operationId": "UploadContentScreenshot",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Upload screenshots for content",
        "tags": [
          "Public Content (Legacy)"
        ]
      },
      "put": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]\u0026lt;/b\u0026gt;. \n\t\t\t\t\tMaximum description length: 1024.\n\t\t\t\t\t",
        "operationId": "UpdateScreenshots",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update screenshot of content",
        "tags": [
          "Public Content (Legacy)"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/users/{userId}/contents/{contentId}/screenshots/{screenshotId}": {
      "delete": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]\u0026lt;/b\u0026gt;.\n\t\t\t\t",
        "operationId": "DeleteContentScreenshot",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete screenshots content",
        "tags": [
          "Public Content (Legacy)"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/users/{userId}/follow": {
      "put": {
        "description": "Requires valid user token",
        "operationId": "UpdateUserFollowStatus",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Update follow/unfollow status to a user",
        "tags": [
          "Public Follow"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/users/{userId}/followers": {
      "get": {
        "operationId": "GetPublicFollowers",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get list of followers",
        "tags": [
          "Public Follow"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/users/{userId}/following": {
      "get": {
        "operationId": "GetPublicFollowing",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get list of following",
        "tags": [
          "Public Follow"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/users/{userId}/groups": {
      "delete": {
        "description": "Required permission NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [DELETE]",
        "operationId": "DeleteAllUserGroup",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete all user group",
        "tags": [
          "Anonymization"
        ]
      },
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [READ]\u0026lt;/b\u0026gt;.",
        "operationId": "GetGroups",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get all user groups",
        "tags": [
          "Public Group"
        ]
      },
      "post": {
        "description": "Required permission NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [CREATE]",
        "operationId": "CreateGroup",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Create groups",
        "tags": [
          "Public Group"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/users/{userId}/groups/{groupId}": {
      "delete": {
        "description": "Required permission NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [DELETE]",
        "operationId": "DeleteGroup",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete group",
        "tags": [
          "Public Group"
        ]
      },
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [READ]\u0026lt;/b\u0026gt;.",
        "operationId": "GetGroup",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get user's groups",
        "tags": [
          "Public Group"
        ]
      },
      "put": {
        "description": "Required permission NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [UPDATE]\n\t\t\t\treplace group name and contents with new ones",
        "operationId": "UpdateGroup",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENTGROUP [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update group",
        "tags": [
          "Public Group"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/users/{userId}/groups/{groupId}/contents": {
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]\u0026lt;/b\u0026gt;.",
        "operationId": "GetGroupContent",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "(Legacy) Get contents belong to a group",
        "tags": [
          "Public Group"
        ]
      }
    },
    "/ugc/v1/public/namespaces/{namespace}/users/{userId}/states": {
      "delete": {
        "description": "Required permission NAMESPACE:{namespace}:USER:{userId}\u0026#34; [DELETE]",
        "operationId": "DeleteAllUserStates",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId} [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Remove all user related state: likes, downloads, followers, following",
        "tags": [
          "Anonymization"
        ]
      }
    },
    "/ugc/v2/admin/namespaces/{namespace}/channels/{channelId}/contents": {
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminGetContentByChannelIDV2",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "List contents specific to a channel",
        "tags": [
          "Admin Content V2"
        ]
      },
      "post": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [CREATE]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminCreateContentV2",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Create a content",
        "tags": [
          "Admin Content V2"
        ]
      }
    },
    "/ugc/v2/admin/namespaces/{namespace}/channels/{channelId}/contents/{contentId}": {
      "delete": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminDeleteOfficialContentV2",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete official content",
        "tags": [
          "Admin Content V2"
        ]
      },
      "patch": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminUpdateOfficialContentV2",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update official content",
        "tags": [
          "Admin Content V2"
        ]
      }
    },
    "/ugc/v2/admin/namespaces/{namespace}/channels/{channelId}/contents/{contentId}/fileLocation": {
      "patch": {
        "description": "This endpoint should be used after calling generate official content upload url endpoint to commit the changes.\nRequired permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminUpdateOfficialContentFileLocation",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update content file location",
        "tags": [
          "Admin Content V2"
        ]
      }
    },
    "/ugc/v2/admin/namespaces/{namespace}/channels/{channelId}/contents/{contentId}/uploadUrl": {
      "patch": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminGenerateOfficialContentUploadURLV2",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Generate official content upload URL",
        "tags": [
          "Admin Content V2"
        ]
      }
    },
    "/ugc/v2/admin/namespaces/{namespace}/configs": {
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:UGCCONFIG [READ]\u0026lt;/b\u0026gt;",
        "operationId": "AdminGetConfigs",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:UGCCONFIG [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get configs",
        "tags": [
          "Admin Config"
        ]
      }
    },
    "/ugc/v2/admin/namespaces/{namespace}/configs/{key}": {
      "patch": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:UGCCONFIG [UPDATE]\u0026lt;/b\u0026gt;.\n\t\t\t\t\tIt will create a new config if the \u0026lt;i\u0026gt;key\u0026lt;/i\u0026gt; doesn\u0026#39;t exist.\n\t\t\t\t\tAllowed key value:\n\t\t\t\t\t- \u0026lt;i\u0026gt;contentReview\u0026lt;/i\u0026gt;: \u0026lt;i\u0026gt;enabled\u0026lt;/i\u0026gt;,\u0026lt;i\u0026gt;disabled\u0026lt;/i\u0026gt;",
        "operationId": "AdminUpdateConfig",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:UGCCONFIG [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update config",
        "tags": [
          "Admin Config"
        ]
      }
    },
    "/ugc/v2/admin/namespaces/{namespace}/contents": {
      "get": {
        "description": "\nRequired permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:*:CONTENT [READ]\u0026lt;/b\u0026gt;\nFor advance tag filtering supports \u0026amp; as AND operator and | as OR operator and parentheses () for priority. e.g:\n\n\u0026lt;code\u0026gt;tags=red\u0026lt;/code\u0026gt;\n\u0026lt;code\u0026gt;tags=red\u0026amp;animal\u0026lt;/code\u0026gt;\n\u0026lt;code\u0026gt;tags=red|animal\u0026lt;/code\u0026gt;\n\u0026lt;code\u0026gt;tags=red\u0026amp;animal|wild\[...]",
        "operationId": "AdminListContentV2",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:*:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "List contents",
        "tags": [
          "Admin Content V2"
        ]
      }
    },
    "/ugc/v2/admin/namespaces/{namespace}/contents/bulk": {
      "post": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:*:CONTENT [READ]\u0026lt;/b\u0026gt;.\n\t\t\t\t\t\tMaximum contentId per request 100",
        "operationId": "AdminBulkGetContentByIDsV2",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:*:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Bulk get content by content IDs",
        "tags": [
          "Admin Content V2"
        ]
      }
    },
    "/ugc/v2/admin/namespaces/{namespace}/contents/sharecodes/bulk": {
      "post": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:*:CONTENT [READ]\u0026lt;/b\u0026gt;.\n\t\t\t\t\t\tMaximum sharecodes per request 100",
        "operationId": "AdminGetContentBulkByShareCodesV2",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:*:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Bulk get content by content sharecodes",
        "tags": [
          "Admin Content V2"
        ]
      }
    },
    "/ugc/v2/admin/namespaces/{namespace}/contents/sharecodes/{shareCode}": {
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:*:CONTENT [READ]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminGetContentByShareCodeV2",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:*:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get content by sharecode",
        "tags": [
          "Admin Content V2"
        ]
      }
    },
    "/ugc/v2/admin/namespaces/{namespace}/contents/{contentId}": {
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:*:CONTENT [READ]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminGetContentByContentIDV2",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:*:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get content by content ID",
        "tags": [
          "Admin Content V2"
        ]
      }
    },
    "/ugc/v2/admin/namespaces/{namespace}/contents/{contentId}/rollback/{versionId}": {
      "put": {
        "description": "Required permission: \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]\u0026lt;/b\u0026gt;\n\t\t\t\tRollback content\u0026#39;s payload to specified version.",
        "operationId": "RollbackContentVersionV2",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Rollback content's payload version",
        "tags": [
          "Admin Content V2"
        ]
      }
    },
    "/ugc/v2/admin/namespaces/{namespace}/contents/{contentId}/screenshots": {
      "post": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [CREATE]\u0026lt;/b\u0026gt;. \n\t\t\t\tAll request body are required except for contentType field. \n\t\t\t\tcontentType values is used to enforce the Content-Type header needed by the client to upload the content using the presigned URL.\n\t\t\t\tIf not specified, it will use fileExtension value.\n\t\t\t\tSupported file extensions: pjp, jpg, jpeg, jfif, bmp, png. \n\t\t\t\tMaximum d[...]",
        "operationId": "AdminUploadContentScreenshotV2",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Upload screenshots for content",
        "tags": [
          "Admin Content V2"
        ]
      },
      "put": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]\u0026lt;/b\u0026gt;. \n\t\t\t\t\tMaximum description length: 1024.\n\t\t\t\t\t",
        "operationId": "AdminUpdateScreenshotsV2",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update screenshot of content",
        "tags": [
          "Admin Content V2"
        ]
      }
    },
    "/ugc/v2/admin/namespaces/{namespace}/contents/{contentId}/screenshots/{screenshotId}": {
      "delete": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]\u0026lt;/b\u0026gt;.\n\t\t\t\t",
        "operationId": "AdminDeleteContentScreenshotV2",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete screenshots content",
        "tags": [
          "Admin Content V2"
        ]
      }
    },
    "/ugc/v2/admin/namespaces/{namespace}/contents/{contentId}/versions": {
      "get": {
        "description": "Required permission: \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]\u0026lt;/b\u0026gt;\n\t\t\t\tContent\u0026#39;s payload versions created when UGC is created or updated with \u0026lt;code\u0026gt;updateContentFile\u0026lt;/code\u0026gt; set to true. Only list up to 10 latest versions.",
        "operationId": "ListContentVersionsV2",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "List content's payload versions",
        "tags": [
          "Admin Content V2"
        ]
      }
    },
    "/ugc/v2/admin/namespaces/{namespace}/groups/{groupId}/contents": {
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminGetOfficialGroupContentsV2",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get contents belong to a group",
        "tags": [
          "Admin Group"
        ]
      }
    },
    "/ugc/v2/admin/namespaces/{namespace}/staging-contents": {
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminListStagingContents",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "List staging contents",
        "tags": [
          "Admin Staging Content"
        ]
      }
    },
    "/ugc/v2/admin/namespaces/{namespace}/staging-contents/{contentId}": {
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminGetStagingContentByID",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get staging content by id",
        "tags": [
          "Admin Staging Content"
        ]
      }
    },
    "/ugc/v2/admin/namespaces/{namespace}/staging-contents/{contentId}/approve": {
      "post": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:CONTENT:APPROVAL [CREATE]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminApproveStagingContent",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:CONTENT:APPROVAL [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Approve or reject content",
        "tags": [
          "Admin Staging Content"
        ]
      }
    },
    "/ugc/v2/admin/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/s3/sharecodes/{shareCode}": {
      "put": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]\u0026lt;/b\u0026gt;.\n\n\u0026lt;code\u0026gt;shareCode\u0026lt;/code\u0026gt; format should follows:\n\nMax length: 7\nAvailable characters: abcdefhkpqrstuxyz\n\n",
        "operationId": "AdminUpdateContentByShareCodeV2",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update content to S3 bucket by share code",
        "tags": [
          "Admin Content V2"
        ]
      }
    },
    "/ugc/v2/admin/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/sharecodes/{shareCode}": {
      "delete": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminDeleteContentByShareCodeV2",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete content by share code",
        "tags": [
          "Admin Content V2"
        ]
      }
    },
    "/ugc/v2/admin/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/{contentId}": {
      "delete": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminDeleteUserContentV2",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete user content",
        "tags": [
          "Admin Content V2"
        ]
      },
      "patch": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminUpdateUserContentV2",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update user content",
        "tags": [
          "Admin Content V2"
        ]
      }
    },
    "/ugc/v2/admin/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/{contentId}/fileLocation": {
      "patch": {
        "description": "This endpoint should be used after calling generate user content upload url endpoint to commit the changes.\nRequired permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminUpdateUserContentFileLocation",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update user content file location",
        "tags": [
          "Admin Content V2"
        ]
      }
    },
    "/ugc/v2/admin/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/{contentId}/uploadUrl": {
      "patch": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminGenerateUserContentUploadURLV2",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Generate user content upload URL",
        "tags": [
          "Admin Content V2"
        ]
      }
    },
    "/ugc/v2/admin/namespaces/{namespace}/users/{userId}/contents": {
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminGetContentByUserIDV2",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get user's generated contents",
        "tags": [
          "Admin Content V2"
        ]
      }
    },
    "/ugc/v2/admin/namespaces/{namespace}/users/{userId}/contents/{contentId}/hide": {
      "put": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminUpdateContentHideStatusV2",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Hide/Unhide user's generated contents",
        "tags": [
          "Admin Content V2"
        ]
      }
    },
    "/ugc/v2/admin/namespaces/{namespace}/users/{userId}/groups/{groupId}/contents": {
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminGetUserGroupContentsV2",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get contents belong to a group",
        "tags": [
          "Admin Group"
        ]
      }
    },
    "/ugc/v2/admin/namespaces/{namespace}/users/{userId}/staging-contents": {
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]\u0026lt;/b\u0026gt;.",
        "operationId": "AdminListUserStagingContents",
        "security": [
          {
            "HasPermission": [
              "ADMIN:NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "List user staging contents",
        "tags": [
          "Admin Staging Content"
        ]
      }
    },
    "/ugc/v2/public/namespaces/{namespace}/channels/{channelId}/contents": {
      "get": {
        "description": "Public user can access without token or if token specified, requires valid user token",
        "operationId": "PublicGetContentByChannelIDV2",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "List contents specific to a channel",
        "tags": [
          "Public Content V2"
        ]
      }
    },
    "/ugc/v2/public/namespaces/{namespace}/contents": {
      "get": {
        "description": "\nFor advance tag filtering supports \u0026amp; as AND operator and | as OR operator and parentheses () for priority. e.g:\n\n\u0026lt;code\u0026gt;tags=red\u0026lt;/code\u0026gt;\n\u0026lt;code\u0026gt;tags=red\u0026amp;animal\u0026lt;/code\u0026gt;\n\u0026lt;code\u0026gt;tags=red|animal\u0026lt;/code\u0026gt;\n\u0026lt;code\u0026gt;tags=red\u0026amp;animal|wild\u0026lt;/code\u0026gt;\n\u0026lt;code\u0026gt;tags=red\u0026amp;(animal|wild)\u0026lt;/code\u0026gt;\n\nThe pr[...]",
        "operationId": "PublicListContentV2",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "List contents",
        "tags": [
          "Public Content V2"
        ]
      }
    },
    "/ugc/v2/public/namespaces/{namespace}/contents/bulk": {
      "post": {
        "description": "Maximum requested Ids: 100.\n\t\t\tPublic user can access without token or if token specified, requires valid user token",
        "operationId": "PublicBulkGetContentByIDV2",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get contents by content Ids ",
        "tags": [
          "Public Content V2"
        ]
      }
    },
    "/ugc/v2/public/namespaces/{namespace}/contents/sharecodes/bulk": {
      "post": {
        "description": "Require valid user token.\n\t\t\t\t\t\t\tMaximum sharecodes per request 100",
        "operationId": "PublicGetContentBulkByShareCodesV2",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Bulk get content by content sharecodes",
        "tags": [
          "Public Content V2"
        ]
      }
    },
    "/ugc/v2/public/namespaces/{namespace}/contents/sharecodes/{shareCode}": {
      "get": {
        "description": "Public user can access without token or if token specified, requires valid user token",
        "operationId": "PublicGetContentByShareCodeV2",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get content by sharecode",
        "tags": [
          "Public Content V2"
        ]
      }
    },
    "/ugc/v2/public/namespaces/{namespace}/contents/{contentId}": {
      "get": {
        "description": "Public user can access without token or if token specified, requires valid user token",
        "operationId": "PublicGetContentByIDV2",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Get content by content ID",
        "tags": [
          "Public Content V2"
        ]
      }
    },
    "/ugc/v2/public/namespaces/{namespace}/contents/{contentId}/downloadcount": {
      "post": {
        "description": "Requires valid user token",
        "operationId": "PublicAddDownloadCountV2",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Add unique download count to a content",
        "tags": [
          "Public Download Count V2"
        ]
      }
    },
    "/ugc/v2/public/namespaces/{namespace}/contents/{contentId}/downloader": {
      "get": {
        "description": "This endpoint will only display the list of users who performed add download count from v2 endpoint.",
        "operationId": "PublicListContentDownloaderV2",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "List content downloader",
        "tags": [
          "Public Download Count V2"
        ]
      }
    },
    "/ugc/v2/public/namespaces/{namespace}/contents/{contentId}/like": {
      "get": {
        "description": "This endpoint will only display the list of users who performed like from v2 endpoint.",
        "operationId": "PublicListContentLikeV2",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Retrieve list of user that like specified content.",
        "tags": [
          "Public Like V2"
        ]
      },
      "put": {
        "description": "Requires valid user token",
        "operationId": "UpdateContentLikeStatusV2",
        "security": [
          {
            "authorization": []
          }
        ],
        "summary": "Update like/unlike status to a content",
        "tags": [
          "Public Like V2"
        ]
      }
    },
    "/ugc/v2/public/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents": {
      "post": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [CREATE]\u0026lt;/b\u0026gt;.",
        "operationId": "PublicCreateContentV2",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Create a content",
        "tags": [
          "Public Content V2"
        ]
      }
    },
    "/ugc/v2/public/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/s3/sharecodes/{shareCode}": {
      "put": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]\u0026lt;/b\u0026gt;.",
        "operationId": "PublicUpdateContentByShareCodeV2",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update content to S3 bucket by share code",
        "tags": [
          "Public Content V2"
        ]
      }
    },
    "/ugc/v2/public/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/sharecodes/{shareCode}": {
      "delete": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]\u0026lt;/b\u0026gt;.",
        "operationId": "PublicDeleteContentByShareCodeV2",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete content by share code",
        "tags": [
          "Public Content V2"
        ]
      }
    },
    "/ugc/v2/public/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/{contentId}": {
      "delete": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]\u0026lt;/b\u0026gt;.",
        "operationId": "PublicDeleteContentV2",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete content",
        "tags": [
          "Public Content V2"
        ]
      },
      "patch": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]\u0026lt;/b\u0026gt;.",
        "operationId": "PublicUpdateContentV2",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update content",
        "tags": [
          "Public Content V2"
        ]
      }
    },
    "/ugc/v2/public/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/{contentId}/fileLocation": {
      "patch": {
        "description": "This endpoint should be used after calling generate upload url endpoint to commit the changes.\nRequired permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]\u0026lt;/b\u0026gt;.",
        "operationId": "PublicUpdateContentFileLocation",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update content file location",
        "tags": [
          "Public Content V2"
        ]
      }
    },
    "/ugc/v2/public/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/{contentId}/sharecode": {
      "patch": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT:SHARECODE [UPDATE]\u0026lt;/b\u0026gt;.\u0026lt;br\u0026gt;\n\t\t\t\t\t\t\t\tThis endpoint is used to modify the shareCode of a content. However, this operation is restricted by default and requires the above permission to be granted to the User role.\u0026lt;br\u0026gt;\n\t\t\t\t\t\t\t\t\u0026lt;code\u0026gt;shareCode\u0026lt;/code\u0026gt; format should follows:\n\t\t\t\t\t\t\t\tMax lengt[...]",
        "operationId": "UpdateContentShareCodeV2",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT:SHARECODE [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update content share code",
        "tags": [
          "Public Content V2"
        ]
      }
    },
    "/ugc/v2/public/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/{contentId}/uploadUrl": {
      "patch": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]\u0026lt;/b\u0026gt;.",
        "operationId": "PublicGenerateContentUploadURLV2",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Generate content upload URL",
        "tags": [
          "Public Content V2"
        ]
      }
    },
    "/ugc/v2/public/namespaces/{namespace}/users/{userId}/contents": {
      "get": {
        "description": "Public user can access without token or if token specified, required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]\u0026lt;/b\u0026gt;.",
        "operationId": "PublicGetContentByUserIDV2",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get content by user ID",
        "tags": [
          "Public Content V2"
        ]
      }
    },
    "/ugc/v2/public/namespaces/{namespace}/users/{userId}/contents/{contentId}/screenshots": {
      "post": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [CREATE]\u0026lt;/b\u0026gt;. \n\t\t\t\tAll request body are required except for contentType field. \n\t\t\t\tcontentType values is used to enforce the Content-Type header needed by the client to upload the content using the presigned URL.\n\t\t\t\tIf not specified, it will use fileExtension value.\n\t\t\t\tSupported file extensions: pjp, jpg, jpeg, jfif, bmp, png.\n\t\t\t\tMaximum descript[...]",
        "operationId": "UploadContentScreenshotV2",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [CREATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Upload screenshots for content",
        "tags": [
          "Public Content V2"
        ]
      },
      "put": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]\u0026lt;/b\u0026gt;. \n\t\t\t\t\tMaximum description length: 1024.\n\t\t\t\t\t",
        "operationId": "UpdateScreenshotsV2",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update screenshot of content",
        "tags": [
          "Public Content V2"
        ]
      }
    },
    "/ugc/v2/public/namespaces/{namespace}/users/{userId}/contents/{contentId}/screenshots/{screenshotId}": {
      "delete": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]\u0026lt;/b\u0026gt;.\n\t\t\t\t",
        "operationId": "DeleteContentScreenshotV2",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete screenshots content",
        "tags": [
          "Public Content V2"
        ]
      }
    },
    "/ugc/v2/public/namespaces/{namespace}/users/{userId}/groups/{groupId}/contents": {
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]\u0026lt;/b\u0026gt;.",
        "operationId": "PublicGetGroupContentsV2",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get contents belong to a group",
        "tags": [
          "Public Group"
        ]
      }
    },
    "/ugc/v2/public/namespaces/{namespace}/users/{userId}/staging-contents": {
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]\u0026lt;/b\u0026gt;.",
        "operationId": "ListUserStagingContents",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "List user staging contents",
        "tags": [
          "Public Staging Content"
        ]
      }
    },
    "/ugc/v2/public/namespaces/{namespace}/users/{userId}/staging-contents/{contentId}": {
      "delete": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]\u0026lt;/b\u0026gt;.",
        "operationId": "DeleteUserStagingContentByID",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [DELETE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Delete user staging content by id",
        "tags": [
          "Public Staging Content"
        ]
      },
      "get": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]\u0026lt;/b\u0026gt;.",
        "operationId": "GetUserStagingContentByID",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]"
            ],
            "authorization": []
          }
        ],
        "summary": "Get user staging content by id",
        "tags": [
          "Public Staging Content"
        ]
      },
      "put": {
        "description": "Required permission \u0026lt;b\u0026gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]\u0026lt;/b\u0026gt;.",
        "operationId": "UpdateStagingContent",
        "security": [
          {
            "HasPermission": [
              "NAMESPACE:{namespace}:USER:{userId}:CONTENT [UPDATE]"
            ],
            "authorization": []
          }
        ],
        "summary": "Update staging content",
        "tags": [
          "Public Staging Content"
        ]
      }
    }
  },
  "x-docs": {
    "alias": "ugc",
    "host": "https://demo.accelbyte.io",
    "path": "/ugc/apidocs/api.json"
  },
  "x-version": {
    "buildDate": "2023-12-29T06:36:16+00:00",
    "gitHash": "beb31b95277bf2f311acbc5793ddc99b4518d0ef",
    "name": "justice-ugc-service",
    "realm": "demo",
    "version": "2.19.1",
    "version-roles-seeding": "1.0.21"
  }
}