// Code generated by go-swagger; DO NOT EDIT.

package group_member

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"reflect"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new group member API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for group member API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	CancelGroupJoinRequestV1(params *CancelGroupJoinRequestV1Params, authInfo runtime.ClientAuthInfoWriter) (*CancelGroupJoinRequestV1OK, *CancelGroupJoinRequestV1BadRequest, *CancelGroupJoinRequestV1Unauthorized, *CancelGroupJoinRequestV1Forbidden, *CancelGroupJoinRequestV1NotFound, *CancelGroupJoinRequestV1InternalServerError, error)

	JoinGroupV1(params *JoinGroupV1Params, authInfo runtime.ClientAuthInfoWriter) (*JoinGroupV1Created, *JoinGroupV1BadRequest, *JoinGroupV1Unauthorized, *JoinGroupV1Forbidden, *JoinGroupV1Conflict, *JoinGroupV1InternalServerError, error)

	AcceptGroupInvitationPublicV1(params *AcceptGroupInvitationPublicV1Params, authInfo runtime.ClientAuthInfoWriter) (*AcceptGroupInvitationPublicV1OK, *AcceptGroupInvitationPublicV1BadRequest, *AcceptGroupInvitationPublicV1Unauthorized, *AcceptGroupInvitationPublicV1Forbidden, *AcceptGroupInvitationPublicV1NotFound, *AcceptGroupInvitationPublicV1Conflict, *AcceptGroupInvitationPublicV1InternalServerError, error)

	AcceptGroupJoinRequestPublicV1(params *AcceptGroupJoinRequestPublicV1Params, authInfo runtime.ClientAuthInfoWriter) (*AcceptGroupJoinRequestPublicV1OK, *AcceptGroupJoinRequestPublicV1BadRequest, *AcceptGroupJoinRequestPublicV1Unauthorized, *AcceptGroupJoinRequestPublicV1Forbidden, *AcceptGroupJoinRequestPublicV1NotFound, *AcceptGroupJoinRequestPublicV1Conflict, *AcceptGroupJoinRequestPublicV1InternalServerError, error)

	GetGroupMembersListPublicV1(params *GetGroupMembersListPublicV1Params, authInfo runtime.ClientAuthInfoWriter) (*GetGroupMembersListPublicV1OK, *GetGroupMembersListPublicV1BadRequest, *GetGroupMembersListPublicV1Unauthorized, *GetGroupMembersListPublicV1Forbidden, *GetGroupMembersListPublicV1NotFound, *GetGroupMembersListPublicV1InternalServerError, error)

	GetGroupMembersListV1(params *GetGroupMembersListV1Params, authInfo runtime.ClientAuthInfoWriter) (*GetGroupMembersListV1OK, *GetGroupMembersListV1BadRequest, *GetGroupMembersListV1Unauthorized, *GetGroupMembersListV1Forbidden, *GetGroupMembersListV1NotFound, *GetGroupMembersListV1InternalServerError, error)

	GetUserGroupInformationPublicV1(params *GetUserGroupInformationPublicV1Params, authInfo runtime.ClientAuthInfoWriter) (*GetUserGroupInformationPublicV1OK, *GetUserGroupInformationPublicV1BadRequest, *GetUserGroupInformationPublicV1Unauthorized, *GetUserGroupInformationPublicV1Forbidden, *GetUserGroupInformationPublicV1NotFound, *GetUserGroupInformationPublicV1InternalServerError, error)

	InviteGroupPublicV1(params *InviteGroupPublicV1Params, authInfo runtime.ClientAuthInfoWriter) (*InviteGroupPublicV1OK, *InviteGroupPublicV1BadRequest, *InviteGroupPublicV1Unauthorized, *InviteGroupPublicV1Forbidden, *InviteGroupPublicV1NotFound, *InviteGroupPublicV1Conflict, *InviteGroupPublicV1InternalServerError, error)

	KickGroupMemberPublicV1(params *KickGroupMemberPublicV1Params, authInfo runtime.ClientAuthInfoWriter) (*KickGroupMemberPublicV1OK, *KickGroupMemberPublicV1BadRequest, *KickGroupMemberPublicV1Unauthorized, *KickGroupMemberPublicV1Forbidden, *KickGroupMemberPublicV1NotFound, *KickGroupMemberPublicV1InternalServerError, error)

	LeaveGroupPublicV1(params *LeaveGroupPublicV1Params, authInfo runtime.ClientAuthInfoWriter) (*LeaveGroupPublicV1OK, *LeaveGroupPublicV1BadRequest, *LeaveGroupPublicV1Unauthorized, *LeaveGroupPublicV1Forbidden, *LeaveGroupPublicV1NotFound, *LeaveGroupPublicV1InternalServerError, error)

	RejectGroupInvitationPublicV1(params *RejectGroupInvitationPublicV1Params, authInfo runtime.ClientAuthInfoWriter) (*RejectGroupInvitationPublicV1OK, *RejectGroupInvitationPublicV1BadRequest, *RejectGroupInvitationPublicV1Unauthorized, *RejectGroupInvitationPublicV1Forbidden, *RejectGroupInvitationPublicV1NotFound, *RejectGroupInvitationPublicV1Conflict, *RejectGroupInvitationPublicV1InternalServerError, error)

	RejectGroupJoinRequestPublicV1(params *RejectGroupJoinRequestPublicV1Params, authInfo runtime.ClientAuthInfoWriter) (*RejectGroupJoinRequestPublicV1OK, *RejectGroupJoinRequestPublicV1BadRequest, *RejectGroupJoinRequestPublicV1Unauthorized, *RejectGroupJoinRequestPublicV1Forbidden, *RejectGroupJoinRequestPublicV1NotFound, *RejectGroupJoinRequestPublicV1Conflict, *RejectGroupJoinRequestPublicV1InternalServerError, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  CancelGroupJoinRequestV1 cancels request to join group

  <p>Requires valid user authentication</p>
			<p>This endpoint allows user to cancel request to join specific group.</p>
			<p>Action Code: 73411</p>

*/
func (a *Client) CancelGroupJoinRequestV1(params *CancelGroupJoinRequestV1Params, authInfo runtime.ClientAuthInfoWriter) (*CancelGroupJoinRequestV1OK, *CancelGroupJoinRequestV1BadRequest, *CancelGroupJoinRequestV1Unauthorized, *CancelGroupJoinRequestV1Forbidden, *CancelGroupJoinRequestV1NotFound, *CancelGroupJoinRequestV1InternalServerError, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCancelGroupJoinRequestV1Params()
	}

	if params.Context == nil {
		params.Context = context.Background()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "CancelGroupJoinRequestV1",
		Method:             "POST",
		PathPattern:        "/group/v1/public/namespaces/{namespace}/groups/{groupId}/join/cancel",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CancelGroupJoinRequestV1Reader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, nil, nil, nil, nil, nil, err
	}

	switch v := result.(type) {

	case *CancelGroupJoinRequestV1OK:
		return v, nil, nil, nil, nil, nil, nil
	case *CancelGroupJoinRequestV1BadRequest:
		return nil, v, nil, nil, nil, nil, nil
	case *CancelGroupJoinRequestV1Unauthorized:
		return nil, nil, v, nil, nil, nil, nil
	case *CancelGroupJoinRequestV1Forbidden:
		return nil, nil, nil, v, nil, nil, nil
	case *CancelGroupJoinRequestV1NotFound:
		return nil, nil, nil, nil, v, nil, nil
	case *CancelGroupJoinRequestV1InternalServerError:
		return nil, nil, nil, nil, nil, v, nil
	default:
		return nil, nil, nil, nil, nil, nil, fmt.Errorf("Unexpected Type %v", reflect.TypeOf(v))
	}
}

/*
  JoinGroupV1 joins to group

  <p>Required valid user authentication </p>
			<p>This endpoint is used to join as group member</p>
			<p>Join to the group. This endpoint will check the the the type of the group based on the groupID.</p>
			<p>Additional Information:</p>
			<ul>
				<li>User cannot join to the group with PRIVATE type</li>
				<li>Joining PUBLIC group type will create join request and need approval from the privileged group member to accept the request to become the member</li>
				<li>Joining OPEN group type will make this user become member of that group immediately</li>
			</ul>
			<p>This endpoint will return status field to give information whether the user is JOINED or REQUESTED to join to the specific group</p>
			<p>Action Code: 73403</p>

*/
func (a *Client) JoinGroupV1(params *JoinGroupV1Params, authInfo runtime.ClientAuthInfoWriter) (*JoinGroupV1Created, *JoinGroupV1BadRequest, *JoinGroupV1Unauthorized, *JoinGroupV1Forbidden, *JoinGroupV1Conflict, *JoinGroupV1InternalServerError, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewJoinGroupV1Params()
	}

	if params.Context == nil {
		params.Context = context.Background()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "JoinGroupV1",
		Method:             "POST",
		PathPattern:        "/group/v1/public/namespaces/{namespace}/groups/{groupId}/join",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &JoinGroupV1Reader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, nil, nil, nil, nil, nil, err
	}

	switch v := result.(type) {

	case *JoinGroupV1Created:
		return v, nil, nil, nil, nil, nil, nil
	case *JoinGroupV1BadRequest:
		return nil, v, nil, nil, nil, nil, nil
	case *JoinGroupV1Unauthorized:
		return nil, nil, v, nil, nil, nil, nil
	case *JoinGroupV1Forbidden:
		return nil, nil, nil, v, nil, nil, nil
	case *JoinGroupV1Conflict:
		return nil, nil, nil, nil, v, nil, nil
	case *JoinGroupV1InternalServerError:
		return nil, nil, nil, nil, nil, v, nil
	default:
		return nil, nil, nil, nil, nil, nil, fmt.Errorf("Unexpected Type %v", reflect.TypeOf(v))
	}
}

/*
  AcceptGroupInvitationPublicV1 accepts group invitation

  <p>Required valid user authentication </p>
			<p>This endpoint is used to accept group invitation.</p>
			<p>Accept group invitation. If specific user is not invited in the specific group ID, it will show the the error to show if the user is not invited yet.</p>
			<p>This endpoint will also check if the user who access this endpoint is already joined to specific group</p>
			<p>Accessing this endpoint will make all requests (invite / join request) will be deleted for the user who access this endpoint</p>
			<p>Existing members will receive notification of newly accepted member.</p>
			<p>Action Code: 73401</p>

*/
func (a *Client) AcceptGroupInvitationPublicV1(params *AcceptGroupInvitationPublicV1Params, authInfo runtime.ClientAuthInfoWriter) (*AcceptGroupInvitationPublicV1OK, *AcceptGroupInvitationPublicV1BadRequest, *AcceptGroupInvitationPublicV1Unauthorized, *AcceptGroupInvitationPublicV1Forbidden, *AcceptGroupInvitationPublicV1NotFound, *AcceptGroupInvitationPublicV1Conflict, *AcceptGroupInvitationPublicV1InternalServerError, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAcceptGroupInvitationPublicV1Params()
	}

	if params.Context == nil {
		params.Context = context.Background()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "acceptGroupInvitationPublicV1",
		Method:             "POST",
		PathPattern:        "/group/v1/public/namespaces/{namespace}/groups/{groupId}/invite/accept",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &AcceptGroupInvitationPublicV1Reader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, nil, nil, nil, nil, nil, nil, err
	}

	switch v := result.(type) {

	case *AcceptGroupInvitationPublicV1OK:
		return v, nil, nil, nil, nil, nil, nil, nil
	case *AcceptGroupInvitationPublicV1BadRequest:
		return nil, v, nil, nil, nil, nil, nil, nil
	case *AcceptGroupInvitationPublicV1Unauthorized:
		return nil, nil, v, nil, nil, nil, nil, nil
	case *AcceptGroupInvitationPublicV1Forbidden:
		return nil, nil, nil, v, nil, nil, nil, nil
	case *AcceptGroupInvitationPublicV1NotFound:
		return nil, nil, nil, nil, v, nil, nil, nil
	case *AcceptGroupInvitationPublicV1Conflict:
		return nil, nil, nil, nil, nil, v, nil, nil
	case *AcceptGroupInvitationPublicV1InternalServerError:
		return nil, nil, nil, nil, nil, nil, v, nil
	default:
		return nil, nil, nil, nil, nil, nil, nil, fmt.Errorf("Unexpected Type %v", reflect.TypeOf(v))
	}
}

/*
  AcceptGroupJoinRequestPublicV1 accepts group join request

  <p>Required valid user authentication </p>
			<p>Required Member Role Permission: "GROUP:JOIN [CREATE]"</p>
			<p>This endpoint is used to accept group join request.</p>
			<p>Accept group join request. If specific user is not asked to join the specific group ID, it will show the the error to show if the user is not asked to join yet.</p>
			<p>This endpoint will also check if the specific user is already joined to specific group</p>
			<p>Action Code: 73407</p>

*/
func (a *Client) AcceptGroupJoinRequestPublicV1(params *AcceptGroupJoinRequestPublicV1Params, authInfo runtime.ClientAuthInfoWriter) (*AcceptGroupJoinRequestPublicV1OK, *AcceptGroupJoinRequestPublicV1BadRequest, *AcceptGroupJoinRequestPublicV1Unauthorized, *AcceptGroupJoinRequestPublicV1Forbidden, *AcceptGroupJoinRequestPublicV1NotFound, *AcceptGroupJoinRequestPublicV1Conflict, *AcceptGroupJoinRequestPublicV1InternalServerError, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAcceptGroupJoinRequestPublicV1Params()
	}

	if params.Context == nil {
		params.Context = context.Background()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "acceptGroupJoinRequestPublicV1",
		Method:             "POST",
		PathPattern:        "/group/v1/public/namespaces/{namespace}/users/{userId}/join/accept",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &AcceptGroupJoinRequestPublicV1Reader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, nil, nil, nil, nil, nil, nil, err
	}

	switch v := result.(type) {

	case *AcceptGroupJoinRequestPublicV1OK:
		return v, nil, nil, nil, nil, nil, nil, nil
	case *AcceptGroupJoinRequestPublicV1BadRequest:
		return nil, v, nil, nil, nil, nil, nil, nil
	case *AcceptGroupJoinRequestPublicV1Unauthorized:
		return nil, nil, v, nil, nil, nil, nil, nil
	case *AcceptGroupJoinRequestPublicV1Forbidden:
		return nil, nil, nil, v, nil, nil, nil, nil
	case *AcceptGroupJoinRequestPublicV1NotFound:
		return nil, nil, nil, nil, v, nil, nil, nil
	case *AcceptGroupJoinRequestPublicV1Conflict:
		return nil, nil, nil, nil, nil, v, nil, nil
	case *AcceptGroupJoinRequestPublicV1InternalServerError:
		return nil, nil, nil, nil, nil, nil, v, nil
	default:
		return nil, nil, nil, nil, nil, nil, nil, fmt.Errorf("Unexpected Type %v", reflect.TypeOf(v))
	}
}

/*
  GetGroupMembersListPublicV1 gets list of group members

  <p>Required valid user authentication </p>
			<p>This endpoint is used to get list of group members.</p>
			<p>Action Code: 73410</p>

*/
func (a *Client) GetGroupMembersListPublicV1(params *GetGroupMembersListPublicV1Params, authInfo runtime.ClientAuthInfoWriter) (*GetGroupMembersListPublicV1OK, *GetGroupMembersListPublicV1BadRequest, *GetGroupMembersListPublicV1Unauthorized, *GetGroupMembersListPublicV1Forbidden, *GetGroupMembersListPublicV1NotFound, *GetGroupMembersListPublicV1InternalServerError, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetGroupMembersListPublicV1Params()
	}

	if params.Context == nil {
		params.Context = context.Background()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getGroupMembersListPublicV1",
		Method:             "GET",
		PathPattern:        "/group/v1/public/namespaces/{namespace}/groups/{groupId}/members",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetGroupMembersListPublicV1Reader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, nil, nil, nil, nil, nil, err
	}

	switch v := result.(type) {

	case *GetGroupMembersListPublicV1OK:
		return v, nil, nil, nil, nil, nil, nil
	case *GetGroupMembersListPublicV1BadRequest:
		return nil, v, nil, nil, nil, nil, nil
	case *GetGroupMembersListPublicV1Unauthorized:
		return nil, nil, v, nil, nil, nil, nil
	case *GetGroupMembersListPublicV1Forbidden:
		return nil, nil, nil, v, nil, nil, nil
	case *GetGroupMembersListPublicV1NotFound:
		return nil, nil, nil, nil, v, nil, nil
	case *GetGroupMembersListPublicV1InternalServerError:
		return nil, nil, nil, nil, nil, v, nil
	default:
		return nil, nil, nil, nil, nil, nil, fmt.Errorf("Unexpected Type %v", reflect.TypeOf(v))
	}
}

/*
  GetGroupMembersListV1 gets list of group members

  <p>Required permission ADMIN:NAMESPACE:{namespace}:GROUP:MEMBER [READ] </p>
			<p>This endpoint is used to get list of group members.</p>
			<p>Action Code: 73410</p>

*/
func (a *Client) GetGroupMembersListV1(params *GetGroupMembersListV1Params, authInfo runtime.ClientAuthInfoWriter) (*GetGroupMembersListV1OK, *GetGroupMembersListV1BadRequest, *GetGroupMembersListV1Unauthorized, *GetGroupMembersListV1Forbidden, *GetGroupMembersListV1NotFound, *GetGroupMembersListV1InternalServerError, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetGroupMembersListV1Params()
	}

	if params.Context == nil {
		params.Context = context.Background()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getGroupMembersListV1",
		Method:             "GET",
		PathPattern:        "/group/v1/admin/namespaces/{namespace}/groups/{groupId}/members",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetGroupMembersListV1Reader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, nil, nil, nil, nil, nil, err
	}

	switch v := result.(type) {

	case *GetGroupMembersListV1OK:
		return v, nil, nil, nil, nil, nil, nil
	case *GetGroupMembersListV1BadRequest:
		return nil, v, nil, nil, nil, nil, nil
	case *GetGroupMembersListV1Unauthorized:
		return nil, nil, v, nil, nil, nil, nil
	case *GetGroupMembersListV1Forbidden:
		return nil, nil, nil, v, nil, nil, nil
	case *GetGroupMembersListV1NotFound:
		return nil, nil, nil, nil, v, nil, nil
	case *GetGroupMembersListV1InternalServerError:
		return nil, nil, nil, nil, nil, v, nil
	default:
		return nil, nil, nil, nil, nil, nil, fmt.Errorf("Unexpected Type %v", reflect.TypeOf(v))
	}
}

/*
  GetUserGroupInformationPublicV1 gets user group information

  <p>Required valid user authentication </p>
			<p>This endpoint is used to get user group information.</p>
			<p>Get user group information. If user is not belong to any group, it will return warning to give information about it</p>
			<p>Group Member Status:</p>
			<ul>
				<li>JOIN : status of user requested to join group </li>
				<li>INVITE: status of user invited to a group </li>
				<li>JOINED: status of user already joined to a group</li>
			</ul>
			<p>Action Code: 73405</p>

*/
func (a *Client) GetUserGroupInformationPublicV1(params *GetUserGroupInformationPublicV1Params, authInfo runtime.ClientAuthInfoWriter) (*GetUserGroupInformationPublicV1OK, *GetUserGroupInformationPublicV1BadRequest, *GetUserGroupInformationPublicV1Unauthorized, *GetUserGroupInformationPublicV1Forbidden, *GetUserGroupInformationPublicV1NotFound, *GetUserGroupInformationPublicV1InternalServerError, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetUserGroupInformationPublicV1Params()
	}

	if params.Context == nil {
		params.Context = context.Background()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getUserGroupInformationPublicV1",
		Method:             "GET",
		PathPattern:        "/group/v1/public/namespaces/{namespace}/users/{userId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetUserGroupInformationPublicV1Reader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, nil, nil, nil, nil, nil, err
	}

	switch v := result.(type) {

	case *GetUserGroupInformationPublicV1OK:
		return v, nil, nil, nil, nil, nil, nil
	case *GetUserGroupInformationPublicV1BadRequest:
		return nil, v, nil, nil, nil, nil, nil
	case *GetUserGroupInformationPublicV1Unauthorized:
		return nil, nil, v, nil, nil, nil, nil
	case *GetUserGroupInformationPublicV1Forbidden:
		return nil, nil, nil, v, nil, nil, nil
	case *GetUserGroupInformationPublicV1NotFound:
		return nil, nil, nil, nil, v, nil, nil
	case *GetUserGroupInformationPublicV1InternalServerError:
		return nil, nil, nil, nil, nil, v, nil
	default:
		return nil, nil, nil, nil, nil, nil, fmt.Errorf("Unexpected Type %v", reflect.TypeOf(v))
	}
}

/*
  InviteGroupPublicV1 invites user to group

  <p>Required valid user authentication </p>
			<p>Required Member Role Permission: "GROUP:INVITE [CREATE]"</p>
			<p>This endpoint is used to invite specific user to the group.</p>
			<p>invite specific user to the group. If specific user is already have the join request to the group, this endpoint will notify if this user already have join request that needs to be accepted / rejected</p>
			<p>Invited user will receive notification through lobby.</p>
			<p>Action Code: 73406</p>

*/
func (a *Client) InviteGroupPublicV1(params *InviteGroupPublicV1Params, authInfo runtime.ClientAuthInfoWriter) (*InviteGroupPublicV1OK, *InviteGroupPublicV1BadRequest, *InviteGroupPublicV1Unauthorized, *InviteGroupPublicV1Forbidden, *InviteGroupPublicV1NotFound, *InviteGroupPublicV1Conflict, *InviteGroupPublicV1InternalServerError, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewInviteGroupPublicV1Params()
	}

	if params.Context == nil {
		params.Context = context.Background()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "inviteGroupPublicV1",
		Method:             "POST",
		PathPattern:        "/group/v1/public/namespaces/{namespace}/users/{userId}/invite",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &InviteGroupPublicV1Reader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, nil, nil, nil, nil, nil, nil, err
	}

	switch v := result.(type) {

	case *InviteGroupPublicV1OK:
		return v, nil, nil, nil, nil, nil, nil, nil
	case *InviteGroupPublicV1BadRequest:
		return nil, v, nil, nil, nil, nil, nil, nil
	case *InviteGroupPublicV1Unauthorized:
		return nil, nil, v, nil, nil, nil, nil, nil
	case *InviteGroupPublicV1Forbidden:
		return nil, nil, nil, v, nil, nil, nil, nil
	case *InviteGroupPublicV1NotFound:
		return nil, nil, nil, nil, v, nil, nil, nil
	case *InviteGroupPublicV1Conflict:
		return nil, nil, nil, nil, nil, v, nil, nil
	case *InviteGroupPublicV1InternalServerError:
		return nil, nil, nil, nil, nil, nil, v, nil
	default:
		return nil, nil, nil, nil, nil, nil, nil, fmt.Errorf("Unexpected Type %v", reflect.TypeOf(v))
	}
}

/*
  KickGroupMemberPublicV1 kicks group member

  <p>Required valid user authentication </p>
			<p>Required Member Role Permission: "GROUP:KICK [CREATE]"</p>
			<p>This endpoint is used to kick group member.</p>
			<p>Kick group member. This endpoint will check the member and group information, and also the role permission of the the user who accesses this endpoint</p>
			<p>This endpoint will also check if the user that wanted to be kicked is the group member or not.</p>
			<p>Action Code: 73409</p>

*/
func (a *Client) KickGroupMemberPublicV1(params *KickGroupMemberPublicV1Params, authInfo runtime.ClientAuthInfoWriter) (*KickGroupMemberPublicV1OK, *KickGroupMemberPublicV1BadRequest, *KickGroupMemberPublicV1Unauthorized, *KickGroupMemberPublicV1Forbidden, *KickGroupMemberPublicV1NotFound, *KickGroupMemberPublicV1InternalServerError, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewKickGroupMemberPublicV1Params()
	}

	if params.Context == nil {
		params.Context = context.Background()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "kickGroupMemberPublicV1",
		Method:             "POST",
		PathPattern:        "/group/v1/public/namespaces/{namespace}/users/{userId}/kick",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &KickGroupMemberPublicV1Reader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, nil, nil, nil, nil, nil, err
	}

	switch v := result.(type) {

	case *KickGroupMemberPublicV1OK:
		return v, nil, nil, nil, nil, nil, nil
	case *KickGroupMemberPublicV1BadRequest:
		return nil, v, nil, nil, nil, nil, nil
	case *KickGroupMemberPublicV1Unauthorized:
		return nil, nil, v, nil, nil, nil, nil
	case *KickGroupMemberPublicV1Forbidden:
		return nil, nil, nil, v, nil, nil, nil
	case *KickGroupMemberPublicV1NotFound:
		return nil, nil, nil, nil, v, nil, nil
	case *KickGroupMemberPublicV1InternalServerError:
		return nil, nil, nil, nil, nil, v, nil
	default:
		return nil, nil, nil, nil, nil, nil, fmt.Errorf("Unexpected Type %v", reflect.TypeOf(v))
	}
}

/*
  LeaveGroupPublicV1 leaves group

  <p>Required valid user authentication </p>
			<p>This endpoint is used to leave from group.</p>
			<p>leave from group. Admin is not allowed to leave the group. This endpoint will also give response if the user is not belong to any group.</p>
			<p>Action Code: 73404</p>

*/
func (a *Client) LeaveGroupPublicV1(params *LeaveGroupPublicV1Params, authInfo runtime.ClientAuthInfoWriter) (*LeaveGroupPublicV1OK, *LeaveGroupPublicV1BadRequest, *LeaveGroupPublicV1Unauthorized, *LeaveGroupPublicV1Forbidden, *LeaveGroupPublicV1NotFound, *LeaveGroupPublicV1InternalServerError, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewLeaveGroupPublicV1Params()
	}

	if params.Context == nil {
		params.Context = context.Background()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "leaveGroupPublicV1",
		Method:             "POST",
		PathPattern:        "/group/v1/public/namespaces/{namespace}/leave",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &LeaveGroupPublicV1Reader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, nil, nil, nil, nil, nil, err
	}

	switch v := result.(type) {

	case *LeaveGroupPublicV1OK:
		return v, nil, nil, nil, nil, nil, nil
	case *LeaveGroupPublicV1BadRequest:
		return nil, v, nil, nil, nil, nil, nil
	case *LeaveGroupPublicV1Unauthorized:
		return nil, nil, v, nil, nil, nil, nil
	case *LeaveGroupPublicV1Forbidden:
		return nil, nil, nil, v, nil, nil, nil
	case *LeaveGroupPublicV1NotFound:
		return nil, nil, nil, nil, v, nil, nil
	case *LeaveGroupPublicV1InternalServerError:
		return nil, nil, nil, nil, nil, v, nil
	default:
		return nil, nil, nil, nil, nil, nil, fmt.Errorf("Unexpected Type %v", reflect.TypeOf(v))
	}
}

/*
  RejectGroupInvitationPublicV1 rejects group invitation

  <p>Required valid user authentication </p>
			<p>This endpoint is used to reject group invitation.</p>
			<p>Reject group invitation. If specific user is not invited in the specific group ID, it will show the the error to show if the user is not invited yet.</p>
			<p>Action Code: 73402</p>

*/
func (a *Client) RejectGroupInvitationPublicV1(params *RejectGroupInvitationPublicV1Params, authInfo runtime.ClientAuthInfoWriter) (*RejectGroupInvitationPublicV1OK, *RejectGroupInvitationPublicV1BadRequest, *RejectGroupInvitationPublicV1Unauthorized, *RejectGroupInvitationPublicV1Forbidden, *RejectGroupInvitationPublicV1NotFound, *RejectGroupInvitationPublicV1Conflict, *RejectGroupInvitationPublicV1InternalServerError, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRejectGroupInvitationPublicV1Params()
	}

	if params.Context == nil {
		params.Context = context.Background()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "rejectGroupInvitationPublicV1",
		Method:             "POST",
		PathPattern:        "/group/v1/public/namespaces/{namespace}/groups/{groupId}/invite/reject",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &RejectGroupInvitationPublicV1Reader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, nil, nil, nil, nil, nil, nil, err
	}

	switch v := result.(type) {

	case *RejectGroupInvitationPublicV1OK:
		return v, nil, nil, nil, nil, nil, nil, nil
	case *RejectGroupInvitationPublicV1BadRequest:
		return nil, v, nil, nil, nil, nil, nil, nil
	case *RejectGroupInvitationPublicV1Unauthorized:
		return nil, nil, v, nil, nil, nil, nil, nil
	case *RejectGroupInvitationPublicV1Forbidden:
		return nil, nil, nil, v, nil, nil, nil, nil
	case *RejectGroupInvitationPublicV1NotFound:
		return nil, nil, nil, nil, v, nil, nil, nil
	case *RejectGroupInvitationPublicV1Conflict:
		return nil, nil, nil, nil, nil, v, nil, nil
	case *RejectGroupInvitationPublicV1InternalServerError:
		return nil, nil, nil, nil, nil, nil, v, nil
	default:
		return nil, nil, nil, nil, nil, nil, nil, fmt.Errorf("Unexpected Type %v", reflect.TypeOf(v))
	}
}

/*
  RejectGroupJoinRequestPublicV1 rejects group join request

  <p>Required valid user authentication </p>
			<p>Required Member Role Permission: "GROUP:JOIN [CREATE]"</p>
			<p>This endpoint is used to reject group join request.</p>
			<p>Reject group join request. If specific user is not asked to join the specific group ID, it will show the the error to show if the user is not asked to join yet.</p>
			<p>This endpoint will also check if the specific user is already joined to specific group</p>
			<p>Action Code: 73408</p>

*/
func (a *Client) RejectGroupJoinRequestPublicV1(params *RejectGroupJoinRequestPublicV1Params, authInfo runtime.ClientAuthInfoWriter) (*RejectGroupJoinRequestPublicV1OK, *RejectGroupJoinRequestPublicV1BadRequest, *RejectGroupJoinRequestPublicV1Unauthorized, *RejectGroupJoinRequestPublicV1Forbidden, *RejectGroupJoinRequestPublicV1NotFound, *RejectGroupJoinRequestPublicV1Conflict, *RejectGroupJoinRequestPublicV1InternalServerError, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRejectGroupJoinRequestPublicV1Params()
	}

	if params.Context == nil {
		params.Context = context.Background()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "rejectGroupJoinRequestPublicV1",
		Method:             "POST",
		PathPattern:        "/group/v1/public/namespaces/{namespace}/users/{userId}/join/reject",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &RejectGroupJoinRequestPublicV1Reader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, nil, nil, nil, nil, nil, nil, err
	}

	switch v := result.(type) {

	case *RejectGroupJoinRequestPublicV1OK:
		return v, nil, nil, nil, nil, nil, nil, nil
	case *RejectGroupJoinRequestPublicV1BadRequest:
		return nil, v, nil, nil, nil, nil, nil, nil
	case *RejectGroupJoinRequestPublicV1Unauthorized:
		return nil, nil, v, nil, nil, nil, nil, nil
	case *RejectGroupJoinRequestPublicV1Forbidden:
		return nil, nil, nil, v, nil, nil, nil, nil
	case *RejectGroupJoinRequestPublicV1NotFound:
		return nil, nil, nil, nil, v, nil, nil, nil
	case *RejectGroupJoinRequestPublicV1Conflict:
		return nil, nil, nil, nil, nil, v, nil, nil
	case *RejectGroupJoinRequestPublicV1InternalServerError:
		return nil, nil, nil, nil, nil, nil, v, nil
	default:
		return nil, nil, nil, nil, nil, nil, nil, fmt.Errorf("Unexpected Type %v", reflect.TypeOf(v))
	}
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
