// Code generated by go-swagger; DO NOT EDIT.

package reportingclientmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RestapiCreateReasonRequest restapi create reason request
//
// swagger:model restapi.createReasonRequest
type RestapiCreateReasonRequest struct {

	// max 280 chars
	// Required: true
	Description *string `json:"description"`

	// group ids
	// Required: true
	GroupIds []string `json:"groupIds"`

	// max 256 chars
	// Required: true
	Title *string `json:"title"`
}

// Validate validates this restapi create reason request
func (m *RestapiCreateReasonRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGroupIds(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTitle(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RestapiCreateReasonRequest) validateDescription(formats strfmt.Registry) error {

	if err := validate.Required("description", "body", m.Description); err != nil {
		return err
	}

	return nil
}

func (m *RestapiCreateReasonRequest) validateGroupIds(formats strfmt.Registry) error {

	if err := validate.Required("groupIds", "body", m.GroupIds); err != nil {
		return err
	}

	return nil
}

func (m *RestapiCreateReasonRequest) validateTitle(formats strfmt.Registry) error {

	if err := validate.Required("title", "body", m.Title); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RestapiCreateReasonRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RestapiCreateReasonRequest) UnmarshalBinary(b []byte) error {
	var res RestapiCreateReasonRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
