// Code generated by go-swagger; DO NOT EDIT.

package platformclientmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BulkEntitlementGrantRequest A DTO object for granting entitlement in bulk
//
// swagger:model BulkEntitlementGrantRequest
type BulkEntitlementGrantRequest struct {

	// entitlement grant list
	EntitlementGrantList []*EntitlementGrant `json:"entitlementGrantList"`

	// user ids
	// Unique: true
	UserIds []string `json:"userIds"`
}

// Validate validates this bulk entitlement grant request
func (m *BulkEntitlementGrantRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEntitlementGrantList(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BulkEntitlementGrantRequest) validateEntitlementGrantList(formats strfmt.Registry) error {

	if swag.IsZero(m.EntitlementGrantList) { // not required
		return nil
	}

	for i := 0; i < len(m.EntitlementGrantList); i++ {
		if swag.IsZero(m.EntitlementGrantList[i]) { // not required
			continue
		}

		if m.EntitlementGrantList[i] != nil {
			if err := m.EntitlementGrantList[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("entitlementGrantList" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *BulkEntitlementGrantRequest) validateUserIds(formats strfmt.Registry) error {

	if swag.IsZero(m.UserIds) { // not required
		return nil
	}

	if err := validate.UniqueItems("userIds", "body", m.UserIds); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *BulkEntitlementGrantRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BulkEntitlementGrantRequest) UnmarshalBinary(b []byte) error {
	var res BulkEntitlementGrantRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
