// Code generated by go-swagger; DO NOT EDIT.

package platformclientmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PayPalConfig A DTO object for updating PayPal config.
//
// swagger:model PayPalConfig
type PayPalConfig struct {

	// client id
	ClientID string `json:"clientID,omitempty"`

	// client secret, max length is 4096
	ClientSecret string `json:"clientSecret,omitempty"`

	// return url, max length is 2048
	ReturnURL string `json:"returnUrl,omitempty"`

	// web hook id
	WebHookID string `json:"webHookId,omitempty"`
}

// Validate validates this pay pal config
func (m *PayPalConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PayPalConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PayPalConfig) UnmarshalBinary(b []byte) error {
	var res PayPalConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
