AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-lambda-example

  AccelByte Go SDK Lambda Example

Globals:
  Function:
    Timeout: 15
    Environment:
      Variables:
        AB_BASE_URL: 'https://demo.accelbyte.io'
        AB_CLIENT_ID: 'xxxxxxxxxxxxxxxxxx'
        AB_CLIENT_SECRET: 'xxxxxxxxxxxxxxxxxx'

Resources:
  UserStatsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: UserStatsFunction
      Handler: main.go
      Runtime: go1.x
      MemorySize: 512
      FunctionUrlConfig: # https://docs.aws.amazon.com/lambda/latest/dg/urls-tutorial.html
        AuthType: NONE # Change to "AWS_IAM" based on your needs https://docs.aws.amazon.com/lambda/latest/dg/urls-auth.html
        Cors:
          AllowOrigins:
            - "*"
          AllowHeaders:
            - "*"
          AllowMethods:
            - "*"

Outputs:
  UserStatsFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt UserStatsFunction.Arn
  UserStatsFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt UserStatsFunctionRole.Arn
  UserStatsFunctionUrlEndpoint:
    Description: "Golang Simple App Lambda Function URL Endpoint"
    Value:
      Fn::GetAtt: UserStatsFunctionUrl.FunctionUrl # {Function Name}Url.FunctionUrl
