// Copyright (c) 2021 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by go-swagger; DO NOT EDIT.

package users_v4

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"io/ioutil"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/AccelByte/accelbyte-go-sdk/iam-sdk/pkg/iamclientmodels"
)

// PublicEnableMyBackupCodesV4Reader is a Reader for the PublicEnableMyBackupCodesV4 structure.
type PublicEnableMyBackupCodesV4Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PublicEnableMyBackupCodesV4Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPublicEnableMyBackupCodesV4OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPublicEnableMyBackupCodesV4BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPublicEnableMyBackupCodesV4Unauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewPublicEnableMyBackupCodesV4Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewPublicEnableMyBackupCodesV4NotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 409:
		result := NewPublicEnableMyBackupCodesV4Conflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewPublicEnableMyBackupCodesV4InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		data, err := ioutil.ReadAll(response.Body())
		if err != nil {
			return nil, err
		}

		return nil, fmt.Errorf("Requested POST /iam/v4/public/namespaces/{namespace}/users/me/mfa/backupCode/enable returns an error %d: %s", response.Code(), string(data))
	}
}

// NewPublicEnableMyBackupCodesV4OK creates a PublicEnableMyBackupCodesV4OK with default headers values
func NewPublicEnableMyBackupCodesV4OK() *PublicEnableMyBackupCodesV4OK {
	return &PublicEnableMyBackupCodesV4OK{}
}

/*PublicEnableMyBackupCodesV4OK handles this case with default header values.

  Backup codes enabled
*/
type PublicEnableMyBackupCodesV4OK struct {
	Payload *iamclientmodels.ModelBackupCodesResponseV4
}

func (o *PublicEnableMyBackupCodesV4OK) Error() string {
	return fmt.Sprintf("[POST /iam/v4/public/namespaces/{namespace}/users/me/mfa/backupCode/enable][%d] publicEnableMyBackupCodesV4OK  %+v", 200, o.Payload)
}

func (o *PublicEnableMyBackupCodesV4OK) GetPayload() *iamclientmodels.ModelBackupCodesResponseV4 {
	return o.Payload
}

func (o *PublicEnableMyBackupCodesV4OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(iamclientmodels.ModelBackupCodesResponseV4)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPublicEnableMyBackupCodesV4BadRequest creates a PublicEnableMyBackupCodesV4BadRequest with default headers values
func NewPublicEnableMyBackupCodesV4BadRequest() *PublicEnableMyBackupCodesV4BadRequest {
	return &PublicEnableMyBackupCodesV4BadRequest{}
}

/*PublicEnableMyBackupCodesV4BadRequest handles this case with default header values.

  <table><tr><td>errorCode</td><td>errorMessage</td></tr><tr><td>10191</td><td>email address not verified</td></tr><tr><td>10171</td><td>email address not found</td></tr></table>
*/
type PublicEnableMyBackupCodesV4BadRequest struct {
	Payload *iamclientmodels.RestErrorResponse
}

func (o *PublicEnableMyBackupCodesV4BadRequest) Error() string {
	return fmt.Sprintf("[POST /iam/v4/public/namespaces/{namespace}/users/me/mfa/backupCode/enable][%d] publicEnableMyBackupCodesV4BadRequest  %+v", 400, o.Payload)
}

func (o *PublicEnableMyBackupCodesV4BadRequest) GetPayload() *iamclientmodels.RestErrorResponse {
	return o.Payload
}

func (o *PublicEnableMyBackupCodesV4BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(iamclientmodels.RestErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPublicEnableMyBackupCodesV4Unauthorized creates a PublicEnableMyBackupCodesV4Unauthorized with default headers values
func NewPublicEnableMyBackupCodesV4Unauthorized() *PublicEnableMyBackupCodesV4Unauthorized {
	return &PublicEnableMyBackupCodesV4Unauthorized{}
}

/*PublicEnableMyBackupCodesV4Unauthorized handles this case with default header values.

  <table><tr><td>errorCode</td><td>errorMessage</td></tr><tr><td>20001</td><td>unauthorized access</td></tr></table>
*/
type PublicEnableMyBackupCodesV4Unauthorized struct {
	Payload *iamclientmodels.RestErrorResponse
}

func (o *PublicEnableMyBackupCodesV4Unauthorized) Error() string {
	return fmt.Sprintf("[POST /iam/v4/public/namespaces/{namespace}/users/me/mfa/backupCode/enable][%d] publicEnableMyBackupCodesV4Unauthorized  %+v", 401, o.Payload)
}

func (o *PublicEnableMyBackupCodesV4Unauthorized) GetPayload() *iamclientmodels.RestErrorResponse {
	return o.Payload
}

func (o *PublicEnableMyBackupCodesV4Unauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(iamclientmodels.RestErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPublicEnableMyBackupCodesV4Forbidden creates a PublicEnableMyBackupCodesV4Forbidden with default headers values
func NewPublicEnableMyBackupCodesV4Forbidden() *PublicEnableMyBackupCodesV4Forbidden {
	return &PublicEnableMyBackupCodesV4Forbidden{}
}

/*PublicEnableMyBackupCodesV4Forbidden handles this case with default header values.

  <table><tr><td>errorCode</td><td>errorMessage</td></tr><tr><td>20003</td><td>forbidden access</td></tr></table>
*/
type PublicEnableMyBackupCodesV4Forbidden struct {
	Payload *iamclientmodels.RestErrorResponse
}

func (o *PublicEnableMyBackupCodesV4Forbidden) Error() string {
	return fmt.Sprintf("[POST /iam/v4/public/namespaces/{namespace}/users/me/mfa/backupCode/enable][%d] publicEnableMyBackupCodesV4Forbidden  %+v", 403, o.Payload)
}

func (o *PublicEnableMyBackupCodesV4Forbidden) GetPayload() *iamclientmodels.RestErrorResponse {
	return o.Payload
}

func (o *PublicEnableMyBackupCodesV4Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(iamclientmodels.RestErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPublicEnableMyBackupCodesV4NotFound creates a PublicEnableMyBackupCodesV4NotFound with default headers values
func NewPublicEnableMyBackupCodesV4NotFound() *PublicEnableMyBackupCodesV4NotFound {
	return &PublicEnableMyBackupCodesV4NotFound{}
}

/*PublicEnableMyBackupCodesV4NotFound handles this case with default header values.

  <table><tr><td>errorCode</td><td>errorMessage</td></tr><tr><td>10139</td><td>platform account not found</td></tr><tr><td>20008</td><td>user not found</td></tr></table>
*/
type PublicEnableMyBackupCodesV4NotFound struct {
	Payload *iamclientmodels.RestErrorResponse
}

func (o *PublicEnableMyBackupCodesV4NotFound) Error() string {
	return fmt.Sprintf("[POST /iam/v4/public/namespaces/{namespace}/users/me/mfa/backupCode/enable][%d] publicEnableMyBackupCodesV4NotFound  %+v", 404, o.Payload)
}

func (o *PublicEnableMyBackupCodesV4NotFound) GetPayload() *iamclientmodels.RestErrorResponse {
	return o.Payload
}

func (o *PublicEnableMyBackupCodesV4NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(iamclientmodels.RestErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPublicEnableMyBackupCodesV4Conflict creates a PublicEnableMyBackupCodesV4Conflict with default headers values
func NewPublicEnableMyBackupCodesV4Conflict() *PublicEnableMyBackupCodesV4Conflict {
	return &PublicEnableMyBackupCodesV4Conflict{}
}

/*PublicEnableMyBackupCodesV4Conflict handles this case with default header values.

  <table><tr><td>errorCode</td><td>errorMessage</td></tr><tr><td>10194</td><td>factor already enabled</td></tr></table>
*/
type PublicEnableMyBackupCodesV4Conflict struct {
	Payload *iamclientmodels.RestErrorResponse
}

func (o *PublicEnableMyBackupCodesV4Conflict) Error() string {
	return fmt.Sprintf("[POST /iam/v4/public/namespaces/{namespace}/users/me/mfa/backupCode/enable][%d] publicEnableMyBackupCodesV4Conflict  %+v", 409, o.Payload)
}

func (o *PublicEnableMyBackupCodesV4Conflict) GetPayload() *iamclientmodels.RestErrorResponse {
	return o.Payload
}

func (o *PublicEnableMyBackupCodesV4Conflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(iamclientmodels.RestErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPublicEnableMyBackupCodesV4InternalServerError creates a PublicEnableMyBackupCodesV4InternalServerError with default headers values
func NewPublicEnableMyBackupCodesV4InternalServerError() *PublicEnableMyBackupCodesV4InternalServerError {
	return &PublicEnableMyBackupCodesV4InternalServerError{}
}

/*PublicEnableMyBackupCodesV4InternalServerError handles this case with default header values.

  <table><tr><td>errorCode</td><td>errorMessage</td></tr><tr><td>20000</td><td>internal server error</td></tr></table>
*/
type PublicEnableMyBackupCodesV4InternalServerError struct {
	Payload *iamclientmodels.RestErrorResponse
}

func (o *PublicEnableMyBackupCodesV4InternalServerError) Error() string {
	return fmt.Sprintf("[POST /iam/v4/public/namespaces/{namespace}/users/me/mfa/backupCode/enable][%d] publicEnableMyBackupCodesV4InternalServerError  %+v", 500, o.Payload)
}

func (o *PublicEnableMyBackupCodesV4InternalServerError) GetPayload() *iamclientmodels.RestErrorResponse {
	return o.Payload
}

func (o *PublicEnableMyBackupCodesV4InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(iamclientmodels.RestErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
