// Code generated by go-swagger; DO NOT EDIT.

package game_profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"io/ioutil"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/AccelByte/accelbyte-go-sdk/social-sdk/pkg/socialclientmodels"
)

// PublicGetUserProfilesReader is a Reader for the PublicGetUserProfiles structure.
type PublicGetUserProfilesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PublicGetUserProfilesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPublicGetUserProfilesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		data, err := ioutil.ReadAll(response.Body())
		if err != nil {
			return nil, err
		}

		return nil, fmt.Errorf("Requested GET /public/namespaces/{namespace}/users/{userId}/profiles returns an error %d: %s", response.Code(), string(data))
	}
}

// NewPublicGetUserProfilesOK creates a PublicGetUserProfilesOK with default headers values
func NewPublicGetUserProfilesOK() *PublicGetUserProfilesOK {
	return &PublicGetUserProfilesOK{}
}

/*PublicGetUserProfilesOK handles this case with default header values.

  successful operation
*/
type PublicGetUserProfilesOK struct {
	Payload []*socialclientmodels.GameProfileHeader
}

func (o *PublicGetUserProfilesOK) Error() string {
	return fmt.Sprintf("[GET /public/namespaces/{namespace}/users/{userId}/profiles][%d] publicGetUserProfilesOK  %+v", 200, o.Payload)
}

func (o *PublicGetUserProfilesOK) GetPayload() []*socialclientmodels.GameProfileHeader {
	return o.Payload
}

func (o *PublicGetUserProfilesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
